import {
    ComplianceRule,
    GovernanceHealthMetric,
    GovernanceKpi,
    GovernanceStatus,
    LifecycleStep,
    OperationalCard,
    RuleDomain,
} from "./governance.types";

export const governanceKpis: GovernanceKpi[] = [
    {
        id: 1,
        title: "Total Compliance Rules",
        value: 428,
        trend: 8.1,
        trendDirection: "up",
        positive: true,
        icon: "rules",
    },
    {
        id: 2,
        title: "Active Rules",
        value: 362,
        trend: 6.4,
        trendDirection: "up",
        positive: true,
        icon: "active",
    },
    {
        id: 3,
        title: "Draft Rules",
        value: 24,
        trend: 9.1,
        trendDirection: "up",
        positive: false,
        icon: "draft",
    },
    {
        id: 4,
        title: "Pending Approval",
        value: 18,
        trend: 12.8,
        trendDirection: "up",
        positive: false,
        icon: "approval",
    },
    {
        id: 5,
        title: "Scheduled Rules",
        value: 14,
        trend: 3.7,
        trendDirection: "up",
        positive: true,
        icon: "scheduled",
    },
    {
        id: 6,
        title: "Rule Conflicts",
        value: 9,
        trend: 18.2,
        trendDirection: "up",
        positive: false,
        icon: "conflict",
    },
    {
        id: 7,
        title: "Policy Versions Active",
        value: 18,
        trend: 5.6,
        trendDirection: "up",
        positive: true,
        icon: "version",
    },
    {
        id: 8,
        title: "SLA Definitions",
        value: 36,
        trend: 6.7,
        trendDirection: "up",
        positive: true,
        icon: "sla",
    },
    {
        id: 9,
        title: "Escalation Paths",
        value: 12,
        trend: 9.1,
        trendDirection: "up",
        positive: true,
        icon: "escalation",
    },
    {
        id: 10,
        title: "Exceptions Active",
        value: 7,
        trend: 7.7,
        trendDirection: "up",
        positive: true,
        icon: "exception",
    },
    {
        id: 11,
        title: "Rules Revalidation Due",
        value: 26,
        trend: 14.3,
        trendDirection: "up",
        positive: false,
        icon: "revalidation",
    },
    {
        id: 12,
        title: "Governance SLA Breaches",
        value: 5,
        trend: 25,
        trendDirection: "up",
        positive: false,
        icon: "breach",
    },
];

export const trendData = [
    { date: "Jul 3", active: 30, approvals: 20, conflicts: 6, escalations: 4, revalidations: 3 },
    { date: "Jul 6", active: 38, approvals: 26, conflicts: 8, escalations: 7, revalidations: 5 },
    { date: "Jul 9", active: 44, approvals: 31, conflicts: 10, escalations: 9, revalidations: 6 },
    { date: "Jul 13", active: 59, approvals: 39, conflicts: 14, escalations: 15, revalidations: 8 },
    { date: "Jul 16", active: 67, approvals: 42, conflicts: 18, escalations: 18, revalidations: 10 },
    { date: "Jul 20", active: 64, approvals: 38, conflicts: 16, escalations: 18, revalidations: 9 },
    { date: "Jul 23", active: 65, approvals: 39, conflicts: 16, escalations: 20, revalidations: 10 },
    { date: "Jul 27", active: 68, approvals: 42, conflicts: 18, escalations: 22, revalidations: 11 },
    { date: "Jul 30", active: 75, approvals: 49, conflicts: 22, escalations: 28, revalidations: 12 },
    { date: "Aug 3", active: 80, approvals: 54, conflicts: 24, escalations: 31, revalidations: 13 },
];

export const ruleDomains: RuleDomain[] = [
    { name: "Product Safety", value: 128 },
    { name: "Supplier Verification", value: 92 },
    { name: "Brand Authorization", value: 68 },
    { name: "Document Verification", value: 56 },
    { name: "Authenticity", value: 36 },
    { name: "Recall", value: 28 },
    { name: "Marketplace Policy", value: 20 },
];

export const governanceStatuses: GovernanceStatus[] = [
    { label: "Draft", value: 24, percentage: 5.6, color: "#991b1b" },
    { label: "Pending Approval", value: 18, percentage: 4.2, color: "#dc2626" },
    { label: "Active", value: 362, percentage: 84.6, color: "#16a34a" },
    { label: "Scheduled", value: 14, percentage: 3.3, color: "#f59e0b" },
    { label: "Conflict Review", value: 9, percentage: 2.1, color: "#ef4444" },
    { label: "Escalated", value: 7, percentage: 1.6, color: "#6b7280" },
    { label: "Retired", value: 12, percentage: 2.8, color: "#9ca3af" },
];

export const governanceHealth: GovernanceHealthMetric[] = [
    { label: "Triage Readiness", value: 92 },
    { label: "Policy Coverage", value: 88 },
    { label: "Rule Accuracy", value: 90 },
    { label: "SLA Compliance", value: 86 },
    { label: "Escalation Control", value: 84 },
    { label: "Conflict Resolution", value: 78 },
    { label: "Exception Governance", value: 81 },
    { label: "Approval Governance", value: 87 },
    { label: "Revalidations", value: 79 },
    { label: "Audit Readiness", value: 85 },
];

export const complianceRules: ComplianceRule[] = [
    {
        id: "RULE-SAFETY-0015",
        name: "High-Concentration Active Ingredient Safety Evidence",
        domain: "Product Safety",
        type: "Validation",
        trigger: "Product Claimed",
        conditionSummary: "Active ingredient threshold exceeds configured safety limit.",
        outcome: "Block / Escalate",
        entityScope: "Products, Suppliers",
        severity: "CRITICAL",
        conflictStatus: "None",
        version: "v3.2",
        owner: "Elena Vance",
        effectiveDate: "06 Aug 2025",
        expiryDate: "06 Aug 2026",
        status: "Active",
        updatedAt: "04 Aug 2025",
    },
    {
        id: "RULE-VENDOR-0042",
        name: "Vendor Certification Expiry Warning",
        domain: "Supplier Verification",
        type: "Monitoring",
        trigger: "Cert Expiry",
        conditionSummary: "Certification expires within 30 days.",
        outcome: "Notify / Escalate",
        entityScope: "Suppliers",
        severity: "HIGH",
        conflictStatus: "None",
        version: "v2.1",
        owner: "Marco Lee",
        effectiveDate: "01 Aug 2025",
        expiryDate: "01 Aug 2026",
        status: "Active",
        updatedAt: "04 Aug 2025",
    },
    {
        id: "RULE-CLAIMS-0091",
        name: "Unauthorized Claim Publication Block",
        domain: "Brand Authorization",
        type: "Prevention",
        trigger: "Content Publish",
        conditionSummary: "Claim not found in approved authorization set.",
        outcome: "Block Publication",
        entityScope: "Listings, Brands",
        severity: "HIGH",
        conflictStatus: "Moderate",
        version: "v1.8",
        owner: "Priya Kapoor",
        effectiveDate: "15 Jul 2025",
        expiryDate: "15 Jul 2026",
        status: "Active",
        updatedAt: "03 Aug 2025",
    },
    {
        id: "RULE-RECALL-0020",
        name: "Missing KYC Document Escalation",
        domain: "Supplier Verification",
        type: "Escalation",
        trigger: "KYC Missing",
        conditionSummary: "Mandatory verification document missing.",
        outcome: "Escalate to Level 1",
        entityScope: "Suppliers",
        severity: "MEDIUM",
        conflictStatus: "None",
        version: "v1.4",
        owner: "Nisha David",
        effectiveDate: "20 Jul 2025",
        expiryDate: "20 Jul 2026",
        status: "Active",
        updatedAt: "02 Aug 2025",
    },
    {
        id: "RULE-DOC-0036",
        name: "Product Safety Document Expiry",
        domain: "Document Verification",
        type: "Monitoring",
        trigger: "Doc Expiry",
        conditionSummary: "Safety document expires within 15 days.",
        outcome: "Notify / Block",
        entityScope: "Products, Suppliers",
        severity: "MEDIUM",
        conflictStatus: "None",
        version: "v1.9",
        owner: "Marco Lee",
        effectiveDate: "12 Jul 2025",
        expiryDate: "12 Jul 2026",
        status: "Scheduled",
        updatedAt: "29 Jul 2025",
    },
];

export const operationalCards: OperationalCard[] = [
    {
        id: 1,
        title: "Rule Domain Operations",
        headers: ["Active", "Draft", "Pending"],
        rows: [
            { label: "Product Safety", values: [128, 5, 3] },
            { label: "Supplier Verification", values: [92, 4, 2] },
            { label: "Brand Authorization", values: [64, 3, 2] },
            { label: "Document Verification", values: [56, 3, 1] },
        ],
    },
    {
        id: 2,
        title: "Rule Triggers & Conditions",
        headers: ["Count"],
        rows: [
            { label: "Product Claimed", values: [74] },
            { label: "Cert Expiry", values: [62] },
            { label: "Content Publish", values: [58] },
            { label: "KYC Missing", values: [34] },
        ],
    },
    {
        id: 3,
        title: "Rule Outcomes & Controls",
        headers: ["Count"],
        rows: [
            { label: "Block / Prevent", values: [132] },
            { label: "Notify / Warn", values: [116] },
            { label: "Escalate", values: [84] },
            { label: "Require Review", values: [56] },
        ],
    },
    {
        id: 4,
        title: "Rule Scope & Eligibility",
        headers: ["Rules"],
        rows: [
            { label: "Products", values: [108] },
            { label: "Suppliers", values: [142] },
            { label: "Brands", values: [116] },
            { label: "Listings", values: [98] },
        ],
    },
    {
        id: 5,
        title: "Compliance Policy Management",
        headers: ["Active", "Pending"],
        rows: [
            { label: "Policies", values: [18, 4] },
        ],
    },
    {
        id: 6,
        title: "Policy Version Control",
        headers: ["Count"],
        rows: [
            { label: "Current", values: [14] },
            { label: "Superseded", values: [3] },
            { label: "Draft", values: [1] },
        ],
    },
    {
        id: 7,
        title: "SLA Definition",
        headers: ["Count"],
        rows: [
            { label: "Default", values: [16] },
            { label: "Breached", values: [5] },
            { label: "At Risk", values: [8] },
        ],
    },
    {
        id: 8,
        title: "Escalation Path Management",
        headers: ["Paths", "Active", "Draft"],
        rows: [
            { label: "L1", values: [12, 9, 2] },
            { label: "L2", values: [10, 8, 2] },
        ],
    },
    {
        id: 9,
        title: "Active Compliance Escalations",
        headers: ["Open", "SLA Breached"],
        rows: [
            { label: "Level 1", values: [3, 1] },
            { label: "Level 2", values: [2, 1] },
            { label: "Level 3", values: [2, 0] },
        ],
    },
    {
        id: 10,
        title: "Exceptions & Waivers",
        headers: ["Count"],
        rows: [
            { label: "Active", values: [7] },
            { label: "Expiring Soon", values: [2] },
            { label: "Pending Approval", values: [3] },
        ],
    },
    {
        id: 11,
        title: "Rule Conflict & Dependency Management",
        headers: ["Count"],
        rows: [
            { label: "Critical", values: [2] },
            { label: "Moderate", values: [5] },
            { label: "Minor", values: [6] },
        ],
    },
    {
        id: 12,
        title: "Rule Impact Simulation",
        headers: ["Count"],
        rows: [
            { label: "Run", values: [46] },
            { label: "Passed", values: [34] },
            { label: "Failed", values: [12] },
        ],
    },
    {
        id: 13,
        title: "Rule Performance & Effectiveness",
        headers: ["Score"],
        rows: [
            { label: "Effectiveness Score", values: ["89%"] },
            { label: "False Positive Rate", values: ["4.2%"] },
            { label: "Compliance Impact", values: ["High"] },
        ],
    },
    {
        id: 14,
        title: "Governance Approval & Publication Queue",
        headers: ["Count"],
        rows: [
            { label: "Awaiting Review", values: [12] },
            { label: "Peer Review", values: [6] },
            { label: "Approval Pending", values: [4] },
            { label: "Ready to Publish", values: [6] },
        ],
    },
    {
        id: 15,
        title: "Recent Compliance Governance Activity",
        headers: ["Time"],
        rows: [
            { label: "Rule Updated", values: ["11:30 AM"] },
            { label: "Policy Approved", values: ["06:15 AM"] },
            { label: "SLA Breach Recorded", values: ["06:48 AM"] },
            { label: "Escalation Raised", values: ["05:40 AM"] },
        ],
    },
];

export const lifecycleSteps: LifecycleStep[] = [
    { id: 1, title: "Draft Created", count: 24 },
    { id: 2, title: "Rule Defined", count: 18 },
    { id: 3, title: "Scope Configured", count: 24 },
    { id: 4, title: "Simulation Run", count: 12 },
    { id: 5, title: "Conflict Review", count: 9 },
    { id: 6, title: "Peer Review", count: 6 },
    { id: 7, title: "Approval Requested", count: 18 },
    { id: 8, title: "Approved", count: 14, active: true },
    { id: 9, title: "Scheduled", count: 14 },
    { id: 10, title: "Active", count: 362 },
    { id: 11, title: "Monitored", count: 368 },
    { id: 12, title: "Revalidation", count: 26 },
    { id: 13, title: "Suspended", count: 4 },
    { id: 14, title: "Retired", count: 12 },
    { id: 15, title: "Rolled Back", count: 2 },
];