"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import {AlertTriangle,ArrowLeft,Check,CheckCircle2,ChevronDown,ChevronRight,ClipboardCopy,Download,ExternalLink,Eye,Info,LockKeyhole,Mail,MoreHorizontal,RefreshCw,ShieldAlert,Tag,UserRound,X,XCircle} from "lucide-react";
import toast from "react-hot-toast";
import {fetchMarketplacePromotionDetail,recordPromotionDetailPreviewAction} from "@/services/api/marketplacePromotionDetailService";
import styles from "./promotion-detail-approval.module.css";

const tabs=["Overview","Promotion Rules","Eligibility & Scope","Budget & Funding","Seller Participation","Eligible Listings","Customer Experience","Financial Forecast","Conflict Review","Approval Workflow","Communications","Audit History"];
const counts={"Seller Participation":1,"Eligible Listings":86,"Conflict Review":2,Communications:3,"Audit History":16};
const decisions=["Approve Promotion","Approve with Conditions","Request Changes","Reject Promotion","More Actions"];

export default function PromotionDetailApprovalView({promotionId}){
  const router=useRouter(),searchParams=useSearchParams();const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refreshing,setRefreshing]=useState(false),[modal,setModal]=useState(null),[status,setStatus]=useState("Pending Approval"),[audit,setAudit]=useState([]);
  const activeTab=useMemo(()=>tabs.find(tab=>slug(tab)===searchParams.get("tab"))??"Overview",[searchParams]);
  useEffect(()=>{const controller=new AbortController();void fetchMarketplacePromotionDetail(decodeURIComponent(promotionId),controller.signal).then(result=>{setData(result);setStatus(result.identity.approvalStatus)}).catch(e=>{if(e.name!=="AbortError")setError(e.message==="PROMOTION_NOT_FOUND"?"The requested promotion could not be found.":"Promotion details could not be loaded.")}).finally(()=>setLoading(false));return()=>controller.abort()},[promotionId]);
  const load=async()=>{try{setRefreshing(true);setError("");const result=await fetchMarketplacePromotionDetail(decodeURIComponent(promotionId));setData(result);toast.success("Promotion detail refreshed from the frontend fixture")}catch{setError("Promotion details could not be loaded.")}finally{setRefreshing(false)}};
  const changeTab=tab=>{const query=new URLSearchParams(searchParams.toString());tab==="Overview"?query.delete("tab"):query.set("tab",slug(tab));router.replace(`/admin/marketplace/promotions/${encodeURIComponent(promotionId)}${query.size?`?${query}`:""}`,{scroll:false})};
  const complete=async(action,note)=>{const event=await recordPromotionDetailPreviewAction(data.id,action,note);setAudit(items=>[event,...items]);if(action==="Approve Promotion")setStatus("Approved Locally");if(action==="Reject Promotion")setStatus("Rejected Locally");if(action==="Request Changes")setStatus("Changes Requested");if(action==="Approve with Conditions")setStatus("Conditionally Approved");setModal(null);toast.success(`${action} saved in local preview state (not server-persisted)`) };
  if(loading&&!data)return <Loading/>;
  if(error&&!data)return <section className={styles.state} role="alert"><XCircle/><h1>Promotion unavailable</h1><p>{error}</p><div><Link href="/admin/marketplace/promotions">Back to Promotions</Link><button onClick={()=>void load()}>Retry</button></div></section>;
  if(!data)return <section className={styles.state}><Tag/><h1>No promotion detail available</h1></section>;
  if(data.permissions?.canView===false)return <section className={styles.state}><LockKeyhole/><h1>Permission required</h1><p>Your role cannot access this promotion approval record.</p></section>;
  return <main className={styles.page}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><Link href="/admin/marketplace/promotions">Promotions</Link><ChevronRight/><span>{data.id}</span></nav>
    <div className={styles.backRow}><Link href="/admin/marketplace/promotions"><ArrowLeft/>Back to Marketplace Promotions</Link><div><i/>Live data <small>Last updated: {data.lastUpdated}</small><button aria-label="Refresh promotion detail" disabled={refreshing} onClick={()=>void load()}><RefreshCw className={refreshing?styles.spin:""}/></button></div></div>
    <header className={styles.header}><div><h1>{data.name}<button aria-label="Copy promotion ID" onClick={()=>{void navigator.clipboard?.writeText(data.id);toast.success("Promotion ID copied")}}><ClipboardCopy/></button></h1><div className={styles.reference}>{data.id}{data.badges.map((badge,index)=><span className={styles[badge.tone]} key={`${badge.label}-${index}`}>{badge.label}</span>)}</div></div><div className={styles.headerActions}><button onClick={()=>setModal("Preview Customer Experience")}><Eye/>Preview Customer Experience</button><button onClick={()=>setModal("Contact Seller")}><Mail/>Contact Seller</button><button onClick={()=>setModal("Export Promotion Report")}><Download/>Export Promotion Report</button><button onClick={()=>setModal("More Actions")}>More Actions<ChevronDown/></button><button className={styles.primary} onClick={()=>setModal("Approve Promotion")}>Approve Promotion</button></div></header>
    <Context data={data.context}/><Identity data={data}/><Lifecycle items={data.lifecycle}/>
    <div className={styles.tabs} role="tablist" aria-label="Promotion detail sections">{tabs.map((tab,index)=><button role="tab" aria-selected={activeTab===tab} tabIndex={activeTab===tab?0:-1} key={tab} onClick={()=>changeTab(tab)} onKeyDown={e=>{if(e.key==="ArrowRight")changeTab(tabs[(index+1)%tabs.length]);if(e.key==="ArrowLeft")changeTab(tabs[(index-1+tabs.length)%tabs.length])}}>{tab}{counts[tab]&&<b>{counts[tab]}</b>}</button>)}</div>
    <div className={styles.layout}><div className={styles.workspace} role="tabpanel">{activeTab==="Overview"?<Overview data={data} onAction={setModal} onConflict={()=>changeTab("Conflict Review")}/>:<TabPanel tab={activeTab} data={data} audit={audit} onAction={setModal}/>}<ConflictBanner onClick={()=>changeTab("Conflict Review")}/></div><ApprovalRail data={data} status={status} onAction={setModal}/></div>
    {modal&&<ActionModal type={modal} data={data} onClose={()=>setModal(null)} onConfirm={complete}/>} 
  </main>
}

const slug=value=>value.toLowerCase().replaceAll(" ","-").replaceAll("&","and");
function Context({data}){return <section className={styles.context}>{Object.entries(data).map(([key,value])=><p key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><b>{value}</b></p>)}<aside><ShieldAlert/>Access limited to assigned business context</aside></section>}
function Identity({data}){const i=data.identity;return <section className={styles.identity}><CampaignArt compact/><div className={styles.identityColumns}><dl>{[["Promotion Type",i.promotionType],["Seller",i.seller],["Seller ID",i.sellerId],["Brand",i.brand],["Business Unit",i.businessUnit],["Channel",i.channel],["Campaign Owner",i.campaignOwner],["Created",i.created],["Last Updated",data.lastUpdated]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><dl>{[["Discount",i.discount],["Funding Source",i.fundingSource],["Total Budget",i.totalBudget],["Budget Used",i.budgetUsed],["Participant Sellers",i.participantSellers],["Eligible Listings",i.eligibleListings]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><dl>{[["Promotion Status",i.promotionStatus],["Approval Status",i.approvalStatus],["Conflict Status",i.conflictStatus],["Budget Status",i.budgetStatus],["Assigned Reviewer",i.assignedReviewer],["Approval SLA",i.approvalSla],["Current Version",i.currentVersion],["Next Action",i.nextAction]].map(([a,b],index)=><div key={a}><dt>{a}</dt><dd className={index===2||index===7?styles.danger:index===3?styles.good:""}>{b}</dd></div>)}</dl></div></section>}
function CampaignArt({compact=false}){return <div className={`${styles.campaignArt} ${compact?styles.compactArt:""}`} role="img" aria-label="Tokyo Beauty Flash Weekend campaign artwork"><span>TOKYO BEAUTY</span><b>FLASH<br/>WEEKEND</b><strong>20% OFF</strong><small>LIMITED TIME ONLY</small></div>}
function Lifecycle({items}){return <section className={styles.lifecycle} aria-label="Campaign lifecycle">{items.map((item,index)=><div className={`${styles.step} ${styles[item.state]}`} key={item.label}><div>{item.state==="complete"?<Check/>:index+1}</div><b>{item.label}</b><small>{item.date}</small></div>)}</section>}
function Overview({data,onAction,onConflict}){return <div className={styles.overview}><ApprovalScore data={data}/><InfoCard title="Campaign Summary" values={data.campaignSummary}/><InfoCard title="Promotion Rules Summary" values={data.rulesSummary}/><InfoCard title="Eligibility Summary" values={data.eligibilitySummary}/><Funding data={data.funding}/><Participation data={data.participation} onAction={onAction}/><Conflict data={data.conflicts} onConflict={onConflict}/><Preview data={data} onAction={onAction}/></div>}
function ApprovalScore({data}){return <section className={`${styles.card} ${styles.scoreCard}`}><h2>Promotion Approval Score</h2><div className={styles.scoreBody}><div className={styles.scoreRing} style={{"--score":`${data.approvalScore}%`}}><span><b>{data.approvalScore}</b>/100</span></div><div>{data.dimensions.map(item=><Progress key={item.label} {...item}/>)}</div></div><p className={styles.recommendation}><span>Recommendation</span><b>{data.recommendation}</b><small>Based on current analysis</small></p><div className={styles.findings}>{[["Critical Blockers",data.findings.critical,"danger"],["High Findings",data.findings.high,"danger"],["Medium Findings",data.findings.medium,"warning"],["Required Changes",data.findings.changes,"info"]].map(([a,b,tone])=><p key={a}><span>{a}</span><b className={styles[tone]}>↓ {b}</b></p>)}</div></section>}
function InfoCard({title,values}){return <section className={styles.card}><h2>{title}</h2><dl>{Object.entries(values).map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></section>}
function Progress({label,value,warning}){return <div className={styles.progress}><p><span>{label}</span><b>{value}%</b></p><i><b className={warning?styles.warningBar:""} style={{width:`${value}%`}}/></i></div>}
function Funding({data}){return <section className={`${styles.card} ${styles.funding}`}><h2>Budget & Funding Summary</h2><div><div className={styles.fundingRing}><span><small>Total Budget</small><b>{data.total}</b></span></div><ul><li><i/>Seller Funding <b>{data.seller}</b></li><li><i/>Platform Funding <b>{data.platform}</b></li><li><i/>Brand Contribution <b>{data.brand}</b></li></ul><dl>{[["Committed Amount",data.committed],["Remaining Amount",data.remaining],["Projected Overspend",data.overspend]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></div><footer><span><CheckCircle2/>Funding Verification <b>{data.verification}</b></span><span><CheckCircle2/>Agreement Status <b>{data.agreement}</b></span></footer></section>}
function Participation({data,onAction}){return <section className={`${styles.card} ${styles.participation}`}><h2>Seller Participation Summary</h2><div className={styles.participationCounts}>{[["Invited",data.invited],["Accepted",data.accepted],["Pending",data.pending],["Declined",data.declined]].map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</div><dl><div><dt>Contribution Confirmed</dt><dd>{data.confirmed}</dd></div><div><dt>Contribution Outstanding</dt><dd>{data.outstanding}</dd></div><div><dt>Agreement Status</dt><dd>{data.agreement}</dd></div><div><dt>Response Deadline</dt><dd>{data.responseDeadline}</dd></div></dl><button onClick={()=>onAction("View Participation Details")}>View Participation Details</button></section>}
function Conflict({data,onConflict}){return <section className={`${styles.card} ${styles.conflictCard}`}><h2>Conflict Summary</h2>{[["High Severity",data.high,"danger"],["Medium Severity",data.medium,"warning"],["Low Severity",data.low,"muted"],["Total Conflicts",data.total,"danger"]].map(([a,b,tone])=><p key={a}><AlertTriangle className={styles[tone]}/><span>{a}</span><b>{b}</b></p>)}<button onClick={onConflict}>View Conflict Review Tab<ChevronRight/></button></section>}
function Preview({data,onAction}){return <section className={`${styles.card} ${styles.preview}`}><h2>Customer Experience Preview</h2><CampaignArt/><div><p><span>Campaign Dates</span><b>08 Aug – 10 Aug 2026</b></p><p><span>Discount</span><b>{data.identity.discount}</b></p><p><span>Applies To</span><b>{data.identity.seller}</b></p></div><button onClick={()=>onAction("Preview Customer Experience")}>Open Full Customer Preview<ChevronRight/></button></section>}
function ConflictBanner({onClick}){return <section className={styles.conflictBanner}><ShieldAlert/><p><b>This promotion has conflicts that must be resolved or accepted with conditions before approval.</b><span>Please review Conflict Review tab and apply resolution.</span></p><button onClick={onClick}>Go to Conflict Review<ChevronRight/></button></section>}
function TabPanel({tab,data,audit,onAction}){if(tab==="Audit History")return <section className={`${styles.card} ${styles.tabPanel}`}><h2>Audit History</h2>{audit.length?audit.map(item=><article key={item.id}><b>{item.action}</b><time>{new Date(item.at).toLocaleString()}</time><p>{item.note}</p></article>):<p>No local audit events in this session. The fixture reports 16 historical records.</p>}</section>;const source={"Promotion Rules":data.rulesSummary,"Eligibility & Scope":data.eligibilitySummary,"Budget & Funding":data.financial,"Seller Participation":data.participation,"Eligible Listings":{"Eligible Listings":"86","Seller":data.identity.seller,"Status":"Validated"},"Customer Experience":{"Preview":"Customer-facing banner and automatic discount","Discount":data.identity.discount,"Status":"Ready"},"Financial Forecast":data.financial,"Conflict Review":{"High Severity":"1","Medium Severity":"2","Required Resolution":"Accept with conditions or amend commission rule"},"Approval Workflow":data.approval,Communications:{"Seller Notifications":"2","Internal Notes":"1","Last Contact":"03 Aug 2026, 6:10 PM"}}[tab]??{};return <section className={`${styles.card} ${styles.tabPanel}`}><h2>{tab}</h2><p>Promotion-specific operational information for {data.name}.</p><dl>{Object.entries(source).map(([a,b])=><div key={a}><dt>{a}</dt><dd>{String(b)}</dd></div>)}</dl><button onClick={()=>onAction(`Review ${tab}`)}>Open {tab} Workflow</button></section>}
function ApprovalRail({data,status,onAction}){const a=data.approval;return <aside className={styles.rail}><section className={styles.railCard}><h2>Approval Status</h2><div className={styles.completion}><div style={{"--score":`${a.completion}%`}}><span><b>{a.completion}%</b>Overall Progress</span></div><p><span>Current Stage</span><b>{a.stage}</b><span>Status</span><strong>{status}</strong></p></div>{[["Assigned Reviewer",a.reviewer],["Budget SLA",a.budgetSla],["Elapsed Time",a.elapsed],["Due Date",a.due],["Last Updated",data.lastUpdated],["Stale Version",a.version]].map(([x,y])=><p className={styles.railRow} key={x}><span>{x}</span><b>{y}</b></p>)}</section><section className={styles.railCard}><h2>Promotion Health</h2>{data.health.map(item=><Progress key={item.label} {...item}/>)}<p className={styles.overall}><b>Overall Score</b><strong>{data.approvalScore}<small>/100</small></strong></p></section><section className={styles.railCard}><h2>Blocking & Warning Issues</h2>{Object.entries(data.issues).map(([x,y],index)=><p className={styles.issue} key={x}><AlertTriangle className={index===0?styles.danger:index<3?styles.warning:styles.muted}/><span>{x}</span><b>{y}</b></p>)}<button className={styles.railLink} onClick={()=>onAction("View All Issues")}>View All Issues</button></section><section className={styles.railCard}><h2>Financial Summary</h2>{Object.entries(data.financial).map(([x,y],index)=><p className={styles.railRow} key={x}><span>{x}</span><b className={index===6?styles.danger:""}>{y}</b></p>)}</section><section className={`${styles.railCard} ${styles.recommendationRail}`}><h2>Recommendation</h2><p><CheckCircle2/><span><b>{data.recommendation}</b><small>System, Finance & Reviewer Recommendation</small></span></p><button onClick={()=>onAction("View Conditions")}>View Conditions (3)</button></section><section className={styles.railCard}><h2>Decision Actions</h2><div className={styles.decisions}>{decisions.map((item,index)=><button className={index===0?styles.primary:item==="Reject Promotion"?styles.reject:""} onClick={()=>onAction(item)} key={item}>{item}{item==="More Actions"&&<ChevronDown/>}</button>)}</div></section></aside>}
function ActionModal({type,data,onClose,onConfirm}){const [note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const preview=type==="Preview Customer Experience",contact=type==="Contact Seller",exporting=type==="Export Promotion Report",more=type==="More Actions",view=type.startsWith("View ")||type.startsWith("Review ");const sensitive=/Approve|Reject|Changes|Review|Conditions/.test(type);const submit=async()=>{if(sensitive&&!note.trim()){setError("An audit note is required for this approval action.");return}setBusy(true);try{if(exporting){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`${data.id}-promotion-report.json`;anchor.click();URL.revokeObjectURL(url);onClose();toast.success("Promotion report exported");return}await onConfirm(type,note)}finally{setBusy(false)}};return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="promotion-action-title"><header><div><small>Promotion Approval · Frontend Preview</small><h2 id="promotion-action-title">{type}</h2></div><button aria-label="Close dialog" onClick={onClose}><X/></button></header><div className={styles.modalBody}>{preview?<><CampaignArt/><h3>{data.name}</h3><p>{data.identity.discount} applies automatically to eligible {data.identity.seller} listings.</p></>:contact?<><label>Subject<input defaultValue={`Promotion approval · ${data.id}`}/></label><label>Message<textarea placeholder="Write a message to the participating seller"/></label></>:more?<div className={styles.moreGrid}>{["Duplicate Promotion","Edit Promotion","Pause Promotion","View Version History","Archive Promotion"].map(item=><button onClick={()=>{onClose();toast(`Safe preview: ${item}`)}} key={item}>{item}<ChevronRight/></button>)}</div>:<><p>Apply <b>{type}</b> to <b>{data.name}</b> ({data.id}). This fixture-backed workflow updates only the current page session.</p>{!exporting&&<label>Internal audit note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Enter approval rationale and conditions"/></label>}</>}{error&&<p className={styles.formError} role="alert">{error}</p>}</div><footer><button onClick={onClose} disabled={busy}>Cancel</button>{!preview&&!more&&<button className={styles.primary} disabled={busy} onClick={()=>void submit()}>{busy?"Saving…":contact?"Send Message":exporting?"Export":"Confirm"}</button>}</footer></section></div>}
function Loading(){return <div className={styles.loading} role="status" aria-label="Loading promotion detail"><div/><div/><section><i/><i/><i/><i/></section><div/></div>}
