'use client';

import { ArrowLeft, Check, ChevronRight, Pencil } from 'lucide-react';
import { tAdvisor } from '@/lib/beautyAdvisorTranslations';

const COPY = {
  en: { goals: ['Build a skincare routine','Build a haircare routine','Find makeup products','Find a fragrance','Review ingredients','Find a beauty gift','Improve my routine','Browse current offers'], type: 'Which option best describes you?', concerns: 'What are your main concerns?', budget: 'What budget suits you?', prefs: 'Any product preferences?', options: { skincare: ['Dry','Oily','Combination','Normal','Sensitive','Not sure'], haircare: ['Straight','Wavy','Curly','Coily','Not sure'], makeup: ['Natural look','Full coverage','Radiant finish','Matte finish'], fragrance: ['Floral','Fresh','Citrus','Woody','Amber','Gourmand','Aquatic','Musky','Not sure'] }, concernOptions: ['Dryness','Excess oil','Dullness','Sensitivity','Sun protection','General maintenance'], budgets: ['Budget-friendly','Mid-range','Premium','Custom amount'], preferences: ['Fragrance-free','Lightweight texture','Rich texture','Vegan where verified','Cruelty-free where verified','No preference'] },
  si: { goals: ['සම සත්කාර ක්‍රමයක් සාදන්න','හිසකෙස් සත්කාර ක්‍රමයක් සාදන්න','මේකප් නිෂ්පාදන සොයන්න','සුවඳ විලවුන් සොයන්න','අමුද්‍රව්‍ය පරීක්ෂා කරන්න','රූපලාවණ්‍ය තෑග්ගක් සොයන්න','මගේ ක්‍රමය වැඩිදියුණු කරන්න','වත්මන් දීමනා බලන්න'], type: 'ඔබට වඩාත් ගැළපෙන විකල්පය කුමක්ද?', concerns: 'ඔබේ ප්‍රධාන අවශ්‍යතා මොනවාද?', budget: 'ඔබට ගැළපෙන අයවැය කුමක්ද?', prefs: 'නිෂ්පාදන මනාප තිබේද?', options: {}, concernOptions: ['වියළි බව','අධික තෙල්','අඳුරු පෙනුම','සංවේදී බව','හිරු ආරක්ෂාව','සාමාන්‍ය සත්කාර'], budgets: ['අයවැයට හිතකර','මධ්‍යම','ප්‍රිමියම්','වෙනත් මුදලක්'], preferences: ['සුවඳ රහිත','සැහැල්ලු ස්වභාවය','ඝන ස්වභාවය','තහවුරු කළ වීගන්','තහවුරු කළ සත්ව හිංසා රහිත','මනාපයක් නැත'] },
  ta: { goals: ['தோல் பராமரிப்பு முறையை உருவாக்கு','முடி பராமரிப்பு முறையை உருவாக்கு','ஒப்பனைப் பொருட்களைக் கண்டறி','வாசனைத் திரவியம் கண்டறி','மூலப்பொருட்களை மதிப்பாய்வு செய்','அழகுப் பரிசைக் கண்டறி','என் முறையை மேம்படுத்து','தற்போதைய சலுகைகளைப் பார்'], type: 'உங்களைச் சிறப்பாக விவரிக்கும் விருப்பம் எது?', concerns: 'உங்கள் முக்கிய கவலைகள் என்ன?', budget: 'உங்களுக்கு ஏற்ற பட்ஜெட் எது?', prefs: 'தயாரிப்பு விருப்பங்கள் உள்ளதா?', options: {}, concernOptions: ['வறட்சி','அதிக எண்ணெய்','பொலிவின்மை','உணர்திறன்','சூரிய பாதுகாப்பு','பொது பராமரிப்பு'], budgets: ['பட்ஜெட் நட்பு','நடுத்தரம்','பிரீமியம்','தனிப்பயன் தொகை'], preferences: ['வாசனையற்றது','இலகுவான அமைப்பு','செறிவான அமைப்பு','சரிபார்க்கப்பட்ட வீகன்','சரிபார்க்கப்பட்ட கொடுமையற்றது','விருப்பம் இல்லை'] },
};

const goalKeys = ['skincare','haircare','makeup','fragrance','ingredients','gift','routine','offers'];
export default function AIAdvisorConsultationFlow({ language, profile, onChange, onComplete }) {
  const c = COPY[language] || COPY.en;
  const step = profile.consultationStep || 0;
  const category = profile.goal || 'skincare';
  const questions = [
    { key: 'goal', text: tAdvisor(language, 'welcome'), options: c.goals, values: goalKeys },
    { key: 'type', text: c.type, options: c.options[category] || COPY.en.options[category] || ['Not sure'] },
    { key: 'concerns', text: c.concerns, options: c.concernOptions, multi: true },
    { key: 'budgetType', text: c.budget, options: c.budgets },
    { key: 'productPreferences', text: c.prefs, options: c.preferences, multi: true, optional: true },
  ];
  const reviewing = step >= questions.length;
  const q = questions[Math.min(step, questions.length - 1)];
  const selected = profile[q?.key] || (q?.multi ? [] : null);
  const choose = (option, index) => {
    const value = q.key === 'goal' ? q.values[index] : option;
    const next = q.multi ? (selected.includes(value) ? selected.filter(x => x !== value) : [...selected, value]) : value;
    onChange({ ...profile, [q.key]: next, consultationStep: q.multi ? step : step + 1 });
  };
  return <section className="rounded-2xl border border-primary-100 bg-white p-4 shadow-sm" aria-labelledby="advisor-question">
    <div className="mb-4"><div className="flex items-center justify-between text-[11px] font-bold uppercase tracking-wider text-gray-500"><span>{tAdvisor(language,'step',{current: Math.min(step + 1, questions.length),total: questions.length})}</span><span>{Math.round((Math.min(step, questions.length) / questions.length) * 100)}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-gray-100" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow={Math.round((Math.min(step, questions.length) / questions.length) * 100)}><div className="h-full rounded-full bg-gradient-to-r from-[#cc2b5e] to-[#753a88] transition-all motion-reduce:transition-none" style={{width:`${Math.round((Math.min(step, questions.length) / questions.length) * 100)}%`}} /></div></div>
    {reviewing ? <><h4 id="advisor-question" className="font-bold text-gray-900">{tAdvisor(language,'review')}</h4><dl className="mt-3 space-y-2 text-sm">{questions.map((item,i)=><div key={item.key} className="flex items-start justify-between gap-3 rounded-xl bg-gray-50 p-3"><div><dt className="font-semibold text-gray-600">{item.text}</dt><dd className="mt-1 text-gray-900">{Array.isArray(profile[item.key]) ? profile[item.key].join(', ') : profile[item.key]}</dd></div><button type="button" onClick={()=>onChange({...profile,consultationStep:i})} className="flex min-h-11 items-center gap-1 text-xs font-bold text-primary-700"><Pencil size={13}/>{tAdvisor(language,'edit')}</button></div>)}</dl><button type="button" onClick={()=>onComplete(profile)} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#cc2b5e] to-[#753a88] px-4 text-sm font-bold text-white"><Check size={16}/>{tAdvisor(language,'finish')}</button></> : <><h4 id="advisor-question" className="text-base font-bold text-gray-900">{q.text}</h4><div className="mt-3 grid gap-2">{q.options.map((option,index)=>{const active=q.multi?selected.includes(option):(q.key==='goal'?selected===q.values[index]:selected===option);return <button key={option} type="button" aria-pressed={active} onClick={()=>choose(option,index)} className={`flex min-h-11 items-center justify-between rounded-xl border px-3 text-left text-sm font-semibold transition-colors ${active?'border-primary-600 bg-primary-50 text-primary-800':'border-gray-200 bg-white text-gray-800 hover:border-primary-300'}`}><span>{option}</span>{active?<Check size={16}/>:<ChevronRight size={16}/>}</button>})}</div><div className="mt-4 flex justify-between gap-2"><button type="button" disabled={step===0} onClick={()=>onChange({...profile,consultationStep:Math.max(0,step-1)})} className="flex min-h-11 items-center gap-1 rounded-xl px-3 text-sm font-bold text-gray-600 disabled:opacity-30"><ArrowLeft size={16}/>{tAdvisor(language,'back')}</button><div className="flex gap-2">{q.optional&&<button type="button" onClick={()=>onChange({...profile,consultationStep:step+1})} className="min-h-11 rounded-xl px-3 text-sm font-bold text-gray-600">{tAdvisor(language,'skip')}</button>}{q.multi&&<button type="button" disabled={!selected.length&&!q.optional} onClick={()=>onChange({...profile,consultationStep:step+1})} className="min-h-11 rounded-xl bg-primary-700 px-4 text-sm font-bold text-white disabled:opacity-40">{tAdvisor(language,'continue')}</button>}</div></div></>}
  </section>;
}
