import { ProductSupplierCase, SelectedProductCaseDetailsData, ProductSupplierOperationsRailData } from "./types";

export const MOCK_PRODUCT_SUPPLIER_CASES: ProductSupplierCase[] = [
  {
    id: "CS-2025-008402",
    reference: "CS-2025-008402",
    customerName: "Dinara Perera",
    customerId: "CUS-8402",
    isVip: true,
    priority: "Critical",
    issueType: "Authenticity",
    caseStatus: "Under Review",
    productName: "Radiance Vitamin C Serum 30 ml",
    productId: "PRO-00004512",
    sku: "SLB-VITC-30ML",
    brand: "Radiance",
    supplier: "Lane Distribution",
    batchLot: "LOT-ABC-006421",
    productQualityRisk: "At Risk",
    authenticityStatus: "Under Verification",
    safetyStatus: "Clear",
    complianceStatus: "On Track",
    dependency: "Auth Team",
    sentiment: "Negative",
    risk: "High",
    slaStatus: "At Risk",
    assignedAgent: "Elena Vance",
    assignedTeam: "Auth Team",
    lastSupplierUpdate: "12 May, 08:14 AM",
    lastComplianceUpdate: "12 May, 09:12 AM",
    lastCustomerUpdate: "12 May, 09:40 AM",
    age: "18h",
  },
  {
    id: "CS-2025-008301",
    reference: "CS-2025-008301",
    customerName: "Robert Perera",
    customerId: "CUS-8301",
    isVip: false,
    priority: "High",
    issueType: "Product Quality",
    caseStatus: "In Progress",
    productName: "Hydration Night Cream — 50 ml",
    productId: "PRO-00004513",
    sku: "SLB-HYD-50ML",
    brand: "GlowGlow",
    supplier: "Glow Distribution",
    batchLot: "LOT-ABC-006501",
    productQualityRisk: "At Risk",
    authenticityStatus: "Verified",
    safetyStatus: "Clear",
    complianceStatus: "On Track",
    dependency: "Quality Team",
    sentiment: "Concerned",
    risk: "Medium",
    slaStatus: "On Track",
    assignedAgent: "M. Silva",
    assignedTeam: "Quality Team",
    lastSupplierUpdate: "11 May, 09:14 AM",
    lastComplianceUpdate: "11 May, 10:12 AM",
    lastCustomerUpdate: "11 May, 10:50 AM",
    age: "1d 7h",
  },
  {
    id: "CS-2025-008112",
    reference: "CS-2025-008112",
    customerName: "Nimal Jayasundara",
    customerId: "CUS-8112",
    isVip: false,
    priority: "High",
    issueType: "Damaged",
    caseStatus: "Waiting Supplier",
    productName: "Silk Touch Body Lotion — 200 ml",
    productId: "PRO-00004514",
    sku: "SLB-LTH-200",
    brand: "Silk Touch",
    supplier: "BeautyPlus Global",
    batchLot: "LOT-LTL-050920",
    productQualityRisk: "At Risk",
    authenticityStatus: "Verified",
    safetyStatus: "Clear",
    complianceStatus: "On Track",
    dependency: "Supplier",
    sentiment: "Concerned",
    risk: "High",
    slaStatus: "At Risk",
    assignedAgent: "Sara O.",
    assignedTeam: "Customer Care",
    lastSupplierUpdate: "11 May, 04:20 PM",
    lastComplianceUpdate: "11 May, 04:50 PM",
    lastCustomerUpdate: "11 May, 05:58 PM",
    age: "2d 5h",
  },
  {
    id: "CS-2025-008016",
    reference: "CS-2025-008016",
    customerName: "Sankalpa Fernando",
    customerId: "CUS-8016",
    isVip: false,
    priority: "Medium",
    issueType: "Usage / Ingredient",
    caseStatus: "In Progress",
    productName: "Herbal Face Oil — 100 ml",
    productId: "PRO-00004515",
    sku: "SLB-HFO-100",
    brand: "HerbalPure",
    supplier: "Herbal Pure Ltd.",
    batchLot: "LOT-HFO-061021",
    productQualityRisk: "Good",
    authenticityStatus: "Verified",
    safetyStatus: "Clear",
    complianceStatus: "On Track",
    dependency: "Care Team",
    sentiment: "Concerned",
    risk: "Medium",
    slaStatus: "On Track",
    assignedAgent: "K. Fernando",
    assignedTeam: "Care Team",
    lastSupplierUpdate: "11 May, 11:00 AM",
    lastComplianceUpdate: "11 May, 11:20 AM",
    lastCustomerUpdate: "11 May, 11:30 AM",
    age: "3d 4h",
  },
  {
    id: "CS-2025-007928",
    reference: "CS-2025-007928",
    customerName: "Janani Wickramage",
    customerId: "CUS-7928",
    isVip: false,
    priority: "Medium",
    issueType: "Packaging",
    caseStatus: "Queued",
    productName: "BrightGlow SPF 50 Sunscreen — 50 ml",
    productId: "PRO-00004516",
    sku: "SLB-SPF50-50ML",
    brand: "BrightGlow",
    supplier: "BrightCare",
    batchLot: "LOT-SPF-040220",
    productQualityRisk: "Good",
    authenticityStatus: "Verified",
    safetyStatus: "Clear",
    complianceStatus: "On Track",
    dependency: "Safety Team",
    sentiment: "Neutral",
    risk: "Low",
    slaStatus: "On Track",
    assignedAgent: "N. Perera",
    assignedTeam: "Safety Team",
    lastSupplierUpdate: "10 May, 05:10 PM",
    lastComplianceUpdate: "10 May, 05:25 PM",
    lastCustomerUpdate: "10 May, 06:10 PM",
    age: "4d 12h",
  },
];

export const MOCK_SELECTED_PRODUCT_CASE_DETAILS: SelectedProductCaseDetailsData = {
  caseInfo: MOCK_PRODUCT_SUPPLIER_CASES[0],
  summaryMetrics: {
    caseAge: "18h 18m",
    productIssuesCount: "3 Linked",
    supplierCases30dCount: "6 in 30d",
    similarAuthenticityReportsCount: 4,
    evidenceCompletenessPercent: 78,
    currentDependency: "Compliance",
    nextCustomerUpdate: "24m",
    caseHealthPercent: 81,
  },
  productSummary: {
    productId: "PRO-00004512",
    brand: "Radiance",
    category: "Serums & Treatments",
    sku: "SLB-VITC-30ML",
    confidenceQuality: "Active",
    returnableItem: "Yes",
    complianceStatus: "0.8%",
    verifiedSupplier: "Yes",
  },
  supplierSummary: {
    supplierId: "SUP-00001234",
    name: "Lane Distribution",
    tier: "Tier 1",
    contractStatus: "Active",
    productCoverage: "68 SKUs",
    supplierSla: "Good",
    supplierRiskHealth: "91%",
    authenticityIncidentsCount: 1,
  },
  variantBatchLot: {
    batchLot: "LOT-ABC-006421",
    mfgDate: "04 Apr 2025",
    expiryDate: "04 Apr 2027",
    batchStatus: "Usable",
    unitLevelComplaintsCount: 2,
    relatedReturnsCount: 14,
    safetyAlerts: "None",
  },
  productQualityAssessment: {
    issueType: "Packaging Difference",
    reportedCondition: "Sealed",
    productType: "Serum",
    usability: "Usable",
    confidencePercent: 72,
  },
  authenticityAssessment: {
    confidenceScorePercent: 68,
    status: "Under Verification",
    batchTrace: true,
    qrSerialVerification: true,
    packaging: true,
    imagingOverlay: false,
    knownComparison: false,
  },
  safetyAssessment: {
    severity: "Low",
    immediateGuidance: "Safe to use",
    incidentStatus: "Under Review",
    complianceTrigger: "Auto Review",
    evidenceRequired: "Packaging, Serial, Receipt, Images",
  },
  customerStatement: {
    text: "“The packaging looks different from my previous purchase. The label quality is poor and the QR code is not scanning. I'm worried this is not an original product.”",
    author: "Dinara Perera",
  },
  customerEvidence: [
    { label: "Front Photo", status: "Uploaded", isUploaded: true },
    { label: "Back Label", status: "Uploaded", isUploaded: true },
    { label: "Batch Code", status: "Uploaded", isUploaded: true },
    { label: "Product Texture", status: "Uploaded", isUploaded: true },
    { label: "Receipt", status: "Uploaded", isUploaded: true },
  ],
  authenticityTimeline: {
    stages: [
      { label: "Case Created", timestamp: "09:12 AM", status: "completed" },
      { label: "Evidence Received", timestamp: "09:45 AM", status: "completed" },
      { label: "Supplier Contacted", timestamp: "09:58 AM", status: "completed" },
      { label: "Auth Team Review", timestamp: "10:17 AM", status: "completed" },
      { label: "Preliminary Findings", timestamp: "10:32 AM", status: "completed" },
      { label: "Compliance Decision Pending", timestamp: "Waiting", status: "active" },
    ],
  },
  similarIssueAnalysis: {
    sameSku: 7,
    sameBatch: 4,
    sameSupplier: 6,
    samePackaging: 4,
    confirmedCounterfeit90d: 0,
  },
  investigationChecklist: [
    { label: "1. Verify Customer Details", isCompleted: true },
    { label: "2. Confirm Product & SKU", isCompleted: true },
    { label: "3. Verify Serial / QR Code", isCompleted: true },
    { label: "4. Compare Packaging", isCompleted: true },
  ],
  blockingGuidance: {
    guidanceText: "“The authenticity team is currently reviewing this product and working with our compliance team and supplier.”",
    updateEta: "We will update you within 24–48 hours.",
  },
  dependencies: {
    verificationCompliance: "Waiting",
    supplier: "Reviewing",
    packagingTeam: "Confirmed",
    finance: "Not Required",
    customer: "Waiting",
  },
  complianceEscalation: {
    escalationId: "ESC-2025-00567",
    owner: "Elena Vance",
    reason: "Authenticity Risk",
    status: "Open",
    risk: "High",
  },
  customerProductImpact: {
    sentiment: "Negative",
    authenticityRisk: "High",
    supplierRisk: "Medium",
  },
  recommendedCustomerGuidance: {
    previewText: "We understand your concern. We are verifying this product and working with our compliance team and supplier. We will update you within 24–48 hours.",
  },
  caseHistorySnapshot: {
    initialResponseSla: "Met",
    supplierResponseSla: "At Risk",
    supplierResponseTime: "17h 42m",
    complianceReviewSla: "At Risk",
    complianceReviewTime: "by Today, 10:05 AM",
  },
  exceptionHistory: [
    { type: "Packaging Variation", raisedOn: "12 May, 08:14 AM", raisedBy: "R. Perera", status: "Active" },
    { type: "Sample/Prn Label Printing", raisedOn: "12 May, 09:18 AM", raisedBy: "Agent", status: "Active" },
    { type: "Supplier Delay", raisedOn: "12 May, 09:25 AM", raisedBy: "Agent", status: "Active" },
  ],
};

export const MOCK_OPERATIONS_RAIL_DATA: ProductSupplierOperationsRailData = {
  supportHealthScore: 94,
  supportHealthLabel: "Excellent",
  targetScore: "90+",

  selectedCaseHealthScore: 81,
  selectedCaseHealthLabel: "Healthy",

  caseSummary: {
    open: 198,
    atRisk: 18,
    reopened: 11,
    critical: 9,
    escalated: 12,
  },

  productIssueSummary: {
    quality: 64,
    defective: 21,
    usageIngredient: 45,
    damaged: 29,
    packaging: 18,
  },

  authenticitySummary: {
    concerns: 17,
    complianceCases: 9,
    confirmedCounterfeit: 0,
    reviewRequired: 11,
    counterfeitSuspected: 7,
  },

  supplierSummary: {
    supplierIssues: 38,
    slaRisk: 12,
    repeatedSupplierIssues: 6,
    waitingSupplier: 22,
    qualityIncidents: 9,
  },

  safetySummary: {
    safetyConcerns: 9,
    complianceEscalated: 6,
    highSeverity: 4,
    openSafetyCases: 5,
  },

  dependencySummary: {
    waitingCompliance: 9,
    waitingCustomer: 5,
    waitingSupplier: 22,
    waitingCatalogue: 3,
  },

  quickQueues: [
    { label: "Product Quality", count: 64, variant: "info" },
    { label: "Authenticity Review", count: 17, variant: "warning" },
    { label: "Safety Concern", count: 9, variant: "danger" },
    { label: "Waiting Compliance", count: 9, variant: "warning" },
    { label: "Supplier Issues", count: 38, variant: "info" },
    { label: "Compliance Escalation", count: 7, variant: "danger" },
    { label: "Waiting Supplier", count: 22, variant: "warning" },
    { label: "SLA At Risk", count: 18, variant: "warning" },
  ],
};
