"use client";
import React,{useCallback,useDeferredValue,useEffect,useMemo,useState}from"react";import toast from"react-hot-toast";
import type{BrandFilterState,BrandManagementData,CatalogueBrand}from"@/types/brandManagement";
import{archiveBrand,createBrand,exportBrands,getBrandManagement,importBrands,updateBrand}from"@/services/api/brandManagement";
import{BrandHeader}from"./components/BrandHeader";import{BrandBusinessContext}from"./components/BrandBusinessContext";import{BrandKpiGrid}from"./components/BrandKpiGrid";import{BrandStatusTabs}from"./components/BrandStatusTabs";import{BrandFilters}from"./components/BrandFilters";import{BrandTable}from"./components/BrandTable";import{BrandIntelligenceSidebar}from"./components/BrandIntelligenceSidebar";import{BrandLowerDashboards}from"./components/BrandLowerDashboards";import{BrandFormDrawer,type BrandPayload}from"./modals/BrandFormDrawer";import{BrandAuthorizationDrawer}from"./modals/BrandAuthorizationDrawer";import{ImportBrandsModal}from"./modals/ImportBrandsModal";
const blank:BrandFilterState={searchQuery:"",statusTab:"All Brands",verificationStatus:"All",authorizationStatus:"All",brandOwner:"All",supplier:"All",country:"All",channelEligibility:"All",riskLevel:"All",updatedDate:""};
const scopes:Record<string,string>={"All Brands":"all",Active:"active",Verified:"verified",Archived:"archived"};
export const BrandManagementView=()=>{const[data,setData]=useState<BrandManagementData|null>(null),[filters,setFilters]=useState(blank),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[selectedIds,setSelectedIds]=useState<string[]>([]),[selected,setSelected]=useState<CatalogueBrand|null>(null),[activeKpi,setActiveKpi]=useState<string|null>(null),[formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState<CatalogueBrand|null>(null),[authBrand,setAuthBrand]=useState<CatalogueBrand|null>(null),[importOpen,setImportOpen]=useState(false);const search=useDeferredValue(filters.searchQuery);
 const params=useMemo(()=>({page,pageSize,search:search||undefined,scope:scopes[filters.statusTab]??undefined,verified:filters.verificationStatus==="Verified"?1:filters.verificationStatus==="Unverified"?0:undefined,authorization:filters.authorizationStatus==="All"?undefined:filters.authorizationStatus,supplierId:filters.supplier==="All"?undefined:filters.supplier,countryId:filters.country==="All"?undefined:filters.country,updatedFrom:filters.updatedDate||undefined}),[page,pageSize,search,filters]);
 const load=useCallback(async(silent=false)=>{if(!silent)setBusy(true);try{const next=await getBrandManagement(params);setData(next);setError(null);setSelected(old=>old?next.brands.data.find(x=>x.id===old.id)??next.brands.data[0]??null:next.brands.data[0]??null)}catch(e){setError(e instanceof Error?e.message:"Unable to load brands.")}finally{setBusy(false)}},[params]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{const timer=setInterval(()=>void load(true),30000);return()=>clearInterval(timer)},[load]);
 const unavailable=(label:string)=>toast.error(`${label} is unavailable: this installation has no authoritative workflow or schema for it.`);
 const change=(key:keyof BrandFilterState,value:string)=>{if(["brandOwner","channelEligibility","riskLevel"].includes(key)){unavailable(String(key));return}setPage(1);setFilters(old=>({...old,[key]:value}))};
 const selectScope=(label:string)=>{if(!scopes[label]){unavailable(label);return}setPage(1);setFilters(old=>({...old,statusTab:label}))};
 const clickKpi=(id:string)=>{const kpi=data?.kpis.find(x=>x.id===id);if(!kpi)return;if(kpi.value===null||kpi.filterKey==="unsupported"){unavailable(kpi.label);return}setActiveKpi(id);const label=data?.tabs.find(x=>x.id===kpi.filterKey)?.label;if(label)selectScope(label);else if(kpi.filterKey==="expired"){setPage(1);setFilters(old=>({...old,statusTab:"All Brands",authorizationStatus:"expired"}))}else if(kpi.filterKey==="duplicates")unavailable("Duplicate candidate filtering")};
 const save=async(payload:BrandPayload)=>{if(editing)await updateBrand(editing.id,payload);else await createBrand(payload);toast.success(editing?"Brand updated.":"Brand created.");await load()};
 const archive=async(brand:CatalogueBrand)=>{if(!window.confirm(`Archive ${brand.brandName}?`))return;try{await archiveBrand(brand.id);toast.success("Brand archived.");setSelectedIds(x=>x.filter(id=>id!==brand.id));await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to archive brand.")}};
 if(!data&&busy)return <div className="p-8 text-sm text-gray-500">Loading authoritative brand data…</div>;if(!data)return <div className="m-6 rounded border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><b>Brand management could not load.</b><p>{error}</p><button onClick={()=>void load()} className="mt-3 rounded bg-[#741d35] px-3 py-2 text-white">Retry</button></div>;
 const counts=Object.fromEntries(data.tabs.map(x=>[x.id,x.count]));const rows=data.brands.data;
 return <div className="w-full flex flex-col min-h-screen bg-gray-50/50 pb-12 min-w-0"><BrandHeader canExport={data.capabilities.canExport} canImport={data.capabilities.canImport} canManage={data.capabilities.canManage} onExport={()=>void exportBrands(params).catch(e=>toast.error(e.message))} onImport={()=>data.capabilities.canImport?setImportOpen(true):unavailable("Import")} onBulkActions={()=>unavailable("Bulk actions (no source-defined action exists)")} onCreateBrand={()=>{setEditing(null);setFormOpen(true)}} selectedCount={selectedIds.length}/><BrandBusinessContext lastSynced={new Date(data.lastSyncedAt).toLocaleString()} onRefresh={()=>void load()} isRefreshing={busy} tenantScoped={data.capabilities.tenantScope}/>
 {error&&<div className="mx-6 mt-3 rounded border border-amber-200 bg-amber-50 p-2 text-xs text-amber-800">Last refresh failed: {error}. Displaying the last successful response.</div>}
 <main className="p-4 sm:p-6 flex flex-col gap-5 min-w-0"><BrandKpiGrid kpis={data.kpis} activeKpiId={activeKpi} onKpiClick={clickKpi}/><BrandStatusTabs activeTab={filters.statusTab} onTabChange={selectScope} counts={counts}/><BrandFilters filters={filters} countries={data.options.countries} suppliers={data.options.suppliers} authorizationStatuses={data.options.authorizationStatuses} isRefreshing={busy} onFilterChange={change} onClearAll={()=>{setFilters(blank);setSelectedIds([]);setPage(1);setActiveKpi(null)}} onOpenMoreFilters={()=>unavailable("More filters")} onOpenSaveView={()=>unavailable("Saved views")} onRefresh={()=>void load()}/>
 <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1fr)_280px] gap-4 items-start min-w-0"><div className="min-w-0 flex flex-col gap-6"><BrandTable brands={rows} pagination={data.brands} selectedBrandIds={selectedIds} selectedBrand={selected} canManage={data.capabilities.canManage} onPageChange={setPage} onPageSizeChange={n=>{setPageSize(n);setPage(1)}} onSelectBrand={setSelected} onToggleSelectRow={id=>setSelectedIds(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id])} onToggleSelectAll={()=>setSelectedIds(selectedIds.length===rows.length?[]:rows.map(x=>x.id))} onEditBrand={b=>{setEditing(b);setFormOpen(true)}} onManageAuthorization={setAuthBrand} onViewProducts={()=>unavailable("View products by brand")} onArchiveBrand={b=>void archive(b)} onUnavailable={unavailable}/><BrandLowerDashboards data={data} onCompareDuplicate={p=>toast(`Exact normalized-name match: ${p.brandA} / ${p.brandB}. Merge is unavailable without a canonical relationship migration.`)} onSelectAuthorization={()=>selected?setAuthBrand(selected):unavailable("Authorization record")}/></div><aside className="sticky top-4"><BrandIntelligenceSidebar data={data} onSelectQueue={key=>{const tab=data.tabs.find(x=>x.id===key);if(tab)selectScope(tab.label);else if(key==="expired"){setPage(1);setFilters(old=>({...old,authorizationStatus:"expired"}))}else unavailable(key)}}/></aside></div></main>
 <BrandFormDrawer isOpen={formOpen} onClose={()=>setFormOpen(false)} brandToEdit={editing} countries={data.options.countries} onSave={save}/><BrandAuthorizationDrawer isOpen={!!authBrand} onClose={()=>setAuthBrand(null)} brand={authBrand} canReview={data.capabilities.canReviewAuthorizations} onChanged={()=>void load()}/><ImportBrandsModal isOpen={importOpen} onClose={()=>setImportOpen(false)} onImport={async file=>{const result=(await importBrands(file)).data;await load();return result}}/>
 </div>};
