"use client";
import {useCallback,useEffect,useMemo,useRef,useState}from"react";
import{useDebounce}from"./useDebounce";
import{getCatalogueDataOperations}from"@/services/api/catalogueDataOperations";
import type{CatalogueDataJob,DataOperationsQuery,FilterState}from"@/types/importExport";

const initial:FilterState={searchQuery:"",activeTab:"All Jobs",jobType:"All",source:"All",businessUnit:"All",template:"All",approvalStatus:"All",validationStatus:"All",dateRange:"Last 30 Days",owner:"All"};
const scopes:Record<string,string>={"All Jobs":"all",Imports:"imports",Exports:"exports",Running:"running","Pending Review":"pending",Scheduled:"scheduled",Failed:"failed",Completed:"completed",Templates:"templates"};
export function useImportExportManagement(){
 const[filters,setFilters]=useState(initial);const[page,setCurrentPage]=useState(1);const[rowsPerPage,setRowsPerPage]=useState(25);const[granularity,setGranularity]=useState<"daily"|"weekly"|"monthly">("daily");const[sortColumn,setSortColumn]=useState<keyof CatalogueDataJob>("updatedAt");const[sortDirection,setSortDirection]=useState<"asc"|"desc">("desc");const[selectedRowIds,setSelectedRowIds]=useState<string[]>([]);const[selectedJobId,setSelectedJobId]=useState("");const[activeWorkflowStage,setActiveWorkflowStage]=useState(1);
 const[data,setData]=useState<Awaited<ReturnType<typeof getCatalogueDataOperations>>|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<Error|null>(null);const[isRefreshing,setRefreshing]=useState(false);const controller=useRef<AbortController|null>(null);const search=useDebounce(filters.searchQuery,350);
 const[isNewImportOpen,setIsNewImportOpen]=useState(false);const[isScheduleExportOpen,setIsScheduleExportOpen]=useState(false);const[isMoreFiltersOpen,setIsMoreFiltersOpen]=useState(false);const[isSaveViewOpen,setIsSaveViewOpen]=useState(false);const[isDuplicateModalOpen,setIsDuplicateModalOpen]=useState(false);
 const query:DataOperationsQuery=useMemo(()=>{const days=filters.dateRange==="Today"?0:filters.dateRange==="Last 7 Days"?6:29;const from=filters.dateRange==="Custom"?undefined:new Date(Date.now()-days*86400000).toISOString().slice(0,10);return{page,pageSize:rowsPerPage,search:search||undefined,operationType:filters.jobType!=="All"?filters.jobType.toLowerCase()as"import"|"export":undefined,status:filters.validationStatus!=="All"?filters.validationStatus.toLowerCase():undefined,userId:filters.owner!=="All"?Number(filters.owner):undefined,dateFrom:from,scope:scopes[filters.activeTab]||"all",granularity,sort:({updatedAt:"updatedAt",recordsCount:"recordsCount",fileName:"fileName",operationType:"operationType",outcome:"outcome"}as Record<string,string>)[String(sortColumn)]||"updatedAt",direction:sortDirection};},[page,rowsPerPage,search,filters,granularity,sortColumn,sortDirection]);
 const refresh=useCallback(async(background=false)=>{controller.current?.abort();const next=new AbortController();controller.current=next;background?setRefreshing(true):setLoading(true);try{const result=await getCatalogueDataOperations(query,next.signal);setData(result);setError(null);}catch(cause){if(!next.signal.aborted)setError(cause instanceof Error?cause:new Error("Unable to load import/export jobs."));}finally{if(!next.signal.aborted){setLoading(false);setRefreshing(false);}}},[JSON.stringify(query)]);
 useEffect(()=>{void refresh();return()=>controller.current?.abort();},[refresh]);useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void refresh(true);},(data?.meta.refreshIntervalSeconds??30)*1000);const focus=()=>void refresh(true);window.addEventListener("focus",focus);return()=>{clearInterval(timer);window.removeEventListener("focus",focus);};},[data?.meta.refreshIntervalSeconds,refresh]);useEffect(()=>setCurrentPage(1),[filters]);
 const jobs=data?.jobs.data??[];const selectedJob=jobs.find(job=>job.id===selectedJobId)??data?.activeJob??jobs[0]??null;useEffect(()=>{if(selectedJob&&!selectedJobId)setSelectedJobId(selectedJob.id);},[selectedJob,selectedJobId]);useEffect(()=>{if(data?.workflow)setActiveWorkflowStage(data.workflow.activeStage);},[data?.workflow]);
 return{data,jobs,filteredJobs:jobs,paginatedJobs:jobs,totalCount:data?.jobs.total??0,selectedJobId,setSelectedJobId,selectedJob,selectedRowIds,setSelectedRowIds,activeWorkflowStage,setActiveWorkflowStage,filters,setFilters,granularity,setGranularity,sortColumn,sortDirection,currentPage:page,setCurrentPage,rowsPerPage,setRowsPerPage,loading,error,isRefreshing,lastSynced:data?.lastSyncedAt??"",query,refresh,handleRefresh:()=>refresh(true),handleSort:(column:keyof CatalogueDataJob)=>{if(sortColumn===column)setSortDirection(value=>value==="asc"?"desc":"asc");else{setSortColumn(column);setSortDirection("asc");}},handleSelectRow:(id:string)=>setSelectedRowIds(old=>old.includes(id)?old.filter(value=>value!==id):[...old,id]),handleSelectAllOnPage:()=>setSelectedRowIds(old=>jobs.every(job=>old.includes(job.id))?old.filter(id=>!jobs.some(job=>job.id===id)):[...new Set([...old,...jobs.map(job=>job.id)])]),handleClearFilters:()=>{setFilters(initial);setSelectedRowIds([]);},isNewImportOpen,setIsNewImportOpen,isScheduleExportOpen,setIsScheduleExportOpen,isMoreFiltersOpen,setIsMoreFiltersOpen,isSaveViewOpen,setIsSaveViewOpen,isDuplicateModalOpen,setIsDuplicateModalOpen};
}
