"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useDebounce } from "./useDebounce";
import { getMediaDashboard } from "@/services/api/mediaAssets";
import type { MediaAsset, MediaFilterState, MediaQuery } from "@/types/mediaManagement";

const initial: MediaFilterState={search:"",assetType:"All Types",approvalStatus:"All Statuses",linkedEntity:"All Entities",brand:"All Brands",supplier:"All Suppliers",productSku:"All Products",qualityStatus:"All",rightsStatus:"All",channelCompatibility:"All",resolutionQuality:"All",dateRange:"",quickChips:[],activeTab:"All Assets"};
const scopes:Record<string,string>={"All Assets":"all",Images:"images",Videos:"videos",Documents:"documents","Pending Approval":"pending","Quality Issues":"quality",Duplicates:"duplicates","Usage Rights":"rights",Archived:"archived"};
export function useMediaManagement(){
 const[filters,setFilters]=useState(initial);const[page,setCurrentPage]=useState(1);const[rowsPerPage,setRowsPerPage]=useState(25);const[sortColumn,setSortColumn]=useState<keyof MediaAsset>("updatedAt");const[sortDirection,setSortDirection]=useState<"asc"|"desc">("desc");const[selectedRowIds,setSelectedRowIds]=useState<string[]>([]);const[selectedAssetId,setSelectedAssetId]=useState("");
 const[data,setData]=useState<Awaited<ReturnType<typeof getMediaDashboard>>|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<Error|null>(null);const[isRefreshing,setRefreshing]=useState(false);const controller=useRef<AbortController|null>(null);const search=useDebounce(filters.search,350);
 const query:MediaQuery=useMemo(()=>({page,pageSize:rowsPerPage,search:search||undefined,linkedEntity:filters.linkedEntity==="Product"?"product":filters.linkedEntity==="Unlinked"?"unlinked":undefined,fileType:filters.assetType!=="All Types"?filters.assetType.toLowerCase():undefined,approvalStatus:filters.approvalStatus!=="All Statuses"?filters.approvalStatus.toLowerCase().replaceAll(" ","_"):undefined,productId:filters.productSku!=="All Products"?filters.productSku:undefined,supplierId:filters.supplier!=="All Suppliers"?filters.supplier:undefined,dateFrom:filters.dateRange||undefined,scope:scopes[filters.activeTab]||"all",sort:({name:"name",fileSizeBytes:"fileSize",updatedAt:"updatedAt"}as Record<string,string>)[String(sortColumn)]||"updatedAt",direction:sortDirection}),[page,rowsPerPage,search,filters,sortColumn,sortDirection]);
 const refresh=useCallback(async(background=false)=>{controller.current?.abort();const next=new AbortController();controller.current=next;background?setRefreshing(true):setLoading(true);try{setData(await getMediaDashboard(query,next.signal));setError(null);}catch(cause){if(!next.signal.aborted)setError(cause instanceof Error?cause:new Error("Unable to load media assets."));}finally{if(!next.signal.aborted){setLoading(false);setRefreshing(false);}}},[JSON.stringify(query)]);
 useEffect(()=>{void refresh();return()=>controller.current?.abort();},[refresh]);useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void refresh(true);},(data?.meta.refreshIntervalSeconds??30)*1000);const focus=()=>void refresh(true);window.addEventListener("focus",focus);return()=>{clearInterval(timer);window.removeEventListener("focus",focus);};},[data?.meta.refreshIntervalSeconds,refresh]);useEffect(()=>setCurrentPage(1),[filters]);
 const assets=data?.assets.data||[];const selectedPreviewAsset=assets.find(a=>a.id===selectedAssetId)||assets[0]||null;useEffect(()=>{if(selectedPreviewAsset&&!selectedAssetId)setSelectedAssetId(selectedPreviewAsset.id);},[selectedPreviewAsset,selectedAssetId]);
 return{data,assets,paginatedAssets:assets,filteredAssets:assets,totalCount:data?.assets.total||0,selectedPreviewAsset,selectedAssetId,setSelectedAssetId,selectedRowIds,setSelectedRowIds,filters,setFilters,currentPage:page,setCurrentPage,rowsPerPage,setRowsPerPage,sortColumn,sortDirection,loading,error,isRefreshing,lastSynced:data?.lastSyncedAt||"",refresh,query,handleSort:(column:keyof MediaAsset)=>{if(sortColumn===column)setSortDirection(v=>v==="asc"?"desc":"asc");else{setSortColumn(column);setSortDirection("asc");}},handleSelectAllOnPage:(checked:boolean)=>setSelectedRowIds(checked?assets.map(a=>a.id):[]),handleSelectRow:(id:string,checked:boolean)=>setSelectedRowIds(old=>checked?[...new Set([...old,id])]:old.filter(x=>x!==id)),handleClearFilters:()=>{setFilters(initial);setSelectedRowIds([]);},handleToggleQuickChip:(chip:string)=>{const map:Record<string,string>={"Pending Approval":"pending","Missing Mandatory":"missing","Low Resolution":"quality","Duplicate Risk":"duplicates",Unlinked:"unlinked","Missing Alt Text":"quality","Rights Expiring":"rights","Processing Failed":"processing"};const target=map[chip];if(!target)return;setFilters(old=>({...old,activeTab:Object.entries(scopes).find(([,scope])=>scope===target)?.[0]||old.activeTab,linkedEntity:target==="unlinked"?"Unlinked":"All Entities",quickChips:old.quickChips.includes(chip)?[]:[chip]}));},handleRefresh:()=>refresh(true)};
}
