<?php
namespace App\Repositories\Admin;
use Illuminate\Support\Facades\DB;
class FinanceDocumentsConfigurationRepository{
public function invoices(array$f){$sort=['reference'=>'i.invoice_number','name'=>'COALESCE(bp.company_name,s.company_name)','amount'=>'i.total_amount','status'=>'i.status','date'=>'i.invoice_date','updatedAt'=>'i.updated_at'][$f['sort']];return DB::table('invoices as i')->join('orders as o','o.id','=','i.order_id')->leftJoin('suppliers as s','s.id','=','i.supplier_id')->leftJoin('buyer_profiles as bp','bp.id','=','i.buyer_profile_id')->leftJoin('currencies as c','c.id','=','i.currency_id')->whereNull('i.deleted_at')->whereBetween('i.created_at',[$f['from'],$f['to']])->whereRaw('COALESCE(c.code,o.currency)=?',[$f['currency']])->when($f['status'],fn($q,$v)=>$q->where('i.status',$v))->when($f['search'],fn($q,$v)=>$q->where(fn($x)=>$x->where('i.invoice_number','like','%'.$v.'%')->orWhere('o.order_number','like','%'.$v.'%')->orWhere('s.company_name','like','%'.$v.'%')->orWhere('bp.company_name','like','%'.$v.'%')))->selectRaw("i.*,o.order_number,o.approval_status,COALESCE(c.code,o.currency) currency,COALESCE(bp.company_name,s.company_name,'Not available') party,CASE WHEN bp.id IS NULL THEN 'Supplier' ELSE 'Customer' END party_type,COALESCE(bp.id,s.id) party_id")->orderByRaw($sort.' '.$f['direction'])->paginate($f['perPage'],['*'],'page',$f['page']);}
public function invoiceTotals(array$f):object{return DB::table('invoices as i')->join('orders as o','o.id','=','i.order_id')->leftJoin('currencies as c','c.id','=','i.currency_id')->whereNull('i.deleted_at')->whereBetween('i.created_at',[$f['from'],$f['to']])->whereRaw('COALESCE(c.code,o.currency)=?',[$f['currency']])->selectRaw("COUNT(*) count,COALESCE(SUM(i.total_amount),0) total,COALESCE(SUM(i.balance_due),0) outstanding,COALESCE(SUM(CASE WHEN i.balance_due>0 AND i.due_date<CURRENT_DATE THEN i.balance_due ELSE 0 END),0) overdue,SUM(CASE WHEN i.status='draft' THEN 1 ELSE 0 END) drafts,SUM(CASE WHEN i.payment_status='partially_paid' THEN 1 ELSE 0 END) partial")->first();}
public function invoiceTrend(array$f):array{return DB::table('invoices as i')->join('orders as o','o.id','=','i.order_id')->leftJoin('currencies as c','c.id','=','i.currency_id')->whereNull('i.deleted_at')->whereBetween('i.created_at',[$f['from'],$f['to']])->whereRaw('COALESCE(c.code,o.currency)=?',[$f['currency']])->groupByRaw('DATE(i.created_at)')->orderByRaw('DATE(i.created_at)')->selectRaw('DATE(i.created_at) date,SUM(i.total_amount) invoiceValue,SUM(i.balance_due) outstanding,SUM(i.amount_paid) paid')->get()->map(fn($r)=>(array)$r)->all();}
public function invoice(string$id):?object{return DB::table('invoices as i')->join('orders as o','o.id','=','i.order_id')->leftJoin('suppliers as s','s.id','=','i.supplier_id')->leftJoin('currencies as c','c.id','=','i.currency_id')->whereNull('i.deleted_at')->where(fn($q)=>$q->where('i.id',$id)->orWhere('i.uuid',$id)->orWhere('i.invoice_number',$id))->selectRaw("i.*,o.order_number,o.approval_status,COALESCE(c.code,o.currency) currency,COALESCE(s.company_name,'Not available') party")->first();}
public function configurations(array$f){$tax=DB::table('tax_rules as t')->leftJoin('countries as c','c.id','=','t.country_id')->whereNull('t.deleted_at')->selectRaw("CONCAT('tax:',t.id) id,'Tax' domain,t.tax_type type,t.name,COALESCE(c.name,'Global') jurisdiction,t.rate value,t.effective_from,t.effective_until,'Configured' source,t.status,t.updated_at");$fx=DB::table('currency_exchange_rates as x')->join('currencies as b','b.id','=','x.base_currency_id')->join('currencies as q','q.id','=','x.quote_currency_id')->selectRaw("CONCAT('fx:',x.id) id,'FX' domain,'Exchange Rate' type,CONCAT(b.code,' / ',q.code) name,CONCAT(b.code,'/',q.code) jurisdiction,x.rate value,x.rate_date effective_from,NULL effective_until,COALESCE(x.source,'Not available') source,x.status,x.updated_at");$union=$tax->unionAll($fx);$base=DB::query()->fromSub($union,'cfg')->when($f['type'],fn($q,$v)=>$q->where('domain',$v))->when($f['status'],fn($q,$v)=>$q->where('status',$v))->when($f['search'],fn($q,$v)=>$q->where(fn($x)=>$x->where('name','like','%'.$v.'%')->orWhere('jurisdiction','like','%'.$v.'%')));return$base->orderBy('updated_at',$f['direction'])->paginate($f['perPage'],['*'],'page',$f['page']);}
public function configurationTotals():array{return['taxRules'=>DB::table('tax_rules')->whereNull('deleted_at')->where('status','active')->count(),'jurisdictions'=>DB::table('tax_rules')->whereNull('deleted_at')->where('status','active')->whereNotNull('country_id')->distinct()->count('country_id'),'currencies'=>DB::table('currencies')->where('status','active')->count(),'rates'=>DB::table('currency_exchange_rates')->where('status','active')->count()];}}
