import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import MarketplaceSellersPage from "@/app/admin/marketplace/sellers/page";
import { ADMIN_NAVIGATION } from "@/constants/adminNavigation";

const replace=vi.fn();
vi.mock("next/navigation",()=>({useRouter:()=>({replace}),usePathname:()=>"/admin/marketplace/sellers",useSearchParams:()=>new URLSearchParams()}));
vi.mock("@/hooks/admin/useMarketplaceSellers",()=>({useMarketplaceSellers:()=>({data:fixture,loading:false,refreshing:false,error:null,stale:false,refresh:vi.fn()})}));
vi.mock("@/services/api/marketplaceSellersService",()=>({exportMarketplaceSellers:vi.fn()}));
vi.mock("recharts",()=>({ResponsiveContainer:({children})=><div>{children}</div>,LineChart:({children})=><div>{children}</div>,Line:()=>null,CartesianGrid:()=>null,XAxis:()=>null,YAxis:()=>null,Tooltip:()=>null,Legend:()=>null,PieChart:({children})=><div>{children}</div>,Pie:({children})=><div>{children}</div>,Cell:()=>null}));

const unavailable={available:false,value:null,reason:"not_defined"};
const seller=(id,name,risk)=>({id:String(id),sellerCode:`SELL-${String(id).padStart(8,"0")}`,name,type:"Brand Owner",country:"Sri Lanka",activeListings:2,orders:1,gmv:{available:true,value:100,currency:"USD"},aov:{available:true,value:100,currency:"USD"},fulfilmentRate:unavailable,cancellationRate:{available:true,value:0},returnRate:unavailable,rating:unavailable,slaBreaches:unavailable,policyFindings:unavailable,riskLevel:risk,status:"active",verificationStatus:"verified",lastActivityAt:"2026-08-07T10:00:00Z"});
const fixture={context:{tenant:"SL Beauty",ecosystem:"Beauty Marketplace",country:null,currency:"USD",dateFrom:"2026-07-09",dateTo:"2026-08-07",timezone:"Asia/Colombo"},availableCurrencies:["USD"],kpis:[{id:"active",label:"Active Marketplace Sellers",available:true,value:2,format:"number",definition:"database"}],trend:{available:true,currency:"USD",items:[{period:"2026-08-07",gmv:200,cancellationRate:0}]},risks:[{level:"low",count:1,percentage:50},{level:"medium",count:0,percentage:0},{level:"high",count:1,percentage:50},{level:"critical",count:0,percentage:0}],scorecards:[{id:"sales",label:"Sales Performance",...unavailable}],health:{...unavailable},alerts:[],statusSummary:{active:2,underReview:0,suspended:0,highRisk:1,newThisMonth:0},sla:{...unavailable,items:[]},financial:{available:true,currency:"USD",total:100,pending:25,exceptions:0,refundLiability:0},quickQueues:[{id:"high-risk",label:"High-Risk Sellers",count:1,href:"/admin/marketplace/sellers?status=high-risk"}],items:[seller(1,"Database Seller","low"),seller(2,"Risk Seller","high")],permissions:{canView:true,canExport:true,canManage:false,canCompare:true},meta:{page:1,perPage:25,total:2,totalPages:1,from:1,to:2,dataAsOf:"2026-08-07T10:00:00Z",refreshIntervalSeconds:30}};

describe("Seller Marketplace Performance",()=>{
  it("renders live API-shaped metrics, charts, table and honest unavailable states",()=>{render(<MarketplaceSellersPage/>);expect(screen.getByRole("heading",{name:"Seller Marketplace Performance",level:1})).toBeInTheDocument();expect(screen.getByText("Active Marketplace Sellers")).toBeInTheDocument();expect(screen.getByText("Database Seller")).toBeInTheDocument();expect(screen.getAllByText(/Not available/).length).toBeGreaterThan(0)});
  it("writes status filtering to the URL",()=>{render(<MarketplaceSellersPage/>);fireEvent.click(screen.getByRole("tab",{name:"Under Review"}));expect(replace).toHaveBeenCalledWith("/admin/marketplace/sellers?status=under-review",{scroll:false})});
  it("supports row selection and seller comparison",()=>{render(<MarketplaceSellersPage/>);fireEvent.click(screen.getByRole("checkbox",{name:"Select Database Seller"}));fireEvent.click(screen.getByRole("checkbox",{name:"Select Risk Seller"}));const compare=screen.getAllByRole("button",{name:/Compare Sellers/})[0];expect(compare).toBeEnabled();fireEvent.click(compare);expect(screen.getByRole("dialog")).toBeInTheDocument()});
  it("keeps the Sellers route in Marketplace navigation",()=>{const marketplace=ADMIN_NAVIGATION.find(item=>item.id==="marketplace");expect(marketplace.children.find(item=>item.id==="sellers").href).toBe("/admin/marketplace/sellers")});
});
