import {render, screen} from "@testing-library/react";
import {describe, expect, it, vi} from "vitest";
import MarketplaceCommissionsPage from "@/app/admin/marketplace/commissions/page";
import {ADMIN_NAVIGATION} from "@/constants/adminNavigation";
import {fetchMarketplaceCommissions} from "@/services/api/marketplaceCommissionsService";

const unavailable = reason => ({available: false, reason, items: []});
const apiData = {availability: {available: false, reason: "commission_rule_domain_not_present"}, context: {tenant: "SL Beauty", ecosystem: "Beauty Marketplace", currency: "LKR", dateFrom: "2026-07-09", dateTo: "2026-08-07"}, availableCurrencies: ["LKR", "USD"], kpis: [{id: "revenue", label: "Commission Revenue", available: true, value: "15.35", currency: "LKR", definition: "settlement_sum"}, {id: "rate", label: "Average Commission Rate", available: false, value: null, reason: "commission_rate_source_not_present"}], financial: {available: true, currency: "LKR", commissionRevenue: "15.35", pendingSettlementImpact: "89.90", settlementCount: 2}, trend: {available: true, items: [{period: "2026-08-07", commissionRevenue: "15.35", settlementImpact: "134.65"}]}, rules: unavailable("commission_rule_domain_not_present"), approvals: unavailable("commission_approval_domain_not_present"), conflicts: unavailable("commission_conflict_domain_not_present"), distribution: unavailable("commission_rule_types_not_defined"), precedence: unavailable("commission_precedence_configuration_not_present"), health: unavailable("commission_health_formula_not_defined"), scorecard: unavailable("commission_scorecard_formula_not_defined"), statusSummary: unavailable("commission_rule_domain_not_present"), sla: unavailable("commission_approval_sla_not_defined"), permissions: {canView: true, canCreate: false, canUpdate: false, canApprove: false, canExport: true}, meta: {page: 1, perPage: 25, total: 0, totalPages: 1, dataAsOf: "2026-08-07T10:00:00Z", refreshIntervalSeconds: 600}};

vi.mock("next/navigation", () => ({useRouter: () => ({replace: vi.fn()}), usePathname: () => "/admin/marketplace/commissions", useSearchParams: () => new URLSearchParams()}));
vi.mock("@/services/api/marketplaceCommissionsService", () => ({fetchMarketplaceCommissions: vi.fn(async () => apiData), exportMarketplaceCommissions: vi.fn()}));
vi.mock("recharts", () => ({ResponsiveContainer: ({children}) => <div>{children}</div>, ComposedChart: ({children}) => <div>{children}</div>, CartesianGrid: () => null, XAxis: () => null, YAxis: () => null, Tooltip: () => null, Bar: () => null}));

describe("Marketplace Commission Management", () => {
  it("registers the nested Commissions route", () => {const marketplace = ADMIN_NAVIGATION.find(item => item.id === "marketplace"); expect(marketplace.children.find(item => item.id === "commissions").href).toBe("/admin/marketplace/commissions");});
  it("renders settlement-backed financials and explicit rule-domain blockers", async () => {render(<MarketplaceCommissionsPage/>); expect(await screen.findByRole("heading", {name: "Marketplace Commission Management"})).toBeInTheDocument(); expect(screen.getAllByText("LKR 15.35").length).toBeGreaterThan(0); expect(screen.getByText("No commission rule domain configured")).toBeInTheDocument(); expect(screen.getByRole("button", {name: /Create Commission Rule/})).toBeDisabled(); expect(fetchMarketplaceCommissions).toHaveBeenCalled();});
});
