import{fireEvent,render,screen,waitFor}from"@testing-library/react";
import{beforeEach,describe,expect,it,vi}from"vitest";
import{MarketplaceWorkspaceView}from"@/components/admin/marketplace/shared/MarketplaceWorkspaceView";
import{MarketplaceRecordDetailView}from"@/components/admin/marketplace/shared/MarketplaceRecordDetailView";
import{fetchMarketplaceWorkspace,exportMarketplaceWorkspace,fetchMarketplaceOrder,transitionMarketplaceOrder,addMarketplaceOrderNote}from"@/services/api/marketplaceWorkspaceService";

let params=new URLSearchParams();const replace=vi.fn();
vi.mock("next/navigation",()=>({useRouter:()=>({replace}),useSearchParams:()=>params}));
vi.mock("@/services/api/marketplaceWorkspaceService",()=>({fetchMarketplaceWorkspace:vi.fn(),exportMarketplaceWorkspace:vi.fn(),fetchMarketplaceOrder:vi.fn(),fetchMarketplaceReturn:vi.fn(),transitionMarketplaceOrder:vi.fn(),transitionMarketplaceReturn:vi.fn(),addMarketplaceOrderNote:vi.fn()}));
const data:any={source:"database",workspace:"orders",title:"Order Management",description:"Real orders",generatedAt:"2026-08-06T10:00:00Z",permissions:{canView:true,canExport:true,canManage:true},context:{currency:"LKR",currencies:["LKR"],dateFrom:"2026-07-08",dateTo:"2026-08-06"},capability:{availability:"available"},metrics:[{id:"total",label:"Orders",availability:"available",value:1},{id:"gmv",label:"GMV",availability:"available",value:"1200",unit:"LKR"}],columns:[{key:"reference",label:"Order"},{key:"customer",label:"Customer"},{key:"amount",label:"Total"}],items:[{id:"1",reference:"ORD-DB-001",customer:"Database Customer",amount:{value:"1200",currency:"LKR"},detailHref:"/admin/marketplace/orders/1"}],meta:{page:1,perPage:25,total:1,lastPage:1,refreshIntervalSeconds:45}};
describe("integrated marketplace workspaces",()=>{beforeEach(()=>{params=new URLSearchParams();replace.mockClear();vi.mocked(fetchMarketplaceWorkspace).mockResolvedValue(data);vi.mocked(exportMarketplaceWorkspace).mockResolvedValue(undefined as never)});
it("renders database records and metrics",async()=>{render(<MarketplaceWorkspaceView workspace="orders"/>);expect(await screen.findByText("ORD-DB-001")).toBeInTheDocument();expect(screen.getByText("Database Customer")).toBeInTheDocument();expect(screen.getAllByText("LKR 1,200")).toHaveLength(2)});
it("persists sort state in the URL and exports server data",async()=>{render(<MarketplaceWorkspaceView workspace="orders"/>);fireEvent.change(await screen.findByLabelText("Sort records"),{target:{value:"reference"}});expect(replace).toHaveBeenCalledWith("/admin/marketplace/orders?sortBy=reference&page=1",{scroll:false});fireEvent.click(screen.getByRole("button",{name:/Export/}));await waitFor(()=>expect(exportMarketplaceWorkspace).toHaveBeenCalled())});
it("shows unsupported capabilities without fake zeroes",async()=>{vi.mocked(fetchMarketplaceWorkspace).mockResolvedValue({...data,workspace:"promotions",title:"Promotions",capability:{availability:"unavailable",reason:"promotion_domain_missing"},metrics:[{id:"total",label:"Promotions",availability:"unavailable",reason:"promotion_domain_missing"}],columns:[],items:[],meta:{...data.meta,total:0}});render(<MarketplaceWorkspaceView workspace="promotions"/>);expect(await screen.findByText("Configuration required")).toBeInTheDocument();expect(screen.getAllByText("Not available")).toHaveLength(1)});
});
describe("marketplace order detail",()=>{it("loads real detail and sends concurrency-safe transition",async()=>{vi.mocked(fetchMarketplaceOrder).mockResolvedValue({record:{id:"1",reference:"ORD-DB-001",status:"pending",customer:{name:"Customer"},supplier:"Seller",amount:{value:"1200",currency:"LKR"},createdAt:"2026-08-06T10:00:00Z"},items:[],timeline:[],permissions:{canManage:true}});vi.mocked(transitionMarketplaceOrder).mockResolvedValue({} as never);vi.mocked(addMarketplaceOrderNote).mockResolvedValue({} as never);render(<MarketplaceRecordDetailView kind="order" id="1"/>);expect(await screen.findByRole("heading",{name:"ORD-DB-001"})).toBeInTheDocument();fireEvent.change(screen.getByLabelText("Next status"),{target:{value:"confirmed"}});fireEvent.change(screen.getByLabelText("Audit reason"),{target:{value:"Reviewed payment"}});fireEvent.click(screen.getByRole("button",{name:"Update status"}));await waitFor(()=>expect(transitionMarketplaceOrder).toHaveBeenCalledWith("1","confirmed","pending","Reviewed payment"))})});
