import {fireEvent,render,screen} from "@testing-library/react";
import {describe,expect,it,vi} from "vitest";
import MarketplacePromotionsPage from "@/app/admin/marketplace/promotions/page";
import {ADMIN_NAVIGATION} from "@/constants/adminNavigation";
import {fetchMarketplacePromotions,recordPromotionPreviewAction} from "@/services/api/marketplacePromotionsService";

const push=vi.fn();
vi.mock("next/navigation",()=>({useRouter:()=>({push})}));
vi.mock("recharts",()=>({ResponsiveContainer:({children})=><div data-testid="chart">{children}</div>,ComposedChart:({children})=><div>{children}</div>,CartesianGrid:()=>null,XAxis:()=>null,YAxis:()=>null,Tooltip:()=>null,Legend:()=>null,Bar:()=>null,Line:()=>null,PieChart:({children})=><div>{children}</div>,Pie:({children})=><div>{children}</div>,Cell:()=>null}));

describe("Marketplace Promotions & Deals",()=>{
  it("loads the explicit frontend fixture and local audit action",async()=>{const data=await fetchMarketplacePromotions();expect(data.source).toBe("frontend-fixture");expect(data.kpis).toHaveLength(12);expect(data.promotions).toHaveLength(4);const event=await recordPromotionPreviewAction("Pause",[data.promotions[0].id],"QA review");expect(event.source).toBe("local-preview");expect(event.promotionIds).toEqual(["PROM-2026-00138"])});

  it("registers Promotions without deprecated Marketplace submenus",()=>{const marketplace=ADMIN_NAVIGATION.find(item=>item.id==="marketplace");const promotion=marketplace.children.find(item=>item.id==="promotions");const ids=marketplace.children.map(item=>item.id);expect(promotion.href).toBe("/admin/marketplace/promotions");expect(ids).not.toEqual(expect.arrayContaining(["campaigns","vouchers","bundles","deals"]))});

  it("renders the dashboard, charts, operational panels, and right rail",async()=>{render(<MarketplacePromotionsPage/>);expect(await screen.findByRole("heading",{name:"Marketplace Promotions & Deals"})).toBeInTheDocument();expect(screen.getByText("Active Promotions")).toBeInTheDocument();expect(screen.getByRole("heading",{name:/Promotion Revenue & Discount Trend/})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Promotion Type Distribution"})).toBeInTheDocument();for(const heading of ["Pending Promotion Approvals","Promotion Conflict Summary","Promotion Budget & Funding","Seller Participation","Eligibility & Scope Summary","Promotion Performance","Campaign Timeline","Promotion Stacking Precedence","Promotion Health","Priority Promotion Alerts","Approval SLA Summary","Financial Impact","Quick Queues"]){expect(screen.getByRole("heading",{name:heading})).toBeInTheDocument()}});

  it("filters the promotions table by text and status",async()=>{render(<MarketplacePromotionsPage/>);await screen.findByRole("checkbox",{name:"Select SL Beauty August Glow Sale"});fireEvent.change(screen.getByPlaceholderText("Search promotions…"),{target:{value:"Tokyo Beauty"}});expect(screen.getByRole("checkbox",{name:"Select Tokyo Beauty Flash Weekend"})).toBeInTheDocument();expect(screen.queryByRole("checkbox",{name:"Select Premium Skincare Voucher"})).not.toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:/Pending Approval/}));expect(screen.getByRole("checkbox",{name:"Select Tokyo Beauty Flash Weekend"})).toBeInTheDocument()});

  it("supports selection, bulk validation, and column visibility",async()=>{render(<MarketplacePromotionsPage/>);const row=await screen.findByRole("checkbox",{name:"Select SL Beauty August Glow Sale"});const bulk=screen.getByRole("button",{name:/Bulk Actions/});expect(bulk).toBeDisabled();fireEvent.click(row);expect(bulk).toBeEnabled();fireEvent.click(bulk);expect(screen.getByRole("dialog",{name:"Bulk Actions"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Confirm"}));expect(screen.getByRole("alert")).toHaveTextContent("audit reason is required");fireEvent.click(screen.getByRole("button",{name:"Cancel"}));fireEvent.click(screen.getByRole("button",{name:/Columns/}));expect(screen.getByRole("dialog",{name:"Column Visibility"})).toBeInTheDocument();expect(screen.getByLabelText("Promotion ID")).toBeChecked()});

  it("opens a working create form and row action workflow",async()=>{render(<MarketplacePromotionsPage/>);fireEvent.click(await screen.findByRole("button",{name:/Create Promotion/}));expect(screen.getByRole("dialog",{name:"Create Promotion"})).toBeInTheDocument();expect(screen.getByPlaceholderText("Promotion name")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Cancel"}));fireEvent.click(screen.getByRole("button",{name:"Actions for Haircare Bundle Week"}));fireEvent.click(screen.getByRole("button",{name:"Pause Promotion"}));expect(screen.getByRole("dialog",{name:"Pause Promotion: Haircare Bundle Week"})).toBeInTheDocument()});

  it("opens promotion names, IDs, and review actions with the selected record ID",async()=>{render(<MarketplacePromotionsPage/>);fireEvent.click(await screen.findByRole("button",{name:"Tokyo Beauty Flash Weekend"}));expect(push).toHaveBeenCalledWith("/admin/marketplace/promotions/PROM-2026-00119");fireEvent.click(screen.getByRole("button",{name:"PROM-2026-00104"}));expect(push).toHaveBeenCalledWith("/admin/marketplace/promotions/PROM-2026-00104");fireEvent.click(screen.getByRole("button",{name:"Actions for Haircare Bundle Week"}));fireEvent.click(screen.getByRole("button",{name:"Review Promotion"}));expect(push).toHaveBeenCalledWith("/admin/marketplace/promotions/PROM-2026-00098")});
});
