import { ReportsAuditFullData } from './reports-audit.types';

export const REPORTS_AUDIT_TABS = [
  { id: 'overview', label: 'Audit Overview' },
  { id: 'change-history', label: 'Change History' },
];

export const MOCK_REPORTS_AUDIT_DATA: ReportsAuditFullData = {
  row1Kpis: [
    {
      id: 'kpi-audit-events',
      title: 'Audit Events',
      value: '326.4K',
      trend: '+12.4%',
      trendDirection: 'up',
      color: '#3b82f6',
      sparkline: [280, 295, 310, 305, 320, 315, 326.4],
    },
    {
      id: 'kpi-admin-changes',
      title: 'Administration Changes',
      value: '8,742',
      trend: '+4.2%',
      trendDirection: 'up',
      color: '#10b981',
      sparkline: [7500, 7800, 8100, 8300, 8600, 8500, 8742],
    },
    {
      id: 'kpi-reports',
      title: 'Reports',
      value: '524',
      trend: '+8.1%',
      trendDirection: 'up',
      color: '#8b5cf6',
      sparkline: [420, 450, 480, 470, 500, 510, 524],
    },
    {
      id: 'kpi-exports',
      title: 'Exports',
      value: '386',
      trend: '+2.5%',
      trendDirection: 'up',
      color: '#0284c7',
      sparkline: [310, 330, 350, 340, 370, 380, 386],
    },
    {
      id: 'kpi-scheduled-reports',
      title: 'Scheduled Reports',
      value: '222',
      trend: '0.0%',
      trendDirection: 'neutral',
      color: '#6366f1',
      sparkline: [210, 215, 220, 220, 222, 222, 222],
    },
    {
      id: 'kpi-audit-exceptions',
      title: 'Audit Exceptions',
      value: '22',
      trend: '-3.5%',
      trendDirection: 'down',
      status: 'Warning',
      color: '#f59e0b',
      sparkline: [28, 26, 25, 24, 23, 23, 22],
    },
    {
      id: 'kpi-failed-exports',
      title: 'Failed Exports',
      value: '34',
      trend: '-8.2%',
      trendDirection: 'down',
      status: 'Alert',
      color: '#ef4444',
      sparkline: [42, 40, 38, 39, 36, 35, 34],
    },
    {
      id: 'kpi-evidence-packages',
      title: 'Evidence Packages',
      value: '48',
      trend: '+6.5%',
      trendDirection: 'up',
      color: '#0ea5e9',
      sparkline: [38, 40, 42, 44, 45, 47, 48],
    },
    {
      id: 'kpi-high-risk-changes',
      title: 'High-Risk Changes',
      value: '14',
      trend: '-12.5%',
      trendDirection: 'down',
      status: 'Critical',
      color: '#dc2626',
      sparkline: [20, 18, 17, 16, 15, 15, 14],
    },
  ],

  row2Kpis: [
    { id: 'kpi-identity-changes', title: 'Identity Changes', value: '1,428', color: '#64748b' },
    { id: 'kpi-role-permission-changes', title: 'Role & Permission Changes', value: '912', color: '#64748b' },
    { id: 'kpi-organization-changes', title: 'Organization Changes', value: '684', color: '#64748b' },
    { id: 'kpi-configuration-changes', title: 'Configuration Changes', value: '1,736', color: '#64748b' },
    { id: 'kpi-localization-changes', title: 'Localization Changes', value: '524', color: '#64748b' },
    { id: 'kpi-communication-changes', title: 'Communication Changes', value: '486', color: '#64748b' },
    { id: 'kpi-security-changes', title: 'Security Changes', value: '912', color: '#64748b' },
    { id: 'kpi-workflow-changes', title: 'Workflow Changes', value: '778', color: '#64748b' },
    { id: 'kpi-data-governance-changes', title: 'Data Governance Changes', value: '639', color: '#64748b' },
  ],

  auditRecords: [
    {
      id: 'rec-1',
      auditId: 'AUD-2026-05-12-0001',
      timestamp: 'May 12, 2026 10:15:32',
      actor: 'jdoe@slbeauty.com',
      actorType: 'Human Administrator',
      changeArea: 'User Management',
      operation: 'Create',
      entity: 'User',
      result: 'Success',
      integrity: 'Verified',
      risk: 'Low',
      businessUnit: 'Global',
      channelRegion: 'All Channels',
      sourceIP: '10.20.12.14',
      sessionId: 'sess-9182a11b',
    },
    {
      id: 'rec-2',
      auditId: 'AUD-2026-05-12-0002',
      timestamp: 'May 12, 2026 09:47:11',
      actor: 'sec-service@slbeauty.com',
      actorType: 'Service Principal',
      changeArea: 'Roles & Permissions',
      operation: 'Update',
      entity: 'Role',
      result: 'Success',
      integrity: 'Verified',
      risk: 'Low',
      businessUnit: 'Global',
      channelRegion: 'All Channels',
      sourceIP: '10.20.12.99',
      sessionId: 'sess-3391b44c',
    },
    {
      id: 'rec-3',
      auditId: 'AUD-2026-05-12-0003',
      timestamp: 'May 12, 2026 06:12:08',
      actor: 'asmith@slbeauty.com',
      actorType: 'Human Administrator',
      changeArea: 'System Configuration',
      operation: 'Update',
      entity: 'Setting',
      result: 'Success',
      integrity: 'Verified',
      risk: 'Medium',
      businessUnit: 'Global',
      channelRegion: 'All Channels',
      sourceIP: '10.20.34.57',
      sessionId: 'sess-8174d23f',
    },
    {
      id: 'rec-4',
      auditId: 'AUD-2026-05-12-0004',
      timestamp: 'May 12, 2026 08:30:44',
      actor: 'wf-approval@slbeauty.com',
      actorType: 'Workflow / System',
      changeArea: 'Workflows & Approvals',
      operation: 'Approve',
      entity: 'Approval',
      result: 'Success',
      integrity: 'Verified',
      risk: 'Medium',
      businessUnit: 'APAC Retail',
      channelRegion: 'APAC / SG',
      sourceIP: '10.20.45.12',
      sessionId: 'sess-7721e90d',
    },
    {
      id: 'rec-5',
      auditId: 'AUD-2026-05-12-0005',
      timestamp: 'May 12, 2026 06:44:02',
      actor: 'gov-bot@slbeauty.com',
      actorType: 'Automated Job',
      changeArea: 'Data Governance',
      operation: 'Update',
      entity: 'Asset',
      result: 'Success',
      integrity: 'Verified',
      risk: 'Low',
      businessUnit: 'Global',
      channelRegion: 'Global',
      sourceIP: '10.20.08.100',
      sessionId: 'sess-1002f55a',
    },
    {
      id: 'rec-6',
      auditId: 'AUD-2026-05-12-0006',
      timestamp: 'May 12, 2026 07:21:56',
      actor: 'hwilson@slbeauty.com',
      actorType: 'Human Administrator',
      changeArea: 'Localization & Regional',
      operation: 'Update',
      entity: 'Language',
      result: 'Success',
      integrity: 'Verified',
      risk: 'Low',
      businessUnit: 'EU Retail',
      channelRegion: 'EU / FR',
      sourceIP: '10.20.88.22',
      sessionId: 'sess-6610c88b',
    },
    {
      id: 'rec-7',
      auditId: 'AUD-2026-05-12-0007',
      timestamp: 'May 12, 2026 06:03:09',
      actor: 'sec-agent@slbeauty.com',
      actorType: 'Service Principal',
      changeArea: 'Reports',
      operation: 'Create',
      entity: 'Export Job',
      result: 'Success',
      integrity: 'Verified',
      risk: 'Low',
      businessUnit: 'Global',
      channelRegion: 'Global',
      sourceIP: '10.20.90.15',
      sessionId: 'sess-9901d34c',
    },
  ],

  selectedRecord: {
    auditId: 'AUD-2026-05-12-0003',
    timestamp: 'May 12, 2026 06:12:08',
    actor: 'asmith@slbeauty.com',
    actorType: 'Human Administrator',
    changeArea: 'System Configuration',
    operation: 'Update',
    entity: 'Setting: Password Policy',
    result: 'Success',
    integrity: 'Verified',
    riskLevel: 'Medium',
    businessUnit: 'Global',
    channelRegion: 'Global',
    sourceIP: '10.20.34.57',
    sessionId: 'sess-8174d23f',
  },

  comparisonFields: [
    { field: 'Minimum Password Length', before: 8, after: 12, changed: true },
    { field: 'Require Special Character', before: 'No', after: 'Yes', changed: true },
    { field: 'Password Expiration (Days)', before: 90, after: 90, changed: false },
    { field: 'Lockout Threshold', before: 5, after: 5, changed: false },
    { field: 'Lockout Duration (Minutes)', before: 15, after: 15, changed: false },
  ],

  changeSummaries: [
    { id: 'cs-1', changeArea: 'Identity Management', changes: 1428, success: 1386, failed: 28, partial: 9, cancelled: 5, successRate: '97.0%', highRisk: 3 },
    { id: 'cs-2', changeArea: 'Roles & Permissions', changes: 912, success: 884, failed: 16, partial: 8, cancelled: 4, successRate: '97.0%', highRisk: 1 },
    { id: 'cs-3', changeArea: 'System Configuration', changes: 1736, success: 1701, failed: 21, partial: 9, cancelled: 5, successRate: '98.0%', highRisk: 4 },
    { id: 'cs-4', changeArea: 'Workflows & Approvals', changes: 778, success: 748, failed: 19, partial: 7, cancelled: 4, successRate: '96.1%', highRisk: 2 },
    { id: 'cs-5', changeArea: 'Data Governance', changes: 639, success: 614, failed: 15, partial: 6, cancelled: 4, successRate: '96.0%', highRisk: 2 },
    { id: 'cs-6', changeArea: 'Localization & Regional', changes: 524, success: 515, failed: 5, partial: 2, cancelled: 2, successRate: '98.3%', highRisk: 1 },
    { id: 'cs-7', changeArea: 'Communications', changes: 486, success: 475, failed: 6, partial: 3, cancelled: 2, successRate: '97.7%', highRisk: 1 },
    { id: 'cs-8', changeArea: 'Operations & Maintenance', changes: 638, success: 621, failed: 9, partial: 5, cancelled: 3, successRate: '97.3%', highRisk: 2 },
  ],

  highRiskChanges: [
    { id: 'hr-1', auditId: 'AUD-2026-05-11-0987', changeArea: 'System Configuration', entity: 'Auth Policy', operation: 'Update', actor: 'jdoe@slbeauty.com', risk: 'High', result: 'Success', time: 'May 11, 2026 14:22' },
    { id: 'hr-2', auditId: 'AUD-2026-05-11-0765', changeArea: 'Data Governance', entity: 'Customer Export', operation: 'Create', actor: 'sec-ops@slbeauty.com', risk: 'High', result: 'Success', time: 'May 11, 2026 14:18' },
    { id: 'hr-3', auditId: 'AUD-2026-05-10-0432', changeArea: 'Roles & Permissions', entity: 'Admin Role', operation: 'Update', actor: 'asmith@slbeauty.com', risk: 'High', result: 'Success', time: 'May 10, 2026 11:09' },
    { id: 'hr-4', auditId: 'AUD-2026-05-09-0123', changeArea: 'System Configuration', entity: 'SSO Settings', operation: 'Update', actor: 'sec-identity@slbeauty.com', risk: 'High', result: 'Success', time: 'May 9, 2026 09:55' },
    { id: 'hr-5', auditId: 'AUD-2026-05-07-0610', changeArea: 'Operations & Maintenance', entity: 'DB Access', operation: 'Update', actor: 'dua-icon@slbeauty.com', risk: 'High', result: 'Success', time: 'May 7, 2026 18:43' },
  ],

  approvalTrace: [
    { step: 'Request Initiated', approver: 'asmith@slbeauty.com', decision: '—', time: 'May 11, 2026 14:32' },
    { step: 'Manager Approval', approver: 'mroberts@slbeauty.com', decision: 'Approved', time: 'May 12, 2026 09:15:41' },
    { step: 'Security Review', approver: 'sec-ops@slbeauty.com', decision: 'Approved', time: 'May 12, 2026 09:17:22' },
    { step: 'Final Approval', approver: 'vps@slbeauty.com', decision: 'Approved', time: 'May 12, 2026 09:18:07' },
    { step: 'Change Applied', approver: 'wf-approval@slbeauty.com', decision: 'Completed', time: 'May 12, 2026 09:19:03' },
  ],

  reportCatalogue: [
    { id: 'rep-1', reportName: 'Administration Audit Summary', category: 'Audit', frequency: 'Daily', lastRun: 'May 12, 2026 06:00', status: 'Completed' },
    { id: 'rep-2', reportName: 'Access Review Report', category: 'Risk', frequency: 'Daily', lastRun: 'May 12, 2026 05:15', status: 'Completed' },
    { id: 'rep-3', reportName: 'High-Risk Changes Report', category: 'Audit', frequency: 'Daily', lastRun: 'May 12, 2026 04:30', status: 'Completed' },
    { id: 'rep-4', reportName: 'Access Review Report', category: 'Identity', frequency: 'Weekly', lastRun: 'May 11, 2026 09:00', status: 'Completed' },
    { id: 'rep-5', reportName: 'Configuration Drift Report', category: 'Config', frequency: 'Weekly', lastRun: 'May 11, 2026 08:30', status: 'Completed' },
  ],

  scheduledReports: [
    { id: 'sch-1', report: 'Administration Audit Summary', frequency: 'Daily', nextRun: 'May 13, 2026 06:00', owner: 'asmith@slbeauty.com', status: 'Active' },
    { id: 'sch-2', report: 'Access Review Report', frequency: 'Weekly', nextRun: 'May 18, 2026 09:00', owner: 'sec-ops@slbeauty.com', status: 'Active' },
    { id: 'sch-3', report: 'Configuration Drift Report', frequency: 'Daily', nextRun: 'May 13, 2026 08:30', owner: 'ops@slbeauty.com', status: 'Active' },
    { id: 'sch-4', report: 'User Access Review', frequency: 'Monthly', nextRun: 'Jun 01, 2026 07:00', owner: 'compliance@slbeauty.com', status: 'Active' },
  ],

  exportJobs: [
    { id: 'exp-1', exportName: 'Customer Data Export', status: 'Completed', requested: 'May 12, 09:00', completed: 'May 12, 09:12', size: '1.2 GB', requestedBy: 'sec-export@slbeauty.com' },
    { id: 'exp-2', exportName: 'Product Data Export', status: 'Completed', requested: 'May 12, 08:30', completed: 'May 12, 08:45', size: '856 MB', requestedBy: 'sec-export@slbeauty.com' },
    { id: 'exp-3', exportName: 'Financial Data Export', status: 'Completed', requested: 'May 11, 19:10', completed: 'May 11, 19:35', size: '2.4 GB', requestedBy: 'sec-export@slbeauty.com' },
    { id: 'exp-4', exportName: 'Marketing Data Export', status: 'Generating', requested: 'May 12, 10:01', completed: '—', size: '1.1 GB', requestedBy: 'sec-export@slbeauty.com' },
  ],

  sensitiveExports: [
    { id: 'sen-1', exportName: 'Customer PII Export', status: 'Awaiting Review', risk: 'High', reviewer: 'sec-ops@slbeauty.com', due: 'May 12, 13:00' },
    { id: 'sen-2', exportName: 'Financial Report', status: 'Awaiting Review', risk: 'High', reviewer: 'finance-lead@slbeauty.com', due: 'May 12, 15:30' },
    { id: 'sen-3', exportName: 'Employee Data Export', status: 'Pending Review', risk: 'Medium', reviewer: 'hr-compliance@slbeauty.com', due: 'May 12, 16:00' },
  ],

  failedExports: [
    { id: 'fail-1', exportName: 'Sales Data Export', reason: 'Timeout', failed: 'May 12, 08:12' },
    { id: 'fail-2', exportName: 'Inventory Export', reason: 'Permission Denied', failed: 'May 11, 19:45' },
    { id: 'fail-3', exportName: 'Knowledge Export', reason: 'Validation Error', failed: 'May 11, 14:22' },
    { id: 'fail-4', exportName: 'Marketing Export', reason: 'System Error', failed: 'May 10, 23:11' },
  ],

  changeVolumeData: [
    { date: 'Feb 13', volume: 110 },
    { date: 'Feb 20', volume: 180 },
    { date: 'Feb 27', volume: 140 },
    { date: 'Mar 06', volume: 220 },
    { date: 'Mar 13', volume: 195 },
    { date: 'Mar 20', volume: 240 },
    { date: 'Mar 27', volume: 210 },
    { date: 'Apr 03', volume: 260 },
    { date: 'Apr 10', volume: 230 },
    { date: 'Apr 17', volume: 290 },
    { date: 'Apr 24', volume: 275 },
    { date: 'May 01', volume: 310 },
    { date: 'May 08', volume: 295 },
    { date: 'May 12', volume: 330 },
  ],

  highRiskTrendData: [
    { name: 'Feb 13', count: 12, color: '#dc2626' },
    { name: 'Feb 20', count: 18, color: '#dc2626' },
    { name: 'Feb 27', count: 15, color: '#dc2626' },
    { name: 'Mar 06', count: 24, color: '#dc2626' },
    { name: 'Mar 13', count: 20, color: '#dc2626' },
    { name: 'Mar 20', count: 28, color: '#dc2626' },
    { name: 'Mar 27', count: 22, color: '#dc2626' },
    { name: 'Apr 03', count: 32, color: '#dc2626' },
    { name: 'Apr 10', count: 26, color: '#dc2626' },
    { name: 'Apr 17', count: 30, color: '#dc2626' },
    { name: 'Apr 24', count: 25, color: '#dc2626' },
    { name: 'May 01', count: 35, color: '#dc2626' },
    { name: 'May 08', count: 29, color: '#dc2626' },
    { name: 'May 12', count: 14, color: '#dc2626' },
  ],

  reportsExportsTrendData: [
    { date: 'Feb 13', reports: 120, exports: 90 },
    { date: 'Feb 20', reports: 150, exports: 110 },
    { date: 'Feb 27', reports: 140, exports: 105 },
    { date: 'Mar 06', reports: 180, exports: 130 },
    { date: 'Mar 13', reports: 210, exports: 155 },
    { date: 'Mar 20', reports: 230, exports: 170 },
    { date: 'Mar 27', reports: 220, exports: 160 },
    { date: 'Apr 03', reports: 260, exports: 190 },
    { date: 'Apr 10', reports: 250, exports: 185 },
    { date: 'Apr 17', reports: 290, exports: 215 },
    { date: 'Apr 24', reports: 280, exports: 210 },
    { date: 'May 01', reports: 320, exports: 240 },
    { date: 'May 08', reports: 310, exports: 235 },
    { date: 'May 12', reports: 350, exports: 260 },
  ],

  healthMatrixData: [
    { category: 'Identity Management', poor: 98, fair: 98, good: 98, excellent: 98 },
    { category: 'Roles & Permissions', poor: 97, fair: 97, good: 97, excellent: 97 },
    { category: 'System Configuration', poor: 97, fair: 97, good: 97, excellent: 97 },
    { category: 'Workflows & Approvals', poor: 96, fair: 96, good: 96, excellent: 96 },
    { category: 'Data Governance', poor: 96, fair: 96, good: 96, excellent: 96 },
    { category: 'Localization & Regional', poor: 98, fair: 98, good: 98, excellent: 98 },
    { category: 'Communications & Maintenance', poor: 97, fair: 97, good: 97, excellent: 97 },
    { category: 'Overall', poor: 98, fair: 98, good: 98, excellent: 98 },
  ],

  auditIntegrityDonut: [
    { name: 'Integrity Verified', value: 320300, color: '#10b981' },
    { name: 'Integrity Warning', value: 3200, color: '#f59e0b' },
    { name: 'Integrity Failed', value: 3100, color: '#ef4444' },
  ],

  auditIntegrityMetrics: {
    verified: '320.3K',
    warning: '3.2K',
    failed: '3.1K',
    total: '326.4K',
    successRate: '97.7%',
  },

  governanceGates: [
    { id: 'gate-1', title: 'Immutable Audit Records', status: 'Passed' },
    { id: 'gate-2', title: 'Change Approval Required', status: 'Passed' },
    { id: 'gate-3', title: 'Segregation of Duties', status: 'Passed' },
    { id: 'gate-4', title: 'Audit Integrity Verified', status: 'Passed' },
    { id: 'gate-5', title: 'Retention Policy Compliant', status: 'Passed' },
    { id: 'gate-6', title: 'Evidence Package Generated', status: 'Passed' },
    { id: 'gate-7', title: 'Export Approval Enforced', status: 'Passed' },
    { id: 'gate-8', title: 'High-Risk Alerting', status: 'Passed' },
  ],

  recentEvidenceActivity: [
    { id: 'act-1', timestamp: 'May 12, 2026 10:15:32', activity: 'Created user account', entity: 'jdoe', actor: 'jdoe@slbeauty.com', size: '1.2 GB', requestedBy: 'sec-export@slbeauty.com' },
    { id: 'act-2', timestamp: 'May 12, 2026 10:05:11', activity: 'High-risk permission granted', entity: 'asmith', actor: 'asmith@slbeauty.com', size: '856 MB', requestedBy: 'sec-export@slbeauty.com' },
    { id: 'act-3', timestamp: 'May 12, 2026 09:47:22', activity: 'Updated role permissions', entity: 'sec-role', actor: 'sec-ops@slbeauty.com', size: '2.4 GB', requestedBy: 'sec-export@slbeauty.com' },
    { id: 'act-4', timestamp: 'May 12, 2026 09:18:07', activity: 'Change approved', entity: 'sys-config', actor: 'vps@slbeauty.com', size: '1.1 GB', requestedBy: 'sec-export@slbeauty.com' },
    { id: 'act-5', timestamp: 'May 12, 2026 09:12:08', activity: 'Updated system setting', entity: 'pwd-policy', actor: 'asmith@slbeauty.com', size: '—', requestedBy: 'sec-export@slbeauty.com' },
  ],

  recentAuditActivity: [
    { id: 'aud-act-1', timestamp: 'May 12, 2026 00:15:32', activity: 'Created user account', actor: 'jdoe@slbeauty.com', actorType: 'Human Administrator', result: 'Success', integrity: 'Verified' },
    { id: 'aud-act-2', timestamp: 'May 12, 2026 00:05:11', activity: 'Export job completed', actor: 'sec-service@slbeauty.com', actorType: 'Service Principal', result: 'Success', integrity: 'Verified' },
    { id: 'aud-act-3', timestamp: 'May 12, 2026 09:47:22', activity: 'Updated role permissions', actor: 'sec-ops@slbeauty.com', actorType: 'Human Administrator', result: 'Success', integrity: 'Verified' },
    { id: 'aud-act-4', timestamp: 'May 12, 2026 09:36:07', activity: 'Change approved', actor: 'vps@slbeauty.com', actorType: 'Human Administrator', result: 'Success', integrity: 'Verified' },
    { id: 'aud-act-5', timestamp: 'May 12, 2026 09:12:08', activity: 'Updated system setting', actor: 'asmith@slbeauty.com', actorType: 'Human Administrator', result: 'Success', integrity: 'Verified' },
  ],

  healthScore: 98,

  quickQueues: {
    pendingApprovals: 12,
    exportsAwaitingReview: 8,
    failedExports: 14,
    unreviewedHighRisk: 14,
  },

  summaryStats: {
    totalChanges: '8,742',
    successRate: '97.7%',
    highRiskChanges: 14,
    reportsGenerated: 524,
    exportsCompleted: 312,
    failedExports: 34,
    exportsAwaitingApproval: 12,
    riskyAuthEvents: 6,
    policyViolations: 3,
    openAuditExceptions: 22,
  },
};
