<?php
namespace App\Http\Controllers\Api\Admin;
use App\Http\Controllers\Controller; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\Rule;
class DeliveryConfigurationController extends Controller {
 public function index(Request $r):JsonResponse{$this->permit($r,'logistics.view');$f=$r->validate(['search'=>['nullable','string','max:150'],'rule_type'=>['nullable','string','max:40'],'status'=>['nullable','string','max:30'],'region'=>['nullable','string','max:100'],'carrier_id'=>['nullable','integer'],'sort'=>['nullable',Rule::in(['created_at','name','reference','rule_type','status','effective_from'])],'direction'=>['nullable',Rule::in(['asc','desc'])],'per_page'=>['nullable','integer','between:1,100']]);$q=$this->query($f);$rows=(clone$q)->leftJoin('logistics_partners as lp','lp.id','=','dc.logistics_partner_id')->select('dc.*','lp.name as carrier_name')->orderBy('dc.'.($f['sort']??'created_at'),$f['direction']??'desc')->paginate($f['per_page']??25);return response()->json(['data'=>['metrics'=>$this->metrics($q),'intelligence'=>$this->intelligence($q),'configurations'=>$rows]]);}
 public function show(Request$r,string$id):JsonResponse{$this->permit($r,'logistics.view');$row=$this->find($id);abort_unless($row,404);return response()->json(['data'=>['configuration'=>$row,'lifecycle'=>DB::table('activity_log')->where('subject_type','delivery_configuration')->where('subject_id',$row->id)->oldest()->get()]]);}
 public function store(Request$r):JsonResponse{$this->permit($r,'logistics.create');return $this->save($r);}
 public function update(Request$r,string$id):JsonResponse{$this->permit($r,'logistics.update');$row=$this->find($id);abort_unless($row,404);return $this->save($r,(int)$row->id);}
 public function status(Request$r,string$id):JsonResponse{$this->permit($r,'logistics.update');$row=$this->find($id);abort_unless($row,404);$d=$r->validate(['status'=>['required',Rule::in(['draft','active','scheduled','suspended','archived'])]]);if($d['status']==='active')$this->assertNoConflict((array)$row,$row->id);DB::table('delivery_configurations')->where('id',$row->id)->update(['status'=>$d['status'],'updated_by'=>$r->user()->id,'updated_at'=>now()]);activity('admin')->causedBy($r->user())->withProperties(['from'=>$row->status,'to'=>$d['status']])->log('delivery_configuration.status_changed');return response()->json(['data'=>['configuration'=>$this->find((string)$row->id)]]);}
 private function save(Request$r,?int$id=null):JsonResponse{$d=$r->validate(['name'=>[$id?'sometimes':'required','string','max:150'],'rule_type'=>[$id?'sometimes':'required','string','max:40'],'zone_name'=>[$id?'sometimes':'required','string','max:150'],'region'=>['nullable','string','max:100'],'province'=>['nullable','string','max:100'],'district'=>['nullable','string','max:100'],'city_area'=>['nullable','string','max:120'],'logistics_partner_id'=>['nullable','integer','exists:logistics_partners,id'],'service'=>['nullable','string','max:80'],'service_level'=>['nullable','string','max:80'],'base_rate'=>['nullable','numeric','min:0'],'surcharge'=>['nullable','numeric','min:0'],'free_shipping_threshold'=>['nullable','numeric','min:0'],'capacity_limit'=>['nullable','integer','min:0'],'cutoff_time'=>['nullable','date_format:H:i'],'promised_sla_days'=>['nullable','integer','between:0,365'],'same_day'=>['nullable','boolean'],'next_day'=>['nullable','boolean'],'cod'=>['nullable','boolean'],'rto'=>['nullable','boolean'],'effective_from'=>['nullable','date'],'effective_to'=>['nullable','date','after_or_equal:effective_from'],'status'=>['nullable',Rule::in(['draft','active','scheduled','suspended','archived'])]]);if(($d['status']??null)==='active')$this->assertNoConflict($d,$id);$creating=$id===null;$id=DB::transaction(function()use($r,$d,$id,$creating){$d['updated_by']=$r->user()->id;$d['updated_at']=now();if($creating){$d['uuid']=(string)Str::uuid();$d['reference']='DC-'.now()->format('Y').'-'.str_pad((string)((DB::table('delivery_configurations')->max('id')??0)+1),6,'0',STR_PAD_LEFT);$d['created_by']=$r->user()->id;$d['created_at']=now();$id=DB::table('delivery_configurations')->insertGetId($d);}else DB::table('delivery_configurations')->where('id',$id)->update($d);activity('admin')->causedBy($r->user())->withProperties(['configuration_id'=>$id])->log($creating?'delivery_configuration.created':'delivery_configuration.updated');return$id;});return response()->json(['data'=>['configuration'=>$this->find((string)$id)]],$creating?201:200);}
 private function query(array$f){$q=DB::table('delivery_configurations as dc')->whereNull('dc.deleted_at');foreach(['rule_type','status','region']as$k)if(!empty($f[$k]))$q->where('dc.'.$k,$f[$k]);if(!empty($f['carrier_id']))$q->where('dc.logistics_partner_id',$f['carrier_id']);if(!empty($f['search'])){$s='%'.$f['search'].'%';$q->where(fn($x)=>$x->where('dc.name','like',$s)->orWhere('dc.reference','like',$s)->orWhere('dc.zone_name','like',$s));}return$q;}
 private function metrics($q):array{$total=(clone$q)->count();return['activeDeliveryZones'=>(clone$q)->where('dc.rule_type','Delivery Zone')->where('dc.status','active')->count(),'activeDeliveryServices'=>(clone$q)->whereNotNull('dc.service')->where('dc.status','active')->distinct('dc.service')->count('dc.service'),'activeRateRules'=>(clone$q)->where('dc.rule_type','Rate Rule')->where('dc.status','active')->count(),'activeSlaRules'=>(clone$q)->where('dc.rule_type','SLA Rule')->where('dc.status','active')->count(),'activeCapacityRules'=>(clone$q)->where('dc.rule_type','Capacity Rule')->where('dc.status','active')->count(),'carrierZoneMappings'=>(clone$q)->whereNotNull('dc.logistics_partner_id')->count(),'configurationConflicts'=>0,'zonesAtCapacityRisk'=>(clone$q)->where('dc.capacity_limit','>',0)->whereRaw('dc.capacity_used * 100 >= dc.capacity_limit * 90')->count(),'rateRulesExpiring'=>(clone$q)->whereDate('dc.effective_to','<',today())->count(),'rateRulesExpiringSoon'=>(clone$q)->whereBetween('dc.effective_to',[today(),today()->addDays(30)])->count(),'slaBreachRiskRules'=>0,'pendingConfigurationApprovals'=>(clone$q)->whereIn('dc.approval_status',['draft','pending_review'])->count(),'configurationExceptions'=>0,'lastSynced'=>now()->toIso8601String()];}
 private function intelligence($q):array{$m=$this->metrics($q);return['healthScore'=>0,'healthLabel'=>'Critical','healthTrend'=>'—','alerts'=>[],'coverageSummary'=>['zonesCoveredRatio'=>(string)$m['activeDeliveryZones'],'zonesPercentage'=>0,'servicesCoveredRatio'=>(string)$m['activeDeliveryServices'],'servicesPercentage'=>0],'rateSummary'=>['activeRateRules'=>$m['activeRateRules'],'expiring'=>$m['rateRulesExpiringSoon'],'conflicts'=>0],'capacitySummary'=>['utilisationPercentage'=>0,'atRiskZones'=>$m['zonesAtCapacityRisk'],'capacityLimitText'=>'—'],'slaSummary'=>['slaCompliancePercentage'=>0,'breachRiskRules'=>0,'breached30D'=>0],'carrierEligibilitySummary'=>['eligible'=>$m['carrierZoneMappings'],'restricted'=>0,'ineligible'=>0],'approvalConflictSummary'=>['pendingApproval'=>$m['pendingConfigurationApprovals'],'pendingReview'=>0,'conflicts'=>0],'quickQueues'=>['conflicts'=>0,'pendingApproval'=>$m['pendingConfigurationApprovals'],'exceptions'=>0]];}
 private function assertNoConflict(array$d,?int$id):void{$q=DB::table('delivery_configurations')->whereNull('deleted_at')->where('status','active')->where('zone_name',$d['zone_name']??'')->where('service',$d['service']??null)->where('logistics_partner_id',$d['logistics_partner_id']??null)->where('priority',$d['priority']??100);if($id)$q->where('id','<>',$id);abort_if($q->exists(),422,'An active configuration with the same zone, service, carrier and priority already exists.');}
 private function find(string$id){return DB::table('delivery_configurations as dc')->leftJoin('logistics_partners as lp','lp.id','=','dc.logistics_partner_id')->whereNull('dc.deleted_at')->where(fn($q)=>$q->where('dc.reference',$id)->orWhere('dc.uuid',$id)->when(ctype_digit($id),fn($x)=>$x->orWhere('dc.id',(int)$id)))->select('dc.*','lp.name as carrier_name')->first();} private function permit(Request$r,string$p):void{abort_unless($r->user()->hasPermission($p),403);}
}
