<?php
namespace App\Http\Controllers\Api\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
class InventoryAllocationController extends Controller {
 private const STATUSES=['pending','fully_allocated','partially_allocated','failed','transfer_required','completed','cancelled'];
 public function index(Request $r): JsonResponse {$this->permit($r,'logistics.view');$f=$r->validate(['search'=>['nullable','string','max:150'],'allocation_status'=>['nullable',Rule::in(self::STATUSES)],'facility_id'=>['nullable','integer'],'supplier_id'=>['nullable','integer'],'date_from'=>['nullable','date'],'date_to'=>['nullable','date','after_or_equal:date_from'],'sort'=>['nullable',Rule::in(['created_at','updated_at','reference','status','requested_quantity'])],'direction'=>['nullable',Rule::in(['asc','desc'])],'per_page'=>['nullable','integer','between:1,100']]);$q=$this->query($f);$total=(clone$q)->count();$counts=(clone$q)->groupBy('inventory_allocations.status')->selectRaw('inventory_allocations.status,COUNT(*) count')->get()->pluck('count','status');$rows=(clone$q)->leftJoin('orders','orders.id','=','inventory_allocations.order_id')->leftJoin('products','products.id','=','inventory_allocations.product_id')->leftJoin('suppliers','suppliers.id','=','inventory_allocations.supplier_id')->leftJoin('logistics_facilities as source','source.id','=','inventory_allocations.source_facility_id')->leftJoin('logistics_facilities as destination','destination.id','=','inventory_allocations.destination_facility_id')->select(['inventory_allocations.*','orders.order_number','products.name as product_name','suppliers.company_name as supplier_name','source.name as source_facility','destination.name as destination_facility'])->orderBy('inventory_allocations.'.($f['sort']??'created_at'),$f['direction']??'desc')->paginate($f['per_page']??15);$distribution=collect(self::STATUSES)->map(fn($s)=>['status'=>$s,'count'=>(int)($counts[$s]??0),'percentage'=>$total?round(($counts[$s]??0)/$total*100,1):0]);$trend=(clone$q)->where('inventory_allocations.created_at','>=',now()->subDays(29)->startOfDay())->groupByRaw('DATE(inventory_allocations.created_at)')->selectRaw('DATE(inventory_allocations.created_at) date,COUNT(*) requests,SUM(CASE WHEN inventory_allocations.status = ? THEN 1 ELSE 0 END) allocated',['fully_allocated'])->orderBy('date')->get();return response()->json(['data'=>['updated_at'=>now()->toIso8601String(),'kpis'=>['total'=>$total,'fully_allocated'=>(int)($counts['fully_allocated']??0),'partially_allocated'=>(int)($counts['partially_allocated']??0),'pending'=>(int)($counts['pending']??0),'failed'=>(int)($counts['failed']??0),'transfer_required'=>(int)($counts['transfer_required']??0),'active_reservations'=>DB::table('inventory_reservations')->where('status','active')->count(),'expiring_reservations'=>DB::table('inventory_reservations')->where('status','active')->whereBetween('expires_at',[now(),now()->addDay()])->count()],'trend'=>$trend,'distribution'=>$distribution,'summary'=>$distribution,'allocations'=>$rows]]);}
 public function show(Request$r,int$a):JsonResponse{$this->permit($r,'logistics.view');$row=DB::table('inventory_allocations')->whereNull('deleted_at')->find($a);abort_unless($row,404);return response()->json(['data'=>['allocation'=>$row,'reservations'=>DB::table('inventory_reservations')->where('inventory_allocation_id',$a)->get(),'transfers'=>DB::table('inventory_transfers')->where('inventory_allocation_id',$a)->get(),'events'=>DB::table('inventory_allocation_events')->where('inventory_allocation_id',$a)->orderBy('occurred_at')->get()]]);}
 public function allocate(Request$r,int$a):JsonResponse{$this->permit($r,'logistics.update');$d=$r->validate(['inventory_stock_id'=>['required','integer','exists:inventory_stocks,id'],'quantity'=>['required','numeric','gt:0'],'expires_at'=>['nullable','date','after:now']]);$row=DB::transaction(function()use($r,$a,$d){$allocation=DB::table('inventory_allocations')->whereNull('deleted_at')->lockForUpdate()->find($a);abort_unless($allocation,404);$stock=DB::table('inventory_stocks')->lockForUpdate()->find($d['inventory_stock_id']);abort_unless($stock&&$stock->product_id===$allocation->product_id,422,'Stock does not match allocation product.');$available=(float)$stock->on_hand-(float)$stock->reserved;abort_if((float)$d['quantity']>$available,422,'Insufficient available stock.');abort_if((float)$allocation->allocated_quantity+(float)$d['quantity']>(float)$allocation->requested_quantity,422,'Allocation exceeds requested quantity.');DB::table('inventory_stocks')->where('id',$stock->id)->update(['reserved'=>DB::raw('reserved + '.(float)$d['quantity']),'updated_at'=>now()]);DB::table('inventory_reservations')->insert(['uuid'=>(string)Str::uuid(),'inventory_allocation_id'=>$a,'inventory_stock_id'=>$stock->id,'quantity'=>$d['quantity'],'status'=>'active','expires_at'=>$d['expires_at']??null,'created_at'=>now(),'updated_at'=>now()]);$allocated=(float)$allocation->allocated_quantity+(float)$d['quantity'];$status=$allocated>=(float)$allocation->requested_quantity?'fully_allocated':'partially_allocated';DB::table('inventory_allocations')->where('id',$a)->update(['allocated_quantity'=>$allocated,'status'=>$status,'updated_at'=>now()]);$this->event($r,$a,'stock_reserved',['quantity'=>$d['quantity'],'stock_id'=>$stock->id]);activity('admin')->causedBy($r->user())->withProperties(['allocation_id'=>$a,'quantity'=>$d['quantity']])->log('inventory.allocated');return DB::table('inventory_allocations')->find($a);});return response()->json(['data'=>['allocation'=>$row]]);}
 public function release(Request$r,int$reservation):JsonResponse{$this->permit($r,'logistics.update');$row=DB::transaction(function()use($r,$reservation){$res=DB::table('inventory_reservations')->where('status','active')->lockForUpdate()->find($reservation);abort_unless($res,404);$stock=DB::table('inventory_stocks')->lockForUpdate()->find($res->inventory_stock_id);abort_unless($stock,404);DB::table('inventory_stocks')->where('id',$res->inventory_stock_id)->update(['reserved'=>max(0,(float)$stock->reserved-(float)$res->quantity),'updated_at'=>now()]);DB::table('inventory_reservations')->where('id',$reservation)->update(['status'=>'released','released_at'=>now(),'updated_at'=>now()]);$this->event($r,$res->inventory_allocation_id,'reservation_released',['reservation_id'=>$reservation]);activity('admin')->causedBy($r->user())->withProperties(['reservation_id'=>$reservation])->log('inventory.reservation_released');return DB::table('inventory_reservations')->find($reservation);});return response()->json(['data'=>['reservation'=>$row]]);}
 public function transfer(Request$r):JsonResponse{$this->permit($r,'logistics.update');$d=$r->validate(['inventory_allocation_id'=>['nullable','integer','exists:inventory_allocations,id'],'product_id'=>['required','integer','exists:products,id'],'source_facility_id'=>['required','integer','different:destination_facility_id','exists:logistics_facilities,id'],'destination_facility_id'=>['required','integer','exists:logistics_facilities,id'],'quantity'=>['required','numeric','gt:0']]);$id=DB::transaction(function()use($r,$d){$stock=DB::table('inventory_stocks')->where('product_id',$d['product_id'])->where('logistics_facility_id',$d['source_facility_id'])->lockForUpdate()->first();abort_unless($stock&&((float)$stock->on_hand-(float)$stock->reserved)>=(float)$d['quantity'],422,'Insufficient transferable stock.');$id=DB::table('inventory_transfers')->insertGetId([...$d,'uuid'=>(string)Str::uuid(),'reference'=>'TRF-'.now()->format('YmdHis').'-'.Str::upper(Str::random(4)),'status'=>'requested','created_at'=>now(),'updated_at'=>now()]);if($d['inventory_allocation_id']??null)$this->event($r,$d['inventory_allocation_id'],'transfer_requested',['transfer_id'=>$id]);activity('admin')->causedBy($r->user())->withProperties(['transfer_id'=>$id])->log('inventory.transfer_requested');return$id;});return response()->json(['data'=>['transfer'=>DB::table('inventory_transfers')->find($id)]],201);}
 private function query(array$f){$q=DB::table('inventory_allocations')->whereNull('inventory_allocations.deleted_at');if($v=$f['allocation_status']??null)$q->where('inventory_allocations.status',$v);if($v=$f['facility_id']??null)$q->where(fn($x)=>$x->where('source_facility_id',$v)->orWhere('destination_facility_id',$v));if($v=$f['supplier_id']??null)$q->where('inventory_allocations.supplier_id',$v);if($v=$f['date_from']??null)$q->whereDate('inventory_allocations.created_at','>=',$v);if($v=$f['date_to']??null)$q->whereDate('inventory_allocations.created_at','<=',$v);if($v=$f['search']??null)$q->where(fn($x)=>$x->where('inventory_allocations.reference','like','%'.$v.'%')->orWhere('inventory_allocations.sku','like','%'.$v.'%'));return$q;}
 private function event(Request$r,int$a,string$event,array$p=[]):void{DB::table('inventory_allocation_events')->insert(['inventory_allocation_id'=>$a,'actor_id'=>$r->user()->id,'event'=>$event,'properties'=>json_encode($p),'occurred_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);}
 private function permit(Request$r,string$p):void{abort_unless($r->user()->hasPermission($p),403);}
}
