"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {AlertTriangle,ChevronRight,RefreshCw,ShieldAlert} from "lucide-react";
import toast from "react-hot-toast";
import {addMarketplaceOrderNote,fetchMarketplaceOrder,fetchMarketplaceReturn,transitionMarketplaceOrder,transitionMarketplaceReturn} from "@/services/api/marketplaceWorkspaceService";
import styles from "./marketplace-workspace.module.css";

const orderTransitions:Record<string,string[]>={pending:["confirmed","cancelled"],confirmed:["production","cancelled"],production:["shipped","cancelled"],shipped:["completed","cancelled"],completed:["cancelled"],cancelled:[]};
const returnTransitions:Record<string,string[]>={requested:["evidence_required","under_review","cancelled"],evidence_required:["under_review","cancelled"],under_review:["approved","rejected","evidence_required"],approved:["return_shipment_pending","item_received"],return_shipment_pending:["item_received"],item_received:["inspection_pending"],inspection_pending:["refund_pending","rejected"],refund_pending:["completed"],rejected:[],completed:[],cancelled:[]};

export function MarketplaceRecordDetailView({kind,id}:{kind:"order"|"return";id:string}){const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[note,setNote]=useState("");const[nextStatus,setNextStatus]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");const controller=new AbortController();try{setData(await(kind==="order"?fetchMarketplaceOrder(id,controller.signal):fetchMarketplaceReturn(id,controller.signal)))}catch(e:any){setError(e?.status===404?"Record not found.":"The record could not be loaded.")}finally{setLoading(false)}return()=>controller.abort()},[kind,id]);useEffect(()=>{void load()},[load]);if(loading&&!data)return <div className={styles.loading}><i/><i/></div>;if(error&&!data)return <section className={styles.state}><ShieldAlert/><h1>Record unavailable</h1><p>{error}</p><button onClick={()=>void load()}>Retry</button></section>;if(!data)return null;
const record=kind==="order"?data.record:data;const transitions=(kind==="order"?orderTransitions:returnTransitions)[record.status]||[];const saveStatus=async()=>{if(!nextStatus||!note.trim()){toast.error("Choose a status and enter a reason.");return}try{kind==="order"?await transitionMarketplaceOrder(id,nextStatus,record.status,note):await transitionMarketplaceReturn(id,nextStatus,note);toast.success("Status updated");setNote("");setNextStatus("");await load()}catch(e:any){toast.error(e?.message||"Status update failed")}};const addNote=async()=>{if(!note.trim())return;try{await addMarketplaceOrderNote(id,note);toast.success("Internal note added");setNote("");await load()}catch(e:any){toast.error(e?.message||"Note could not be added")}};
return <main className={styles.page}><nav><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><Link href={kind==="order"?"/admin/marketplace/orders":"/admin/marketplace/returns"}>{kind==="order"?"Orders":"Returns"}</Link><ChevronRight/><span>{record.order_number||record.return_number||record.reference}</span></nav><header><div><h1>{record.order_number||record.return_number||record.reference}</h1><p>Database-backed {kind} record and authoritative lifecycle state.</p></div><button onClick={()=>void load()}><RefreshCw/>Refresh</button></header><section className={`${styles.capability} ${styles.available}`}><AlertTriangle/><div><b>Status: {human(record.status)}</b><p>Transitions are validated again by the backend and written transactionally to history.</p></div></section><section className={styles.detailGrid}>{Object.entries(kind==="order"?record:pickReturn(record)).map(([key,value])=><article key={key}><small>{human(key)}</small><strong>{show(value)}</strong></article>)}</section>{kind==="order"&&<section className={styles.card}><h2 className={styles.sectionTitle}>Order items</h2><div className={styles.table}><table><thead><tr><th>Product</th><th>Quantity</th><th>Unit price</th><th>Tax</th><th>Discount</th><th>Total</th></tr></thead><tbody>{data.items.map((item:any)=><tr key={item.id}><td>{item.product_name}</td><td>{item.quantity}</td><td>{item.unit_price}</td><td>{item.tax_amount}</td><td>{item.discount_amount}</td><td>{item.total_amount}</td></tr>)}</tbody></table></div></section>}<section className={styles.actions}><h2>Authorized workflow</h2>{transitions.length?<><select aria-label="Next status" value={nextStatus} onChange={e=>setNextStatus(e.target.value)}><option value="">Choose next status</option>{transitions.map(x=><option key={x}>{x}</option>)}</select><textarea aria-label="Audit reason" value={note} onChange={e=>setNote(e.target.value)} placeholder="Required audit reason"/><div><button onClick={()=>void saveStatus()}>Update status</button>{kind==="order"&&<button onClick={()=>void addNote()}>Add internal note only</button>}</div></>:<p>This record is in a terminal state.</p>}</section>{kind==="order"&&<section className={styles.card}><h2 className={styles.sectionTitle}>Status timeline</h2><div className={styles.timeline}>{data.timeline.length?data.timeline.map((event:any)=><article key={event.id}><b>{human(event.previous_status||"created")} → {human(event.new_status)}</b><span>{event.actor||"System"} · {new Date(event.created_at).toLocaleString()}</span><p>{event.notes||"No note."}</p></article>):<p>No status-history records.</p>}</div></section>}</main>}
function pickReturn(r:any){return{id:r.id,return_number:r.return_number,order:r.order?.order_number,customer:r.customer?.name,supplier:r.supplier?.company_name,status:r.status,reason_code:r.reason_code,reason:r.reason,resolution:r.resolution,reviewed_at:r.reviewed_at,completed_at:r.completed_at,created_at:r.created_at,updated_at:r.updated_at}}const human=(v:string)=>String(v).replaceAll("_"," ").replace(/^./,c=>c.toUpperCase());const show=(v:unknown)=>v===null||v===undefined||v===""?"—":typeof v==="object"?JSON.stringify(v):String(v);
