"use client";
import React from"react";import type{DataOperationsDashboard}from"@/types/importExport";
const Card=({title,children}:{title:string;children:React.ReactNode})=><div className="flex h-full min-w-0 flex-col rounded-lg border border-line bg-white p-3.5 text-[11px] shadow-sm"><h3 className="mb-2 truncate font-mono text-[11px] font-black uppercase tracking-wider text-ink">{title}</h3>{children}</div>;
const Empty=({text}:{text:string})=><p className="rounded border border-dashed p-3 text-[10px] text-muted">{text}</p>;
export function BottomOperationalPanels({data}:{data:DataOperationsDashboard}){const totalExports=data.statusSummaries.exports.reduce((sum,item)=>sum+item.count,0);return <div className="flex flex-col gap-4"><div className="grid grid-cols-1 items-stretch gap-3.5 md:grid-cols-2 2xl:grid-cols-[0.9fr_1.45fr_1.45fr_1.45fr_1.8fr]">
 <Card title="Catalogue Export Operations"><div className="grid grid-cols-2 gap-2"><Metric label="Total exports" value={totalExports}/><Metric label="Scheduled" value={data.lower.schedules.length}/></div><p className="mt-3 text-[10px] text-muted">Generated asynchronously and stored on the private local disk.</p></Card>
 <Card title="Scheduled Exports">{data.lower.schedules.length?data.lower.schedules.map(item=><div key={item.id} className="grid grid-cols-3 gap-1 border-b py-1 text-[9px]"><b>{item.feedName}</b><span>{item.frequency}</span><span>{item.nextRun}</span></div>):<Empty text="No scheduled exports."/>}</Card>
 <Card title="Import Templates & Mapping Profiles"><Empty text="Unavailable — no persistent template or mapping-profile schema is installed."/></Card>
 <Card title="Reconciliation & Audit Summary">{data.lower.reconciliation.length?data.lower.reconciliation.map(item=><div key={item.id} className="flex justify-between border-b py-1 text-[9px]"><b>{item.jobId}</b><span>{item.status}</span></div>):<Empty text="No completed jobs to reconcile."/>}</Card>
 <Card title="Recent Import & Export Activity">{data.lower.activities.length?data.lower.activities.map(item=><div key={item.id} className="grid grid-cols-[1fr_auto] gap-2 border-b py-1 text-[9px]"><span>{item.action}</span><b>{item.result}</b></div>):<Empty text="No recent import/export activity."/>}</Card>
 </div></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded bg-slate-50 p-2"><span className="block text-[9px] text-muted">{label}</span><b className="font-mono text-[12px]">{value.toLocaleString()}</b></div>}
