"use client";
import React from"react";import{AlertCircle}from"lucide-react";import type{DataOperationsDashboard}from"@/types/importExport";
const Panel=({title,children}:{title:string;children:React.ReactNode})=><div className="rounded-lg border border-line bg-white p-3.5 text-[11px] shadow-sm"><h4 className="mb-2 font-mono text-[11px] font-bold uppercase tracking-wider text-ink">{title}</h4>{children}</div>;
export function DataOperationsIntelligenceSidebar({data,onFilterClick}:{data:DataOperationsDashboard;onFilterClick?:(type:string,value:string)=>void;showToast:(message:string)=>void}){const imports=data.statusSummaries.imports.reduce((sum,item)=>sum+item.count,0),exports=data.statusSummaries.exports.reduce((sum,item)=>sum+item.count,0);return <div className="flex min-w-0 flex-col gap-4">
 <Panel title="Data Operations Health"><div className="mb-3 flex items-center gap-3 rounded bg-slate-50 p-2"><div className="flex h-12 w-12 items-center justify-center rounded-full border-4 border-emerald-500 font-mono text-sm font-black">{data.health.score??"N/A"}</div><div><b>{data.health.status}</b><p className="text-[9px] text-muted">Database-derived operation health</p></div></div>{data.health.metrics.map(item=><div key={item.label} className="mb-1"><div className="flex justify-between text-[9px]"><span>{item.label}</span><b>{item.value===null?"N/A":`${item.value}%`}</b></div><div className="h-1 rounded bg-slate-100"><div className="h-1 rounded bg-emerald-500" style={{width:`${item.value??0}%`}}/></div></div>)}</Panel>
 <Panel title="Priority Data Alerts">{data.alerts.length?data.alerts.map(alert=><button key={alert.id} onClick={()=>onFilterClick?.("tab",alert.scope==="failed"?"Failed":"All Jobs")} className="flex w-full justify-between rounded bg-slate-50 p-2 text-left text-[10px]"><span className="flex gap-1"><AlertCircle size={12}/>{alert.label}</span><b>{alert.count}</b></button>):<p className="text-[10px] text-muted">No priority alerts.</p>}</Panel>
 <Panel title="Import Status Summary">{data.statusSummaries.imports.map(item=><Row key={item.label} label={item.label} value={item.count}/>)}<Row label="Total Import Jobs" value={imports}/></Panel>
 <Panel title="Export Status Summary">{data.statusSummaries.exports.map(item=><Row key={item.label} label={item.label} value={item.count}/>)}<Row label="Total Export Jobs" value={exports}/></Panel>
 <Panel title="Processing Queue"><Row label="Running / queued" value={data.tabs.find(tab=>tab.scope==="running")?.count??0}/><Row label="Queue connection" value={data.meta.queueConnection}/></Panel>
 <Panel title="Quick Queues">{data.tabs.filter(tab=>["running","failed","scheduled"].includes(tab.scope)).map(tab=><button key={tab.scope} onClick={()=>onFilterClick?.("tab",tab.label)} className="flex w-full justify-between py-1 text-left"><span>{tab.label}</span><b>{tab.count}</b></button>)}</Panel>
 </div>}
function Row({label,value}:{label:string;value:string|number}){return <div className="flex justify-between border-b py-1 text-[10px]"><span>{label}</span><b>{value}</b></div>}
