"use client";
import React from"react";import type{CatalogueDataJob,DataOperationsDashboard}from"@/types/importExport";
const Panel=({title,children}:{title:string;children:React.ReactNode})=><div className="flex h-full min-w-0 flex-col justify-between rounded-lg border border-line bg-white p-3.5 text-[11px] shadow-sm"><div><h4 className="mb-2 font-mono text-[11px] font-bold uppercase tracking-wider text-ink">{title}</h4>{children}</div></div>;
const Empty=({children}:{children:React.ReactNode})=><p className="rounded border border-dashed p-3 text-[10px] text-muted">{children}</p>;
export function LowerWorkflowPanels({data,job,onOpenValidationDrawer}:{data:DataOperationsDashboard["lower"];job:CatalogueDataJob|null;onOpenCompareDuplicate:(conflict?:never)=>void;onOpenMappingDrawer:()=>void;onOpenValidationDrawer:()=>void;onOpenChangePreviewDrawer:()=>void;showToast:(message:string)=>void}){return <div className="mb-6 grid grid-cols-1 gap-4 md:grid-cols-2 2xl:grid-cols-4">
 <Panel title="Field Mapping & Transformation Summary"><Empty>Unavailable — this platform has no persistent field-mapping or transformation-profile schema.</Empty></Panel>
 <Panel title="Validation Summary"><div className="mb-2 grid grid-cols-2 gap-2"><Metric label="Rejected records" value={job?.failedRecords??0}/><Metric label="Validated records" value={job?.processedRecords??0}/></div>{data.validationIssues.length?data.validationIssues.map(issue=><button key={issue.label} onClick={onOpenValidationDrawer} className="flex w-full justify-between border-b py-1 text-left"><span>{issue.label}</span><b>{issue.count}</b></button>):<Empty>No validation issues recorded.</Empty>}</Panel>
 <Panel title="Duplicate Conflict Review"><Empty>Unavailable — duplicate-conflict staging and resolution records are not implemented.</Empty></Panel>
 <Panel title="Change Preview Summary"><div className="grid grid-cols-2 gap-2"><Metric label="Processed" value={job?.processedRecords??0}/><Metric label="Successful" value={job?.successfulRecords??0}/><Metric label="Rejected" value={job?.failedRecords??0}/><Metric label="Progress" value={`${job?.progress??0}%`}/></div></Panel>
 </div>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded bg-slate-50 p-2"><span className="block text-[9px] text-muted">{label}</span><b className="font-mono">{value}</b></div>}
