import { apiClient, downloadApiFile } from "@/services/api/apiClient";

export type WorkspaceName = "orders"|"manual-orders"|"cancellations"|"returns"|"promotions"|"policy-violations"|"commissions"|"settings"|"channels";
export type WorkspaceFilters = {search?:string;status?:string;supplierId?:string;currency?:string;dateFrom?:string;dateTo?:string;sortBy?:string;sortDirection?:"asc"|"desc";page?:number;perPage?:number};
export type WorkspaceMetric = {id:string;label:string;availability:"available"|"unavailable";value?:string|number|null;unit?:string|null;reason?:string};
export type WorkspaceData = {source:"database";workspace:WorkspaceName;title:string;description:string;generatedAt:string;permissions:{canView:boolean;canExport:boolean;canManage:boolean};context:{currency:string|null;currencies:string[];dateFrom:string;dateTo:string};capability:{availability:"available"|"partial"|"unavailable";reason?:string;limitations?:string[]};metrics:WorkspaceMetric[];columns:{key:string;label:string}[];items:Record<string,unknown>[];meta:{page:number;perPage:number;total:number;lastPage:number;refreshIntervalSeconds:number}};

const qs=(filters:WorkspaceFilters={})=>{const p=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!==""&&v!=="all")p.set(k,String(v))});return p.size?`?${p}`:""};
export async function fetchMarketplaceWorkspace(workspace:WorkspaceName,filters:WorkspaceFilters={},signal?:AbortSignal):Promise<WorkspaceData>{const response=await apiClient<{success:true;data:WorkspaceData}>(`/admin/marketplace/workspaces/${workspace}${qs(filters)}`,{signal});if(!response?.data)throw new Error("Marketplace workspace response is missing data.");return response.data}
export async function exportMarketplaceWorkspace(workspace:WorkspaceName,filters:WorkspaceFilters={},signal?:AbortSignal){return downloadApiFile(`/admin/marketplace/workspaces/${workspace}/export${qs(filters)}`,`marketplace-${workspace}.csv`,signal)}
export async function fetchMarketplaceOrder(id:string,signal?:AbortSignal){const response=await apiClient<{success:true;data:any}>(`/admin/marketplace/orders/${encodeURIComponent(id)}`,{signal});return response.data}
export async function addMarketplaceOrderNote(id:string,note:string){return apiClient(`/admin/marketplace/orders/${encodeURIComponent(id)}/notes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({note})})}
export async function transitionMarketplaceOrder(id:string,status:string,expectedStatus:string,reason:string){return apiClient(`/admin/marketplace/orders/${encodeURIComponent(id)}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,expectedStatus,reason})})}
export async function fetchMarketplaceReturn(id:string,signal?:AbortSignal){const response=await apiClient<{success:true;data:{return:any}}>(`/admin/returns/${encodeURIComponent(id)}`,{signal});return response.data.return}
export async function transitionMarketplaceReturn(id:string,status:string,notes:string){return apiClient(`/admin/returns/${encodeURIComponent(id)}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,notes})})}
