import { API_BASE, api, getAuthToken, withQuery } from '@/lib/api/client';

export interface SupplierPayableFilters { dateFrom:string; dateTo:string; currency:string; search:string; status:string; page:number; perPage:number; sort:string; direction:'asc'|'desc' }
export interface PayablesOverview { context:{tenant:string;tenantScopeAvailable:boolean;currency:string;dateFrom:string;dateTo:string};kpis:Array<{key:string;label:string;value:string;currency:string|null;comparisonPercentage:number|null;direction:string;sparkline:number[];available:boolean;reason:string|null}>;trend:{items:Array<{date:string;payables:string;payments:string;scheduled:string}>};typeDistribution:{items:Array<{type:string;count:number;amount:string;percentage:number}>};statusSummary:Array<{status:string;count:number;amount:string;percentage:number}>;health:{score:number|null;status:string;reason:string;items:unknown[]};alerts:Array<{id:string;severity:string;message:string;status:string}>;financialSummary:{gross:string;net:string;paid:string;outstanding:string;currency:string};queues:Record<string,number>;capabilities:Record<string,boolean>;permissions:Record<string,boolean>;updatedAt:string;refreshIntervalSeconds:number}
export interface PayablesPage {items:Array<Record<string,unknown>>;meta:{page:number;perPage:number;total:number;lastPage:number};permissions:Record<string,boolean>}
const query=(f:SupplierPayableFilters)=>({dateFrom:f.dateFrom,dateTo:f.dateTo,currency:f.currency,search:f.search||undefined,status:f.status||undefined,page:f.page,perPage:f.perPage,sort:f.sort,direction:f.direction});
export async function fetchSupplierPayablesOverview(f:SupplierPayableFilters,signal?:AbortSignal):Promise<PayablesOverview>{return (await api.get(withQuery('/admin/finance/supplier-payables/overview',query(f)),{signal})).data;}
export async function fetchSupplierPayables(f:SupplierPayableFilters,signal?:AbortSignal):Promise<PayablesPage>{return (await api.get(withQuery('/admin/finance/supplier-payables',query(f)),{signal})).data;}
export async function fetchSupplierPayable(id:string,signal?:AbortSignal){return (await api.get(`/admin/finance/supplier-payables/${encodeURIComponent(id)}`,{signal})).data;}
export async function exportSupplierPayables(f:SupplierPayableFilters){const token=getAuthToken();const r=await fetch(`${API_BASE}${withQuery('/admin/finance/supplier-payables/export',query(f))}`,{headers:{Accept:'text/csv',...(token?{Authorization:`Bearer ${token}`}:{})},credentials:'include'});if(!r.ok)throw new Error(r.status===403?'You do not have permission to export supplier payables.':'Unable to export supplier payables.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`supplier-payables-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
