"use client";
import React from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import type { InventoryOperationsData } from "@/types/inventoryOperations";
import styles from "../inventory.module.css";

interface Props {searchTerm:string;onSearchChange:(value:string)=>void;selectedBrand:string;onBrandChange:(value:string)=>void;selectedSupplier:string;onSupplierChange:(value:string)=>void;selectedCategory:string;onCategoryChange:(value:string)=>void;selectedVariant:string;onVariantChange:(value:string)=>void;selectedLocation:string;onLocationChange:(value:string)=>void;activeQuickFilter:string|null;onQuickFilterToggle:(chip:string)=>void;onClearAll:()=>void;onOpenMoreFilters:()=>void;options:InventoryOperationsData['options'];supportedQuickFilters:string[];}
const QUICK_FILTERS=[['Near Expiry','near-expiry'],['Expired','expired'],['Low Stock','low-stock'],['Out of Stock','out-of-stock'],['Quarantined','quarantined'],['Recalled','recalled'],['Negative Stock','negative-stock'],['Missing Batch No.','missing-batch'],['Missing Expiry Date','missing-expiry']];
export function InventoryFiltersBar({searchTerm,onSearchChange,selectedBrand,onBrandChange,selectedSupplier,onSupplierChange,selectedCategory,onCategoryChange,selectedVariant,onVariantChange,selectedLocation,onLocationChange,activeQuickFilter,onQuickFilterToggle,onClearAll,onOpenMoreFilters,options,supportedQuickFilters}:Props){return <div className={styles.filtersContainerCard}><div className={styles.filterControlsRow}><div className={styles.searchBox}><Search size={16} className={styles.searchIcon}/><input type="text" className={styles.searchInput} placeholder="Search by SKU, Name, Batch No. or Variant..." value={searchTerm} onChange={e=>onSearchChange(e.target.value)}/></div>
  <select disabled className={styles.dropdownSelect} value={selectedBrand} onChange={e=>onBrandChange(e.target.value)} title="Products have no direct brand relationship"><option value="ALL">All Brands — Unavailable</option>{options.brands.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>
  <select className={styles.dropdownSelect} value={selectedSupplier} onChange={e=>onSupplierChange(e.target.value)}><option value="ALL">All Suppliers</option>{options.suppliers.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>
  <select className={styles.dropdownSelect} value={selectedCategory} onChange={e=>onCategoryChange(e.target.value)}><option value="ALL">All Categories</option>{options.categories.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>
  <select className={styles.dropdownSelect} value={selectedVariant} onChange={e=>onVariantChange(e.target.value)}><option value="ALL">All Variants</option>{options.variants.map(o=><option key={o.id} value={o.id}>{o.name}{o.sku?` (${o.sku})`:''}</option>)}</select>
  <select disabled className={styles.dropdownSelect} value={selectedLocation} onChange={e=>onLocationChange(e.target.value)} title="No inventory location domain exists"><option value="ALL">All Locations — Unavailable</option>{options.locations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>
  <button type="button" className={styles.moreFiltersBtn} onClick={onOpenMoreFilters}><SlidersHorizontal size={14}/> More Filters</button><button type="button" className={styles.clearAllBtn} onClick={onClearAll}>Clear All</button></div>
  <div className={styles.quickFiltersRow}><span className={styles.quickFilterLabel}>Quick Filters:</span><div className={styles.quickFilterChipsContainer}>{QUICK_FILTERS.map(([label,key])=>{const supported=supportedQuickFilters.includes(key);return <button key={key} type="button" disabled={!supported} title={supported?undefined:'Unavailable in the current inventory schema'} className={`${styles.quickFilterChip} ${activeQuickFilter===key?styles.quickFilterChipActive:""}`} onClick={()=>onQuickFilterToggle(key)}>{label}</button>;})}</div></div></div>;}
