"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {AlertTriangle,ArrowLeft,BarChart3,CalendarDays,Check,CheckCircle2,ChevronRight,CircleAlert,Clock3,FileText,Info,LockKeyhole,Paperclip,Plus,RefreshCw,Save,ShieldAlert,Trash2,Upload,X,XCircle} from "lucide-react";
import toast from "react-hot-toast";
import {createCommissionRuleEditorDraft,fetchCommissionRuleEditor,recordCommissionRuleEditorAction} from "@/services/api/marketplaceCommissionRuleService";
import styles from "./commission-rule-editor.module.css";

const selectOptions={owner:["E. Vance","M. Fernando","S. Perera"],priority:["Normal","High","Critical"],type:["Standard","Category","Channel","Seller-Specific Exception","Promotional"],status:["Draft","Scheduled","Active"],businessUnit:["Imported Beauty","Consumer Beauty","B2B Trade"],marketplace:["Beauty Marketplace"],channel:["Online Marketplace","Mobile App","Wholesale Portal"],seller:["Tokyo Beauty Ceylon","All Sellers"],brand:["Tokyo Beauty","All Brands"],category:["All Categories","Premium Skincare"],region:["Sri Lanka"],method:["Percentage","Fixed Fee","Tiered"],maximumFee:["No Limit","25,000","50,000"],basis:["Net Item Value","Gross Item Value"],tax:["Exclusive of Tax","Inclusive of Tax"],refund:["Reverse Commission on Approved Refund","Retain Commission"],shipping:["Excluded","Included"],discount:["Apply After Seller-Funded Discount","Apply Before Discount"],promotion:["Exclude Promotional Subsidies","Include Subsidies"],timeZone:["Asia/Colombo"],activation:["Scheduled after approval","Activate immediately"],renewal:["Does not renew","Auto renew"],expiry:["Fallback to standard rule","Deactivate rule"],grace:["7 days","3 days","None"],retroactive:["No","Yes"],orderTreatment:["Apply to new orders only","Apply to open orders"],precedence:["1 (Highest)","2","3"],override:["Yes","No"],allowPromotional:["Yes","No"],allowManualFinance:["No","Yes"],fallback:["Standard Beauty Marketplace Commission"],strategy:["Seller-specific rule takes precedence","Highest rate wins","Lowest rate wins"]};

export default function CommissionRuleEditorView({mode,ruleId}){
  const [data,setData]=useState(null);const [form,setForm]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [dirty,setDirty]=useState(false);const [saving,setSaving]=useState(false);const [validated,setValidated]=useState(false);const [conflictsChecked,setConflictsChecked]=useState(false);const [previewed,setPreviewed]=useState(false);const [fieldErrors,setFieldErrors]=useState({});const [modal,setModal]=useState(null);const [audit,setAudit]=useState([]);const [tiers,setTiers]=useState([]);const [attachments,setAttachments]=useState([]);
  useEffect(()=>{const controller=new AbortController();const request=mode==="edit"?fetchCommissionRuleEditor(decodeURIComponent(ruleId),controller.signal):createCommissionRuleEditorDraft(controller.signal);void request.then(result=>{setData(result);setForm(result.rule);setTiers(result.tiers);setAttachments(result.attachments)}).catch(e=>{if(e.name!=="AbortError")setError(e.message==="RULE_NOT_FOUND"?"The requested commission rule could not be found.":"The commission rule editor could not be loaded.")}).finally(()=>setLoading(false));return()=>controller.abort()},[mode,ruleId]);
  useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
  const update=(key,value)=>{setForm(current=>({...current,[key]:value}));setDirty(true);setValidated(false);setPreviewed(false);setFieldErrors(errors=>({...errors,[key]:undefined}))};
  const required=useMemo(()=>["name","owner","type","businessUnit","marketplace","channel","method","rate","effectiveFrom","effectiveTo","precedence"],[ ]);
  const validate=()=>{const errors={};required.forEach(key=>{if(!String(form[key]??"").trim())errors[key]="Required"});if(Number(form.rate)<=0||Number(form.rate)>100)errors.rate="Enter a rate between 0 and 100";if(form.effectiveTo<form.effectiveFrom)errors.effectiveTo="End date must be after start date";setFieldErrors(errors);setValidated(!Object.keys(errors).length);if(Object.keys(errors).length){toast.error("Complete the required fields before validation");return false}toast.success("Rule validation completed in local preview state");return true};
  const action=async(type)=>{if(type==="Validate Rule"){validate();return}if(type==="Preview Impact"){if(!validate())return;setPreviewed(true);toast.success("Financial impact preview recalculated");return}if(type==="Resolve Conflicts"){setConflictsChecked(true);toast.success("Conflict resolutions staged locally");return}if(type==="Discard Changes"){setModal("Discard Changes");return}if(type==="Submit for Approval"&&(!validate()||!conflictsChecked)){toast.error("Validate the rule and resolve blocking conflicts first");return}setSaving(true);try{const event=await recordCommissionRuleEditorAction(form.id,type,{form,tiers,attachments});setAudit(items=>[event,...items]);if(type==="Save Draft")setDirty(false);if(type==="Submit for Approval"){setDirty(false);setForm(current=>({...current,status:"Pending Approval"}))}toast.success(`${type} saved in local preview state (not server-persisted)`)}finally{setSaving(false)}};
  const discard=()=>{setForm(data.rule);setTiers(data.tiers);setAttachments(data.attachments);setDirty(false);setValidated(false);setConflictsChecked(false);setPreviewed(false);setModal(null);toast.success("Unsaved changes discarded")};
  if(loading)return <Loading/>;
  if(error)return <section className={styles.state} role="alert"><XCircle/><h1>Commission rule unavailable</h1><p>{error}</p><Link href="/admin/marketplace/commissions">Back to Commission Management</Link></section>;
  if(!data||!form)return <section className={styles.state}><FileText/><h1>No rule editor data</h1></section>;
  if(data.permissions?.canView===false)return <section className={styles.state}><LockKeyhole/><h1>Permission required</h1><p>Your role cannot access commission rule configuration.</p></section>;
  const title=mode==="edit"?"Edit Commission Rule":"Create Commission Rule";const completion=Math.min(100,Math.round(([form.name,form.type,form.businessUnit,form.channel,form.rate,form.effectiveFrom,validated,conflictsChecked,previewed].filter(Boolean).length/9)*100));
  return <main className={styles.page}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><Link href="/admin/marketplace/commissions">Commissions</Link><ChevronRight/>{mode==="edit"&&<><span>{form.id}</span><ChevronRight/></>}<b>{mode==="edit"?"Edit":"Create Rule"}</b></nav>
    <div className={styles.topLine}><Link href="/admin/marketplace/commissions"><ArrowLeft/>Back to Commission Management</Link><aside><i/>Live data <small>Last updated: {data.lastUpdated}</small><RefreshCw/></aside></div>
    <header className={styles.header}><div><h1>{title}</h1><p>{mode==="edit"?form.name:"Configure a new marketplace commission rule and approval workflow."}</p></div><div className={styles.badges}><span className={styles.warning}>{form.status}</span><span className={styles.info}>Scheduled</span>{data.conflicts.length>0&&<span className={styles.danger}>Conflict Detected</span>}<span className={styles.dark}>Version {form.version}</span>{dirty&&<span className={styles.unsaved}>Unsaved changes</span>}</div></header>
    <Context data={data}/><StageTracker stages={data.stages} validated={validated} conflictsChecked={conflictsChecked} previewed={previewed}/>
    <div className={styles.layout}><div className={styles.workspace}>
      <div className={styles.topGrid}><Section number="1" title="Rule Identity"><div className={styles.formGrid}><Field label="Rule Name" required value={form.name} error={fieldErrors.name} onChange={v=>update("name",v)}/><Select label="Rule Owner" required value={form.owner} options={selectOptions.owner} onChange={v=>update("owner",v)}/><Field label="Rule ID" value={form.id} disabled/><Select label="Priority" required value={form.priority} options={selectOptions.priority} onChange={v=>update("priority",v)}/><Select label="Rule Type" required value={form.type} options={selectOptions.type} onChange={v=>update("type",v)}/><Field label="Version" value={form.version} disabled/><Field label="Description" multiline value={form.description} onChange={v=>update("description",v)}/><Select label="Status" required value={form.status} options={selectOptions.status} onChange={v=>update("status",v)}/><Field label="Internal Purpose" multiline value={form.purpose} onChange={v=>update("purpose",v)}/></div></Section>
      <Section number="2" title="Scope Definition" action="Add Scope"><div className={styles.scopeGrid}>{[["Business Unit","businessUnit"],["Marketplace","marketplace"],["Channel","channel"],["Seller","seller"],["Brand / Manufacturer","brand"],["Product Category","category"],["Region","region"]].map(([label,key])=><Select key={key} compact label={label} required value={form[key]} options={selectOptions[key]} onChange={v=>update(key,v)}/>)}</div><button className={styles.addInline}><Plus/>Add Exclusion</button><p className={styles.note}>This rule applies only to Tokyo Beauty Ceylon listings sold through the Online Marketplace in Sri Lanka under Imported Beauty.</p></Section>
      <Section number="3" title="Commission Rate Configuration"><div className={styles.formGrid}><Select label="Method" required value={form.method} options={selectOptions.method} onChange={v=>update("method",v)}/><Field label="Commission Rate" required suffix="%" value={form.rate} error={fieldErrors.rate} onChange={v=>update("rate",v)}/><Field label="Fixed Fee" prefix="LKR" value={form.fixedFee} onChange={v=>update("fixedFee",v)}/><Field label="Minimum Fee" prefix="LKR" value={form.minimumFee} onChange={v=>update("minimumFee",v)}/><Select label="Maximum Fee" value={form.maximumFee} options={selectOptions.maximumFee} onChange={v=>update("maximumFee",v)}/><Select label="Rate Basis" value={form.basis} options={selectOptions.basis} onChange={v=>update("basis",v)}/><Select label="Tax Treatment" value={form.tax} options={selectOptions.tax} onChange={v=>update("tax",v)}/><Select label="Refund Treatment" value={form.refund} options={selectOptions.refund} onChange={v=>update("refund",v)}/><Select label="Shipping Fee Treatment" value={form.shipping} options={selectOptions.shipping} onChange={v=>update("shipping",v)}/><Select label="Discount Treatment" value={form.discount} options={selectOptions.discount} onChange={v=>update("discount",v)}/><Select label="Promotional Subsidy Treatment" value={form.promotion} options={selectOptions.promotion} onChange={v=>update("promotion",v)}/></div><Calculation form={form}/></Section></div>
      <div className={styles.midGrid}><Tiers tiers={tiers} setTiers={value=>{setTiers(value);setDirty(true)}}/><Dates form={form} update={update} errors={fieldErrors}/></div>
      <div className={styles.lowerGrid}><Precedence form={form} update={update}/><Conflicts rows={data.conflicts} checked={conflictsChecked} onRun={()=>void action("Resolve Conflicts")}/><Impact form={form} previewed={previewed}/></div>
      <div className={styles.bottomGrid}><Approval rows={data.approval}/><Notifications form={form} update={update}/><Notes form={form} update={update} attachments={attachments} setAttachments={value=>{setAttachments(value);setDirty(true)}}/></div>
      <Audit versions={data.versions} audit={audit}/>
    </div><CompletionRail completion={completion} data={data} form={form} validated={validated} conflictsChecked={conflictsChecked} previewed={previewed} onAction={action}/></div>
    <StickyBar form={form} dirty={dirty} saving={saving} conflicts={data.conflicts} onAction={action}/>
    {modal==="Discard Changes"&&<ConfirmDiscard onClose={()=>setModal(null)} onConfirm={discard}/>} 
  </main>;
}

function Context({data}){return <section className={styles.context}>{Object.entries(data.context).map(([key,value])=><p key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><b>{value}</b></p>)}<aside><LockKeyhole/>Access limited to assigned business context</aside></section>}
function StageTracker({stages,validated,conflictsChecked,previewed}){const current=conflictsChecked?6:validated?5:4;return <section className={styles.stages}>{stages.map((stage,index)=><div className={`${styles.stage} ${index<current?styles.complete:index===current?styles.active:""}`} key={stage}><span>{index<current?<Check/>:index+1}</span><b>{stage}</b></div>)}</section>}
function Section({number,title,action,children}){return <section className={styles.card}><header className={styles.cardHeader}><h2><span>{number}.</span>{title}</h2>{action&&<button><Plus/>{action}</button>}</header>{children}</section>}
function Field({label,value,onChange,required,error,disabled,multiline,prefix,suffix}){const Control=multiline?"textarea":"input";return <label className={styles.field}>{label}{required&&<i>*</i>}<span>{prefix&&<em>{prefix}</em>}<Control value={value??""} disabled={disabled} onChange={e=>onChange?.(e.target.value)} aria-invalid={!!error}/>{suffix&&<em>{suffix}</em>}</span>{error&&<small>{error}</small>}</label>}
function Select({label,value,onChange,options,required,compact}){return <label className={`${styles.field} ${compact?styles.compact:""}`}>{label}{required&&<i>*</i>}<select value={value??""} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function Calculation({form}){const order=12450,commission=order*(Number(form.rate||0)/100),net=order-commission;return <aside className={styles.calculation}><b>Live Calculation Preview</b><p>Order Item Value<strong>LKR {order.toLocaleString()}</strong></p><p>Calculated Commission<strong>LKR {commission.toLocaleString(undefined,{maximumFractionDigits:2})}</strong></p><p>Estimated Seller Net<strong>LKR {net.toLocaleString(undefined,{maximumFractionDigits:2})}</strong></p></aside>}
function Tiers({tiers,setTiers}){return <Section number="4" title="Tiered or Conditional Rates (Optional)"><table className={styles.tierTable}><thead><tr><th>Tier</th><th>GMV Range (Monthly)</th><th>Rate</th><th/></tr></thead><tbody>{tiers.map((tier,index)=><tr key={tier.id}><td>{index+1}</td><td><input value={tier.range} onChange={e=>setTiers(tiers.map(x=>x.id===tier.id?{...x,range:e.target.value}:x))}/></td><td><input value={tier.rate} onChange={e=>setTiers(tiers.map(x=>x.id===tier.id?{...x,rate:e.target.value}:x))}/>%</td><td><button aria-label={`Remove tier ${index+1}`} onClick={()=>setTiers(tiers.filter(x=>x.id!==tier.id))}><Trash2/></button></td></tr>)}</tbody></table><button className={styles.addInline} onClick={()=>setTiers([...tiers,{id:Date.now(),range:"New range",rate:"0"}])}><Plus/>Add Tier</button></Section>}
function Dates({form,update,errors}){return <Section number="5" title="Effective Dates & Scheduling"><div className={styles.formGrid}><Field label="Effective From" required value={form.effectiveFrom} onChange={v=>update("effectiveFrom",v)}/><Field label="Effective To" required value={form.effectiveTo} error={errors.effectiveTo} onChange={v=>update("effectiveTo",v)}/><Select label="Time Zone" value={form.timeZone} options={selectOptions.timeZone} onChange={v=>update("timeZone",v)}/><Select label="Activation Type" value={form.activation} options={selectOptions.activation} onChange={v=>update("activation",v)}/><Select label="Expiry Behavior" value={form.expiry} options={selectOptions.expiry} onChange={v=>update("expiry",v)}/><Select label="Renewal" value={form.renewal} options={selectOptions.renewal} onChange={v=>update("renewal",v)}/><Select label="Grace Period" value={form.grace} options={selectOptions.grace} onChange={v=>update("grace",v)}/><Select label="Retroactive Application" value={form.retroactive} options={selectOptions.retroactive} onChange={v=>update("retroactive",v)}/><Select label="Existing Order Treatment" value={form.orderTreatment} options={selectOptions.orderTreatment} onChange={v=>update("orderTreatment",v)}/></div><div className={styles.timeline}><i/><span>Current Start</span><b>New Rule Start · {form.effectiveFrom}</b><b>New Rule End · {form.effectiveTo}</b><span>Fallback Start</span></div><p className={styles.successNote}><CheckCircle2/>New rule scheduled to be active from {form.effectiveFrom} to {form.effectiveTo}.</p></Section>}
function Precedence({form,update}){return <Section number="6" title="Precedence & Override Behavior"><ol className={styles.precedence}>{["Approved seller-specific exception","Approved promotional override","Category-specific rule","Channel-specific rule","Business-unit rule","Standard marketplace rule"].map(item=><li key={item}>{item}</li>)}</ol><div className={styles.formGrid}><Select label="Precedence Level" required value={form.precedence} options={selectOptions.precedence} onChange={v=>update("precedence",v)}/><Select label="Override Lower-Level Rules" value={form.override} options={selectOptions.override} onChange={v=>update("override",v)}/><Select label="Allow Promotional Override" value={form.allowPromotional} options={selectOptions.allowPromotional} onChange={v=>update("allowPromotional",v)}/><Select label="Allow Manual Finance Override" value={form.allowManualFinance} options={selectOptions.allowManualFinance} onChange={v=>update("allowManualFinance",v)}/><Select label="Fallback Rule" value={form.fallback} options={selectOptions.fallback} onChange={v=>update("fallback",v)}/><Select label="Conflict Resolution Strategy" value={form.strategy} options={selectOptions.strategy} onChange={v=>update("strategy",v)}/></div></Section>}
function Conflicts({rows,checked,onRun}){return <Section number="7" title="Conflict Detection"><div className={styles.conflictTabs}><span>Passed 4</span><span>Warning 1</span><span>Blocking {checked?0:2}</span><span>Not Checked {checked?0:1}</span><button onClick={onRun}><RefreshCw/>Run Conflict Check</button></div><div className={styles.conflictTable}>{rows.map(row=><article key={row.rule}><b>{row.rule}</b><span>{row.type}</span><em className={row.state==="blocking"?styles.danger:styles.warning}>{checked?"Resolved":row.severity}</em><span>{row.impact}</span><small>{row.resolution}</small><button>Apply</button></article>)}</div><footer><button>View All Rules</button><button>Compare Rules</button><button onClick={onRun}>Recalculate</button></footer></Section>}
function Impact({form,previewed}){const delta=previewed?-76400:0;return <Section number="8" title="Financial & Settlement Impact"><table className={styles.impactTable}><thead><tr><th>Impact Item</th><th>Current</th><th>Proposed</th><th>Change</th></tr></thead><tbody>{[["Projected Monthly GMV","LKR 3,820,000","LKR 3,820,000","—"],["Commission Revenue","LKR 362,900","LKR 286,500",`LKR ${delta.toLocaleString()}`],["Seller Settlement","LKR 3,457,100","LKR 3,533,500","+LKR 76,400"],["Refund Liability Impact","LKR 24,600","LKR 32,800","+LKR 8,200"]].map(row=><tr key={row[0]}>{row.map((cell,index)=><td key={index}>{cell}</td>)}</tr>)}</tbody></table><div className={styles.miniBars}><i/><i/><i/><i/></div><p className={styles.alertNote}><AlertTriangle/>Proposed rate reduces monthly marketplace commission revenue by 21.1%.</p></Section>}
function Approval({rows}){return <Section number="9" title="Approval Workflow"><div className={styles.approvalFlow}>{rows.map((row,index)=><article key={row.step}><small>Step {row.step}</small><b>{row.role}</b><span>{row.person}</span>{index<rows.length-1&&<ChevronRight/>}</article>)}<button><Plus/>Add Approver</button></div><footer className={styles.approvalMeta}><span>Finance Review Required</span><span>Executive Review Required</span><p>Approval SLA <b>24 hours</b></p><p>Escalation <b>Chief Operating Officer</b></p></footer></Section>}
function Notifications({form,update}){const rows=[["Notify Seller","notifySeller"],["Notify Finance","notifyFinance"],["Notify Marketplace Operations","notifyOperations"],["Notify Settlement Team","notifyLegal"],["Notify Account Manager","notifyManager"]];return <Section number="10" title="Notifications"><div className={styles.notificationGrid}><div>{rows.map(([label,key])=><label key={key}>{label}<input type="checkbox" checked={form[key]} onChange={e=>update(key,e.target.checked)}/><i/></label>)}</div><div><Select label="Notification Timing" value="At Approval & Effective Date" options={["At Approval & Effective Date"]} onChange={()=>{}}/><Select label="Email Template" value="Commission Rule Notification" options={["Commission Rule Notification"]} onChange={()=>{}}/><Select label="Effective Date Reminder" value="1 day before" options={["1 day before"]} onChange={()=>{}}/></div><aside><b>Notification Preview</b><p>Commission Rule Scheduled</p><small>Rule “{form.name||"Untitled rule"}” has been scheduled.</small><button>View Full Preview</button></aside></div></Section>}
function Notes({form,update,attachments,setAttachments}){return <Section number="11" title="Internal Notes & Attachments"><Field label="Internal Note" multiline value={form.internalNote} onChange={v=>update("internalNote",v)}/><div className={styles.files}>{attachments.map(file=><p key={file.name}><Paperclip/><span>{file.name}<small>{file.size}</small></span><button aria-label={`Remove ${file.name}`} onClick={()=>setAttachments(attachments.filter(x=>x.name!==file.name))}><Trash2/></button></p>)}</div><button className={styles.upload} onClick={()=>setAttachments([...attachments,{name:`supporting-note-${attachments.length+1}.pdf`,size:"Local preview"}])}><Upload/>Attach Supporting Note</button></Section>}
function Audit({versions,audit}){return <Section number="12" title="Audit & Version Information"><div className={styles.auditTable}><table><thead><tr>{["Version","Status","Effective Date","Changed By","Change Summary","Approved By","Approved Date","Action"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{[...audit.map(item=>({version:"Local",status:item.action,effective:new Date(item.at).toLocaleString(),by:"Current admin",summary:"Local preview event; not server-persisted.",approvedBy:"—",approvedDate:"—"})),...versions].map((row,index)=><tr key={`${row.version}-${index}`}><td>{row.version}</td><td>{row.status}</td><td>{row.effective}</td><td>{row.by}</td><td>{row.summary}</td><td>{row.approvedBy}</td><td>{row.approvedDate}</td><td><button>Compare</button><button>Audit</button></td></tr>)}</tbody></table></div></Section>}

function CompletionRail({completion,data,form,validated,conflictsChecked,previewed,onAction}){const validations=[["Required Fields",form.name?"24 / 24":"22 / 24",!!form.name],["Scope Validation","Passed",true],["Rate Validation",validated?"Passed":"Pending",validated],["Effective Date Validation",validated?"Passed":"Warning",validated],["Conflict Check",conflictsChecked?"Passed":"2 Blocking",conflictsChecked],["Financial Impact",previewed?"Reviewed":"Warning",previewed],["Approval Routing","Incomplete",false]];return <aside className={styles.rail}><section className={styles.railCard}><h2>Completion Status</h2><div className={styles.completion}><div style={{"--completion":`${completion}%`}}><span>{completion}%</span></div><p><b>Stage {conflictsChecked?6:5} of 9</b><span>Conflict Validation</span><em>● Autosaved</em><small>Last saved: {data.lastUpdated}</small></p></div></section><section className={styles.railCard}><h2>Validation Summary</h2>{validations.map(([label,value,ok])=><p className={styles.validation} key={label}><span>{ok?<CheckCircle2/>:<CircleAlert/>}{label}</span><b className={ok?styles.good:styles.danger}>{value}</b></p>)}</section><section className={styles.railCard}><h2>Rule Preview</h2>{[["Name",form.name||"Untitled Rule"],["Type",form.type],["Scope","1 Seller / 1 Channel / 1 Region"],["Rate",`${form.rate}%`],["Effective",`${form.effectiveFrom} to ${form.effectiveTo}`],["Precedence","Level 1"],["Fallback",form.fallback]].map(([a,b])=><p className={styles.railRow} key={a}><span>{a}</span><b>{b}</b></p>)}</section><section className={styles.railCard}><h2>Impact Summary</h2>{[["Monthly Revenue Change","-LKR 76,400"],["Seller Settlement Change","+LKR 76,400"],["Rules Overridden","2"],["Conflicts",conflictsChecked?"0":"2"],["Approvals Required","3"],["Revenue at Risk","LKR 82,000"]].map(([a,b],index)=><p className={styles.railRow} key={a}><span>{a}</span><b className={index===0||index===5?styles.danger:index===1?styles.good:""}>{b}</b></p>)}</section><section className={styles.railCard}><h2>Blocking Issues</h2>{conflictsChecked?<p className={styles.resolved}><CheckCircle2/>Blocking conflicts resolved locally.</p>:<ul className={styles.blockers}><li>Finance approver missing</li><li>Existing seller rule overlap</li><li>Effective date begins before approval SLA ends</li></ul>}</section><section className={styles.railCard}><h2>Final Actions</h2><div className={styles.finalActions}>{["Submit for Approval","Save Draft","Run Validation","Preview Impact","Resolve Conflicts","Discard Changes"].map((item,index)=><button className={index===0?styles.primary:item==="Discard Changes"?styles.discard:""} key={item} onClick={()=>void onAction(item==="Run Validation"?"Validate Rule":item)}>{item}</button>)}</div></section><section className={styles.safeguard}><ShieldAlert/><p><b>Safeguard Notice</b><span>Commission changes require permission, validation, reason, approval, version control and immutable audit logging.</span></p></section></aside>}
function StickyBar({form,dirty,saving,conflicts,onAction}){return <footer className={styles.sticky}><div><span><CheckCircle2/>Autosaved</span><b>Draft Version {form.version}</b><em><XCircle/>{conflicts.length-1} Blocking</em>{dirty&&<small>Unsaved changes</small>}</div><aside>{["Cancel","Save Draft","Validate Rule","Preview Impact","Submit for Approval"].map(item=><button className={item==="Submit for Approval"?styles.primary:""} disabled={saving} key={item} onClick={()=>void onAction(item==="Cancel"?"Discard Changes":item)}>{item}</button>)}</aside></footer>}
function ConfirmDiscard({onClose,onConfirm}){return <div className={styles.backdrop}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="discard-title"><header><h2 id="discard-title">Discard unsaved changes?</h2><button aria-label="Close dialog" onClick={onClose}><X/></button></header><p>All local edits since the last draft state will be discarded.</p><footer><button onClick={onClose}>Cancel</button><button className={styles.dangerButton} onClick={onConfirm}>Discard Changes</button></footer></section></div>}
function Loading(){return <div className={styles.loading} role="status" aria-label="Loading commission rule editor"><div/><div/><section>{Array.from({length:9},(_,i)=><i key={i}/>)}</section><div/></div>}
