"use client";

import {useMemo,useState} from "react";
import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import {AlertTriangle,Columns3,Download,Filter,RefreshCw,Save,Search} from "lucide-react";
import {CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Badge,Breadcrumb,Card,ContextBar,State,styles} from "@/components/admin/marketplace/enterprise-workspaces/WorkspaceUI";
import {OrderPagination} from "@/components/admin/orders/OrderPagination";
import {useMarketplaceCancellations} from "@/hooks/admin/useMarketplaceCancellations";
import {exportMarketplaceCancellations} from "@/services/api/marketplaceCancellationsService";

const human=value=>value?String(value).replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase()):"Not recorded";
const unavailable=reason=><span title={reason} className={styles.muted}>Not available</span>;
const money=(value,currency)=>`${currency} ${Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function CancellationManagementView(){
  const router=useRouter(),params=useSearchParams(),serialized=params.toString();
  const filters=useMemo(()=>{const p=new URLSearchParams(serialized);return{search:p.get("search")||"",paymentStatus:p.get("paymentStatus")||"",fulfilmentStatus:p.get("fulfilmentStatus")||"",deliveryStatus:p.get("deliveryStatus")||"",refundStatus:p.get("refundStatus")||"",sellerId:p.get("sellerId")||"",customerId:p.get("customerId")||"",currency:p.get("currency")||"",dateFrom:p.get("dateFrom")||"",dateTo:p.get("dateTo")||"",sortBy:p.get("sortBy")||"recordedAt",sortDirection:p.get("sortDirection")||"desc",page:Number(p.get("page"))||1,perPage:Number(p.get("perPage"))||10}},[serialized]);
  const {data,loading,error,stale,reload}=useMarketplaceCancellations(filters); const [search,setSearch]=useState(filters.search),[exporting,setExporting]=useState(false);
  const update=values=>{const next=new URLSearchParams(serialized);Object.entries(values).forEach(([key,value])=>value&&value!=="all"?next.set(key,String(value)):next.delete(key));router.push(`/admin/marketplace/orders/cancellations${next.size?`?${next}`:""}`)};
  const context=data?{Tenant:data.context.tenant,Ecosystem:data.context.ecosystem,Currency:data.context.currency??"Select currency","Date From":data.context.dateFrom,"Date To":data.context.dateTo,Mode:"Cancelled Order Ledger"}:{};
  if(loading&&!data)return <State title="Loading cancellation ledger" loading/>;
  if(error&&!data)return <State title="Cancellation workspace unavailable" text={error} onRetry={reload}/>;
  if(data&&!data.permissions.canView)return <State title="Permission required" text="Your role cannot access cancellation operations."/>;
  return <main className={styles.page}><Breadcrumb items={[{label:"Marketplace",href:"/admin/marketplace"},{label:"Orders",href:"/admin/marketplace/orders"},{label:"Cancellation Management"}]}/>
    <header className={styles.header}><div><h1>Order Cancellation Management</h1><p>Review the authoritative ledger of cancelled orders and their recorded payment, refund, fulfilment, and shipment state.</p></div><div className={styles.headerActions}><button disabled title="Saved cancellation views are not modeled"><Save/>Save View</button><button onClick={()=>update({search,page:1})}><Filter/>Apply Filters</button><button onClick={()=>{setSearch("");router.push("/admin/marketplace/orders/cancellations")}}>Reset</button><button disabled={!data?.permissions.canExport||exporting} onClick={async()=>{setExporting(true);try{await exportMarketplaceCancellations(filters)}finally{setExporting(false)}}}><Download/>{exporting?"Exporting…":"Export"}</button></div></header>
    {data&&<ContextBar data={context} lastUpdated={new Date(data.meta.dataAsOf).toLocaleString()} onRefresh={reload}/>}<div className={styles.alertBar}><AlertTriangle/><div><b>Cancellation request workflows are not configured.</b> This screen is a read-only ledger of orders whose authoritative status is Cancelled. Request review, eligibility, approval, rejection, inventory release, shipment interception, liability, risk, and SLA actions remain unavailable.</div></div>
    <Kpis rows={data?.kpis??[]}/><div className={styles.tabs} role="tablist" aria-label="Cancellation status"><button role="tab" aria-selected={!filters.refundStatus} onClick={()=>update({refundStatus:"",page:1})}>All Cancelled Orders</button><button role="tab" aria-selected={filters.refundStatus==="pending"} onClick={()=>update({refundStatus:"pending",page:1})}>Refunds Pending</button></div>
    <div className={styles.layout}><div className={styles.workspace}><div className={styles.chartGrid}><Trend trend={data?.trend}/><AvailabilityCard title="Cancellation Reason Distribution" availability={data?.reasons}/></div><AvailabilityCard title="Cancellation Health Summary" availability={data?.health}/><Toolbar data={data} filters={filters} search={search} setSearch={setSearch} update={update} reload={reload}/>{error&&<div className={styles.alertBar} role="alert"><AlertTriangle/>{error}{stale&&" Showing the last successfully loaded data."}<button onClick={reload}>Retry</button></div>}<Requests rows={data?.items??[]}/>{data&&<OrderPagination currentPage={data.meta.page} pageSize={data.meta.perPage} totalRecords={data.meta.total} totalPages={data.meta.totalPages} onPageChange={page=>update({page})} onPageSizeChange={perPage=>update({perPage,page:1})}/>}<LowerPanels data={data}/></div><CancellationRail data={data} update={update}/></div>
  </main>;
}

function Kpis({rows}){return <section className={styles.kpis}>{rows.map(row=><article key={row.id} title={row.reason??row.definition}><small>{row.label}</small><strong>{row.available?(row.unit?money(row.value,row.unit):Number.isFinite(Number(row.value))&&String(row.value).includes(".")?Number(row.value).toLocaleString(undefined,{minimumFractionDigits:2}):row.value):"N/A"}</strong></article>)}</section>}
function Trend({trend}){return <Card title="Cancellation Request Trend">{trend?.available?<div className={styles.chart}><ResponsiveContainer width="100%" height="100%"><LineChart data={trend.items} margin={{top:10,right:10,left:-28,bottom:0}}><CartesianGrid vertical={false} stroke="#eee"/><XAxis dataKey="date" tick={{fontSize:9}}/><YAxis allowDecimals={false} tick={{fontSize:9}}/><Tooltip/><Line dataKey="cancelled" name="Cancelled Orders" stroke="#790019"/></LineChart></ResponsiveContainer></div>:<Unavailable reason={trend?.reason}/>}</Card>}
function AvailabilityCard({title,availability}){return <Card title={title}><Unavailable reason={availability?.reason}/></Card>}
function Unavailable({reason}){return <div className={styles.formBody}><p><b>Not available</b></p><small>{human(reason||"required_domain_not_present")}</small></div>}
function Toolbar({data,filters,search,setSearch,update,reload}){const select=(label,key,values)=><label><span>{label}</span><select value={filters[key]||"all"} onChange={event=>update({[key]:event.target.value,page:1})}><option value="all">All</option>{values.map(item=><option key={typeof item==="string"?item:item.id} value={typeof item==="string"?item:item.id}>{typeof item==="string"?human(item):item.name}</option>)}</select></label>;return <div className={styles.toolbar}><label><Search/><input aria-label="Search cancellation ledger" value={search} onChange={event=>setSearch(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")update({search,page:1})}} placeholder="Search order, customer, seller or email…"/></label>{select("Payment Status","paymentStatus",data?.filters.paymentStatuses??[])}{select("Fulfilment Status","fulfilmentStatus",data?.filters.fulfilmentStatuses??[])}{select("Delivery Status","deliveryStatus",data?.filters.deliveryStatuses??[])}{select("Refund Status","refundStatus",data?.filters.refundStatuses??[])}{select("Seller","sellerId",data?.filters.sellers??[])}{select("Customer","customerId",data?.filters.customers??[])}{select("Currency","currency",data?.availableCurrencies??[])}<label><span>From</span><input aria-label="Recorded from" type="date" value={filters.dateFrom} onChange={event=>update({dateFrom:event.target.value,page:1})}/></label><label><span>To</span><input aria-label="Recorded to" type="date" value={filters.dateTo} onChange={event=>update({dateTo:event.target.value,page:1})}/></label><label><span>Sort</span><select value={filters.sortBy} onChange={event=>update({sortBy:event.target.value,page:1})}>{[["recordedAt","Recorded time"],["orderReference","Order reference"],["customer","Customer"],["seller","Seller"],["total","Order total"],["paymentStatus","Payment status"],["refundAmount","Refund amount"]].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>Direction</span><select value={filters.sortDirection} onChange={event=>update({sortDirection:event.target.value,page:1})}><option value="desc">Descending</option><option value="asc">Ascending</option></select></label><button disabled title="Column preferences are not persisted"><Columns3/>Columns</button><button onClick={reload}><RefreshCw/>Refresh</button></div>}
function Requests({rows}){return <Card title="Order Cancellation Ledger"><div className={styles.tableWrap}><table><thead><tr>{["Cancellation ID","Order ID","Customer","Seller","Order Value","Type","Reason","Source","Payment Status","Refund Status","Fulfilment Status","Delivery Status","Refund Amount","Seller Liability","Risk","SLA","Recorded At","Action"].map(value=><th key={value}>{value}</th>)}</tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id}><td>{unavailable("cancellation_request_domain_not_present")}</td><td><Link href={`/admin/marketplace/orders/${row.orderId}`}>{row.orderReference}</Link><small>DB #{row.orderId}</small></td><td>{row.customer.name}</td><td>{row.seller?.name??"Not assigned"}</td><td>{money(row.orderTotal.amount,row.orderTotal.currency)}</td><td>{unavailable(row.requestType.reason)}</td><td>{unavailable(row.reason.reason)}</td><td>{unavailable(row.source.reason)}</td><td><Badge>{human(row.paymentStatus)}</Badge></td><td>{row.refund.status?<Badge>{human(row.refund.status)}</Badge>:"No refund recorded"}</td><td><Badge>{human(row.fulfilmentStatus)}</Badge></td><td>{human(row.delivery?.status)}</td><td>{money(row.refund.amount,row.orderTotal.currency)}</td><td>{unavailable(row.sellerLiability.reason)}</td><td>{unavailable(row.risk.reason)}</td><td>{unavailable(row.sla.reason)}</td><td>{new Date(row.recordedAt).toLocaleString()}<small title={row.timestampSource}>{row.timestampSource==="order_status_histories.created_at"?"Status history":"Order updated time"}</small></td><td><Link href={`/admin/marketplace/orders/${row.orderId}`}>Open Order</Link></td></tr>):<tr><td colSpan={18}><div className={styles.state}><h3>No cancelled orders found</h3><p>Adjust the filters or date range.</p></div></td></tr>}</tbody></table></div></Card>}
function LowerPanels({data}){if(!data)return null;return <div className={styles.grid3} style={{marginTop:9}}><RefundImpact impact={data.refundImpact}/>{[["Pending Cancellation Reviews",data.eligibility],["Cancellation Reason Summary",data.reasons],["Inventory Release Status",data.inventoryRelease],["Shipment Intervention",data.shipmentIntervention],["Seller Liability",data.sellerLiability],["Cancellation Risk & Abuse",data.risk],["Customer and Seller Communication",data.communication],["Cancellation SLA Summary",data.sla]].map(([title,value])=><AvailabilityCard key={title} title={title} availability={value}/>)}</div>}
function RefundImpact({impact}){return <Card title="Payment & Refund Impact">{impact.available?<div className={styles.formBody}>{impact.items.length?impact.items.map(row=><p key={row.status} style={{display:"flex",justifyContent:"space-between"}}><span>{human(row.status)} ({row.count})</span><b>{money(row.amount,impact.currency)}</b></p>):<p>No refund records exist for cancelled orders in this period.</p>}</div>:<Unavailable reason={impact.reason}/>}</Card>}
function CancellationRail({data,update}){return <aside className={styles.rail}><section className={styles.railCard}><h2>Cancellation Operations Health</h2><Unavailable reason={data?.health.reason}/></section><section className={styles.railCard}><h2>Priority Cancellation Alerts</h2>{data?.alerts.length?data.alerts.map(alert=><Link key={alert.id} href={`/admin/marketplace/orders/${alert.orderId}`}><AlertTriangle/><span><b>{alert.type}</b><small>{alert.orderReference} · {alert.refundReference}</small></span></Link>):<p>No pending-refund alerts in this period.</p>}</section><section className={styles.railCard}><h2>Cancellation Status Summary</h2>{data?.statusSummary.map(row=><p key={row.status} style={{display:"flex",justifyContent:"space-between"}}><span>{human(row.status)}</span><b>{row.count}</b></p>)}</section><section className={styles.railCard}><h2>Financial Impact</h2>{data?.refundImpact.available?<RefundRows impact={data.refundImpact}/>:<Unavailable reason={data?.refundImpact.reason}/>}</section><section className={styles.railCard}><h2>Cancellation SLA</h2><Unavailable reason={data?.sla.reason}/></section><section className={styles.railCard}><h2>Quick Queues</h2>{data?.quickQueues.map(queue=><button key={queue.id} onClick={()=>update({...queue.filter,page:1})}><span>{queue.label}</span><b>{queue.count}</b><em>Open</em></button>)}</section></aside>}
function RefundRows({impact}){return <div>{impact.items.map(row=><p key={row.status} style={{display:"flex",justifyContent:"space-between"}}><span>{human(row.status)}</span><b>{money(row.amount,impact.currency)}</b></p>)}</div>}
