<?php
namespace Tests\Feature;
use App\Models\EcosystemModule;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Laravel\Sanctum\Sanctum;use Tests\TestCase;
class EcosystemSectorPacksApiTest extends TestCase{
 use RefreshDatabase;
 public function test_empty_dashboard_registry_and_unknown_pack():void{Sanctum::actingAs(User::factory()->create(['role'=>'super_admin']));$this->getJson('/api/admin/ecosystem/sector-packs/dashboard')->assertOk()->assertJsonPath('dashboard.summary.packs',0)->assertJsonPath('dashboard.health.score',null);$this->getJson('/api/admin/ecosystem/sector-packs')->assertOk()->assertJsonPath('packs.total',0);$this->getJson('/api/admin/ecosystem/sector-packs/missing')->assertNotFound();}
 public function test_create_filter_detail_release_immutability_and_version_clone():void{Sanctum::actingAs($admin=User::factory()->create(['role'=>'super_admin']));$pack=$this->postJson('/api/admin/ecosystem/sector-packs',$this->payload())->assertCreated()->assertJsonPath('pack.slug','beauty-retail-pack')->json('pack');$this->assertDatabaseHas('ecosystem_sector_pack_audits',['sector_pack_id'=>$pack['id'],'action'=>'created']);$version=DB::table('ecosystem_sector_pack_versions')->where('sector_pack_id',$pack['id'])->first();$module=EcosystemModule::create(['uuid'=>(string)Str::uuid(),'module_key'=>'commerce','name'=>'Commerce','category'=>'Commerce','status'=>'operational','is_enabled'=>true]);DB::table('ecosystem_sector_pack_modules')->insert(['sector_pack_version_id'=>$version->id,'ecosystem_module_id'=>$module->id,'requirement'=>'required','compatibility_status'=>'compatible','created_at'=>now(),'updated_at'=>now()]);$this->getJson('/api/admin/ecosystem/sector-packs?search=Beauty&status=draft&sort=name&direction=asc')->assertOk()->assertJsonPath('packs.total',1);$this->getJson('/api/admin/ecosystem/sector-packs/beauty-retail-pack')->assertOk()->assertJsonPath('pack.summary.modules',1)->assertJsonPath('pack.releaseReadiness.status','ready');$this->postJson('/api/admin/ecosystem/sector-packs/beauty-retail-pack/release')->assertOk()->assertJsonPath('version.status','released');$this->patchJson('/api/admin/ecosystem/sector-packs/beauty-retail-pack',['name'=>'Changed','lock_version'=>1])->assertConflict();$draft=$this->postJson('/api/admin/ecosystem/sector-packs/beauty-retail-pack/versions',['version'=>'1.1.0'])->assertCreated()->assertJsonPath('version.status','draft')->json('version');$this->assertDatabaseHas('ecosystem_sector_pack_modules',['sector_pack_version_id'=>$draft['id'],'ecosystem_module_id'=>$module->id]);$this->getJson('/api/admin/ecosystem/sector-packs/beauty-retail-pack/export')->assertOk()->assertJsonPath('source','database');}
 public function test_semver_and_permissions_are_enforced():void{Sanctum::actingAs(User::factory()->create(['role'=>'buyer']));$this->getJson('/api/admin/ecosystem/sector-packs')->assertForbidden();Sanctum::actingAs(User::factory()->create(['role'=>'super_admin']));$this->postJson('/api/admin/ecosystem/sector-packs',[...$this->payload(),'version'=>'version one'])->assertUnprocessable()->assertJsonValidationErrors('version');}
 private function payload():array{return['name'=>'Beauty Retail Pack','slug'=>'beauty-retail-pack','code'=>'SP-BEAUTY','description'=>'Beauty retail capabilities','sector'=>'Beauty','industry'=>'Retail','owner'=>'Platform','version'=>'1.0.0'];}
}
