<?php
namespace Tests\Feature;
use App\Models\EcosystemModule; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Laravel\Sanctum\Sanctum; use Tests\TestCase;
class EcosystemAssignmentsApiTest extends TestCase {
 use RefreshDatabase;
 public function test_empty_assignment_dashboards_and_lists_are_successful():void { Sanctum::actingAs(User::factory()->create(['role'=>'super_admin'])); foreach(['assignments','capabilities'] as $kind){$this->getJson("/api/admin/ecosystem/$kind/dashboard")->assertOk()->assertJsonPath('dashboard.summary.total',0)->assertJsonPath('dashboard.health.score',null);$this->getJson("/api/admin/ecosystem/$kind")->assertOk()->assertJsonPath('assignments.total',0);} }
 public function test_module_and_capability_assignment_crud_filters_audit_and_duplicates():void { Sanctum::actingAs($admin=User::factory()->create(['role'=>'super_admin'])); [$tenant,$bu,$channel,$module,$cap]=$this->domain(); $payload=['company_profile_id'=>$tenant,'business_unit_id'=>$bu,'channel_id'=>$channel,'ecosystem_module_id'=>$module->id,'environment'=>'production','assignment_type'=>'direct','status'=>'pending']; $assignment=$this->postJson('/api/admin/ecosystem/assignments',$payload)->assertCreated()->json('assignment'); $this->postJson('/api/admin/ecosystem/assignments',$payload)->assertConflict(); $this->getJson("/api/admin/ecosystem/assignments?tenant_id=$tenant&business_unit_id=$bu&channel_id=$channel&environment=production&search=Support&sort=module_name&direction=asc")->assertOk()->assertJsonPath('assignments.total',1); $this->patchJson('/api/admin/ecosystem/assignments/'.$assignment['id'],['status'=>'active','governance_status'=>'passed','production_eligible'=>true])->assertOk()->assertJsonPath('assignment.status','active'); $capability=$this->postJson('/api/admin/ecosystem/capabilities',['module_assignment_id'=>$assignment['id'],'capability_id'=>$cap,'assignment_type'=>'direct','status'=>'pending'])->assertCreated()->json('assignment'); $this->getJson('/api/admin/ecosystem/capabilities?status=pending')->assertOk()->assertJsonPath('assignments.total',1); $this->deleteJson('/api/admin/ecosystem/capabilities/'.$capability['id'])->assertOk(); $this->assertDatabaseHas('ecosystem_assignment_audits',['entity_type'=>'module_assignment','entity_id'=>$assignment['id'],'action'=>'created','actor_id'=>$admin->id]); }
 public function test_invalid_hierarchy_and_unauthorized_access_are_rejected():void { Sanctum::actingAs(User::factory()->create(['role'=>'buyer']));$this->getJson('/api/admin/ecosystem/assignments')->assertForbidden(); Sanctum::actingAs(User::factory()->create(['role'=>'super_admin']));[$tenant,$bu,$channel,$module]=$this->domain();$otherTenant=$this->tenant('Other Tenant');$this->postJson('/api/admin/ecosystem/assignments',['company_profile_id'=>$otherTenant,'business_unit_id'=>$bu,'channel_id'=>$channel,'ecosystem_module_id'=>$module->id,'environment'=>'production','assignment_type'=>'direct','status'=>'pending'])->assertUnprocessable()->assertJsonValidationErrors('business_unit_id'); }
 private function domain():array { $tenant=$this->tenant('SL Beauty');$now=now();$bu=DB::table('ecosystem_business_units')->insertGetId(['uuid'=>(string)Str::uuid(),'company_profile_id'=>$tenant,'code'=>'retail','name'=>'Retail','status'=>'active','created_at'=>$now,'updated_at'=>$now]);$channel=DB::table('ecosystem_channels')->insertGetId(['uuid'=>(string)Str::uuid(),'business_unit_id'=>$bu,'code'=>'web','name'=>'Web','status'=>'active','created_at'=>$now,'updated_at'=>$now]);$module=EcosystemModule::create(['uuid'=>(string)Str::uuid(),'module_key'=>'support','name'=>'Support','category'=>'Support','status'=>'operational','is_enabled'=>true]);$cap=DB::table('ecosystem_capabilities')->insertGetId(['uuid'=>(string)Str::uuid(),'ecosystem_module_id'=>$module->id,'capability_key'=>'tickets','name'=>'Tickets','status'=>'active','created_at'=>$now,'updated_at'=>$now]);return[$tenant,$bu,$channel,$module,$cap]; }
 private function tenant(string $name):int { return DB::table('company_profiles')->insertGetId(['uuid'=>(string)Str::uuid(),'legal_name'=>$name,'status'=>'active','created_at'=>now(),'updated_at'=>now()]); }
}
