import { BarChart3, BookOpen, LayoutDashboard, LayoutGrid, LifeBuoy, Megaphone, Settings, ShieldCheck, Store, Tags, Truck, Users, Wallet } from "lucide-react";

export const ADMIN_NAVIGATION = [
  {id:"dashboard",label:"Dashboard",href:"/admin/dashboard",icon:LayoutDashboard,exact:true},
  {id:"marketplace",label:"Marketplace",href:"/admin/marketplace",icon:Store,children:[
    {id:"command-center",label:"Command Center",href:"/admin/marketplace",exact:true},
    {id:"listings",label:"Listings",href:"/admin/marketplace/listings"},
    {id:"sellers",label:"Sellers",href:"/admin/marketplace/sellers"},
    {id:"promotions",label:"Promotions",href:"/admin/marketplace/promotions"},
    {id:"policy-violations",label:"Policy Violations",href:"/admin/marketplace/policy-violations"},
    {id:"commissions",label:"Commissions",href:"/admin/marketplace/commissions"},
    {id:"orders",label:"Order Management",href:"/admin/marketplace/orders"},
    {id:"manual-order-creation",label:"Manual Order Creation",href:"/admin/marketplace/orders/create",exact:true},
    {id:"cancellation-management",label:"Cancellation Management",href:"/admin/marketplace/orders/cancellations",exact:true},
    {id:"returns",label:"Returns & Disputes",href:"/admin/marketplace/returns"},
    {id:"marketplace-settings",label:"Marketplace Configuration",href:"/admin/marketplace/settings"},
    {id:"sales-channels",label:"Sales Channels",href:"/admin/marketplace/channels"},
  ]},
  {id:"catalogue",label:"Catalogue",href:"/admin/catalogue",icon:BookOpen,children:[
    {id:"command-center",label:"Command Center",href:"/admin/catalogue",exact:true},
    {id:"product-masters",label:"Product Masters",href:"/admin/catalogue/products"},
    {id:"product-approvals",label:"Product Approvals",href:"/admin/catalogue/approvals"},
    {id:"inventory",label:"Inventory & Expiry",href:"/admin/catalogue/inventory"},
    {id:"categories",label:"Categories",href:"/admin/catalogue/categories"},
    {id:"brands",label:"Brands",href:"/admin/catalogue/brands"},
    {id:"attributes",label:"Attributes & Variants",href:"/admin/catalogue/attributes"},
    {id:"media",label:"Media Assets",href:"/admin/catalogue/media"},
    {id:"import-export",label:"Import & Export",href:"/admin/catalogue/import-export"},
    {id:"quality",label:"Catalogue Quality",href:"/admin/catalogue/quality"},
  ]},
  {id:"brands-suppliers",label:"Brands & Suppliers",href:"/admin/brands-suppliers",icon:Tags,children:[
    {id:"command-center",label:"Command Center",href:"/admin/brands-suppliers",exact:true},
    {id:"suppliers",label:"Suppliers",href:"/admin/brands-suppliers/suppliers"},
    {id:"supplier-onboarding",label:"Supplier Onboarding",href:"/admin/brands-suppliers/suppliers/create"},
    {id:"supplier-verification",label:"Supplier Verification",href:"/admin/brands-suppliers/verification"},
    {id:"brand-authorizations",label:"Brand Authorizations",href:"/admin/brands-suppliers/authorizations"},
    {id:"contracts-agreements",label:"Contracts & Agreements",href:"/admin/brands-suppliers/contracts"},
    {id:"catalogue-coverage",label:"Product & Catalogue Coverage",href:"/admin/brands-suppliers/catalogue-coverage"},
    {id:"performance-sla",label:"Performance & SLA",href:"/admin/brands-suppliers/performance"},
    {id:"risk-compliance",label:"Risk & Compliance",href:"/admin/brands-suppliers/risk-compliance"},
    {id:"users-access",label:"Supplier Users & Access",href:"/admin/brands-suppliers/users-access"},
    {id:"import-export-audit",label:"Import, Export & Audit",href:"/admin/brands-suppliers/import-export-audit"},
  ]},
  {id:"verification",label:"Verification & Compliance",href:"/admin/verification-compliance/documents",icon:ShieldCheck,children:[
    {id:"command-center",label:"Command Center",href:"/admin/verification-compliance",exact:true},
    {id:"supplier-verification",label:"Supplier Verification",href:"/admin/brands-suppliers/verification"},
    {id:"brand-authorizations",label:"Brand Authorizations",href:"/admin/brands-suppliers/authorizations"},
    {id:"document-verification",label:"Document Verification",href:"/admin/verification-compliance/documents"},
    {id:"product-safety",label:"Product Safety & Regulatory",href:"/admin/verification-compliance/product-safety"},
    {id:"authenticity-investigations",label:"Authenticity Investigations",href:"/admin/verification-compliance/authenticity"},
    {id:"recalls",label:"Recalls & Safety Incidents",href:"/admin/verification-compliance/recalls"},
    {id:"governance",label:"Rules & Policies",href:"/admin/verification-compliance/governance"},
    {id:"sla-escalations",label:"SLA & Escalations",href:"/admin/verification-compliance/governance"},
    {id:"reports",label:"Reports & Analytics",href:"/admin/verification-compliance/reports"},
    {id:"import-export-audit",label:"Import, Export & Audit",href:"/admin/verification-compliance/import-export-audit"},
  ]},
  {id:"customers",label:"Customers",href:"/admin/customers",icon:Users,children:[
    {id:"command-center",label:"Command Center",href:"/admin/customers",exact:true},
    {id:"customer-directory",label:"Customer Directory",href:"/admin/customers/directory"},
    {id:"customer-segments",label:"Customer Segments",href:"/admin/customers/segments"},
    {id:"identity-verification",label:"Identity & Verification",href:"/admin/customers/verification"},
    {id:"addresses-contacts",label:"Addresses & Contacts",href:"/admin/customers/addresses-contacts"},
    {id:"orders-purchase-history",label:"Orders & Purchase History",href:"/admin/customers/orders"},
    {id:"returns-disputes",label:"Returns, Refunds & Disputes",href:"/admin/customers/returns-refunds-disputes"},
    {id:"loyalty-membership",label:"Loyalty, Rewards & Membership",href:"/admin/customers/loyalty"},
    {id:"consent-privacy",label:"Consent, Privacy & Preferences",href:"/admin/customers/consent-privacy"},
    {id:"risk-restrictions",label:"Risk, Restrictions & Fraud Signals",href:"/admin/customers/risk-restrictions"},
    {id:"support-communications",label:"Support & Communications",href:"/admin/customers/support-communications"},
    {id:"import-export-audit",label:"Import, Export & Audit",href:"/admin/customers/import-export-audit"},
  ]},
  {id:"marketing",label:"Marketing",icon:Megaphone,disabled:true,badge:"Coming Soon"},
  {id:"finance",label:"Finance",icon:Wallet,href:"/admin/finance",children:[
    {id:"command-center",label:"Command Center",href:"/admin/finance",exact:true},
    {id:"revenue-receivables",label:"Revenue & Receivables",href:"/admin/finance/revenue-receivables"},
    {id:"payments-transactions",label:"Payments & Transactions",href:"/admin/finance/payments"},
    {id:"refunds-compensation",label:"Refunds & Compensation",href:"/admin/finance/refunds-compensation"},
    {id:"supplier-payables",label:"Supplier Payables",href:"/admin/finance/supplier-payables"},
    {id:"commissions-fees",label:"Commissions & Fees",href:"/admin/finance/commissions-fees"},
    {id:"settlements-payouts",label:"Settlements & Payouts",href:"/admin/finance/settlements-payouts"},
    {id:"invoices-notes",label:"Invoices & Notes",href:"/admin/finance/invoices-notes"},
    {id:"tax-currency",label:"Tax & Currency",href:"/admin/finance/tax-currency-configuration"},
    {id:"reconciliation-controls",label:"Reconciliation & Controls",href:"/admin/finance/reconciliation-controls"},
    {id:"reports-audit",label:"Reports / Import / Export / Audit",href:"/admin/finance/reports-import-export-audit"},
  ]},
  {id:"logistics",label:"Logistics",icon:Truck,href:"/admin/logistics",children:[
    {id:"logistics-overview",label:"Overview",href:"/admin/logistics",exact:true},
    {id:"shipment-operations",label:"Shipment Operations",href:"/admin/logistics/shipments"},
  ]},
  {id:"customer-support",label:"Customer Support",icon:LifeBuoy,href:"/admin/customer-support/cases"},
  {id:"analytics",label:"Analytics",icon:BarChart3,href:"/admin/analytics",children:[
    {id:"analytics-overview",label:"Analytics & BI",href:"/admin/analytics",exact:true},
    {id:"analytics-reports",label:"Reports",href:"/admin/analytics/reports"},
  ]},
  {id:"ecosystem-modules",label:"Ecosystem Modules",icon:LayoutGrid,href:"/admin/ecosystem-modules"},
  {id:"administration",label:"Administration",icon:Settings,disabled:true,badge:"Coming Soon"},
];
