import { BarChart3, BookOpen, LayoutDashboard, LayoutGrid, LifeBuoy, Megaphone, Settings, ShieldCheck, Store, Tags, Truck, Users, Wallet } from "lucide-react";

export const ADMIN_NAVIGATION = [
  {id:"dashboard",label:"Dashboard",href:"/admin/dashboard",icon:LayoutDashboard,exact:true},
  {id:"marketplace",label:"Marketplace",href:"/admin/marketplace",icon:Store,children:[
    {id:"command-center",label:"Command Center",href:"/admin/marketplace",exact:true},
    {id:"listings",label:"Listings",href:"/admin/marketplace/listings"},
    {id:"sellers",label:"Sellers",href:"/admin/marketplace/sellers"},
    {id:"promotions",label:"Promotions",href:"/admin/marketplace/promotions"},
    {id:"policy-violations",label:"Policy Violations",href:"/admin/marketplace/policy-violations"},
    {id:"campaigns",label:"Campaigns",href:"/admin/marketplace/campaigns"},
    {id:"commissions",label:"Commissions",href:"/admin/marketplace/commissions"},
    {id:"orders",label:"Order Management",href:"/admin/marketplace/orders"},
    {id:"manual-order-creation",label:"Manual Order Creation",href:"/admin/marketplace/orders/create",exact:true},
    {id:"cancellation-management",label:"Cancellation Management",href:"/admin/marketplace/orders/cancellations",exact:true},
    {id:"returns",label:"Returns & Disputes",href:"/admin/marketplace/returns"},
    {id:"marketplace-settings",label:"Marketplace Configuration",href:"/admin/marketplace/settings"},
    {id:"sales-channels",label:"Sales Channels",href:"/admin/marketplace/channels"},
  ]},
  {id:"catalogue",label:"Catalogue",href:"/admin/catalogue",icon:BookOpen,children:[
    {id:"command-center",label:"Command Center",href:"/admin/catalogue",exact:true},
    {id:"product-masters",label:"Product Masters",href:"/admin/catalogue/products"},
    {id:"product-approvals",label:"Product Approvals",href:"/admin/catalogue/approvals"},
    {id:"inventory",label:"Inventory & Expiry",href:"/admin/catalogue/inventory"},
    {id:"categories",label:"Categories",href:"/admin/catalogue/categories"},
    {id:"brands",label:"Brands",href:"/admin/catalogue/brands"},
    {id:"attributes",label:"Attributes & Variants",href:"/admin/catalogue/attributes"},
    {id:"media",label:"Media Assets",href:"/admin/catalogue/media"},
    {id:"import-export",label:"Import & Export",href:"/admin/catalogue/import-export"},
    {id:"quality",label:"Catalogue Quality",href:"/admin/catalogue/quality"},
  ]},
  {id:"brands-suppliers",label:"Brands & Suppliers",href:"/admin/verification/brand-authorizations",icon:Tags},
  {id:"verification",label:"Verification & Compliance",href:"/admin/verification/suppliers",icon:ShieldCheck,children:[
    {id:"supplier-verification",label:"Supplier Verification",href:"/admin/verification/suppliers"},
    {id:"brand-authorizations",label:"Brand Authorizations",href:"/admin/verification/brand-authorizations"},
  ]},
  {id:"customers",label:"Customers",icon:Users,disabled:true,badge:"Coming Soon"},
  {id:"marketing",label:"Marketing",icon:Megaphone,disabled:true,badge:"Coming Soon"},
  {id:"finance",label:"Finance",icon:Wallet,disabled:true,badge:"Coming Soon"},
  {id:"logistics",label:"Logistics",icon:Truck,href:"/admin/logistics",children:[
    {id:"logistics-overview",label:"Overview",href:"/admin/logistics",exact:true},
    {id:"shipment-operations",label:"Shipment Operations",href:"/admin/logistics/shipments"},
  ]},
  {id:"customer-support",label:"Customer Support",icon:LifeBuoy,href:"/admin/customer-support/cases"},
  {id:"analytics",label:"Analytics",icon:BarChart3,href:"/admin/analytics",children:[
    {id:"analytics-overview",label:"Analytics & BI",href:"/admin/analytics",exact:true},
    {id:"analytics-reports",label:"Reports",href:"/admin/analytics/reports"},
  ]},
  {id:"ecosystem-modules",label:"Ecosystem Modules",icon:LayoutGrid,href:"/admin/ecosystem-modules"},
  {id:"administration",label:"Administration",icon:Settings,disabled:true,badge:"Coming Soon"},
];
