"use client";
import {useMemo} from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {AlertTriangle,BarChart3,CalendarDays,ChevronRight,Download,LockKeyhole,Plus,RefreshCw,Search,ShieldAlert,Tag,Users} from "lucide-react";
import {useMarketplacePromotions} from "@/hooks/admin/useMarketplacePromotions";
import styles from "./marketplace-promotions.module.css";

const human=value=>value?.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())||"Not available";
const sections=[["Promotion Revenue and Discount Trend","trend"],["Promotion Type Distribution","typeDistribution"],["Promotion Health Scorecard","scorecard"],["Awaiting Approval","approvals"],["Promotion Conflicts and Exceptions","conflicts"],["Promotion Budget and Funding","budget"],["Seller Participation","participation"],["Eligibility and Scope Summary","eligibility"],["Campaign Timeline","timeline"],["Promotion Policy Checklist","policyChecklist"]];

export default function MarketplacePromotionsView(){const params=useSearchParams(),paramsKey=params.toString();const filters=useMemo(()=>({search:params.get("search")||undefined,dateFrom:params.get("dateFrom")||undefined,dateTo:params.get("dateTo")||undefined,page:Number(params.get("page")||1),perPage:Number(params.get("perPage")||25)}),[paramsKey]); // eslint-disable-line react-hooks/exhaustive-deps
  const{data,loading,refreshing,error,stale,refresh}=useMarketplacePromotions(filters);
  if(loading&&!data)return <main className={`${styles.page} ${styles.loading}`} aria-busy="true"><div/><div/><div/><div/></main>;
  if(error&&!data)return <section className={styles.state} role="alert"><ShieldAlert/><h1>Marketplace Promotions &amp; Deals</h1><p>{error}</p><button onClick={()=>void refresh()}>Retry</button></section>;
  if(!data)return null;
  if(data.permissions?.canView===false)return <section className={styles.state}><LockKeyhole/><h1>Permission required</h1></section>;
  return <main className={styles.page}><nav className={styles.breadcrumb}><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><span>Promotions</span></nav><header className={styles.header}><div><h1>Marketplace Promotions &amp; Deals</h1><p>Create, approve and monitor promotions, vouchers, discounts and funded deals when the promotion domain is configured.</p></div><div className={styles.headerActions}><button disabled title="Promotion reporting is unavailable"><Download/>Export Promotion Report</button><button disabled>Compare Campaigns</button><button disabled>Bulk Actions</button><button className={styles.primary} disabled title="Promotion creation requires a promotion schema and workflow"><Plus/>Create Promotion</button></div></header>
    <section className={styles.context}><div><div><Tag/><span>Tenant</span><strong>SL Beauty</strong></div><div><Tag/><span>Ecosystem</span><strong>Beauty Marketplace</strong></div><div><CalendarDays/><span>Date range</span><strong>{data.filters.dateFrom} – {data.filters.dateTo}</strong></div></div><footer><LockKeyhole/>Authenticated administrator context <aside><i/><b>{stale?"Stale":"Live polling"}</b><small>Last updated: {new Date(data.meta.dataAsOf).toLocaleString()}</small><button aria-label="Refresh promotions" onClick={()=>void refresh(true)} disabled={refreshing}><RefreshCw className={refreshing?styles.spin:""}/></button></aside></footer></section>
    <section className={`${styles.card} ${styles.warning}`} role="status"><AlertTriangle/><div><h2>Promotion engine configuration required</h2><p>No promotion records or calculations are shown because the database has no promotion, redemption, budget, eligibility, approval, conflict, or promotion-order attribution tables.</p><small>Missing capability: {human(data.availability.reason)}</small></div></section>
    <section className={styles.kpis}>{data.kpis.map((item,index)=><article key={item.id} title={item.reason}><span>{index%2?<BarChart3/>:<Tag/>}</span><div><small>{item.label}</small><strong>Not available</strong><em>Configuration required</em></div></article>)}</section>
    <div className={styles.layout}><div className={styles.workspace}><section className={styles.heroCharts}>{sections.slice(0,2).map(([title,key])=><UnavailableCard key={key} title={title} block={data[key]}/>)}</section><UnavailableCard title="Promotion Health Scorecard" block={data.scorecard}/><section className={`${styles.card} ${styles.tableCard}`}><div className={styles.tabs} role="tablist"><button role="tab" aria-selected="true">All Promotions</button></div><div className={styles.filters}><label className={styles.search}><Search/><input disabled placeholder="Search requires promotion records"/></label></div><div className={styles.tableTitle}><h2>Marketplace Promotions</h2><span>0 promotions</span></div><div className={styles.empty}><Tag/><h3>No promotion domain configured</h3><p>Real promotion records cannot load until a reviewed schema, status model, and attribution rules are added.</p></div></section><section className={styles.dual}>{sections.slice(3,5).map(([title,key])=><UnavailableCard key={key} title={title} block={data[key]}/>)}</section><section className={styles.triptych}>{sections.slice(5,8).map(([title,key])=><UnavailableCard key={key} title={title} block={data[key]}/>)}</section><section className={styles.bottom}>{sections.slice(8).map(([title,key])=><UnavailableCard key={key} title={title} block={data[key]}/>)}</section></div><aside className={styles.rail}><UnavailableCard title="Promotion Health" block={data.health}/><RailEmpty title="Priority Promotion Alerts" text="No promotion alert source exists."/><UnavailableCard title="Promotion Status Summary" block={data.statusSummary}/><UnavailableCard title="Approval SLA Summary" block={data.sla}/><UnavailableCard title="Financial Impact" block={data.financial}/><RailEmpty title="Quick Queues" text="No promotion queues are available."/></aside></div>
  </main>}
function UnavailableCard({title,block}){return <section className={`${styles.card} ${styles.chartCard}`}><header className={styles.cardHeader}><h2>{title}</h2></header><div className={styles.empty}><AlertTriangle/><h3>Not available</h3><p>{human(block?.reason||"promotion_domain_not_present")}</p></div></section>}
function RailEmpty({title,text}){return <section className={styles.railCard}><header><h2>{title}</h2></header><div className={styles.empty}><Users/><p>{text}</p></div></section>}
