"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {AlertTriangle,ArrowDownUp,BadgePercent,CalendarDays,CheckCircle2,ChevronDown,ChevronLeft,ChevronRight,Clock3,Columns3,Download,Filter,HeartPulse,Info,LockKeyhole,MoreVertical,Plus,RefreshCw,Save,Search,ShieldAlert,SlidersHorizontal,Tag,Upload,Users,X,XCircle} from "lucide-react";
import {Bar,CartesianGrid,Cell,ComposedChart,Legend,Line,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import toast from "react-hot-toast";
import {fetchMarketplacePromotions,recordPromotionPreviewAction} from "@/services/api/marketplacePromotionsService";
import styles from "./marketplace-promotions.module.css";

const tabs=["All Promotions","Active","Scheduled","Pending Approval","Draft","Ending Soon","Expired","Paused","Rejected","Conflicts"];
const counts={"Pending Approval":9,Draft:11,"Ending Soon":6,Expired:32,Paused:4,Rejected:2,Conflicts:5};
const filters=["Status","Type","Funding Source","Business Unit","Channel","Marketplace","Seller","Category"];

export default function MarketplacePromotionsView(){
  const router=useRouter();
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refreshing,setRefreshing]=useState(false),[active,setActive]=useState("All Promotions"),[query,setQuery]=useState(""),[selected,setSelected]=useState([]),[modal,setModal]=useState(null),[menu,setMenu]=useState(null),[page,setPage]=useState(1),[period,setPeriod]=useState("Weekly"),[columns,setColumns]=useState(false);const menuRef=useRef(null);
  const load=async(refresh=false)=>{try{setError("");refresh?setRefreshing(true):setLoading(true);const result=await fetchMarketplacePromotions();setData(result);if(refresh)toast.success("Promotion data refreshed from the frontend fixture")}catch(e){if(e.name!=="AbortError")setError("Marketplace promotion data could not be loaded.")}finally{setLoading(false);setRefreshing(false)}};
  useEffect(()=>{const controller=new AbortController();void fetchMarketplacePromotions(controller.signal).then(setData).catch(e=>{if(e.name!=="AbortError")setError("Marketplace promotion data could not be loaded.")}).finally(()=>setLoading(false));return()=>controller.abort()},[]);
  useEffect(()=>{const close=e=>{if(menuRef.current&&!menuRef.current.contains(e.target))setMenu(null)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
  const rows=useMemo(()=>data?.promotions.filter(row=>{const match=Object.values(row).join(" ").toLowerCase().includes(query.toLowerCase());const tab=active==="All Promotions"||row.approval===active||(active==="Conflicts"&&row.conflict!=="Clear")||(active==="Ending Soon"&&row.end.includes("Aug 2026"))||(active==="Active"&&row.approval==="Approved");return match&&tab})??[],[data,query,active]);
  const toggleAll=()=>setSelected(selected.length===rows.length?[]:rows.map(row=>row.id));
  const previewAction=async(type,note="")=>{await recordPromotionPreviewAction(type,selected,note);setModal(null);setColumns(false);toast.success(`${type} saved in local preview state (not server-persisted)`) };
  const openPromotion=id=>router.push(`/admin/marketplace/promotions/${encodeURIComponent(id)}`);
  const openPromotionReference=value=>{const promotion=data.promotions.find(item=>item.id===value||item.name===value);if(promotion)openPromotion(promotion.id);else setModal(value)};
  const exportReport=()=>{const lines=[["Promotion","Promotion ID","Type","Budget","GMV","Approval","Conflict"],...data.promotions.map(row=>[row.name,row.id,row.type,row.budget,row.gmv,row.approval,row.conflict])];const blob=new Blob([lines.map(line=>line.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="marketplace-promotions.csv";anchor.click();URL.revokeObjectURL(url);toast.success("Promotion report exported")};
  if(loading&&!data)return <Loading/>;
  if(error&&!data)return <section className={styles.state} role="alert"><ShieldAlert/><h1>Marketplace Promotions & Deals</h1><p>{error}</p><button onClick={()=>void load()}>Retry</button></section>;
  if(!data)return <section className={styles.state}><BadgePercent/><h1>No promotion data available</h1></section>;
  if(data.permissions?.canView===false)return <section className={styles.state}><LockKeyhole/><h1>Permission required</h1><p>Your role cannot access marketplace promotions.</p></section>;
  return <main className={styles.page}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><span>Promotions</span></nav>
    <header className={styles.header}><div><h1>Marketplace Promotions & Deals</h1><p>Create, approve, schedule and monitor marketplace campaigns, vouchers, discounts, bundles and seller-funded deals.</p></div><div className={styles.headerActions}><button onClick={exportReport}><Download/>Export Promotion Report</button><button onClick={()=>setModal("Compare Campaigns")}><ArrowDownUp/>Compare Campaigns</button><button disabled={!selected.length} onClick={()=>setModal("Bulk Actions")}><SlidersHorizontal/>Bulk Actions<ChevronDown/></button><button className={styles.primary} onClick={()=>setModal("Create Promotion")}><Plus/>Create Promotion</button></div></header>
    <Context data={data}/><div className={styles.live}><i/>Live data <small>Last updated: {data.lastUpdated}</small><button aria-label="Refresh promotions" disabled={refreshing} onClick={()=>void load(true)}><RefreshCw className={refreshing?styles.spin:""}/></button></div>
    <div className={styles.layout}><div className={styles.workspace}>
      <Kpis items={data.kpis}/>
      <section className={styles.card}><div className={styles.tabs} role="tablist" aria-label="Promotion status">{tabs.map(tab=><button role="tab" aria-selected={active===tab} key={tab} onClick={()=>{setActive(tab);setPage(1)}}>{tab}{counts[tab]&&<b>{counts[tab]}</b>}</button>)}</div><div className={styles.heroCharts}><Trend data={data.trend} period={period} setPeriod={setPeriod}/><Distribution data={data.distribution}/></div></section>
      <HealthScorecard items={data.health}/>
      <section className={`${styles.card} ${styles.tableCard}`}><div className={styles.filters}><label className={styles.search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search promotions…"/></label>{filters.map(label=><button key={label}>{label}<ChevronDown/></button>)}<button onClick={()=>setModal("More Filters")}><Filter/>More Filters</button><button className={styles.clear} onClick={()=>{setQuery("");setActive("All Promotions")}}>Clear All</button><button onClick={()=>setModal("Save View")}><Save/>Save View</button><button><ArrowDownUp/>Sort By · Start Date</button><button onClick={()=>setColumns(true)}><Columns3/>Columns</button><button aria-label="Refresh promotion table" onClick={()=>void load(true)}><RefreshCw/></button></div><div className={styles.tableTitle}><h2>Marketplace Promotions</h2><span>{rows.length} of 28 promotions</span></div><PromotionsTable rows={rows} selected={selected} setSelected={setSelected} toggleAll={toggleAll} menu={menu} setMenu={setMenu} menuRef={menuRef} onAction={setModal} onOpen={openPromotion}/><footer className={styles.pagination}><span>Showing 1 to {rows.length} of 28 promotions</span><div><button disabled={page===1} onClick={()=>setPage(value=>value-1)}><ChevronLeft/></button>{[1,2,3,4,5].map(value=><button className={page===value?styles.current:""} onClick={()=>setPage(value)} key={value}>{value}</button>)}<button onClick={()=>setPage(value=>value+1)}><ChevronRight/></button><button>15 / page<ChevronDown/></button></div></footer></section>
      <div className={styles.dual}><Approvals rows={data.approvals} onOpen={openPromotionReference}/><Conflicts rows={data.conflicts} onAction={setModal}/></div>
      <div className={styles.triptych}><Budget budget={data.budget}/><Participation data={data.participation} onAction={setModal}/><Eligibility/></div>
      <div className={styles.bottom}><Performance rows={data.performance}/><Timeline rows={data.timeline}/><Precedence rows={data.precedence}/></div>
    </div><OperationalRail data={data} onAction={setModal} onOpen={openPromotionReference}/></div>
    {(modal||columns)&&<PromotionModal type={columns?"Column Visibility":modal} data={data} selected={selected} onClose={()=>{setModal(null);setColumns(false)}} onConfirm={previewAction}/>} 
  </main>
}

function Context({data}){return <section className={styles.context}><div>{Object.entries(data.context).map(([key,value])=><button key={key}><span>{key.replace(/([A-Z])/g," $1")}:</span><b>{value}</b><ChevronDown/></button>)}</div><aside><LockKeyhole/>Access limited to assigned business context</aside></section>}
function Kpis({items}){return <section className={styles.kpis}>{items.map((item,index)=><article key={item.label}><span>{index%4===1?<CalendarDays/>:index%4===2?<Clock3/>:index%4===3?<Users/>:<BadgePercent/>}</span><div><small>{item.label}</small><strong>{item.value}</strong><em className={styles[item.tone]}>{item.tone==="bad"?"↓":"↑"} {item.change}</em></div></article>)}</section>}
function Trend({data,period,setPeriod}){return <article className={styles.chartCard}><header><h2>Promotion Revenue & Discount Trend <Info/></h2><div>{["Daily","Weekly","Monthly","Quarterly","Custom"].map(item=><button aria-pressed={period===item} onClick={()=>setPeriod(item)} key={item}>{item}</button>)}</div></header><div className={styles.chart} role="img" aria-label="Promotion revenue and discount trend"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:12,right:10,left:-25,bottom:0}}><CartesianGrid stroke="#eee" vertical={false}/><XAxis dataKey="date" tick={{fontSize:8}}/><YAxis tick={{fontSize:8}}/><Tooltip/><Legend wrapperStyle={{fontSize:8}}/><Bar dataKey="net" fill="#c7c3c2" name="Net Sales"/><Bar dataKey="discount" fill="#e99c00" name="Discount Value"/><Bar dataKey="platform" fill="#319069" name="Platform Funding"/><Bar dataKey="seller" fill="#23808e" name="Seller Funding"/><Line type="monotone" dataKey="gmv" stroke="#790019" strokeWidth={2} name="Promotion GMV"/></ComposedChart></ResponsiveContainer></div></article>}
function Distribution({data}){return <article className={styles.chartCard}><header><h2>Promotion Type Distribution</h2></header><div className={styles.distribution}><div><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius={46} outerRadius={72} startAngle={90} endAngle={-270}>{data.map(item=><Cell key={item.label} fill={item.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><span><b>28</b>Total<br/>Promotions</span></div><ul>{data.map(item=><li key={item.label}><i style={{background:item.color}}/><span>{item.label}</span><b>{item.percent}%</b><em>({item.value})</em></li>)}</ul></div></article>}
function HealthScorecard({items}){return <section className={`${styles.card} ${styles.scorecard}`}><h2>Promotion Health Scorecard <Info/></h2><div>{items.map(item=><article key={item.label}><small>{item.label}</small><strong>{item.value}</strong><b className={styles[item.tone]}>{item.rating}</b></article>)}</div></section>}
function PromotionsTable({rows,selected,setSelected,toggleAll,menu,setMenu,menuRef,onAction,onOpen}){if(!rows.length)return <div className={styles.empty}><BadgePercent/><h3>No promotions match the filters</h3><p>Clear or adjust the current search and status controls.</p></div>;const heads=["Promotion Name","Promotion ID","Type","Scope","BU","Channel","Seller / Segment","Category / Brand","Discount","Funding Source","Total Budget","Budget Used","Start Date","End Date","Participants","Orders","Promotion GMV","Conv. Lift","Approval Status","Conflict Status","Created By","Approved By","Last Updated","Action"];return <div className={styles.tableWrap}><table><thead><tr><th><input aria-label="Select all promotions" type="checkbox" checked={selected.length===rows.length} onChange={toggleAll}/></th>{heads.map(head=><th key={head}>{head}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><input aria-label={`Select ${row.name}`} type="checkbox" checked={selected.includes(row.id)} onChange={()=>setSelected(items=>items.includes(row.id)?items.filter(id=>id!==row.id):[...items,row.id])}/></td><td><button className={styles.recordLink} onClick={()=>onOpen(row.id)}>{row.name}</button></td><td><button className={styles.recordLink} onClick={()=>onOpen(row.id)}>{row.id}</button></td><td>{row.type}</td><td>{row.scope}</td><td>{row.unit}</td><td>{row.channel}</td><td>{row.seller}</td><td>{row.category}</td><td><b>{row.discount}</b></td><td>{row.funding}</td><td>{row.budget}</td><td>{row.used}<small className={Number.parseInt(row.utilization)>100?styles.bad:""}>{row.utilization}</small></td><td>{row.start}</td><td>{row.end}</td><td>{row.participants}</td><td>{row.orders}</td><td>{row.gmv}</td><td className={styles.good}>{row.lift}</td><td><Badge value={row.approval}/></td><td><Badge value={row.conflict}/></td><td>{row.creator}</td><td>{row.approver}</td><td>{row.updated}</td><td className={styles.actionCell}><button aria-label={`Actions for ${row.name}`} onClick={()=>setMenu(menu===row.id?null:row.id)}><MoreVertical/></button>{menu===row.id&&<div ref={menuRef} className={styles.rowMenu}>{["View Promotion","Edit Promotion","Review Promotion","Duplicate Promotion","Pause Promotion","Archive Promotion"].map(action=><button key={action} onClick={()=>{setMenu(null);action==="View Promotion"||action==="Review Promotion"?onOpen(row.id):onAction(`${action}: ${row.name}`)}}>{action}</button>)}</div>}</td></tr>)}</tbody></table></div>}
function Badge({value}){const tone=["Approved","Clear","Active"].includes(value)?"success":["Commission Conflict","Budget Overrun","Rejected"].includes(value)?"danger":["Pending Approval","Minor Overlap"].includes(value)?"warning":"info";return <span className={`${styles.badge} ${styles[tone]}`}>{value}</span>}
function Panel({title,action,children}){return <section className={styles.card}><header className={styles.cardHeader}><h2>{title}</h2>{action&&<button>{action}<ChevronRight/></button>}</header>{children}</section>}
function Approvals({rows,onOpen}){return <Panel title="Pending Promotion Approvals" action="View all (7)"><div className={styles.smallTable}><table><thead><tr>{["Promotion","Requested Change","Requested By","Requested Date","Discount Impact","Funding Impact","Budget Impact","Conflict Status","Approval SLA","Action"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.promotion}>{Object.values(row).map((value,index)=><td key={index}>{value}</td>)}<td><button onClick={()=>onOpen(row.promotion)}>Review</button></td></tr>)}</tbody></table></div></Panel>}
function Conflicts({rows,onAction}){return <Panel title="Promotion Conflict Summary"><div className={styles.smallTable}><table><thead><tr>{["Conflict Type","Severity","Affected Promotions","Financial Impact","Status","Action"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.type}><td>{row.type}</td><td><Badge value={row.severity}/></td><td>{row.affected}</td><td>{row.impact}</td><td>{row.status}</td><td><button onClick={()=>onAction(`Resolve Conflict: ${row.type}`)}>Resolve Conflict</button></td></tr>)}</tbody></table></div></Panel>}
function Budget({budget}){return <Panel title="Promotion Budget & Funding"><div className={styles.budget}><dl>{[["Total Campaign Budget",budget.total],["Budget Used",budget.used],["Committed Budget",budget.committed],["Remaining Budget",budget.remaining]].map(([a,b],i)=><div key={a}><dt>{a}</dt><dd>{b}</dd><i><b style={{width:`${[100,41,21,38][i]}%`}}/></i></div>)}</dl><div className={styles.fundingDonut}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={budget.sources} dataKey="value" innerRadius={36} outerRadius={58}>{budget.sources.map(x=><Cell key={x.label} fill={x.color}/>)}</Pie></PieChart></ResponsiveContainer><span><b>{budget.total}</b>Total Budget</span></div><ul>{budget.sources.map(x=><li key={x.label}><i style={{background:x.color}}/>{x.label}<b>{x.amount}</b></li>)}</ul></div></Panel>}
function Participation({data,onAction}){return <Panel title="Seller Participation"><div className={styles.participation}><div>{[["Invited",data.invited],["Accepted",data.accepted],["Pending",data.pending],["Declined",data.declined]].map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</div><h3>Top Participation Sellers</h3>{data.leaders.map((x,index)=><p className={styles.leader} key={x.name}><b>{index+1}</b><span>{x.name}</span><em>{x.value}</em></p>)}<footer><button onClick={()=>onAction("View Participants")}>View Participants</button><button className={styles.primary} onClick={()=>onAction("Invite Sellers")}>Invite Sellers</button></footer></div></Panel>}
function Eligibility(){const rows={"Business Units":"SL Beauty · TOKYO Beauty","Channels":"Online · Mobile App","Sellers":"All Sellers (86) · Top 20 Sellers","Categories":"Skincare · Makeup · Haircare · +2","Brands":"All Brands (124)","Products":"1,138 Eligible Listings","Min. Basket Value":"LKR 2,000","Customer Eligibility":"All Customers","Voucher Limit":"1 per customer","Regional Restrictions":"Sri Lanka Only","Stacking Rules":"See precedence rules"};return <Panel title="Eligibility & Scope Summary"><div className={styles.eligibility}>{Object.entries(rows).map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</div></Panel>}
function Performance({rows}){return <Panel title="Promotion Performance"><div className={styles.performance}>{rows.map(row=><article key={row.label}><small>{row.label}</small><b>{row.value}</b><em>↑ {row.change}</em></article>)}</div></Panel>}
function Timeline({rows}){return <Panel title="Campaign Timeline"><div className={styles.timeline}><header><span>Jul 20</span><span>Jul 27</span><span>Aug 3</span><span>Aug 10</span><span>Aug 17</span></header>{rows.map(row=><p key={row.label}><span>{row.label}</span><i className={styles[row.tone]} style={{marginLeft:`${row.start}%`,width:`${row.width}%`}}>{row.label}</i></p>)}<footer><span className={styles.active}/>Active <span className={styles.scheduled}/>Scheduled <span className={styles.ending}/>Ending Soon <span className={styles.conflict}/>Conflict <span className={styles.approval}/>Approval Deadline</footer></div></Panel>}
function Precedence({rows}){return <Panel title="Promotion Stacking Precedence"><ol className={styles.precedence}>{rows.map((row,index)=><li key={row}><b>{index+1}</b><span>{row}</span><em>{index===0?"Always applied":index<3?"Applied first":"Applied after prior discount"}</em></li>)}</ol><footer className={styles.legend}><span>✓ Applied Discounts</span><span>× Blocked / Not Applied Discounts</span></footer></Panel>}
function OperationalRail({data,onAction,onOpen}){return <aside className={styles.rail}><section className={styles.railCard}><h2>Promotion Health</h2><div className={styles.health}><ShieldAlert/><strong>88<small>/100</small></strong><em>Overall Score</em></div>{data.health.slice(0,6).map(item=><Progress key={item.label} label={item.label} value={Number(item.value.replace("%",""))}/>)}</section><section className={styles.railCard}><h2>Priority Promotion Alerts</h2><div className={styles.alerts}>{data.alerts.map(item=>{const promotion=data.promotions.find(row=>row.id===item.detail||row.name===item.detail);return <button key={item.title} onClick={()=>promotion?onOpen(promotion.id):onAction(item.action)}><AlertTriangle className={styles[item.tone]}/><span><b>{item.title}</b><small>{item.detail}</small></span><em>{item.action}</em></button>})}</div><button className={styles.railLink} onClick={()=>onAction("View all alerts")}>View all alerts (12)</button></section><section className={styles.railCard}><h2>Promotion Status Summary</h2><div className={styles.statusGrid}>{Object.entries(data.statusSummary).map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</div></section><section className={styles.railCard}><h2>Approval SLA Summary</h2>{data.sla.map(item=><Progress key={item.label} label={item.label} value={item.value} detail={item.time}/>)}</section><section className={styles.railCard}><h2>Financial Impact</h2>{Object.entries(data.financial).map(([a,b])=><p className={styles.money} key={a}><span>{a}</span><b>{b}</b></p>)}</section><section className={styles.railCard}><h2>Quick Queues</h2><div className={styles.queues}>{Object.entries(data.queues).map(([a,b])=><button key={a} onClick={()=>onAction(a)}><span>{a}</span><b>{b}</b><ChevronRight/></button>)}</div></section></aside>}
function Progress({label,value,detail}){return <div className={styles.progress}><p><span>{label}</span><b>{value}%</b>{detail&&<em>{detail}</em>}</p><i><b style={{width:`${value}%`}}/></i></div>}
function PromotionModal({type,data,selected,onClose,onConfirm}){const [busy,setBusy]=useState(false),[note,setNote]=useState(""),[validation,setValidation]=useState("");const sensitive=/Bulk|Pause|Archive|Resolve|Review|Budget|Approval/.test(type??"");const submit=async()=>{if(sensitive&&!note.trim()){setValidation("An internal note or audit reason is required.");return}setBusy(true);try{await onConfirm(type,note)}finally{setBusy(false)}};const create=type==="Create Promotion",compare=type==="Compare Campaigns",more=type==="More Filters",save=type==="Save View",column=type==="Column Visibility";return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="promotion-modal-title"><header><div><small>Marketplace Promotions · Frontend Preview</small><h2 id="promotion-modal-title">{type}</h2></div><button aria-label="Close dialog" onClick={onClose}><X/></button></header><div className={styles.modalBody}>{create?<div className={styles.formGrid}>{["Promotion name","Promotion type","Funding source","Business unit","Sales channel","Seller / segment","Category","Discount value","Total budget","Start date","End date","Approver"].map(label=><label key={label}>{label}<input placeholder={label}/></label>)}</div>:compare?<div className={styles.compare}>{data.promotions.filter(row=>selected.length?selected.includes(row.id):true).slice(0,2).map(row=><article key={row.id}><h3>{row.name}</h3><p>GMV <b>{row.gmv}</b></p><p>Budget <b>{row.budget}</b></p><p>Lift <b>{row.lift}</b></p></article>)}</div>:more?<div className={styles.formGrid}>{filters.map(label=><label key={label}>{label}<select><option>All</option><option>Requires attention</option></select></label>)}</div>:save?<label className={styles.field}>Saved view name<input placeholder="My promotion view"/></label>:column?<div className={styles.checkGrid}>{["Promotion ID","Type","Scope","Funding","Budget","Dates","Participants","Orders","GMV","Approval","Conflict","Updated"].map(label=><label key={label}><input type="checkbox" defaultChecked/>{label}</label>)}</div>:<><p>This is a safe frontend workflow because the repository has no promotion mutation endpoint. No server persistence will be claimed.</p><label className={styles.field}>Internal note or audit reason<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Enter decision context"/></label></>}{validation&&<p className={styles.formError} role="alert">{validation}</p>}</div><footer><button onClick={onClose} disabled={busy}>Cancel</button><button className={styles.primary} onClick={()=>void submit()} disabled={busy}>{busy?"Saving…":"Confirm"}</button></footer></section></div>}
function Loading(){return <div className={styles.loading} role="status" aria-label="Loading marketplace promotions"><div/><section>{Array.from({length:12},(_,index)=><i key={index}/>)}</section><div/></div>}
