"use client";
import React,{useState}from"react";import toast from"react-hot-toast";import{useMediaManagement}from"@/hooks/useMediaManagement";import{bulkMedia,exportMedia,importMediaManifest,updateMedia,uploadMedia}from"@/services/api/mediaAssets";import type{MediaAsset}from"@/types/mediaManagement";
import{MediaManagementHeader}from"./MediaManagementHeader";import{MediaBusinessContext}from"./MediaBusinessContext";import{MediaKpiGrid}from"./MediaKpiGrid";import{MediaStatusTabs}from"./MediaStatusTabs";import{MediaFilters}from"./MediaFilters";import{MediaQuickFilters}from"./MediaQuickFilters";import{MediaAssetTable}from"./MediaAssetTable";import{MediaIntelligenceSidebar}from"./MediaIntelligenceSidebar";import{MediaLowerPanels}from"./MediaLowerPanels";import{UploadMediaModal}from"./UploadMediaModal";import{ImportMediaModal}from"./ImportMediaModal";import{EditMediaMetadataDrawer}from"./EditMediaMetadataDrawer";import{MediaPreviewModal}from"./MediaPreviewModal";
export function MediaManagementDashboard(){
 const m=useMediaManagement();const[uploadOpen,setUploadOpen]=useState(false);const[importOpen,setImportOpen]=useState(false);const[edit,setEdit]=useState<MediaAsset|null>(null);const[preview,setPreview]=useState<MediaAsset|null>(null);
 if(m.loading&&!m.data)return <div className="m-6 min-h-[420px] animate-pulse rounded border bg-white p-8 text-sm text-muted"><h1 className="mb-2 text-xl font-bold text-ink">Media Asset Management</h1>Loading live media catalogue…</div>;
 if(m.error&&!m.data)return <div className="m-6 rounded border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800"><b>Unable to load media assets.</b><p>{m.error.message}</p><button onClick={()=>void m.refresh()} className="mt-3 rounded bg-[#671021] px-3 py-1.5 text-white">Retry</button></div>;
 if(!m.data)return null;
 const mutate=async(work:()=>Promise<unknown>,message:string)=>{try{await work();toast.success(message);await m.refresh();}catch(cause){toast.error(cause instanceof Error?cause.message:"Media operation failed.");}};
 const scope=(value:string)=>{const tab=m.data!.tabs.find(item=>item.scope===value);if(tab)m.setFilters(old=>({...old,activeTab:tab.label}));};
 return <div className="flex min-h-screen w-full flex-col bg-[#faf8f8] pb-12">
  <MediaManagementHeader canExport={Boolean(m.data.capabilities.canExport)} canImport={Boolean(m.data.capabilities.canImport)} canManage={Boolean(m.data.capabilities.canManage)} selectedCount={m.selectedRowIds.length} onExport={()=>void exportMedia(m.query)} onOpenImport={()=>setImportOpen(true)} onOpenUpload={()=>setUploadOpen(true)} onBulkAction={action=>{const mapped=action==="Approve Selected"?"approve":action==="Archive Selected"?"archive":null;if(!mapped)return toast.error("This bulk action has no authoritative backend workflow.");void mutate(()=>bulkMedia(m.selectedRowIds,mapped),`${m.selectedRowIds.length} media assets updated.`);}}/>
  <div className="flex flex-col gap-2 px-6 py-4"><MediaBusinessContext lastSynced={new Date(m.data.lastSyncedAt).toLocaleString()} isRefreshing={m.isRefreshing} onRefresh={()=>void m.handleRefresh()}/><MediaKpiGrid kpis={m.data.kpis} onFilterClick={(_,value)=>scope(value)}/>
   <div className="grid grid-cols-1 items-start gap-5 xl:grid-cols-[minmax(0,1fr)_280px]"><main className="min-w-0">
    <MediaStatusTabs tabs={m.data.tabs} activeTab={m.filters.activeTab} onTabChange={tab=>m.setFilters(old=>({...old,activeTab:tab}))}/>
    <MediaFilters options={m.data.options} filters={m.filters} onChange={updated=>m.setFilters(old=>({...old,...updated}))} onClearAll={m.handleClearFilters} onOpenSaveView={()=>toast.error("Saved views are unavailable because no saved-view schema is installed.")} onOpenMoreFilters={()=>toast.error("Additional governance filters are unavailable without authoritative schemas.")} onRefresh={()=>void m.handleRefresh()} isRefreshing={m.isRefreshing}/>
    <MediaQuickFilters activeChips={m.filters.quickChips} onToggleChip={m.handleToggleQuickChip}/>
    <MediaAssetTable assets={m.paginatedAssets} totalCount={m.totalCount} totalPages={m.data.assets.totalPages} canManage={Boolean(m.data.capabilities.canManage)} selectedAssetId={m.selectedAssetId} onSelectAsset={m.setSelectedAssetId} selectedRowIds={m.selectedRowIds} onSelectRow={m.handleSelectRow} onSelectAllOnPage={m.handleSelectAllOnPage} sortColumn={m.sortColumn} sortDirection={m.sortDirection} onSort={m.handleSort} currentPage={m.currentPage} rowsPerPage={m.rowsPerPage} onPageChange={m.setCurrentPage} onRowsPerPageChange={m.setRowsPerPage} onPreview={setPreview} onEdit={setEdit} onApprove={id=>void mutate(()=>updateMedia(id,{approval_status:"approved"}),"Media asset approved.")} onRevoke={id=>void mutate(()=>updateMedia(id,{approval_status:"needs_review"}),"Media approval revoked.")} onArchive={id=>void mutate(()=>bulkMedia([id],"archive"),"Media asset archived.")} showToast={message=>toast.success(message)}/>
    <MediaLowerPanels data={m.data}/></main><aside><MediaIntelligenceSidebar data={m.data} selectedAsset={m.selectedPreviewAsset} onOpenDetail={setPreview} onReplace={()=>toast.error("Replace workflow is unavailable because atomic media replacement is not implemented.")} onRevoke={id=>void mutate(()=>updateMedia(id,{approval_status:"needs_review"}),"Media approval revoked.")} onFilterClick={(_,value)=>scope(value)}/></aside></div>
  </div>
  <UploadMediaModal options={m.data.options} isOpen={uploadOpen} onClose={()=>setUploadOpen(false)} onUpload={async(form,onProgress)=>{await uploadMedia(form,onProgress);await m.refresh();}} onSuccess={name=>toast.success(`Uploaded ${name}.`)}/>
  <ImportMediaModal isOpen={importOpen} onClose={()=>setImportOpen(false)} onImport={importMediaManifest} onSuccess={count=>{toast.success(`Updated ${count} media records.`);void m.refresh();}}/>
  <EditMediaMetadataDrawer options={m.data.options} isOpen={Boolean(edit)} asset={edit} onClose={()=>setEdit(null)} onSave={async updated=>{await mutate(()=>updateMedia(updated.id,{product_id:updated.productId?Number(updated.productId):null,alt_text:updated.altText||null,approval_status:updated.approvalStatus.toLowerCase().replaceAll(" ","_")}),"Media metadata updated.");setEdit(null);}}/>
  <MediaPreviewModal isOpen={Boolean(preview)} asset={preview} onClose={()=>setPreview(null)} onDownload={asset=>{if(asset.downloadUrl)window.open(asset.downloadUrl,"_blank","noopener,noreferrer");}}/>
 </div>;
}
