"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import {AlertTriangle,ChevronRight,LockKeyhole,RefreshCw,X} from "lucide-react";
import toast from "react-hot-toast";
import {fetchEnterpriseWorkspace,recordEnterprisePreviewAction} from "@/services/api/marketplaceEnterpriseWorkspacesService";
import styles from "./enterprise-workspaces.module.css";

export {styles};

export function useWorkspace(name,id){const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{try{setLoading(true);setError("");setData(await fetchEnterpriseWorkspace(name,id))}catch(e){if(e.name!=="AbortError")setError(e.message)}finally{setLoading(false)}};useEffect(()=>{const c=new AbortController();void fetchEnterpriseWorkspace(name,id,c.signal).then(setData).catch(e=>{if(e.name!=="AbortError")setError(e.message)}).finally(()=>setLoading(false));return()=>c.abort()},[name,id]);return{data,loading,error,reload:load}}
export function State({title,text,loading,onRetry}){return <section className={styles.state} role={text?"alert":"status"}>{loading?<div className={styles.spinner}/>:<AlertTriangle/>}<h1>{title}</h1>{text&&<p>{text}</p>}{onRetry&&<button onClick={onRetry}>Retry</button>}</section>}
export function Breadcrumb({items}){return <nav className={styles.breadcrumb} aria-label="Breadcrumb">{items.map((item,index)=><span key={item.label}>{item.href?<Link href={item.href}>{item.label}</Link>:item.label}{index<items.length-1&&<ChevronRight/>}</span>)}</nav>}
export function ContextBar({data,lastUpdated,onRefresh}){return <section className={styles.context}><div>{Object.entries(data).map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</div><aside><div><i/>Live data<small>Last updated: {lastUpdated}</small>{onRefresh&&<button aria-label="Refresh workspace" onClick={onRefresh}><RefreshCw/></button>}</div><p><LockKeyhole/>Access limited to assigned business context</p></aside></section>}
export function Badge({children,tone}){const inferred=tone||(/Critical|Overdue|Blocking|Disabled|High|Error|Reject/i.test(children)?"danger":/Pending|Warning|Review|Restricted|Scheduled|Medium/i.test(children)?"warning":/Active|Passed|Verified|Received|Published|Good|Healthy/i.test(children)?"success":"info");return <span className={`${styles.badge} ${styles[inferred]}`}>{children}</span>}
export function Card({title,number,action,children,className=""}){return <section className={`${styles.card} ${className}`}><header><h2>{number&&<b>{number}</b>}{title}</h2>{action&&<button>{action}<ChevronRight/></button>}</header>{children}</section>}
export function KeyValues({data}){return <dl className={styles.keyValues}>{Object.entries(data).map(([a,b])=><div key={a}><dt>{a}</dt><dd>{String(b)}</dd></div>)}</dl>}
export function Progress({label,value,tone="green"}){return <div className={styles.progress}><span>{label}</span><i><b className={styles[tone]} style={{width:`${value}%`}}/></i><strong>{value}%</strong></div>}
export function ActionModal({workspace,type,recordIds=[],onClose,fields=false,onDone}){const [note,setNote]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const confirm=async()=>{if(!note.trim()){setError("An audit reason is required.");return}setBusy(true);await recordEnterprisePreviewAction(workspace,type,recordIds,note);toast.success(`${type} saved in local preview state (not server-persisted)`);onDone?.();onClose();setBusy(false)};return <div className={styles.backdrop} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={styles.modal} role="dialog" aria-modal="true" aria-label={type}><header><div><small>Frontend preview workflow</small><h2>{type}</h2></div><button aria-label="Close dialog" onClick={onClose}><X/></button></header><div className={styles.modalBody}>{fields&&<div className={styles.formGrid}><label><span>Category</span><select><option>Operational Review</option><option>Policy & Risk</option><option>Financial Control</option></select></label><label><span>Priority</span><select><option>High</option><option>Medium</option><option>Low</option></select></label></div>}<p>This action is recorded only in the current frontend preview unless a production API is connected.</p><label><span>Audit reason / internal note *</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Document the reason and expected outcome"/></label>{error&&<p role="alert" className={styles.formError}>{error}</p>}</div><footer><button onClick={onClose}>Cancel</button><button className={styles.primary} disabled={busy} onClick={()=>void confirm()}>{busy?"Saving…":"Confirm"}</button></footer></section></div>}
