"use client";
import React from "react";
import { AlertTriangle, ShieldCheck } from "lucide-react";
import type { AttributeManagementData } from "@/types/attributeManagement";

type Props = Pick<AttributeManagementData, "health" | "alerts" | "statusSummary" | "variantReadiness" | "coverageSummary" | "capabilities"> & { onSelectQueue: (scope: string) => void };
const Panel = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="rounded border border-gray-200 bg-white p-3.5 shadow-2xs"><h3 className="mb-3 text-[11.5px] font-bold text-gray-900">{title}</h3>{children}</section>;
const Unavailable = ({ reason }: { reason: string }) => <p className="rounded border border-dashed border-gray-200 bg-gray-50 p-3 text-[10.5px] leading-relaxed text-gray-500">Unavailable — {reason}</p>;

export const AttributeIntelligenceSidebar: React.FC<Props> = ({ health, alerts, statusSummary, variantReadiness, coverageSummary, capabilities, onSelectQueue }) => {
  const statusTotal = statusSummary.reduce((sum, item) => sum + item.count, 0);
  return <div className="flex flex-col gap-3 text-xs">
    <Panel title="Overall Attribute & Variant Health"><div className="flex items-center gap-3"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-full border-[6px] border-emerald-500"><span className="text-lg font-black">{health.score}</span></div><div><ShieldCheck className="text-emerald-600" size={16}/><strong className="mt-1 block text-emerald-700">{health.status}</strong></div></div><div className="mt-3 space-y-1 border-t pt-2">{health.dimensions.map(metric => <div key={metric.label} className="flex justify-between text-[10.5px]"><span className="text-gray-600">{metric.label}</span><b>{metric.value}%</b></div>)}</div></Panel>
    <Panel title="Priority Alerts"><div className="space-y-1.5">{alerts.length ? alerts.map(alert => <button key={alert.id} onClick={() => onSelectQueue(alert.scope)} className="flex w-full items-center justify-between rounded border border-gray-100 bg-gray-50 p-2 text-left hover:bg-gray-100"><span className="flex min-w-0 items-center gap-1.5"><AlertTriangle size={11} className={alert.severity === "High" ? "text-rose-500" : "text-amber-500"}/><span className="truncate text-[10.5px]">{alert.label}</span></span><b>{alert.count}</b></button>) : <p className="text-[10.5px] text-gray-500">No active alerts.</p>}</div></Panel>
    <Panel title="Attribute Status Summary"><div className="space-y-2">{statusSummary.map(item => <div key={item.label}><div className="flex justify-between text-[10.5px]"><span>{item.label}</span><b>{item.count.toLocaleString()}</b></div><div className="mt-1 h-1.5 overflow-hidden rounded bg-gray-100"><div className="h-full bg-[#741d35]" style={{width: `${statusTotal ? item.count / statusTotal * 100 : 0}%`}}/></div></div>)}</div></Panel>
    <Panel title="Variant Readiness Summary">{variantReadiness.available ? <div className="grid grid-cols-2 gap-2">{[["Ready",variantReadiness.ready],["Partial",variantReadiness.partial],["Blocked",variantReadiness.blocked],["Invalid",variantReadiness.invalid]].map(([label,count]) => <div key={String(label)} className="rounded bg-gray-50 p-2"><span className="block text-[10px] text-gray-500">{label}</span><b>{count ?? "N/A"}</b></div>)}</div> : <Unavailable reason={String(capabilities.variantRulesReason || "no authoritative variant-rule schema is installed.")}/>}</Panel>
    <Panel title="Attribute Coverage Summary"><div className="space-y-2">{[["Product coverage",coverageSummary.productCoveragePercent],["Variant coverage",coverageSummary.variantCoveragePercent],["Category coverage",coverageSummary.categoryCoveragePercent],["Channel coverage",coverageSummary.channelCoveragePercent]].map(([label,value]) => <div key={String(label)} className="flex justify-between text-[10.5px]"><span>{label}</span><b>{value == null ? "N/A" : `${value}%`}</b></div>)}</div></Panel>
    <Panel title="Quick Queues"><div className="space-y-1">{alerts.map(alert => <button key={alert.id} onClick={() => onSelectQueue(alert.scope)} className="flex w-full justify-between rounded px-2 py-1.5 hover:bg-gray-50"><span>{alert.label}</span><b>{alert.count}</b></button>)}</div></Panel>
  </div>;
};
