<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('marketing_budgets',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('code',40)->unique();$t->string('name',180);$t->string('type',50)->index();$t->string('status',30)->default('draft')->index();$t->string('approval_status',30)->default('not_submitted')->index();$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->string('business_unit',80)->nullable()->index();$t->string('brand',100)->nullable();$t->string('period',40)->index();$t->string('currency',3)->default('LKR');$t->decimal('approved_amount',18,2)->default(0);$t->decimal('allocated_amount',18,2)->default(0);$t->decimal('committed_amount',18,2)->default(0);$t->decimal('actual_spend',18,2)->default(0);$t->decimal('forecast_amount',18,2)->default(0);$t->boolean('is_locked')->default(false);$t->json('controls')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->softDeletes();$t->index(['status','period','created_at']);});
Schema::create('marketing_budget_transactions',function(Blueprint$t){$t->id();$t->foreignId('budget_id')->constrained('marketing_budgets')->cascadeOnDelete();$t->string('type',30)->index();$t->decimal('amount',18,2);$t->string('reference_type',50)->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->text('reason')->nullable();$t->string('approval_status',30)->default('approved')->index();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['budget_id','type','created_at']);});
Schema::create('marketing_attribution_runs',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('model',50)->index();$t->string('version',30);$t->string('status',30)->default('pending')->index();$t->dateTime('period_start');$t->dateTime('period_end');$t->json('configuration')->nullable();$t->unsignedBigInteger('conversions')->default(0);$t->decimal('attributed_revenue',18,2)->default(0);$t->timestamp('completed_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('marketing_attribution_results',function(Blueprint$t){$t->id();$t->foreignId('run_id')->constrained('marketing_attribution_runs')->cascadeOnDelete();$t->string('source_type',40)->index();$t->unsignedBigInteger('source_id')->nullable()->index();$t->string('channel',50)->nullable()->index();$t->unsignedBigInteger('conversion_count')->default(0);$t->decimal('revenue',18,2)->default(0);$t->decimal('spend',18,2)->default(0);$t->date('metric_date')->index();$t->timestamps();});
Schema::create('marketing_governance_records',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('code',40)->unique();$t->string('name',180);$t->string('type',60)->index();$t->string('status',30)->default('draft')->index();$t->string('approval_status',30)->default('not_submitted')->index();$t->string('severity',20)->default('low')->index();$t->string('scope_type',40)->nullable()->index();$t->unsignedBigInteger('scope_id')->nullable();$t->json('rules')->nullable();$t->date('effective_on')->nullable();$t->date('expires_on')->nullable();$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->softDeletes();});
Schema::create('marketing_report_definitions',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('code',40)->unique();$t->string('name',180);$t->string('type',60)->index();$t->string('domain',60)->index();$t->string('status',30)->default('draft')->index();$t->string('format',15)->default('csv');$t->string('privacy_classification',30)->default('internal')->index();$t->json('filters')->nullable();$t->json('sections')->nullable();$t->string('schedule_expression')->nullable();$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->softDeletes();});
Schema::create('marketing_report_runs',function(Blueprint$t){$t->id();$t->foreignId('report_id')->constrained('marketing_report_definitions')->cascadeOnDelete();$t->uuid('uuid')->unique();$t->string('status',30)->default('queued')->index();$t->string('storage_path')->nullable();$t->unsignedBigInteger('row_count')->default(0);$t->text('error_message')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->foreignId('requested_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
}public function down():void{Schema::dropIfExists('marketing_report_runs');Schema::dropIfExists('marketing_report_definitions');Schema::dropIfExists('marketing_governance_records');Schema::dropIfExists('marketing_attribution_results');Schema::dropIfExists('marketing_attribution_runs');Schema::dropIfExists('marketing_budget_transactions');Schema::dropIfExists('marketing_budgets');}};
