<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::table('ecosystem_module_integrations',function(Blueprint$t){$t->uuid('uuid')->nullable()->unique();$t->string('integration_type',40)->default('api');$t->string('environment',40)->default('development');$t->string('health_status',30)->default('not_evaluated');$t->string('auth_type',30)->nullable();$t->string('credential_reference',160)->nullable();$t->string('endpoint_reference',500)->nullable();$t->string('owner',160)->nullable();$t->string('risk_level',20)->default('unknown');$t->string('compliance_status',30)->default('not_evaluated');$t->unsignedInteger('timeout_ms')->nullable();$t->unsignedInteger('retry_limit')->default(0);$t->unsignedInteger('sla_target_ms')->nullable();$t->timestamp('credential_rotated_at')->nullable();$t->timestamp('certificate_expires_at')->nullable();$t->unsignedInteger('lock_version')->default(1);$t->index(['provider','status','environment']);$t->index(['health_status','risk_level']);});
Schema::create('ecosystem_integration_health_checks',function(Blueprint$t){$t->id();$t->foreignId('integration_id')->constrained('ecosystem_module_integrations')->cascadeOnDelete();$t->string('status',30);$t->unsignedInteger('latency_ms')->nullable();$t->unsignedInteger('http_status')->nullable();$t->text('message')->nullable();$t->timestamp('checked_at');$t->index(['integration_id','checked_at']);});
Schema::create('ecosystem_integration_audits',function(Blueprint$t){$t->id();$t->foreignId('integration_id')->nullable()->constrained('ecosystem_module_integrations')->nullOnDelete();$t->string('action',60);$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->json('before')->nullable();$t->json('after')->nullable();$t->text('reason')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['integration_id','created_at']);});
Schema::create('ecosystem_access_policies',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('name')->unique();$t->string('policy_type',40);$t->string('scope',120)->nullable();$t->string('effect',20)->default('allow');$t->json('conditions')->nullable();$t->string('risk_level',20)->default('unknown');$t->string('status',30)->default('draft');$t->unsignedInteger('version')->default(1);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('ecosystem_access_requests',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('requester_id')->constrained('users')->cascadeOnDelete();$t->foreignId('target_user_id')->constrained('users')->cascadeOnDelete();$t->foreignId('role_id')->nullable()->constrained('roles')->nullOnDelete();$t->foreignId('permission_id')->nullable()->constrained('permissions')->nullOnDelete();$t->string('scope',120)->nullable();$t->text('reason');$t->string('risk_level',20)->default('unknown');$t->string('status',30)->default('pending');$t->foreignId('decided_by')->nullable()->constrained('users')->nullOnDelete();$t->text('decision_reason')->nullable();$t->timestamp('decided_at')->nullable();$t->unsignedInteger('lock_version')->default(1);$t->timestamps();$t->index(['status','risk_level','created_at']);});
Schema::create('ecosystem_temporary_access',function(Blueprint$t){$t->id();$t->foreignId('access_request_id')->nullable()->constrained('ecosystem_access_requests')->nullOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('role_id')->nullable()->constrained('roles')->cascadeOnDelete();$t->foreignId('permission_id')->nullable()->constrained('permissions')->cascadeOnDelete();$t->timestamp('starts_at');$t->timestamp('expires_at');$t->string('status',30)->default('active');$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['user_id','status','expires_at']);});
Schema::create('ecosystem_sod_rules',function(Blueprint$t){$t->id();$t->string('name')->unique();$t->foreignId('permission_a_id')->constrained('permissions')->cascadeOnDelete();$t->foreignId('permission_b_id')->constrained('permissions')->cascadeOnDelete();$t->string('severity',20);$t->string('status',30)->default('active');$t->text('description')->nullable();$t->timestamps();$t->unique(['permission_a_id','permission_b_id']);});
Schema::create('ecosystem_access_certifications',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('status',30)->default('planned');$t->timestamp('due_at');$t->timestamp('completed_at')->nullable();$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['status','due_at']);});
Schema::create('ecosystem_governance_audits',function(Blueprint$t){$t->id();$t->string('entity_type',40);$t->unsignedBigInteger('entity_id');$t->string('action',60);$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->json('before')->nullable();$t->json('after')->nullable();$t->text('reason')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['entity_type','entity_id','created_at']);});
Schema::create('ecosystem_report_schedules',function(Blueprint$t){$t->id();$t->foreignId('report_definition_id')->constrained('report_definitions')->cascadeOnDelete();$t->string('frequency',30);$t->string('format',20)->default('json');$t->json('filters')->nullable();$t->string('status',30)->default('active');$t->timestamp('next_run_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['status','next_run_at']);});
Schema::create('ecosystem_evidence_packages',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('status',30)->default('queued');$t->json('filters')->nullable();$t->json('manifest')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('ecosystem_audit_exceptions',function(Blueprint$t){$t->id();$t->unsignedBigInteger('activity_log_id')->nullable();$t->string('type',50);$t->string('severity',20);$t->string('status',30)->default('open');$t->text('reason');$t->foreignId('resolved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('resolved_at')->nullable();$t->timestamps();$t->index(['status','severity']);});}
public function down():void{foreach(['ecosystem_audit_exceptions','ecosystem_evidence_packages','ecosystem_report_schedules','ecosystem_governance_audits','ecosystem_access_certifications','ecosystem_sod_rules','ecosystem_temporary_access','ecosystem_access_requests','ecosystem_access_policies','ecosystem_integration_audits','ecosystem_integration_health_checks']as$t)Schema::dropIfExists($t);Schema::table('ecosystem_module_integrations',function(Blueprint$t){$t->dropIndex(['provider','status','environment']);$t->dropIndex(['health_status','risk_level']);$t->dropColumn(['uuid','integration_type','environment','health_status','auth_type','credential_reference','endpoint_reference','owner','risk_level','compliance_status','timeout_ms','retry_limit','sla_target_ms','credential_rotated_at','certificate_expires_at','lock_version']);});}};
