<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::table('ecosystem_module_dependencies',function(Blueprint $t){$t->string('environment',30)->default('production');$t->string('compatibility_status',30)->default('not_evaluated');$t->string('risk_level',20)->default('unknown');$t->json('validation_reasons')->nullable();$t->boolean('is_active')->default(true);$t->unsignedBigInteger('created_by')->nullable()->index();$t->unsignedBigInteger('updated_by')->nullable()->index();$t->index(['environment','compatibility_status']);$t->index(['risk_level','is_active']);});
  Schema::create('ecosystem_dependency_exceptions',function(Blueprint $t){$t->id();$t->foreignId('dependency_id')->constrained('ecosystem_module_dependencies')->cascadeOnDelete();$t->string('type',60);$t->string('severity',20);$t->text('reason');$t->string('status',30)->default('open');$t->timestamp('expires_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('resolved_at')->nullable();$t->timestamps();$t->index(['status','severity']);});
  Schema::create('ecosystem_dependency_audits',function(Blueprint $t){$t->id();$t->foreignId('dependency_id')->nullable()->constrained('ecosystem_module_dependencies')->nullOnDelete();$t->string('action',60);$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->json('before')->nullable();$t->json('after')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['dependency_id','created_at']);});
  Schema::table('feature_flags',function(Blueprint $t){$t->unsignedBigInteger('ecosystem_module_id')->nullable()->index();$t->unsignedBigInteger('capability_id')->nullable()->index();$t->string('flag_type',30)->default('boolean');$t->string('owner',160)->nullable();$t->string('governance_status',30)->default('not_evaluated');$t->string('risk_level',20)->default('unknown');$t->unsignedBigInteger('created_by')->nullable()->index();$t->unsignedBigInteger('updated_by')->nullable()->index();$t->unsignedInteger('lock_version')->default(1);$t->index(['ecosystem_module_id','status']);});
  Schema::create('feature_flag_environments',function(Blueprint $t){$t->id();$t->foreignId('feature_flag_id')->constrained()->cascadeOnDelete();$t->string('environment',30);$t->boolean('enabled')->default(false);$t->json('value')->nullable();$t->unsignedTinyInteger('rollout_percentage')->default(0);$t->timestamp('effective_from')->nullable();$t->timestamp('effective_until')->nullable();$t->timestamps();$t->unique(['feature_flag_id','environment']);$t->index(['environment','enabled']);});
  Schema::create('feature_flag_rollouts',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('feature_flag_id')->constrained()->cascadeOnDelete();$t->string('environment',30);$t->string('strategy',30)->default('percentage');$t->string('status',30)->default('draft')->index();$t->unsignedTinyInteger('current_percentage')->default(0);$t->unsignedTinyInteger('target_percentage')->default(100);$t->json('targeting')->nullable();$t->json('stages')->nullable();$t->unsignedInteger('lock_version')->default(1);$t->text('reason')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['feature_flag_id','environment','status']);});
  Schema::create('feature_flag_audits',function(Blueprint $t){$t->id();$t->foreignId('feature_flag_id')->constrained()->cascadeOnDelete();$t->foreignId('rollout_id')->nullable()->constrained('feature_flag_rollouts')->nullOnDelete();$t->string('action',60);$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->text('reason')->nullable();$t->json('before')->nullable();$t->json('after')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['feature_flag_id','created_at']);});
 }
 public function down():void{Schema::dropIfExists('feature_flag_audits');Schema::dropIfExists('feature_flag_rollouts');Schema::dropIfExists('feature_flag_environments');Schema::table('feature_flags',fn(Blueprint$t)=>$t->dropColumn(['ecosystem_module_id','capability_id','flag_type','owner','governance_status','risk_level','created_by','updated_by','lock_version']));Schema::dropIfExists('ecosystem_dependency_audits');Schema::dropIfExists('ecosystem_dependency_exceptions');Schema::table('ecosystem_module_dependencies',fn(Blueprint$t)=>$t->dropColumn(['environment','compatibility_status','risk_level','validation_reasons','is_active','created_by','updated_by']));}
};
