<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('inventory_stocks',function(Blueprint $t){$t->id();$t->foreignId('logistics_facility_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('sku')->index();$t->decimal('on_hand',14,2)->default(0);$t->decimal('reserved',14,2)->default(0);$t->timestamps();$t->unique(['logistics_facility_id','product_id','sku'],'inventory_stock_facility_product_sku_unique');});
  Schema::create('inventory_allocations',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('reference')->unique();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('order_item_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('supplier_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('source_facility_id')->nullable()->constrained('logistics_facilities')->nullOnDelete();$t->foreignId('destination_facility_id')->nullable()->constrained('logistics_facilities')->nullOnDelete();$t->string('sku')->index();$t->decimal('requested_quantity',14,2);$t->decimal('allocated_quantity',14,2)->default(0);$t->string('status',30)->default('pending')->index();$t->string('priority',20)->nullable()->index();$t->timestamps();$t->softDeletes();$t->index(['source_facility_id','status']);$t->index(['order_id','status']);});
  Schema::create('inventory_reservations',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('inventory_allocation_id')->constrained()->cascadeOnDelete();$t->foreignId('inventory_stock_id')->constrained()->restrictOnDelete();$t->decimal('quantity',14,2);$t->string('status',30)->default('active')->index();$t->timestamp('expires_at')->nullable()->index();$t->timestamp('released_at')->nullable();$t->timestamps();$t->index(['inventory_allocation_id','status']);});
  Schema::create('inventory_transfers',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('reference')->unique();$t->foreignId('inventory_allocation_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('source_facility_id')->constrained('logistics_facilities')->restrictOnDelete();$t->foreignId('destination_facility_id')->constrained('logistics_facilities')->restrictOnDelete();$t->decimal('quantity',14,2);$t->string('status',30)->default('requested')->index();$t->timestamps();$t->index(['source_facility_id','destination_facility_id','status'],'inventory_transfer_route_status_index');});
  Schema::create('inventory_allocation_events',function(Blueprint $t){$t->id();$t->foreignId('inventory_allocation_id')->constrained()->cascadeOnDelete();$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('event');$t->json('properties')->nullable();$t->timestamp('occurred_at')->index();$t->timestamps();$t->index(['inventory_allocation_id','occurred_at'],'allocation_events_timeline_index');});
 }
 public function down(): void {Schema::dropIfExists('inventory_allocation_events');Schema::dropIfExists('inventory_transfers');Schema::dropIfExists('inventory_reservations');Schema::dropIfExists('inventory_allocations');Schema::dropIfExists('inventory_stocks');}
};
