<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('ecosystem_sector_packs',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('slug')->unique();$t->string('code',60)->unique();$t->string('name');$t->text('description')->nullable();$t->string('sector',100)->nullable()->index();$t->string('industry',100)->nullable()->index();$t->string('status',30)->default('draft')->index();$t->string('owner',160)->nullable();$t->string('risk_level',20)->default('unknown')->index();$t->foreignId('parent_pack_id')->nullable()->constrained('ecosystem_sector_packs')->nullOnDelete();$t->unsignedBigInteger('current_version_id')->nullable()->index();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->softDeletes();});
  Schema::create('ecosystem_sector_pack_versions',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('sector_pack_id')->constrained('ecosystem_sector_packs')->cascadeOnDelete();$t->string('version',40);$t->string('status',30)->default('draft')->index();$t->string('release_channel',40)->nullable();$t->text('release_notes')->nullable();$t->timestamp('target_release_at')->nullable();$t->timestamp('released_at')->nullable();$t->foreignId('released_by')->nullable()->constrained('users')->nullOnDelete();$t->unsignedInteger('lock_version')->default(1);$t->timestamps();$t->unique(['sector_pack_id','version']);});
  Schema::create('ecosystem_sector_pack_modules',function(Blueprint $t){$t->id();$t->foreignId('sector_pack_version_id')->constrained('ecosystem_sector_pack_versions')->cascadeOnDelete();$t->foreignId('ecosystem_module_id')->constrained('ecosystem_modules')->cascadeOnDelete();$t->string('requirement',20)->default('required');$t->string('minimum_version',40)->nullable();$t->string('maximum_version',40)->nullable();$t->string('compatibility_status',30)->default('not_evaluated');$t->json('validation_reasons')->nullable();$t->timestamps();$t->unique(['sector_pack_version_id','ecosystem_module_id']);});
  Schema::create('ecosystem_capability_bundles',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('bundle_key',100)->unique();$t->string('name');$t->text('description')->nullable();$t->string('status',30)->default('active');$t->timestamps();});
  Schema::create('ecosystem_capability_bundle_items',function(Blueprint $t){$t->id();$t->foreignId('capability_bundle_id')->constrained('ecosystem_capability_bundles')->cascadeOnDelete();$t->foreignId('capability_id')->constrained('ecosystem_capabilities')->cascadeOnDelete();$t->string('requirement',20)->default('required');$t->timestamps();$t->unique(['capability_bundle_id','capability_id']);});
  Schema::create('ecosystem_sector_pack_bundles',function(Blueprint $t){$t->id();$t->foreignId('sector_pack_version_id')->constrained('ecosystem_sector_pack_versions')->cascadeOnDelete();$t->foreignId('capability_bundle_id')->constrained('ecosystem_capability_bundles')->cascadeOnDelete();$t->string('requirement',20)->default('required');$t->timestamps();$t->unique(['sector_pack_version_id','capability_bundle_id']);});
  Schema::create('ecosystem_sector_pack_countries',function(Blueprint $t){$t->id();$t->foreignId('sector_pack_version_id')->constrained('ecosystem_sector_pack_versions')->cascadeOnDelete();$t->foreignId('country_id')->constrained('countries')->cascadeOnDelete();$t->string('status',30)->default('supported');$t->text('reason')->nullable();$t->boolean('approval_required')->default(false);$t->timestamps();$t->unique(['sector_pack_version_id','country_id']);});
  Schema::create('ecosystem_sector_pack_tenants',function(Blueprint $t){$t->id();$t->foreignId('sector_pack_id')->constrained('ecosystem_sector_packs')->cascadeOnDelete();$t->foreignId('company_profile_id')->constrained('company_profiles')->cascadeOnDelete();$t->string('status',30)->default('planned');$t->json('overrides')->nullable();$t->timestamps();$t->unique(['sector_pack_id','company_profile_id']);});
  Schema::create('ecosystem_sector_pack_exceptions',function(Blueprint $t){$t->id();$t->foreignId('sector_pack_id')->constrained('ecosystem_sector_packs')->cascadeOnDelete();$t->string('type',60);$t->string('severity',20);$t->text('message');$t->string('status',30)->default('open');$t->timestamp('resolved_at')->nullable();$t->timestamps();$t->index(['sector_pack_id','status','severity']);});
  Schema::create('ecosystem_sector_pack_audits',function(Blueprint $t){$t->id();$t->foreignId('sector_pack_id')->constrained('ecosystem_sector_packs')->cascadeOnDelete();$t->foreignId('version_id')->nullable()->constrained('ecosystem_sector_pack_versions')->nullOnDelete();$t->string('action',60);$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->json('before')->nullable();$t->json('after')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['sector_pack_id','created_at']);});
 }
 public function down():void{Schema::dropIfExists('ecosystem_sector_pack_audits');Schema::dropIfExists('ecosystem_sector_pack_exceptions');Schema::dropIfExists('ecosystem_sector_pack_tenants');Schema::dropIfExists('ecosystem_sector_pack_countries');Schema::dropIfExists('ecosystem_sector_pack_bundles');Schema::dropIfExists('ecosystem_capability_bundle_items');Schema::dropIfExists('ecosystem_capability_bundles');Schema::dropIfExists('ecosystem_sector_pack_modules');Schema::dropIfExists('ecosystem_sector_pack_versions');Schema::dropIfExists('ecosystem_sector_packs');}
};
