<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category' => 'ceylon-tea',
                'supplier' => 'lanka-tea-exports',
                'name' => 'Pure Ceylon Black Tea',
                'slug' => 'pure-ceylon-black-tea',
                'short_description' => 'Export-grade black tea with a bright liquor and classic Ceylon character.',
                'description' => 'Pure Ceylon black tea selected from established Sri Lankan estates and prepared for bulk export, private label, and food-service buyers.',
                'price' => 8.50,
                'moq' => 100,
                'unit' => 'Kg',
                'supply_ability' => '20,000 Kg per month',
                'lead_time' => '14–21 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => '25 Kg food-grade kraft bags or buyer-specified retail packing.',
                'featured_image' => 'https://placehold.co/800x800/e8f5e9/155e2c?text=Ceylon+Black+Tea',
                'is_featured' => true,
                'views_count' => 9800,
            ],
            [
                'category' => 'ceylon-tea',
                'supplier' => 'lanka-tea-exports',
                'name' => 'Green Tea Bags',
                'slug' => 'green-tea-bags',
                'short_description' => 'Individually wrapped Sri Lankan green tea bags for retail and hospitality.',
                'description' => 'Refreshing green tea bags produced with Sri Lankan tea leaves and available for private-label export programs.',
                'price' => 4.75,
                'moq' => 500,
                'unit' => 'Box',
                'supply_ability' => '50,000 boxes per month',
                'lead_time' => '21 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => '20 or 25 individually wrapped tea bags per printed carton.',
                'featured_image' => 'https://placehold.co/800x800/f1f8e9/33691e?text=Green+Tea+Bags',
                'is_featured' => false,
                'views_count' => 6400,
            ],
            [
                'category' => 'cinnamon',
                'supplier' => 'ceylon-spice-gardens',
                'name' => 'Ceylon Cinnamon Sticks',
                'slug' => 'ceylon-cinnamon-sticks',
                'short_description' => 'Premium true cinnamon quills graded and packed for export.',
                'description' => 'Authentic Cinnamomum verum cinnamon sticks processed in Sri Lanka with a delicate aroma and naturally sweet flavour.',
                'price' => 18.00,
                'moq' => 50,
                'unit' => 'Kg',
                'supply_ability' => '8,000 Kg per month',
                'lead_time' => '14 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => '10 Kg lined cartons with moisture protection.',
                'featured_image' => 'https://placehold.co/800x800/fbe9e7/bf360c?text=Cinnamon+Sticks',
                'is_featured' => true,
                'views_count' => 11200,
            ],
            [
                'category' => 'cinnamon',
                'supplier' => 'ceylon-spice-gardens',
                'name' => 'Cinnamon Powder',
                'slug' => 'ceylon-cinnamon-powder',
                'short_description' => 'Finely ground Ceylon cinnamon powder for food manufacturing and retail.',
                'description' => 'Pure Ceylon cinnamon powder milled from selected quills and available in bulk or private-label packaging.',
                'price' => 14.25,
                'moq' => 100,
                'unit' => 'Kg',
                'supply_ability' => '10,000 Kg per month',
                'lead_time' => '14–20 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Food-grade foil pouches or 20 Kg lined cartons.',
                'featured_image' => 'https://placehold.co/800x800/fff3e0/e65100?text=Cinnamon+Powder',
                'is_featured' => false,
                'views_count' => 5700,
            ],
            [
                'category' => 'blue-sapphire',
                'supplier' => 'ceylon-gems-jewels',
                'name' => 'Natural Blue Sapphire',
                'slug' => 'natural-blue-sapphire',
                'short_description' => 'Natural Ceylon blue sapphire suitable for fine jewellery.',
                'description' => 'Responsibly sourced natural blue sapphire from Sri Lanka, available as calibrated stones or individually certified gems.',
                'price' => 850.00,
                'moq' => 1,
                'unit' => 'Carat',
                'supply_ability' => '250 carats per month',
                'lead_time' => '7–14 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Tamper-evident gem box with certification documents where applicable.',
                'featured_image' => 'https://placehold.co/800x800/e8eaf6/1a237e?text=Blue+Sapphire',
                'is_featured' => true,
                'views_count' => 15400,
            ],
            [
                'category' => 'coconut-oil',
                'supplier' => 'coco-lanka-naturals',
                'name' => 'Virgin Coconut Oil',
                'slug' => 'virgin-coconut-oil',
                'short_description' => 'Cold-pressed virgin coconut oil for food, wellness, and cosmetic use.',
                'description' => 'Premium Sri Lankan virgin coconut oil made from fresh coconut kernels and available in bulk drums or retail-ready bottles.',
                'price' => 6.80,
                'moq' => 500,
                'unit' => 'Litre',
                'supply_ability' => '30,000 litres per month',
                'lead_time' => '21 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Food-grade HDPE drums, IBC tanks, glass bottles, or PET bottles.',
                'featured_image' => 'https://placehold.co/800x800/fff9c4/f57f17?text=Virgin+Coconut+Oil',
                'is_featured' => true,
                'views_count' => 8700,
            ],
            [
                'category' => 'ayurvedic-oil',
                'supplier' => 'coco-lanka-naturals',
                'name' => 'Ayurvedic Herbal Oil',
                'slug' => 'ayurvedic-herbal-oil',
                'short_description' => 'Traditional herbal massage oil produced from Sri Lankan botanical ingredients.',
                'description' => 'A Sri Lankan Ayurvedic herbal oil blend prepared for wellness, spa, and private-label markets.',
                'price' => 5.50,
                'moq' => 1000,
                'unit' => 'Bottle',
                'supply_ability' => '40,000 bottles per month',
                'lead_time' => '30 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => '100 ml, 200 ml, or 500 ml bottles with custom label options.',
                'featured_image' => 'https://placehold.co/800x800/e8f5e9/2e7d32?text=Ayurvedic+Oil',
                'is_featured' => false,
                'views_count' => 7200,
            ],
            [
                'category' => 'batik-fabric',
                'supplier' => 'lanka-craft-rubber',
                'name' => 'Handmade Batik Fabric',
                'slug' => 'handmade-batik-fabric',
                'short_description' => 'Hand-dyed Sri Lankan batik fabric for apparel and interior collections.',
                'description' => 'Artisan-made batik fabric featuring traditional wax-resist techniques and customizable colourways.',
                'price' => 12.00,
                'moq' => 100,
                'unit' => 'Metre',
                'supply_ability' => '5,000 metres per month',
                'lead_time' => '21–30 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Rolled fabric with protective wrapping and export cartons.',
                'featured_image' => 'https://placehold.co/800x800/fce4ec/880e4f?text=Batik+Fabric',
                'is_featured' => true,
                'views_count' => 6100,
            ],
            [
                'category' => 'rubber-gloves',
                'supplier' => 'lanka-craft-rubber',
                'name' => 'Latex Rubber Gloves',
                'slug' => 'latex-rubber-gloves',
                'short_description' => 'Natural latex gloves manufactured for industrial and household applications.',
                'description' => 'Durable Sri Lankan latex rubber gloves available in multiple sizes, textures, colours, and private-label formats.',
                'price' => 3.20,
                'moq' => 1000,
                'unit' => 'Pair',
                'supply_ability' => '500,000 pairs per month',
                'lead_time' => '21–30 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Individual polybags or retail printed packs in export cartons.',
                'featured_image' => 'https://placehold.co/800x800/f3e5f5/4a148c?text=Rubber+Gloves',
                'is_featured' => true,
                'views_count' => 12500,
            ],
        ];

        foreach ($products as $attributes) {
            $category = Category::where('slug', $attributes['category'])->firstOrFail();
            $supplier = Supplier::where('slug', $attributes['supplier'])->firstOrFail();
            unset($attributes['category']);
            unset($attributes['supplier']);

            Product::updateOrCreate(
                ['slug' => $attributes['slug']],
                [
                    ...$attributes,
                    'category_id' => $category->id,
                    'supplier_id' => $supplier->id,
                    'status' => 'active',
                ],
            );
        }
    }
}
