<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category' => 'ceylon-tea',
                'supplier' => 'lanka-tea-exports',
                'name' => 'Pure Ceylon Black Tea',
                'slug' => 'pure-ceylon-black-tea',
                'short_description' => 'Export-grade black tea with a bright liquor and classic Ceylon character.',
                'description' => 'Pure Ceylon black tea selected from established Sri Lankan estates and prepared for bulk export, private label, and food-service buyers.',
                'price' => 8.50,
                'moq' => 100,
                'unit' => 'Kg',
                'supply_ability' => '20,000 Kg per month',
                'lead_time' => '14–21 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => '25 Kg food-grade kraft bags or buyer-specified retail packing.',
                'featured_image' => 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'views_count' => 9800,
            ],
            [
                'category' => 'ceylon-tea',
                'supplier' => 'lanka-tea-exports',
                'name' => 'Green Tea Bags',
                'slug' => 'green-tea-bags',
                'short_description' => 'Individually wrapped Sri Lankan green tea bags for retail and hospitality.',
                'description' => 'Refreshing green tea bags produced with Sri Lankan tea leaves and available for private-label export programs.',
                'price' => 4.75,
                'moq' => 500,
                'unit' => 'Box',
                'supply_ability' => '50,000 boxes per month',
                'lead_time' => '21 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => '20 or 25 individually wrapped tea bags per printed carton.',
                'featured_image' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80',
                'is_featured' => false,
                'views_count' => 6400,
            ],
            [
                'category' => 'cinnamon',
                'supplier' => 'ceylon-spice-gardens',
                'name' => 'Ceylon Cinnamon Sticks',
                'slug' => 'ceylon-cinnamon-sticks',
                'short_description' => 'Premium true cinnamon quills graded and packed for export.',
                'description' => 'Authentic Cinnamomum verum cinnamon sticks processed in Sri Lanka with a delicate aroma and naturally sweet flavour.',
                'price' => 18.00,
                'moq' => 50,
                'unit' => 'Kg',
                'supply_ability' => '8,000 Kg per month',
                'lead_time' => '14 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => '10 Kg lined cartons with moisture protection.',
                'featured_image' => 'https://images.unsplash.com/photo-1606914469633-bd39206ea739?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'views_count' => 11200,
            ],
            [
                'category' => 'cinnamon',
                'supplier' => 'ceylon-spice-gardens',
                'name' => 'Cinnamon Powder',
                'slug' => 'ceylon-cinnamon-powder',
                'short_description' => 'Finely ground Ceylon cinnamon powder for food manufacturing and retail.',
                'description' => 'Pure Ceylon cinnamon powder milled from selected quills and available in bulk or private-label packaging.',
                'price' => 14.25,
                'moq' => 100,
                'unit' => 'Kg',
                'supply_ability' => '10,000 Kg per month',
                'lead_time' => '14–20 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Food-grade foil pouches or 20 Kg lined cartons.',
                'featured_image' => 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=900&q=80',
                'is_featured' => false,
                'views_count' => 5700,
            ],
            [
                'category' => 'blue-sapphire',
                'supplier' => 'ceylon-gems-jewels',
                'name' => 'Natural Blue Sapphire',
                'slug' => 'natural-blue-sapphire',
                'short_description' => 'Natural Ceylon blue sapphire suitable for fine jewellery.',
                'description' => 'Responsibly sourced natural blue sapphire from Sri Lanka, available as calibrated stones or individually certified gems.',
                'price' => 850.00,
                'moq' => 1,
                'unit' => 'Carat',
                'supply_ability' => '250 carats per month',
                'lead_time' => '7–14 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Tamper-evident gem box with certification documents where applicable.',
                'featured_image' => 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'views_count' => 15400,
            ],
            [
                'category' => 'coconut-oil',
                'supplier' => 'coco-lanka-naturals',
                'name' => 'Virgin Coconut Oil',
                'slug' => 'virgin-coconut-oil',
                'short_description' => 'Cold-pressed virgin coconut oil for food, wellness, and cosmetic use.',
                'description' => 'Premium Sri Lankan virgin coconut oil made from fresh coconut kernels and available in bulk drums or retail-ready bottles.',
                'price' => 6.80,
                'moq' => 500,
                'unit' => 'Litre',
                'supply_ability' => '30,000 litres per month',
                'lead_time' => '21 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Food-grade HDPE drums, IBC tanks, glass bottles, or PET bottles.',
                'featured_image' => 'https://images.unsplash.com/photo-1581375383689-4f8f974d6b82?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'views_count' => 8700,
            ],
            [
                'category' => 'ayurvedic-oil',
                'supplier' => 'coco-lanka-naturals',
                'name' => 'Ayurvedic Herbal Oil',
                'slug' => 'ayurvedic-herbal-oil',
                'short_description' => 'Traditional herbal massage oil produced from Sri Lankan botanical ingredients.',
                'description' => 'A Sri Lankan Ayurvedic herbal oil blend prepared for wellness, spa, and private-label markets.',
                'price' => 5.50,
                'moq' => 1000,
                'unit' => 'Bottle',
                'supply_ability' => '40,000 bottles per month',
                'lead_time' => '30 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => '100 ml, 200 ml, or 500 ml bottles with custom label options.',
                'featured_image' => 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80',
                'is_featured' => false,
                'views_count' => 7200,
            ],
            [
                'category' => 'batik-fabric',
                'supplier' => 'lanka-craft-rubber',
                'name' => 'Handmade Batik Fabric',
                'slug' => 'handmade-batik-fabric',
                'short_description' => 'Hand-dyed Sri Lankan batik fabric for apparel and interior collections.',
                'description' => 'Artisan-made batik fabric featuring traditional wax-resist techniques and customizable colourways.',
                'price' => 12.00,
                'moq' => 100,
                'unit' => 'Metre',
                'supply_ability' => '5,000 metres per month',
                'lead_time' => '21–30 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Rolled fabric with protective wrapping and export cartons.',
                'featured_image' => 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'views_count' => 6100,
            ],
            [
                'category' => 'rubber-gloves',
                'supplier' => 'lanka-craft-rubber',
                'name' => 'Latex Rubber Gloves',
                'slug' => 'latex-rubber-gloves',
                'short_description' => 'Natural latex gloves manufactured for industrial and household applications.',
                'description' => 'Durable Sri Lankan latex rubber gloves available in multiple sizes, textures, colours, and private-label formats.',
                'price' => 3.20,
                'moq' => 1000,
                'unit' => 'Pair',
                'supply_ability' => '500,000 pairs per month',
                'lead_time' => '21–30 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Individual polybags or retail printed packs in export cartons.',
                'featured_image' => 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'views_count' => 12500,
            ],
            [
                'category' => 'apparel-textiles',
                'supplier' => 'lanka-craft-rubber',
                'name' => 'Organic Cotton Apparel Fabric',
                'slug' => 'organic-cotton-apparel-fabric',
                'short_description' => 'Soft apparel-grade cotton fabric rolls for garment production.',
                'description' => 'Sri Lankan apparel textile fabric supplied in bulk rolls for garment makers, private-label brands, and uniform programs.',
                'price' => 4.90,
                'moq' => 500,
                'unit' => 'Metre',
                'supply_ability' => '30,000 metres per month',
                'lead_time' => '21–30 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Fabric rolls wrapped in poly film and packed in export cartons.',
                'featured_image' => 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'views_count' => 9300,
            ],
            [
                'category' => 'spices-condiments',
                'supplier' => 'ceylon-spice-gardens',
                'name' => 'Sri Lankan Mixed Spices',
                'slug' => 'sri-lankan-mixed-spices',
                'short_description' => 'Export-ready spice assortments for retail and food-service buyers.',
                'description' => 'A curated Sri Lankan spice range including pepper, cloves, cardamom, turmeric, chilli, and curry spice blends.',
                'price' => 9.40,
                'moq' => 100,
                'unit' => 'Kg',
                'supply_ability' => '12,000 Kg per month',
                'lead_time' => '14–21 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Bulk lined cartons, jars, pouches, or buyer-specified private-label packs.',
                'featured_image' => 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'views_count' => 10100,
            ],
            [
                'category' => 'handicrafts-gifts',
                'supplier' => 'lanka-craft-rubber',
                'name' => 'Handmade Wooden Gift Boxes',
                'slug' => 'handmade-wooden-gift-boxes',
                'short_description' => 'Artisan-made wooden boxes for corporate gifting and premium packaging.',
                'description' => 'Handcrafted Sri Lankan wooden gift boxes made for tea, spice, jewellery, and corporate gift packaging programs.',
                'price' => 6.25,
                'moq' => 200,
                'unit' => 'Piece',
                'supply_ability' => '15,000 pieces per month',
                'lead_time' => '30 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Individually wrapped boxes in export cartons with optional custom branding.',
                'featured_image' => 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&w=900&q=80',
                'is_featured' => false,
                'views_count' => 4600,
            ],
            [
                'category' => 'electronics-it',
                'supplier' => 'lanka-tea-exports',
                'name' => 'Export ERP and Marketplace Integration Service',
                'slug' => 'export-erp-marketplace-integration-service',
                'short_description' => 'Software service for exporters managing catalogs, quotations, and orders.',
                'description' => 'Sri Lankan IT service package for B2B exporters who need catalog management, RFQ tracking, quotation workflows, and order integrations.',
                'price' => 1200.00,
                'moq' => 1,
                'unit' => 'Project',
                'supply_ability' => '20 projects per quarter',
                'lead_time' => '30–45 days',
                'port' => 'Remote delivery from Sri Lanka',
                'packaging_details' => 'Digital delivery with implementation documentation and handover sessions.',
                'featured_image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80',
                'is_featured' => false,
                'views_count' => 3900,
            ],
            [
                'category' => 'industrial-machinery',
                'supplier' => 'coco-lanka-naturals',
                'name' => 'Coconut Oil Filling Machine',
                'slug' => 'coconut-oil-filling-machine',
                'short_description' => 'Semi-automatic liquid filling machine for edible oils and wellness products.',
                'description' => 'Compact filling equipment suitable for coconut oil, herbal oil, and liquid food production lines.',
                'price' => 4200.00,
                'moq' => 1,
                'unit' => 'Unit',
                'supply_ability' => '25 units per month',
                'lead_time' => '45 days',
                'port' => 'Colombo, Sri Lanka',
                'packaging_details' => 'Wooden crate packing with spare parts and operating manual.',
                'featured_image' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'views_count' => 5400,
            ],
        ];

        foreach ($products as $attributes) {
            $category = Category::where('slug', $attributes['category'])->firstOrFail();
            $supplier = Supplier::where('slug', $attributes['supplier'])->firstOrFail();
            unset($attributes['category']);
            unset($attributes['supplier']);

            Product::updateOrCreate(
                ['slug' => $attributes['slug']],
                [
                    ...$attributes,
                    'category_id' => $category->id,
                    'supplier_id' => $supplier->id,
                    'status' => 'active',
                ],
            );
        }
    }
}
