"use client";
import React,{useState} from "react";
import { Archive, Copy, Edit3, ExternalLink, MoreHorizontal, ShieldCheck } from "lucide-react";
import toast from "react-hot-toast";
import type { CatalogueBrand } from "@/types/brandManagement";
interface Props {brands:CatalogueBrand[];pagination:{currentPage:number;pageSize:number;total:number;lastPage:number};selectedBrandIds:string[];selectedBrand:CatalogueBrand|null;canManage:boolean;onPageChange:(p:number)=>void;onPageSizeChange:(n:number)=>void;onSelectBrand:(b:CatalogueBrand)=>void;onToggleSelectRow:(id:string)=>void;onToggleSelectAll:()=>void;onEditBrand:(b:CatalogueBrand)=>void;onManageAuthorization:(b:CatalogueBrand)=>void;onViewProducts:(b:CatalogueBrand)=>void;onArchiveBrand:(b:CatalogueBrand)=>void;onUnavailable:(label:string)=>void;}
const display=(value:number|string|null)=>value===null?"Unavailable":typeof value==="number"?value.toLocaleString():value;
export const BrandTable=({brands,pagination,selectedBrandIds,selectedBrand,canManage,onPageChange,onPageSizeChange,onSelectBrand,onToggleSelectRow,onToggleSelectAll,onEditBrand,onManageAuthorization,onViewProducts,onArchiveBrand,onUnavailable}:Props)=>{
 const [menu,setMenu]=useState<string|null>(null);const all=brands.length>0&&brands.every(b=>selectedBrandIds.includes(b.id));
 const copy=async(value:string)=>{await navigator.clipboard.writeText(value);toast.success("Brand UUID copied.")};
 const columns=["Brand / Logo","Brand ID","Legal Owner / Manufacturer","Primary Supplier","Country","Active Products","Categories","Verification","Authorization","Territory","Channel Eligibility","Compliance","Catalogue Readiness","Duplicate Risk","Risk Level","Brand Owner","Updated At","Actions"];
 return <div className="bg-white rounded border border-gray-200 p-3.5 shadow-2xs min-w-0"><div className="flex justify-between mb-3"><div><h3 className="text-sm font-bold">Brand Masters</h3><p className="text-[11px] text-gray-500">Authoritative brand masters and authorization summaries</p></div><span className="text-[11px] text-gray-500 font-semibold">{pagination.total.toLocaleString()} records found</span></div>
 <div className="overflow-x-auto border border-gray-200 rounded max-h-[520px]"><table className="w-full text-left text-[11.5px] min-w-[1700px]"><thead className="sticky top-0 z-10 bg-gray-50 border-b"><tr className="uppercase text-[10px] text-gray-600"><th className="p-3"><input aria-label="Select page" type="checkbox" checked={all} onChange={onToggleSelectAll}/></th>{columns.map(c=><th key={c} className="p-3 whitespace-nowrap">{c}</th>)}</tr></thead><tbody className="divide-y">
 {brands.length===0&&<tr><td colSpan={19} className="p-10 text-center text-gray-500">No brands match the selected filters.</td></tr>}
 {brands.map(b=><tr key={b.id} onClick={()=>onSelectBrand(b)} className={selectedBrand?.id===b.id?"bg-[#f5ebed]/50":"hover:bg-gray-50"}><td className="p-3" onClick={e=>e.stopPropagation()}><input aria-label={`Select ${b.brandName}`} type="checkbox" checked={selectedBrandIds.includes(b.id)} onChange={()=>onToggleSelectRow(b.id)}/></td>
  <td className="p-3 font-bold whitespace-nowrap"><span className="inline-flex w-6 h-6 mr-2 items-center justify-center rounded bg-gray-100 text-[#741d35]">{b.initials}</span>{b.brandName}</td>
  <td className="p-3 whitespace-nowrap"><span className="font-mono bg-gray-100 p-1 rounded">{b.brandId}</span><button aria-label="Copy brand UUID" onClick={e=>{e.stopPropagation();void copy(b.brandId)}} className="ml-1"><Copy size={11}/></button></td>
  <td className="p-3 text-gray-500">{b.legalOwner}</td><td className="p-3 text-gray-500">{b.primarySupplier}</td><td className="p-3">{b.country}</td><td className="p-3 text-right">{display(b.activeProductsCount)}</td><td className="p-3 text-center">{display(b.categoriesCount)}</td>
  <td className="p-3 text-center"><Badge value={b.verificationStatus}/></td><td className="p-3 text-center"><Badge value={b.authorizationStatus}/></td><td className="p-3">{b.territory}</td><td className="p-3 text-center">{b.channelEligibility}</td><td className="p-3 text-center">{b.complianceStatus}</td><td className="p-3">{b.catalogueReadinessPercent===null?"Unavailable":`${b.catalogueReadinessPercent}%`}</td><td className="p-3 text-center">{b.duplicateRisk}</td><td className="p-3 text-center">{b.riskLevel}</td><td className="p-3">{b.brandOwner}</td><td className="p-3 whitespace-nowrap">{b.updatedAt?new Date(b.updatedAt).toLocaleString():"—"}</td>
  <td className="p-3 relative" onClick={e=>e.stopPropagation()}><button aria-label="Brand actions" onClick={()=>setMenu(menu===b.id?null:b.id)}><MoreHorizontal size={15}/></button>{menu===b.id&&<div className="absolute right-3 top-8 z-30 w-48 bg-white border shadow-lg rounded py-1">
   <Action label="Edit Brand" icon={<Edit3 size={13}/>} disabled={!canManage} onClick={()=>onEditBrand(b)}/><Action label="View Products" icon={<ExternalLink size={13}/>} onClick={()=>onViewProducts(b)}/><Action label="Manage Authorization" icon={<ShieldCheck size={13}/>} onClick={()=>onManageAuthorization(b)}/>{["Manage Suppliers","Configure Channels","View Compliance","Assign Brand Owner","View Audit History"].map(x=><Action key={x} label={x} onClick={()=>onUnavailable(x)}/>)}
   <div className="border-t my-1"/><Action label="Archive Brand" icon={<Archive size={13}/>} disabled={!canManage||!!b.archivedAt} danger onClick={()=>onArchiveBrand(b)}/>
  </div>}</td></tr>)}
 </tbody></table></div>
 <div className="flex justify-between items-center pt-3 text-xs text-gray-500"><span>Showing {pagination.total===0?0:(pagination.currentPage-1)*pagination.pageSize+1} to {Math.min(pagination.currentPage*pagination.pageSize,pagination.total)} of {pagination.total}</span><div className="flex gap-2 items-center"><button disabled={pagination.currentPage<=1} onClick={()=>onPageChange(pagination.currentPage-1)} className="border rounded px-2 py-1 disabled:opacity-40">Previous</button><span>Page {pagination.currentPage} of {Math.max(1,pagination.lastPage)}</span><button disabled={pagination.currentPage>=pagination.lastPage} onClick={()=>onPageChange(pagination.currentPage+1)} className="border rounded px-2 py-1 disabled:opacity-40">Next</button><select value={pagination.pageSize} onChange={e=>onPageSizeChange(Number(e.target.value))} className="border rounded p-1"><option value={25}>25 / page</option><option value={50}>50 / page</option><option value={100}>100 / page</option></select></div></div>
 </div>;
};
const Badge=({value}:{value:string})=><span className={`inline-flex rounded border px-2 py-0.5 text-[10px] font-bold ${["Verified","Valid"].includes(value)?"bg-emerald-50 text-emerald-700 border-emerald-200":["Pending"].includes(value)?"bg-amber-50 text-amber-700 border-amber-200":"bg-gray-50 text-gray-600 border-gray-200"}`}>{value}</span>;
const Action=({label,icon,onClick,disabled,danger}:{label:string;icon?:React.ReactNode;onClick:()=>void;disabled?:boolean;danger?:boolean})=><button disabled={disabled} onClick={onClick} className={`w-full px-3 py-1.5 flex gap-2 items-center text-left disabled:text-gray-300 hover:bg-gray-50 ${danger?"text-rose-600":"text-gray-700"}`}>{icon}{label}</button>;
