"use client";import React from "react";import{ShieldCheck}from"lucide-react";import type{BrandManagementData}from"@/types/brandManagement";
interface Props{data:BrandManagementData;onSelectQueue:(key:string)=>void}
const Panel=({title,children}:{title:string;children:React.ReactNode})=><section className="bg-white rounded border border-gray-200 p-3.5 shadow-2xs"><h3 className="font-bold text-xs mb-3">{title}</h3>{children}</section>;
export const BrandIntelligenceSidebar=({data,onSelectQueue}:Props)=>{const health=Object.values(data.analytics.health).filter((x):x is number=>x!==null);const score=health.length?Math.round(health.reduce((a,b)=>a+b,0)/health.length):null;const auth=data.analytics.authorizationSummary;return <div className="flex flex-col gap-4 text-xs"><Panel title="Brand Catalogue Health"><div className="flex gap-3 items-center"><div className="w-16 h-16 rounded-full border-4 border-emerald-500 flex items-center justify-center font-bold text-lg">{score??"N/A"}</div><div><ShieldCheck size={15}/><b>{score===null?"Insufficient data":score>=80?"Healthy":"Needs attention"}</b><p className="text-[10px] text-gray-500">Mean of available real coverage metrics.</p></div></div></Panel>
 <Panel title="Priority Brand Alerts"><Queue label="Expired authorizations" value={data.kpis.find(x=>x.filterKey==="expired")?.value} onClick={()=>onSelectQueue("expired")}/><Queue label="Duplicate exact names" value={data.kpis.find(x=>x.filterKey==="duplicates")?.value} onClick={()=>onSelectQueue("duplicates")}/><p className="mt-2 text-[10px] text-gray-500">Unsupported alert domains are not synthesized.</p></Panel>
 <Panel title="Brand Status Summary">{data.tabs.map(x=><Queue key={x.id} label={x.label} value={x.count} onClick={()=>onSelectQueue(x.id)}/>)}</Panel>
 <Panel title="Authorization Summary">{Object.keys(auth).length===0?<p className="text-gray-500">No records.</p>:Object.entries(auth).map(([k,v])=><Queue key={k} label={k.replaceAll("_"," ")} value={v}/>)}</Panel>
 <Panel title="Supplier Coverage Summary"><Queue label="Mapped suppliers" value={data.analytics.supplierRelationships.length}/><Queue label="Mapped brands" value={data.analytics.supplierRelationships.reduce((n,x)=>n+x.totalBrands,0)}/></Panel>
 <Panel title="Quick Queues"><button onClick={()=>onSelectQueue("verified")} className="border rounded px-2 py-1 mr-1">Verified</button><button onClick={()=>onSelectQueue("expired")} className="border rounded px-2 py-1 mr-1">Expired</button><button onClick={()=>onSelectQueue("archived")} className="border rounded px-2 py-1">Archived</button></Panel></div>};
const Queue=({label,value,onClick}:{label:string;value:number|null|undefined;onClick?:()=>void})=><button disabled={!onClick} onClick={onClick} className="flex justify-between w-full py-1 border-b capitalize disabled:text-gray-700"><span>{label}</span><b>{value===null||value===undefined?"N/A":value}</b></button>;
