"use client";
import React from "react";import type{BrandManagementData,DuplicateBrandPair}from "@/types/brandManagement";
interface Props{data:BrandManagementData;onCompareDuplicate:(pair:DuplicateBrandPair)=>void;onSelectAuthorization:()=>void}
const Card=({title,children}:{title:string;children:React.ReactNode})=><section className="bg-white rounded border border-gray-200 p-3.5 shadow-2xs min-h-36"><h3 className="font-bold text-xs mb-3">{title}</h3>{children}</section>;
const Unavailable=({reason}:{reason:string})=><p className="rounded bg-gray-50 border border-dashed p-3 text-[11px] text-gray-500">Unavailable — {reason}</p>;
const Bar=({label,value}:{label:string;value:number|null})=><div className="mb-2"><div className="flex justify-between text-[10px]"><span>{label}</span><b>{value===null?"N/A":`${value}%`}</b></div><div className="h-1.5 bg-gray-100 rounded"><div className="h-full bg-emerald-500 rounded" style={{width:`${value??0}%`}}/></div></div>;
export const BrandLowerDashboards=({data,onCompareDuplicate,onSelectAuthorization}:Props)=>{const a=data.analytics,r=data.capabilities.reason;return <div className="flex flex-col gap-4 text-xs min-w-0">
 <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4"><Card title="Brand Health Scorecard"><Bar label="Verification Coverage" value={a.health.verificationCoverage}/><Bar label="Authorization Readiness" value={a.health.authorizationReadiness}/><Bar label="Supplier Mapping" value={a.health.supplierMapping}/><Bar label="Logo Coverage" value={a.health.logoCoverage}/></Card><Card title="Product Coverage by Brand"><Unavailable reason={r}/></Card><Card title="Brand Readiness Distribution"><div className="grid grid-cols-3 gap-2 text-center"><Metric label="Ready" value={a.readiness.ready}/><Metric label="Partial" value={a.readiness.partial}/><Metric label="Not Ready" value={a.readiness.notReady}/></div><p className="mt-3 text-[10px] text-gray-500">Ready = verified plus at least one current approved authorization.</p></Card><Card title="Priority Authorization Operations">{Object.keys(a.authorizationSummary).length===0?<p className="text-gray-500">No authorization records.</p>:Object.entries(a.authorizationSummary).map(([k,v])=><button key={k} onClick={onSelectAuthorization} className="w-full flex justify-between py-1 border-b"><span className="capitalize">{k.replaceAll("_"," ")}</span><b>{v}</b></button>)}</Card></div>
 <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4"><Card title="Brand & Supplier Relationship Matrix">{a.supplierRelationships.length===0?<p className="text-gray-500">No supplier authorizations.</p>:a.supplierRelationships.map(x=><div key={x.id} className="flex justify-between border-b py-1"><span>{x.supplierName}</span><span>{x.approvedAuthorizations}/{x.totalBrands}</span></div>)}</Card><Card title="Brand Eligibility by Channel"><Unavailable reason={r}/></Card><Card title="Unauthorized Brand Use"><Unavailable reason={r}/></Card><Card title="Duplicate Brand Candidates">{a.duplicates.length===0?<p className="text-gray-500">No exact normalized-name duplicates.</p>:a.duplicates.map(x=><button key={x.id} onClick={()=>onCompareDuplicate(x)} className="block w-full text-left border-b py-1"><b>{x.brandA}</b> / {x.brandB} ({x.similarityPercent}%)</button>)}</Card></div>
 <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Card title="Brand Compliance & Authenticity"><Unavailable reason={r}/></Card><Card title="Brand Media & SEO Readiness"><Bar label="Logo Coverage" value={a.health.logoCoverage}/><Unavailable reason="SEO metadata is not represented in the brand schema."/></Card></div>
 <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Card title="Recent Brand Activity">{a.activities.length===0?<p className="text-gray-500">No audited brand activity.</p>:a.activities.slice(0,6).map(x=><div key={x.id} className="border-b py-1"><b>{x.activity}</b><span className="float-right text-gray-400">{new Date(x.dateTime).toLocaleString()}</span><div className="text-[10px] text-gray-500">{x.actionBy}</div></div>)}</Card><Card title="Recent Approval & Audit Events">{a.activities.length===0?<p className="text-gray-500">No authorization audit events.</p>:a.activities.filter(x=>x.activity.includes("authorization")).slice(0,6).map(x=><div key={x.id} className="border-b py-1">{x.activity}<span className="float-right">{x.result}</span></div>)}</Card></div>
 </div>};
const Metric=({label,value}:{label:string;value:number})=><div className="rounded border p-2"><b className="text-lg">{value}</b><div className="text-[10px] text-gray-500">{label}</div></div>;
