import {
    AnalyticsCardItem,
    AnalyticsKpi,
    DomainPerformanceRow,
    OperationalStatusItem,
    ReportExportItem,
    RiskCategory,
    SavedSubscriptionItem,
    ScheduledReportItem,
    ScorecardMetric,
} from "./reports.types";

export const analyticsKpis: AnalyticsKpi[] = [
    {
        id: 1,
        title: "Trust Score",
        value: "94.2%",
        trend: 1.4,
        trendDirection: "up",
        positive: true,
        sparklineData: [91, 92, 92.5, 93, 93.8, 94.2],
    },
    {
        id: 2,
        title: "Entity Risk Exposure",
        value: "18.4%",
        trend: 2.1,
        trendDirection: "down",
        positive: true,
        sparklineData: [22, 21, 20.5, 19.8, 19.1, 18.4],
    },
    {
        id: 3,
        title: "Audit Readiness",
        value: "96.8%",
        trend: 0.8,
        trendDirection: "up",
        positive: true,
        sparklineData: [94, 94.8, 95.2, 95.9, 96.1, 96.8],
    },
    {
        id: 4,
        title: "Open Cases",
        value: 42,
        trend: 10.5,
        trendDirection: "down",
        positive: true,
        sparklineData: [55, 50, 48, 46, 44, 42],
    },
    {
        id: 5,
        title: "Overdue",
        value: 6,
        trend: 25.0,
        trendDirection: "down",
        positive: true,
        sparklineData: [12, 10, 9, 8, 7, 6],
    },
    {
        id: 6,
        title: "Expiring Soon",
        value: 14,
        trend: 17.6,
        trendDirection: "down",
        positive: true,
        sparklineData: [20, 18, 17, 16, 15, 14],
    },
    {
        id: 7,
        title: "Documents Verified",
        value: "1,482",
        trend: 9.1,
        trendDirection: "up",
        positive: true,
        sparklineData: [1200, 1280, 1340, 1400, 1450, 1482],
    },
    {
        id: 8,
        title: "Supplier Compliance",
        value: "92.5%",
        trend: 1.2,
        trendDirection: "up",
        positive: true,
        sparklineData: [89, 90, 90.8, 91.4, 92.0, 92.5],
    },
    {
        id: 9,
        title: "Aging SLA Breaches",
        value: 3,
        trend: 25.0,
        trendDirection: "down",
        positive: true,
        sparklineData: [6, 5, 5, 4, 4, 3],
    },
    {
        id: 10,
        title: "SLA Adherence",
        value: "98.1%",
        trend: 0.5,
        trendDirection: "up",
        positive: true,
        sparklineData: [96.5, 97.0, 97.4, 97.8, 98.0, 98.1],
    },
    {
        id: 11,
        title: "Rule Effectiveness",
        value: "95.4%",
        trend: 1.1,
        trendDirection: "up",
        positive: true,
        sparklineData: [93, 93.8, 94.2, 94.8, 95.0, 95.4],
    },
    {
        id: 12,
        title: "Audit Readiness Score",
        value: "96.8%",
        trend: 0.8,
        trendDirection: "up",
        positive: true,
        sparklineData: [94, 94.8, 95.2, 95.9, 96.1, 96.8],
    },
    {
        id: 13,
        title: "Incident Rate",
        value: "0.42%",
        trend: 16.0,
        trendDirection: "down",
        positive: true,
        sparklineData: [0.65, 0.58, 0.52, 0.48, 0.45, 0.42],
    },
];

export const healthTrendData = [
    { date: "May 15", breaches: 12, approvals: 45, riskEvents: 8, slaBreaches: 6 },
    { date: "May 30", breaches: 10, approvals: 52, riskEvents: 7, slaBreaches: 5 },
    { date: "Jun 15", breaches: 9, approvals: 60, riskEvents: 6, slaBreaches: 4 },
    { date: "Jun 30", breaches: 7, approvals: 68, riskEvents: 5, slaBreaches: 4 },
    { date: "Jul 15", breaches: 5, approvals: 74, riskEvents: 4, slaBreaches: 3 },
    { date: "Jul 30", breaches: 4, approvals: 82, riskEvents: 3, slaBreaches: 3 },
    { date: "Aug 12", breaches: 3, approvals: 90, riskEvents: 2, slaBreaches: 2 },
];

export const riskDistributionData: RiskCategory[] = [
    { name: "Supplier Verification", value: 142, percentage: 31.1 },
    { name: "Brand Authorization", value: 98, percentage: 21.5 },
    { name: "Product Compliance", value: 84, percentage: 18.4 },
    { name: "Documents", value: 62, percentage: 13.6 },
    { name: "Authenticity", value: 38, percentage: 8.3 },
    { name: "Recalls & Incidents", value: 22, percentage: 4.8 },
    { name: "Other", value: 10, percentage: 2.2 },
];

export const operationalStatusData: OperationalStatusItem[] = [
    { status: "On Track", count: 312, percentage: 68.4, color: "#16a34a" },
    { status: "At Risk", count: 54, percentage: 11.8, color: "#f59e0b" },
    { status: "Under Review", count: 48, percentage: 10.5, color: "#2563eb" },
    { status: "Escalated", count: 26, percentage: 5.7, color: "#dc2626" },
    { status: "Closed", count: 16, percentage: 3.5, color: "#6b7280" },
];

export const scorecardMetrics: ScorecardMetric[] = [
    { label: "Verification Effectiveness", score: 94, target: 95 },
    { label: "Supplier Compliance", score: 92, target: 90 },
    { label: "Brand Authorization", score: 96, target: 95 },
    { label: "Risk Compliance", score: 89, target: 90 },
    { label: "Evaluation Coverage", score: 91, target: 90 },
    { label: "Document Compliance", score: 95, target: 95 },
    { label: "Incident Response", score: 93, target: 90 },
    { label: "SLA Adherence", score: 98, target: 95 },
    { label: "Due Diligence", score: 90, target: 90 },
    { label: "Regulatory Compliance", score: 97, target: 95 },
];

export const domainTableRows: DomainPerformanceRow[] = [
    {
        id: 1,
        domain: "Supplier Verification",
        totalRecords: 420,
        highRisk: 12,
        criticalIssues: 2,
        resolved: 398,
        resolutionRate: 94.8,
        slaCompliance: 98.2,
        currentScore: 92.5,
        targetScore: 90,
        sparklineData: [88, 89, 90, 91, 92, 92.5],
    },
    {
        id: 2,
        domain: "Brand Authorization",
        totalRecords: 310,
        highRisk: 8,
        criticalIssues: 1,
        resolved: 295,
        resolutionRate: 95.2,
        slaCompliance: 97.5,
        currentScore: 96.1,
        targetScore: 95,
        sparklineData: [92, 93, 94, 95, 95.8, 96.1],
    },
    {
        id: 3,
        domain: "Product Compliance",
        totalRecords: 1240,
        highRisk: 24,
        criticalIssues: 5,
        resolved: 1180,
        resolutionRate: 95.2,
        slaCompliance: 96.8,
        currentScore: 94.3,
        targetScore: 92,
        sparklineData: [90, 91, 92.5, 93, 93.8, 94.3],
    },
    {
        id: 4,
        domain: "Document Verification",
        totalRecords: 890,
        highRisk: 15,
        criticalIssues: 3,
        resolved: 852,
        resolutionRate: 95.7,
        slaCompliance: 99.1,
        currentScore: 95.8,
        targetScore: 95,
        sparklineData: [93, 94, 94.5, 95, 95.4, 95.8],
    },
    {
        id: 5,
        domain: "Authenticity Investigations",
        totalRecords: 145,
        highRisk: 9,
        criticalIssues: 2,
        resolved: 130,
        resolutionRate: 89.7,
        slaCompliance: 94.5,
        currentScore: 88.4,
        targetScore: 90,
        sparklineData: [84, 85, 86, 87, 87.8, 88.4],
    },
    {
        id: 6,
        domain: "Recalls & Safety Incidents",
        totalRecords: 68,
        highRisk: 6,
        criticalIssues: 2,
        resolved: 58,
        resolutionRate: 85.3,
        slaCompliance: 92.0,
        currentScore: 86.2,
        targetScore: 90,
        sparklineData: [80, 81, 83, 84, 85.5, 86.2],
    },
    {
        id: 7,
        domain: "SLA & Escalations",
        totalRecords: 210,
        highRisk: 11,
        criticalIssues: 3,
        resolved: 192,
        resolutionRate: 91.4,
        slaCompliance: 98.6,
        currentScore: 93.7,
        targetScore: 95,
        sparklineData: [89, 90, 91, 92, 93, 93.7],
    },
    {
        id: 8,
        domain: "Rules & Policies",
        totalRecords: 428,
        highRisk: 9,
        criticalIssues: 1,
        resolved: 412,
        resolutionRate: 96.3,
        slaCompliance: 99.4,
        currentScore: 97.2,
        targetScore: 95,
        sparklineData: [94, 95, 96, 96.5, 97, 97.2],
    },
];

export const analyticsMetricCards: AnalyticsCardItem[] = [
    {
        id: 1,
        title: "Supplier & Brand Compliance",
        value: "94.2%",
        change: "+1.5%",
        positive: true,
        sparklineType: "bar",
        sparklineData: [88, 90, 91, 93, 94, 94.2],
    },
    {
        id: 2,
        title: "Verification & Auth Trend",
        value: "96.8%",
        change: "+2.1%",
        positive: true,
        sparklineType: "line",
        sparklineData: [92, 93, 94.5, 95, 96, 96.8],
    },
    {
        id: 3,
        title: "Incidents & Recalls",
        value: "12 Cases",
        change: "-4",
        positive: true,
        sparklineType: "line",
        sparklineData: [20, 18, 16, 15, 13, 12],
    },
    {
        id: 4,
        title: "Compliance Cases Analytics",
        value: "42 Open",
        change: "-5",
        positive: true,
        sparklineType: "line",
        sparklineData: [55, 50, 48, 46, 44, 42],
    },
    {
        id: 5,
        title: "SLA Violation Trend",
        value: "3 Breaches",
        change: "-1",
        positive: true,
        sparklineType: "line",
        sparklineData: [7, 6, 5, 4, 4, 3],
    },
    {
        id: 6,
        title: "Audit Readiness",
        value: "96.8%",
        change: "+0.8%",
        positive: true,
        sparklineType: "bar",
        sparklineData: [94, 94.8, 95.2, 95.9, 96.1, 96.8],
    },
    {
        id: 7,
        title: "Product Safety & Regulatory",
        value: "94.3%",
        change: "+1.2%",
        positive: true,
        sparklineType: "line",
        sparklineData: [90, 91, 92, 93, 93.8, 94.3],
    },
    {
        id: 8,
        title: "Authenticity & Counterfeits",
        value: "99.2%",
        change: "+0.4%",
        positive: true,
        sparklineType: "bar",
        sparklineData: [98, 98.3, 98.6, 98.9, 99.0, 99.2],
    },
    {
        id: 9,
        title: "Recall & Safety Incidents",
        value: "2 Active",
        change: "-1",
        positive: true,
        sparklineType: "line",
        sparklineData: [5, 4, 4, 3, 3, 2],
    },
];

export const reportLibraryItems = [
    { name: "Executive Compliance Overview", category: "Executive", format: "PDF/XLSX", status: "Active" },
    { name: "Supplier Verification Summary", category: "Suppliers", format: "PDF/CSV", status: "Active" },
    { name: "Brand Authorization Report", category: "Brands", format: "XLSX", status: "Active" },
    { name: "Product Compliance Dashboard", category: "Products", format: "PDF", status: "Active" },
    { name: "SLA & Escalation Tracker", category: "SLA", format: "XLSX/CSV", status: "Active" },
    { name: "Audit Readiness Report", category: "Audit", format: "PDF", status: "Active" },
];

export const scheduledReports: ScheduledReportItem[] = [
    { id: "SCH-01", name: "Executive Compliance Overview", frequency: "Weekly", nextRun: "18 Aug 2026, 08:00 AM", recipients: "compliance-execs@slbeauty.lk" },
    { id: "SCH-02", name: "Supplier Verification Summary", frequency: "Daily", nextRun: "13 Aug 2026, 06:00 AM", recipients: "supplier-team@slbeauty.lk" },
    { id: "SCH-03", name: "Product Compliance Dashboard", frequency: "Weekly", nextRun: "17 Aug 2026, 09:00 AM", recipients: "qa-heads@slbeauty.lk" },
    { id: "SCH-04", name: "SLA & Escalation Tracker", frequency: "Daily", nextRun: "13 Aug 2026, 07:00 AM", recipients: "ops-leads@slbeauty.lk" },
    { id: "SCH-05", name: "Audit Readiness Report", frequency: "Monthly", nextRun: "01 Sep 2026, 08:00 AM", recipients: "audit-board@slbeauty.lk" },
];

export const exportHistory: ReportExportItem[] = [
    { id: "EXP-801", name: "Executive Compliance Overview", exportedOn: "12 Aug 2026, 09:15 AM", format: "PDF", status: "Completed" },
    { id: "EXP-802", name: "Supplier Verification Summary", exportedOn: "11 Aug 2026, 04:30 PM", format: "XLSX", status: "Completed" },
    { id: "EXP-803", name: "Brand Authorization Audit", exportedOn: "10 Aug 2026, 11:20 AM", format: "CSV", status: "Completed" },
    { id: "EXP-804", name: "Product Safety Incident Log", exportedOn: "09 Aug 2026, 02:45 PM", format: "PDF", status: "Completed" },
    { id: "EXP-805", name: "Monthly Audit Readiness Pack", exportedOn: "01 Aug 2026, 08:00 AM", format: "PDF", status: "Completed" },
];

export const savedSubscriptions: SavedSubscriptionItem[] = [
    { id: "SUB-101", name: "Daily Risk & Exception Digest", frequency: "Daily @ 7:00 AM", nextRun: "Tomorrow" },
    { id: "SUB-102", name: "Weekly SLA Breach Analytics", frequency: "Mondays @ 8:00 AM", nextRun: "17 Aug 2026" },
    { id: "SUB-103", name: "Monthly Supplier Compliance Matrix", frequency: "1st of Month", nextRun: "01 Sep 2026" },
    { id: "SUB-104", name: "Quarterly Audit Evidence Folder", frequency: "Quarterly", nextRun: "01 Oct 2026" },
];
