import { DeliverySupportCase, SelectedCaseDetailsData, DeliveryOperationsRailData } from "./types";

export const MOCK_DELIVERY_CASES: DeliverySupportCase[] = [
  {
    id: "CS-2024-001821",
    reference: "CS-2024-001821",
    customerName: "Evelyn Carter",
    customerId: "CUS-78439",
    isVip: true,
    loyaltyTier: "Gold",
    issueType: "Dispatch Delay",
    orderSource: "SLB WEBSITE",
    orderStatus: "Order Confirmed",
    fulfilmentStatus: "Connected",
    shipmentStatus: "Connected",
    shipmentSource: "Connected",
    carrier: "In Transit",
    deliveryStatus: "Delayed",
    risk: "High",
    slaStatus: "At Risk",
    deliverySlaState: "At Risk",
    assignedAgent: "Amelia Rivera",
    assignedTeam: "Delivery Support",
    lastUpdated: "9:26 AM",
    estimatedResolution: "Apr 22, 09:00 AM",
    age: "5h",

    orderId: "SLB-7843921",
    fulfilmentId: "FL-667823",
    deliveryEta: "Apr 22, 09:00 AM",
    slaDue: "Apr 22, 09:00 AM",
  },
  {
    id: "CS-2024-001822",
    reference: "CS-2024-001822",
    customerName: "Marcus Chen",
    customerId: "CUS-78440",
    isVip: false,
    loyaltyTier: "Silver",
    issueType: "Shipment Delay",
    orderSource: "SLB MOBILE APP",
    orderStatus: "Shipped",
    fulfilmentStatus: "Connected",
    shipmentStatus: "Ready for Pickup",
    shipmentSource: "Connected",
    carrier: "In Transit",
    deliveryStatus: "Delayed",
    risk: "High",
    slaStatus: "At Risk",
    deliverySlaState: "At Risk",
    assignedAgent: "Jordan Blake",
    assignedTeam: "Delivery Support",
    lastUpdated: "9:15 AM",
    estimatedResolution: "Apr 22, 11:00 AM",
    age: "7h",

    orderId: "SLB-7843922",
    fulfilmentId: "FL-667824",
    deliveryEta: "Apr 22, 11:00 AM",
    slaDue: "Apr 22, 11:00 AM",
  },
  {
    id: "CS-2024-001823",
    reference: "CS-2024-001823",
    customerName: "Priya Nair",
    customerId: "CUS-78441",
    isVip: false,
    loyaltyTier: "Bronze",
    issueType: "Failed Delivery",
    orderSource: "MARKETPLACE",
    orderStatus: "Out for Delivery",
    fulfilmentStatus: "Connected",
    shipmentStatus: "In Transit",
    shipmentSource: "Connected",
    carrier: "In Transit",
    deliveryStatus: "Attempted Delivery",
    risk: "High",
    slaStatus: "At Risk",
    deliverySlaState: "At Risk",
    assignedAgent: "Taylor Morgan",
    assignedTeam: "Delivery Support",
    lastUpdated: "9:02 AM",
    estimatedResolution: "Apr 21, 05:00 PM",
    age: "2h",

    orderId: "SLB-7843923",
    fulfilmentId: "FL-667825",
    deliveryEta: "Apr 21, 05:00 PM",
    slaDue: "Apr 21, 05:00 PM",
  },
  {
    id: "CS-2024-001824",
    reference: "CS-2024-001824",
    customerName: "Daniel Kim",
    customerId: "CUS-78442",
    isVip: false,
    loyaltyTier: "Silver",
    issueType: "Tracking Issue",
    orderSource: "SLB WEBSITE",
    orderStatus: "Shipped",
    fulfilmentStatus: "Connected",
    shipmentStatus: "Out for Delivery",
    shipmentSource: "Connected",
    carrier: "In Transit",
    deliveryStatus: "In Transit",
    risk: "Low",
    slaStatus: "On Track",
    deliverySlaState: "On Track",
    assignedAgent: "Casey Smith",
    assignedTeam: "Delivery Support",
    lastUpdated: "8:48 AM",
    estimatedResolution: "Apr 22, 10:00 AM",
    age: "3h",

    orderId: "SLB-7843924",
    fulfilmentId: "FL-667826",
    deliveryEta: "Apr 22, 10:00 AM",
    slaDue: "Apr 22, 10:00 AM",
  },
  {
    id: "CS-2024-001825",
    reference: "CS-2024-001825",
    customerName: "Sofia Martinez",
    customerId: "CUS-78443",
    isVip: false,
    loyaltyTier: "Bronze",
    issueType: "Address Issue",
    orderSource: "RETAIL STORE",
    orderStatus: "Order Confirmed",
    fulfilmentStatus: "Connected",
    shipmentStatus: "In Transit",
    shipmentSource: "Connected",
    carrier: "Label Created",
    deliveryStatus: "Label Created",
    risk: "Low",
    slaStatus: "On Track",
    deliverySlaState: "On Track",
    assignedAgent: "Riley Adams",
    assignedTeam: "Delivery Support",
    lastUpdated: "8:31 AM",
    estimatedResolution: "Apr 22, 05:00 PM",
    age: "1h",

    orderId: "SLB-7843925",
    fulfilmentId: "FL-667827",
    deliveryEta: "Apr 22, 05:00 PM",
    slaDue: "Apr 22, 05:00 PM",
  },
];

export const MOCK_SELECTED_CASE_DETAILS: SelectedCaseDetailsData = {
  caseInfo: MOCK_DELIVERY_CASES[0],
  caseOverview: {
    caseSource: "WEB PORTAL",
    created: "Apr 21, 08:10 AM",
    issueType: "Dispatch Delay",
    category: "Dispatch & Shipping",
    subcategory: "Carrier Delay",
    impact: "Medium",
    customerImpact: "High",
  },
  fulfilmentDetails: {
    orderSource: "SLB WEBSITE",
    orderDate: "Apr 19",
    orderStatus: "Order Confirmed",
    fulfilmentSource: "Connected",
    fulfilmentStatus: "Ready for Pickup",
    warehouse: "North LA DC",
    shipFrom: "North LA DC",
  },
  shipmentDetails: {
    shipmentSource: "Connected",
    trackingNumber: "123456789012",
    shipmentStatus: "In Transit",
    estimatedDelivery: "Apr 22, 09:00 AM",
    currentLocation: "Memphis, TN",
    lastScan: "Apr 21, 08:31 AM",
  },
  carrierTracking: {
    carrier: "FedEx",
    serviceLevel: "FedEx Ground",
    trackingLink: "Open in New Tab",
    proactiveTrackingRisk: "High",
  },
  deliveryTimeline: {
    stages: [
      { label: "Order Confirmed", timestamp: "Apr 19 10:21 AM", status: "completed" },
      { label: "Ready for Pickup", timestamp: "Apr 20 02:14 PM", status: "completed" },
      { label: "Picked Up", timestamp: "Apr 20 05:42 PM", status: "completed" },
      { label: "In Transit", timestamp: "Apr 21 07:18 AM", status: "active" },
      { label: "Out for Delivery", status: "pending" },
      { label: "Delivered", status: "pending" },
    ],
    delayReason: "Carrier Delay • Weather",
    warningAlert: "Reports heavy storms in transit area",
  },
  slaSummary: {
    healthPercent: 82,
    slaTarget: "Apr 22, 09:00 AM",
    timeRemaining: "2h 12m",
    stageCompliancePercent: 82,
  },
  issueClassification: {
    primaryIssue: "Dispatch Delay",
    rootCauseLikely: "Carrier Delay",
    contributingFactors: "Weather",
    issueDetected: "Proactive Monitoring",
    customerNotified: "Yes",
  },
  investigationChecklist: [
    { label: "Order validated", isCompleted: true },
    { label: "Inventory confirmed", isCompleted: true },
    { label: "Pick & pack verified", isCompleted: true },
    { label: "Label generated", isCompleted: true },
    { label: "Handoff to carrier confirmed", isCompleted: true },
    { label: "Tracking event received", isCompleted: true },
    { label: "Exception logged", isCompleted: true },
  ],
  relatedIssues: {
    sameOrderCount: 0,
    sameCustomer30dCount: 1,
    sameAddress30dCount: 0,
    sameTracking30dCount: 2,
    similarIssues30dCount: 4,
  },
  dependencies: {
    warehouse: { name: "North LA DC", status: "normal" },
    inventory: "Confirmed",
    payment: "Captured",
    fraudReview: "Cleared",
    supplier: "N/A",
    carrier: { name: "Delayed", status: "danger" },
  },
  logisticsEscalation: {
    escalationLevel: "Carrier",
    escalatedTo: "FedEx Support Team Lead",
    escalationStatus: "In Progress",
    escalatedOn: "Apr 21, 08:45 AM",
    nextUpdateEta: "Apr 21, 12:00 PM",
  },
  recoveryPlan: {
    progressPercent: 30,
    steps: [
      { stepNumber: 1, label: "Acknowledge customer", status: "Completed" },
      { stepNumber: 2, label: "Provide update", status: "In Progress" },
      { stepNumber: 3, label: "Request resolution", status: "Pending" },
      { stepNumber: 4, label: "Confirm delivery", status: "Pending" },
      { stepNumber: 5, label: "Close case", status: "Pending" },
    ],
  },
  customerAvailability: {
    shippingAddress: "Verified",
    deliveryInstructions: "None",
    customerAvailability: "Available Apr 22",
    bestContactChannel: "Email",
    doNotDisturb: "No",
  },
  customerCommunication: {
    lastContact: "Apr 21, 08:55 AM",
    by: "Amelia Rivera",
    channel: "Email",
    status: "Customer Replied",
    summary: "Customer notified of delay, update provided, awaiting carrier resolution.",
  },
  customerInput: {
    messageText: "“Where is my order?”",
    sentiment: "Neutral",
    attachmentsCount: 1,
    preferredResolution: "Delivery update",
  },
  slaOverview: {
    dispatch: "On Track",
    transit: "At Risk",
    delivery: "Pending",
    overall: "At Risk",
  },
  exceptionHistory: [
    {
      dateTime: "Apr 20, 05:42 PM",
      exception: "Severe Weather Delay",
      source: "FedEx",
      status: "Open",
    },
    {
      dateTime: "Apr 20, 09:11 AM",
      exception: "Delay Predicted",
      source: "Proactive",
      status: "Resolved",
    },
    {
      dateTime: "Apr 19, 11:02 PM",
      exception: "Pickup Rescheduled",
      source: "FedEx",
      status: "Resolved",
    },
  ],
  repeatIssueAnalysis: {
    repeatIssue30d: "Yes",
    frequency: 2,
    lastOccurrence: "Apr 08, 2024",
    pattern: "Carrier delay - FedEx Ground",
  },
  customerSatisfaction: {
    previousCsat: "★★★★★ (4)",
    thisCaseCsat: "—",
    npsImpact: "Low Risk",
  },
  notes: {
    internalNote: "Customer is VIP. Monitor closely for carrier resolution update.",
  },
};

export const MOCK_OPERATIONS_RAIL_DATA: DeliveryOperationsRailData = {
  healthScore: 92,
  scoreLegend: [
    { label: "Excellent", range: "61–100", color: "text-emerald-600" },
    { label: "Good", range: "41–60", color: "text-blue-600" },
    { label: "Fair", range: "21–40", color: "text-amber-600" },
    { label: "Poor", range: "0–20", color: "text-red-600" },
  ],

  caseSummary: {
    open: 346,
    closed: 12,
    slaAtRisk: 29,
    escalated: 17,
    unassigned: 18,
  },

  fulfilmentSummary: {
    warehouse: { connected: 65, pending: 12, slaAtRisk: 16 },
    supplier: { connected: 58, pending: 8, slaAtRisk: 13 },
  },

  shipmentSummary: {
    inTransit: 64,
    delayed: 31,
    outForDelivery: 27,
    exception: 5,
    attemptedDelivery: 7,
  },

  dependencySummary: {
    open: 38,
    pending: 24,
    resolved: 31,
    overdue: 11,
  },

  quickLinks: [
    { label: "Awaiting Dispatch", count: 82, variant: "warning" },
    { label: "Shipment Delay", count: 64, variant: "danger" },
    { label: "Dispatch Delay", count: 27, variant: "warning" },
    { label: "Tracking Issues", count: 38, variant: "info" },
    { label: "Failed Delivery", count: 27, variant: "danger" },
    { label: "SLA At Risk", count: 29, variant: "warning" },
    { label: "Escalated", count: 17, variant: "danger" },
    { label: "Unassigned", count: 18, variant: "neutral" },
  ],
};
