"use client";
import React,{useCallback,useDeferredValue,useEffect,useMemo,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import toast from "react-hot-toast";
import type {CategoryFilterState,CategoryItem,CategoryManagementData} from "@/types/categoryManagement";
import {createCategory,exportCategories,getCategory,getCategoryManagement,importCategoryMapping,mergeCategory,moveCategory,updateCategory} from "@/services/api/categoryManagement";
import {CategoryHeader} from "./components/CategoryHeader";import {CategoryBusinessContext} from "./components/CategoryBusinessContext";import {CategoryKpiGrid} from "./components/CategoryKpiGrid";import {CategoryStatusTabs} from "./components/CategoryStatusTabs";import {CategoryFilters} from "./components/CategoryFilters";import {CategoryHierarchyTree} from "./components/CategoryHierarchyTree";import {CategoryTable} from "./components/CategoryTable";import {SelectedCategoryOverview} from "./components/SelectedCategoryOverview";
import {CategoryFormDrawer} from "./modals/CategoryFormDrawer";import {ImportCategoryMappingModal} from "./modals/ImportCategoryMappingModal";import {MoveCategoryModal} from "./modals/MoveCategoryModal";import {MergeCategoryModal} from "./modals/MergeCategoryModal";
import {CategoryLowerDashboards} from "./components/CategoryLowerDashboards";import {TaxonomyIntelligenceSidebar} from "./components/TaxonomyIntelligenceSidebar";

const blank:CategoryFilterState={searchQuery:"",department:"all",parentCategory:"all",categoryLevel:"all",status:"all",requiredAttributes:"all",channelEligibility:"all",complianceStatus:"all",owner:"all",updatedDate:"all"};
export function CategoryManagementView(){
 const router=useRouter(),searchParams=useSearchParams();const [data,setData]=useState<CategoryManagementData|null>(null),[filters,setFilters]=useState(blank),[activeTab,setActiveTab]=useState(searchParams?.get("tab")||"all"),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<CategoryItem|null>(null),[selectedIds,setSelectedIds]=useState<string[]>([]),[selectedNode,setSelectedNode]=useState("");

 const [drawer,setDrawer]=useState(false),[mode,setMode]=useState<"create"|"edit">("create"),[drawerData,setDrawerData]=useState<CategoryItem|null>(null),[importOpen,setImportOpen]=useState(false),[moveTarget,setMoveTarget]=useState<CategoryItem|null>(null),[mergeTarget,setMergeTarget]=useState<CategoryItem|null>(null);
 const deferredSearch=useDeferredValue(filters.searchQuery);const params=useMemo(()=>({page,pageSize:25,search:deferredSearch||undefined,parentId:filters.parentCategory,status:filters.status==="Active"?"active":filters.status==="Inactive"?"inactive":undefined,level:filters.categoryLevel,requiredAttributes:filters.requiredAttributes,scope:["duplicates","empty"].includes(activeTab)?activeTab:undefined}),[filters,deferredSearch,page,activeTab]);
 const load=useCallback(async(silent=false)=>{if(!silent)setBusy(true);const controller=new AbortController();try{const next=await getCategoryManagement(params,controller.signal);setData(next);setError(null);setSelected(old=>old?next.categories.data.find(x=>x.id===old.id)||next.categories.data[0]||null:next.categories.data[0]||null);}catch(e){setError(e instanceof Error?e.message:"Unable to load categories.");}finally{setBusy(false)}return()=>controller.abort()},[params]);
 useEffect(()=>{void load();},[load]);useEffect(()=>{const id=setInterval(()=>void load(true),30000);return()=>clearInterval(id)},[load]);
 const unavailable=()=>toast.error("Unavailable: this installation has no authoritative field for that category capability.");
 const change=(field:keyof CategoryFilterState,value:string)=>{if(["department","channelEligibility","complianceStatus","owner","updatedDate"].includes(field)){unavailable();return;}setPage(1);setFilters(p=>({...p,[field]:value}));};
 const tab=(id:string)=>{if(["draft","review","archived"].includes(id)){unavailable();return;}if(id==="uncategorized"){toast("The products schema requires category_id, so an uncategorized queue cannot exist in this installation.");return;}setPage(1);setActiveTab(id);setFilters(p=>({...p,status:id==="active"?"Active":id==="inactive"?"Inactive":"all"}));};
 const payload=(v:Partial<CategoryItem>)=>({name:v.categoryName?.trim(),slug:v.slug?.trim(),description:v.description||null,parent_id:v.parentId?Number(v.parentId):null,sort_order:0,status:v.status==="Inactive"?"inactive":"active"});
 const save=async(v:Partial<CategoryItem>)=>{try{if(mode==="create")await createCategory(payload(v));else if(drawerData)await updateCategory(drawerData.id,payload(v));toast.success(mode==="create"?"Category created.":"Category updated.");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to save category.");throw e;}};
 const openCreate=(parent?:CategoryItem)=>{setMode("create");setDrawerData(parent||null);setDrawer(true)};const openEdit=(c:CategoryItem)=>{setMode("edit");setDrawerData(c);setDrawer(true)};
 if(!data&&busy)return <div className="p-8 text-sm text-gray-500">Loading authoritative category data…</div>;
 if(!data)return <div className="m-6 rounded border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><p className="font-bold">Category management could not load.</p><p>{error}</p><button onClick={()=>void load()} className="mt-3 rounded bg-[#741d35] px-3 py-2 text-white">Retry</button></div>;
 const categories=data.categories.data,parents=data.options.parents;
 return <div className="w-full flex flex-col min-h-screen bg-[#f8fafc] p-4 sm:p-6 pb-24">
  <CategoryHeader canManage={data.capabilities.canManage===true} canImport={data.capabilities.canImport===true} canExport={data.capabilities.canExport===true} selectedCount={selectedIds.length} onExportReport={()=>void exportCategories(params).catch(e=>toast.error(e.message))} onImportMapping={()=>setImportOpen(true)} onBulkActions={unavailable} onCreateCategory={()=>openCreate()}/>
  <CategoryBusinessContext lastSyncedTime={new Date(data.lastSyncedAt).toLocaleString()} onRefresh={()=>void load()} isRefreshing={busy}/>
  {error&&<div className="mb-3 rounded border border-amber-200 bg-amber-50 p-2 text-xs text-amber-800">Last refresh failed: {error}. Displaying the last successful response.</div>}
  <CategoryKpiGrid kpis={data.kpis} onSelectKpi={key=>key==="unsupported"?unavailable():tab(key)}/><CategoryStatusTabs tabs={data.tabs} activeTabId={activeTab} onSelectTab={tab}/>
  <CategoryFilters filters={filters} parentOptions={parents} onChange={change} onClearAll={()=>{setFilters(blank);setActiveTab("all");setSelectedIds([]);setPage(1)}} onMoreFilters={unavailable} onSaveView={unavailable} onRefresh={()=>void load()} isRefreshing={busy}/>
  <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1fr)_280px] gap-4 items-start min-w-0"><div className="min-w-0 flex flex-col gap-6"><div className="grid grid-cols-1 lg:grid-cols-12 gap-4 items-start min-w-0">
   <div className="lg:col-span-3"><CategoryHierarchyTree tree={data.tree} selectedNodeId={selectedNode} onSelectNode={n=>{setSelectedNode(n.id);const local=categories.find(c=>c.id===n.id);if(local)setSelected(local);else void getCategory(n.id).then(setSelected).catch(e=>toast.error(e.message))}} onAddChild={n=>{const local=categories.find(c=>c.id===n?.id);if(local)openCreate(local);else if(n)void getCategory(n.id).then(openCreate).catch(e=>toast.error(e.message));else openCreate()}} onMoveNode={()=>selected?setMoveTarget(selected):undefined} onMergeNode={()=>selected?setMergeTarget(selected):undefined}/></div>
   <div className="lg:col-span-6 min-w-0"><CategoryTable categories={categories} pagination={data.categories} onPageChange={setPage} selectedCategoryIds={selectedIds} selectedCategory={selected} onSelectCategory={setSelected} onToggleSelectRow={id=>setSelectedIds(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id])} onToggleSelectAll={()=>setSelectedIds(selectedIds.length===categories.length?[]:categories.map(c=>c.id))} onEditCategory={openEdit} onManageAttributes={()=>router.push("/admin/catalogue/attributes")} onViewProducts={c=>router.push(`/admin/catalogue/products?categoryId=${c.id}`)} onAddChild={openCreate} onMoveCategory={setMoveTarget} onMergeCategory={setMergeTarget} onArchiveCategory={unavailable}/></div>
   <div className="lg:col-span-3"><SelectedCategoryOverview category={selected} onEditCategory={openEdit} onManageAttributes={()=>router.push("/admin/catalogue/attributes")} onViewProducts={c=>router.push(`/admin/catalogue/products?categoryId=${c.id}`)}/></div>
  </div><CategoryLowerDashboards data={data} onMergeDuplicate={(sourceId,targetId)=>void mergeCategory(sourceId,targetId).then(()=>{toast.success("Duplicate categories merged.");return load()}).catch(e=>toast.error(e.message))}/></div>
  <aside className="sticky top-4"><TaxonomyIntelligenceSidebar data={data} onSelectQueue={tab}/></aside></div>
  <CategoryFormDrawer isOpen={drawer} onClose={()=>setDrawer(false)} initialData={drawerData} mode={mode} onSave={save} parentOptions={parents}/>
  <ImportCategoryMappingModal isOpen={importOpen} onClose={()=>setImportOpen(false)} onImport={async f=>(await importCategoryMapping(f)).data.updated}/>
  <MoveCategoryModal isOpen={!!moveTarget} onClose={()=>setMoveTarget(null)} category={moveTarget} parentOptions={parents} onConfirmMove={(c,p)=>void moveCategory(c.id,p||null).then(()=>{toast.success("Category moved.");setMoveTarget(null);return load()}).catch(e=>toast.error(e.message))}/>
  <MergeCategoryModal isOpen={!!mergeTarget} onClose={()=>setMergeTarget(null)} sourceCategory={mergeTarget} categoryOptions={parents} onConfirmMerge={(c,t)=>void mergeCategory(c.id,t).then(()=>{toast.success("Category merged.");setMergeTarget(null);return load()}).catch(e=>toast.error(e.message))}/>
 </div>;
}
