import { ConversationQueueItem, TimelineMessage, SuggestedReplyData, IntelligenceData } from "./types";

export const MOCK_CONVERSATIONS: ConversationQueueItem[] = [
  {
    id: "CON-2024-0512482",
    reference: "CON-2024-0512482",
    customerId: "CUS-2024-0512482",
    customerName: "Elena Rodriguez",
    customerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    isVip: true,
    country: "Sri Lanka",
    channel: "in-app-chat",
    channelLabel: "In-App Chat",
    priority: "High",
    sentiment: "Concerned",
    unreadCount: 2,
    slaRemaining: "10m",
    isSlaAtRisk: true,
    assignedAgentName: "Aneesh Perera",
    assignedAgentAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    lastActivityAt: "10:14 AM",
    linkedCaseId: "CS-2024-0092561",
    status: "in-progress",
    statusLabel: "In Progress",
    resolutionConfidence: 76,
  },
  {
    id: "CON-2024-0789015",
    reference: "CON-2024-0789015",
    customerId: "CUS-2024-0789015",
    customerName: "Jake Wilson",
    customerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    isVip: false,
    country: "Sri Lanka",
    channel: "whatsapp",
    channelLabel: "WhatsApp",
    priority: "High",
    sentiment: "Concerned",
    unreadCount: 3,
    slaRemaining: "10m",
    isSlaAtRisk: true,
    assignedAgentName: "Aneesh Perera",
    assignedAgentAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    lastActivityAt: "9:32 AM",
    linkedCaseId: "CS-2024-0092562",
    status: "waiting-for-agent",
    statusLabel: "Waiting for Agent",
    resolutionConfidence: 82,
  },
  {
    id: "CON-2026-0098756",
    reference: "CON-2026-0098756",
    customerId: "CUS-2026-0098756",
    customerName: "Nadeesh Silva",
    customerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
    isVip: false,
    country: "Sri Lanka",
    channel: "email",
    channelLabel: "Email",
    priority: "Normal",
    sentiment: "Neutral",
    unreadCount: 1,
    slaRemaining: "1h 12m",
    isSlaAtRisk: false,
    assignedAgentName: "Dinusha Perera",
    assignedAgentAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
    lastActivityAt: "9:15 AM",
    linkedCaseId: "CS-2024-0092563",
    status: "in-progress",
    statusLabel: "In Progress",
    resolutionConfidence: 90,
  },
  {
    id: "CON-2024-0643110",
    reference: "CON-2024-0643110",
    customerId: "CUS-2024-0643110",
    customerName: "Olivia Perez",
    customerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150",
    isVip: true,
    country: "Sri Lanka",
    channel: "web",
    channelLabel: "Web",
    priority: "High",
    sentiment: "Concerned",
    unreadCount: 1,
    slaRemaining: "22m",
    isSlaAtRisk: true,
    assignedAgentName: "Dinusha Perera",
    assignedAgentAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
    lastActivityAt: "9:03 AM",
    linkedCaseId: "CS-2024-0092564",
    status: "in-progress",
    statusLabel: "In Progress",
    resolutionConfidence: 68,
  },
  {
    id: "CON-2024-0551567",
    reference: "CON-2024-0551567",
    customerId: "CUS-2024-0551567",
    customerName: "Sarah Chen",
    customerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150",
    isVip: false,
    country: "Sri Lanka",
    channel: "in-app-chat",
    channelLabel: "In-App Chat",
    priority: "Low",
    sentiment: "Neutral",
    unreadCount: 0,
    slaRemaining: "Completed",
    isSlaAtRisk: false,
    assignedAgentName: "Dinusha Perera",
    assignedAgentAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
    lastActivityAt: "Yesterday",
    linkedCaseId: "CS-2024-0092565",
    status: "waiting-for-customer",
    statusLabel: "Waiting for Customer",
    resolutionConfidence: 95,
  },
  {
    id: "CON-2024-0176542",
    reference: "CON-2024-0176542",
    customerId: "CUS-2024-0176542",
    customerName: "Ravi Kumar",
    customerAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150",
    isVip: false,
    country: "Sri Lanka",
    channel: "instagram",
    channelLabel: "Instagram",
    priority: "High",
    sentiment: "Concerned",
    unreadCount: 1,
    slaRemaining: "45m",
    isSlaAtRisk: false,
    assignedAgentName: "Dinusha Perera",
    assignedAgentAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
    lastActivityAt: "Yesterday",
    linkedCaseId: "CS-2024-0092566",
    status: "in-progress",
    statusLabel: "In Progress",
    resolutionConfidence: 74,
  },
];

export const MOCK_TIMELINE_MESSAGES: Record<string, TimelineMessage[]> = {
  "CON-2024-0512482": [
    {
      id: "msg-1",
      type: "customer",
      senderName: "Elena Rodriguez",
      senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
      timestamp: "10:01 AM",
      content:
        "It's been 5 days and my order still shows “Awaiting Fulfillment”. I haven't received any updates or tracking number. Please check what's happening and let me know when I can expect my order.",
    },
    {
      id: "msg-2",
      type: "system",
      senderName: "System",
      timestamp: "10:03 AM",
      content: "Case CS-2024-0092561 linked to this conversation.",
    },
    {
      id: "msg-3",
      type: "agent",
      senderName: "Aneesh Perera",
      senderAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
      timestamp: "10:04 AM",
      content:
        "Thanks for your patience. We're checking the dispatch status with the fulfillment team and will update you shortly.",
    },
    {
      id: "msg-4",
      type: "internal_note",
      senderName: "Internal Note",
      timestamp: "10:05 AM",
      content:
        "Carrier assignment still missing. Supplier fulfillment confirmed but pickup not dispatched.",
      isPrivateNote: true,
    },
    {
      id: "msg-5",
      type: "customer",
      senderName: "Elena Rodriguez",
      senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
      timestamp: "10:07 AM",
      content: "Please let me know today because I need the order urgently.",
    },
    {
      id: "msg-6",
      type: "escalation",
      senderName: "System",
      timestamp: "10:08 AM",
      content: "Internal escalation created",
      badges: [
        { label: "P2 - High", variant: "danger" },
        { label: "sla_rst + 30m elapsed", variant: "info" },
        { label: "sla_unc + 18m remaining", variant: "warning" },
      ],
    },
  ],
};

export const MOCK_SUGGESTED_REPLY: SuggestedReplyData = {
  id: "sug-1",
  confidencePercent: 75,
  text:
    "Hi Elena, thank you for reaching out and I understand how important this order is. I've escalated this with our fulfillment team and I'll share an update for you before 4:00 PM today.",
};

export const MOCK_INTELLIGENCE: IntelligenceData = {
  healthScore: 88,
  responseSlaPercent: 92,
  resolutionStabilityPercent: 76,
  resolutionConfidencePercent: 74,
  communicationContinuityPercent: 91,

  customerContext: {
    name: "Elena Rodriguez",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    isVip: true,
    country: "Sri Lanka",
    openCases: 2,
    recentCases: 1,
    preferredChannel: "In-App Chat",
    repeatContactRate: "Low",
  },

  linkedCase: {
    caseId: "CS-2024-0092561",
    priority: "High",
    subject: "Order not delivered — delayed dispatch",
    assignedAgent: "Aneesh Perera",
    orderId: "ORD-2024-0512482",
    firstResponse: "Completed in 6m",
    status: "In Progress",
  },

  relatedRecords: {
    orderId: "ORD-2024-0098761",
    shipmentId: "SHP-2024-0127993",
    productName: "Radiance Vitamin C Serum — 30 ml",
    supplierName: "Luxe Distribution Pvt Ltd",
  },

  messageIntelligence: {
    currentSentiment: "Concerned",
    tone: "Neutral",
    detectedIntent: "Delivery Status Request",
    urgency: "High",
    resolutionRisk: "Medium",
  },

  slaPrognosis: {
    firstResponse: "Completed in 6m",
    nextResponseDue: "18m",
    resolutionTarget: "30m remaining",
    slaPolicy: "SUP-SLA-v3",
    status: "At Risk",
  },

  routingSummary: {
    queue: "Order & Delivery",
    team: "Customer Operations",
    agent: "Aneesh Perera",
    workload: "70%",
    availability: "Available",
  },
};
