import { ComplaintItem, ComplaintDetailsData, ComplaintOperationsRailData } from "./types";

export const MOCK_COMPLAINTS: ComplaintItem[] = [
  {
    id: "CMP-2025-00284",
    reference: "CMP-2025-00284",
    relatedCaseId: "CS-2025-008241",
    customerName: "Elena Rodriguez",
    customerId: "CUS-2025-008241",
    isVip: true,
    severity: "High",
    status: "Escalated",
    category: "Delivery Failure",
    issueType: "Shipment Not Dispatched",
    rootCause: "Carrier Assignment Failure",
    escalationLevel: "Support Manager",
    sentiment: "Concerned",
    customerImpact: "High",
    financialImpact: "Medium",
    slaStatus: "At Risk",
    recoveryStatus: "Active",
    remedyStatus: "Pending Approval",
    assignedOwner: "Anupa Perera",
    assignedTeam: "Customer Operations",
    relatedOrderId: "ORD-2025-000241",
    supplierName: "Lane Distribution (Pvt) Ltd",
    lastActivityAt: "10:24 AM",
    age: "2d 4h",
  },
  {
    id: "CMP-2025-00283",
    reference: "CMP-2025-00283",
    relatedCaseId: "CS-2025-008253",
    customerName: "Julia Vance",
    customerId: "CUS-2025-008253",
    isVip: true,
    severity: "High",
    status: "Escalated",
    category: "Payment Issue",
    issueType: "Payment Gateway Failure",
    rootCause: "Payment Gateway Failure",
    escalationLevel: "Team Lead",
    sentiment: "Frustrated",
    customerImpact: "High",
    financialImpact: "High",
    slaStatus: "Breached",
    recoveryStatus: "Active",
    remedyStatus: "Pending Approval",
    assignedOwner: "Dilani Perera",
    assignedTeam: "Payments Team",
    relatedOrderId: "ORD-2025-000180",
    supplierName: "NeePay",
    lastActivityAt: "9:52 AM",
    age: "3d 7h",
  },
  {
    id: "CMP-2025-00282",
    reference: "CMP-2025-00282",
    relatedCaseId: "CS-2025-008227",
    customerName: "Nimal Siriwardana",
    customerId: "CUS-2025-008227",
    isVip: false,
    severity: "Critical",
    status: "Executive Review",
    category: "Product Safety",
    issueType: "Skin Irritation Incident",
    rootCause: "Product Safety Issue",
    escalationLevel: "Operations Director",
    sentiment: "Frustrated",
    customerImpact: "High",
    financialImpact: "High",
    slaStatus: "At Risk",
    recoveryStatus: "Active",
    remedyStatus: "Pending Approval",
    assignedOwner: "Nimal Perera",
    assignedTeam: "Product Safety Team",
    relatedOrderId: "ORD-2025-000292",
    supplierName: "Radiance Labs",
    lastActivityAt: "9:02 AM",
    age: "1d 1h",
  },
  {
    id: "CMP-2025-00281",
    reference: "CMP-2025-00281",
    relatedCaseId: "CS-2025-008227",
    customerName: "Sachini De Silva",
    customerId: "CUS-2025-008227",
    isVip: false,
    severity: "Medium",
    status: "In Progress",
    category: "Authenticity",
    issueType: "Counterfeit Concern",
    rootCause: "Counterfeit Concern",
    escalationLevel: "Supplier Manager",
    sentiment: "Concerned",
    customerImpact: "Medium",
    financialImpact: "Low",
    slaStatus: "Within SLA",
    recoveryStatus: "Active",
    remedyStatus: "Pending Approval",
    assignedOwner: "Sachini De Silva",
    assignedTeam: "Returns Support Team",
    relatedOrderId: "ORD-2025-000281",
    supplierName: "Glow Essentials",
    lastActivityAt: "8:47 AM",
    age: "2d 3h",
  },
  {
    id: "CMP-2025-00280",
    reference: "CMP-2025-00280",
    relatedCaseId: "CS-2025-008210",
    customerName: "Chamara Silva",
    customerId: "CUS-2025-008210",
    isVip: false,
    severity: "High",
    status: "Waiting Customer",
    category: "Refund Failure",
    issueType: "Refund Policy Misunderstood",
    rootCause: "Refund Policy Misunderstood",
    escalationLevel: "Team Lead",
    sentiment: "Concerned",
    customerImpact: "Medium",
    financialImpact: "High",
    slaStatus: "At Risk",
    recoveryStatus: "Pending",
    remedyStatus: "Pending Approval",
    assignedOwner: "Dilani Fernando",
    assignedTeam: "Logistics Team",
    relatedOrderId: "ORD-2025-000190",
    supplierName: "Lane Distribution (Pvt) Ltd",
    lastActivityAt: "Yesterday",
    age: "2d 3h",
  },
  {
    id: "CMP-2025-00279",
    reference: "CMP-2025-00279",
    relatedCaseId: "CS-2025-008175",
    customerName: "Rashmika Silva",
    customerId: "CUS-2025-008175",
    isVip: false,
    severity: "Medium",
    status: "In Progress",
    category: "Delivery Failure",
    issueType: "Address Validation Error",
    rootCause: "Address Validation Error",
    escalationLevel: "Support Agent",
    sentiment: "Concerned",
    customerImpact: "Medium",
    financialImpact: "Low",
    slaStatus: "Within SLA",
    recoveryStatus: "Active",
    remedyStatus: "Pending Approval",
    assignedOwner: "Udara Fernando",
    assignedTeam: "Logistics Team",
    relatedOrderId: "ORD-2025-000181",
    supplierName: "Koombiyo Delivery",
    lastActivityAt: "Yesterday",
    age: "1d 5h",
  },
];

export const MOCK_COMPLAINT_DETAILS: ComplaintDetailsData = {
  complaint: MOCK_COMPLAINTS[0],
  customerStatement: {
    text:
      "I have contacted support several times. I need this resolved immediately. My order has still not been dispatched and I have not received a clear update.",
    tags: ["VIP Customer", "Repeat Contact", "Delivery Issue"],
  },
  lifecycle: [
    { label: "Complaint Raised", status: "completed" },
    { label: "Acknowledged", status: "completed" },
    { label: "Owner Assigned", status: "completed" },
    { label: "Escalation Opened", status: "completed" },
    { label: "Root Cause Confirmed", status: "completed" },
    { label: "Recovery Plan", status: "in-progress" },
    { label: "Remedy Approved", status: "completed" },
    { label: "Customer Offer", status: "completed" },
    { label: "Customer Acceptance", status: "pending" },
    { label: "Resolved", status: "pending" },
    { label: "Closed", status: "pending" },
  ],
  escalation: {
    currentLevel: "Support Manager",
    previousLevel: "Team Lead",
    escalationDue: "1h 30m",
    reason: "Repeat contact + unresolved delivery failure",
    hierarchy: [
      { name: "Support Agent", isCurrent: false },
      { name: "Team Lead", isCurrent: false },
      { name: "Support Manager", isCurrent: true },
      { name: "Operations Director", isCurrent: false },
      { name: "Executive Director", isCurrent: false },
    ],
    dependencies: ["Finance", "Logistics", "Compliance", "Supplier Operations"],
  },
  rootCauseAnalysis: {
    primary: "Carrier Assignment Failure",
    domain: "Logistics",
    repeatFailure: "Yes",
    similarComplaintsCount: 5,
    confidencePercent: 94,
    factors: [
      { label: "Supplier handoff delay", percent: 31 },
      { label: "Manual carrier assignment", percent: 22 },
      { label: "Missed address verification", percent: 18 },
      { label: "Platform follow-up", percent: 12 },
      { label: "Repeat failure", percent: 11 },
      { label: "Similar complaints", percent: 10 },
    ],
  },
  recoveryPlan: {
    slaState: "Completed",
    steps: [
      { stepNumber: 1, label: "Confirm shipment details", status: "Completed" },
      { stepNumber: 2, label: "Confirm carrier assignment", status: "Completed" },
      { stepNumber: 3, label: "Expedite dispatch", status: "In Progress" },
      { stepNumber: 4, label: "Send customer update", status: "In Progress" },
      { stepNumber: 5, label: "Offer approved goodwill remedy", status: "Pending" },
      { stepNumber: 6, label: "Confirm delivery", status: "Pending" },
      { stepNumber: 7, label: "Confirm customer satisfaction", status: "Pending" },
      { stepNumber: 8, label: "Close complaint", status: "Pending" },
    ],
  },
  remedyApproval: {
    approvedValue: "LKR 2,500",
    approvalAuthority: "Team Lead",
    approvedBy: "Anupa Perera",
    approvalTime: "Jul 22, 2025 10:15 AM",
  },
  customerRecoveryOffer: {
    offerType: "Delivery fee refund + goodwill token",
    status: "Draft / Awaiting Approval",
    sendWhen: "Approved",
    customerState: "response is pending",
  },
  customerAcceptance: {
    states: [
      { label: "Not Sent", isActive: false },
      { label: "Awaiting Response", isActive: true, variant: "warning" },
      { label: "Accepted", isActive: false },
      { label: "Partially Accepted", isActive: false },
      { label: "Rejected", isActive: false },
      { label: "No Response", isActive: false },
    ],
  },
  relatedSupportHistory: {
    linkedCaseId: "CS-2025-008241",
    conversationId: "CS-2025-000575",
    previousComplaintId: "CMP-2025-000111",
  },
  relatedOperationalRecords: {
    orderId: "ORD-2025-000241",
    shipmentId: "SHP-2025-002095",
    paymentId: "PAY-2025-000163",
    returnId: "None",
    productName: "Radiance Vitamin C Serum — 30 ml",
    supplierName: "Lane Distribution (Pvt) Ltd",
    carrierName: "Koombiyo Delivery",
  },
  crossModuleDependencies: [
    { module: "Logistics", status: "Pending", team: "Logistics Team", slaRemaining: "1h 40m" },
    { module: "Supplier", status: "Completed", team: "Supplier Ops" },
    { module: "Finance", status: "Awaiting Approval", team: "Finance Review", slaRemaining: "2h 15m" },
    { module: "Compliance", status: "Not Required", team: "Compliance Team" },
  ],
  complaintSla: {
    acknowledgementTarget: "30m",
    acknowledgementElapsed: "13m",
    investigationTarget: "2h",
    investigationElapsed: "2d 02m",
    recoveryPlanTarget: "4h",
    recoveryPlanElapsed: "1d 10m",
    customerUpdateInterval: "2h",
    currentSlaState: "At Risk",
    policy: "SUP-COMP-v5",
  },
  reopenedQueueSummary: {
    reopenedCount: 14,
    customerSupportFailureCount: 9,
    repeatFailureCount: 8,
    executiveEscalationCount: 3,
  },
  executiveReviewQueue: [
    {
      id: "CMP-2025-00282",
      severity: "Critical",
      reason: "Product safety risk",
      businessImpact: "High",
      owner: "Nimal Perera",
      age: "2d 1h",
    },
    {
      id: "CMP-2025-00277",
      severity: "Critical",
      reason: "Repeated SLA breach",
      businessImpact: "High",
      owner: "Anupa Perera",
      age: "2d 4h",
    },
    {
      id: "CMP-2025-00275",
      severity: "High",
      reason: "Executive escalation",
      businessImpact: "Medium",
      owner: "Dilani Perera",
      age: "3d 1h",
    },
  ],
  evidenceAttachments: [
    { category: "Screenshots", count: 3 },
    { category: "Email", count: 4 },
    { category: "Call Transcript", count: 1 },
    { category: "Receipt", count: 1 },
    { category: "Delivery Tracking", count: 2 },
    { category: "Supplier Response", count: 1 },
    { category: "Investigation Note", count: 1 },
  ],
};

export const MOCK_OPERATIONS_RAIL_DATA: ComplaintOperationsRailData = {
  healthScore: 91,
  responseSlaPercent: 92,
  resolutionStabilityPercent: 77,
  customerConfidencePercent: 74,
  recoveryEffectivenessPercent: 90,
  communicationContinuityPercent: 91,

  complaintSummary: {
    open: 184,
    critical: 12,
    escalated: 37,
    executive: 6,
    reopened: 14,
  },

  recoverySummary: {
    activePlans: 42,
    pending: 19,
    completedToday: 18,
    customerAccepted: 31,
    customerRejected: 9,
  },

  remedySummary: {
    pendingApproval: 18,
    approved: 24,
    rejected: 3,
    cashRefund: 7,
    goodwill: 22,
  },

  slaSummary: {
    withinTargetPercent: 91,
    atRisk: 17,
    breached: 8,
    avgComplaintAge: "1.8d",
  },

  rootCauseSummary: [
    { category: "Logistics", percent: 31 },
    { category: "Supplier", percent: 22 },
    { category: "Payment", percent: 18 },
    { category: "Product", percent: 12 },
    { category: "Process", percent: 11 },
    { category: "Other", percent: 10 },
  ],

  quickQueues: [
    { label: "Critical Complaints", count: 12, variant: "danger" },
    { label: "Escalation Review", count: 6, variant: "warning" },
    { label: "SLA At Risk", count: 17, variant: "warning" },
    { label: "Remedy Approval", count: 18, variant: "info" },
    { label: "Customer Rejected", count: 9, variant: "danger" },
    { label: "Reopened", count: 14, variant: "warning" },
    { label: "Compliance Escalations", count: 6, variant: "info" },
  ],
};
