"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {AlertTriangle,ArrowDownUp,BadgeDollarSign,CalendarDays,CheckCircle2,ChevronDown,ChevronLeft,ChevronRight,Columns3,Download,Filter,HeartPulse,Info,LockKeyhole,MoreVertical,Plus,RefreshCw,Save,Search,ShieldAlert,SlidersHorizontal,Upload,X,XCircle} from "lucide-react";
import {Bar,CartesianGrid,Cell,ComposedChart,Legend,Line,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import toast from "react-hot-toast";
import {fetchMarketplaceCommissions,recordCommissionPreviewAction} from "@/services/api/marketplaceCommissionsService";
import styles from "./marketplace-commission-management.module.css";

const tabs=["All Rules","Active","Scheduled","Pending Approval","Draft","Expiring","Expired","Rejected","Conflicts","Exceptions"];
const counts={"Pending Approval":7,Draft:9,Expiring:8,Expired:14,Rejected:3,Conflicts:4,Exceptions:11};
const filters=["Rule Status","Rule Type","Business Unit","Sales Channel","Marketplace","Seller","Product Category","Approval Status","Conflict Status"];

export function MarketplaceCommissionManagementView(){
  const router=useRouter();
  const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [refreshing,setRefreshing]=useState(false);const [active,setActive]=useState("All Rules");const [query,setQuery]=useState("");const [selected,setSelected]=useState([]);const [modal,setModal]=useState(null);const [menu,setMenu]=useState(null);const [page,setPage]=useState(1);const [period,setPeriod]=useState("Monthly");const [distribution,setDistribution]=useState("Rule Type");const menuRef=useRef(null);
  const load=async(refresh=false)=>{try{setError("");refresh?setRefreshing(true):setLoading(true);const result=await fetchMarketplaceCommissions();setData(result);if(refresh)toast.success("Commission data refreshed from the frontend fixture")}catch(e){if(e.name!=="AbortError")setError("Marketplace commission data could not be loaded.")}finally{setLoading(false);setRefreshing(false)}};
  useEffect(()=>{const controller=new AbortController();void fetchMarketplaceCommissions(controller.signal).then(setData).catch(e=>{if(e.name!=="AbortError")setError("Marketplace commission data could not be loaded.")}).finally(()=>setLoading(false));return()=>controller.abort()},[]);
  useEffect(()=>{const close=e=>{if(menuRef.current&&!menuRef.current.contains(e.target))setMenu(null)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
  const rows=useMemo(()=>data?.rules.filter(row=>{const match=Object.values(row).join(" ").toLowerCase().includes(query.toLowerCase());const tab=active==="All Rules"||row.status===active||row.approval===active||(active==="Conflicts"&&row.conflict!=="Clear")||(active==="Exceptions"&&row.type.includes("Exception"))||(active==="Expiring"&&row.to.includes("2026"));return match&&tab})??[],[data,query,active]);
  const toggleAll=()=>setSelected(selected.length===rows.length?[]:rows.map(row=>row.id));
  const confirm=async(type,reason="")=>{await recordCommissionPreviewAction(type,selected);setModal(null);toast.success(`${type} saved in local preview state (not server-persisted)`) };
  const handleRuleAction=value=>{const prefix="Edit Rule: ";if(value.startsWith(prefix)){const row=data.rules.find(item=>item.name===value.slice(prefix.length));if(row){router.push(`/admin/marketplace/commissions/${encodeURIComponent(row.id)}/edit`);return}}setModal(value)};
  const exportReport=()=>{const lines=[["Rule","Rule ID","Type","Rate","Approval","Conflict","Status"],...data.rules.map(row=>[row.name,row.id,row.type,row.rate,row.approval,row.conflict,row.status])];const blob=new Blob([lines.map(line=>line.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="marketplace-commissions.csv";a.click();URL.revokeObjectURL(url);toast.success("Commission report exported")};
  if(loading&&!data)return <Loading/>;
  if(error&&!data)return <section className={styles.state} role="alert"><ShieldAlert/><h1>Marketplace Commission Management</h1><p>{error}</p><button onClick={()=>void load()}>Retry</button></section>;
  if(!data)return <section className={styles.state}><BadgeDollarSign/><h1>No commission data available</h1></section>;
  if(data.permissions?.canView===false)return <section className={styles.state}><LockKeyhole/><h1>Permission required</h1><p>Your role cannot access commission management.</p></section>;
  return <main className={styles.page}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><span>Commissions</span></nav>
    <header className={styles.header}><div><h1>Marketplace Commission Management</h1><p>Manage commission structures, seller rates, category and channel rules, exceptions, approvals and settlement impact.</p></div><div className={styles.headerActions}><button onClick={exportReport}><Download/>Export Commission Report</button><button onClick={()=>setModal("Compare Rules")}><RefreshCw/>Compare Rules</button><button disabled={!selected.length} onClick={()=>setModal("Bulk Actions")}><SlidersHorizontal/>Bulk Actions<ChevronDown/></button><button className={styles.primary} onClick={()=>router.push("/admin/marketplace/commissions/create")}><Plus/>Create Commission Rule</button></div></header>
    <Context data={data}/><div className={styles.live}><i/>Live data <small>Last updated: {data.lastUpdated}</small><button aria-label="Refresh commissions" disabled={refreshing} onClick={()=>void load(true)}><RefreshCw className={refreshing?styles.spin:""}/></button></div>
    <div className={styles.layout}><div className={styles.workspace}>
      <section className={styles.kpis}>{data.kpis.map((kpi,index)=><article key={kpi.label}><span><BadgeDollarSign/></span><div><small>{kpi.label}</small><strong>{kpi.value}</strong><em className={styles[kpi.tone]}>{kpi.tone==="bad"?"▼":"▲"} {kpi.change}</em></div></article>)}</section>
      <section className={`${styles.card} ${styles.rulesCard}`}><div className={styles.tabs} role="tablist" aria-label="Commission rule status">{tabs.map(tab=><button role="tab" aria-selected={active===tab} key={tab} onClick={()=>{setActive(tab);setPage(1)}}>{tab}{counts[tab]&&<b>{counts[tab]}</b>}</button>)}</div><div className={styles.filters}><label className={styles.search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search rules…"/></label>{filters.slice(0,5).map(label=><button key={label}>{label}<ChevronDown/></button>)}{filters.slice(5).map(label=><button key={label}>{label}<ChevronDown/></button>)}<button onClick={()=>setModal("More Filters")}><Filter/>More Filters</button><button onClick={()=>{setQuery("");setActive("All Rules")}}>Clear All</button><button onClick={()=>setModal("Save View")}><Save/>Save View</button><button>Sort By · Last Updated<ChevronDown/></button><button><Columns3/>Columns</button><button onClick={()=>void load(true)}><RefreshCw/>Refresh</button></div><div className={styles.tableTitle}><h2>Marketplace Commission Rules</h2><span>{rows.length} of 84 rules</span></div><RulesTable rows={rows} selected={selected} setSelected={setSelected} toggleAll={toggleAll} menu={menu} setMenu={setMenu} menuRef={menuRef} onAction={handleRuleAction}/><footer className={styles.pagination}><span>Showing 1 to {rows.length} of 84 rules</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></button><button className={styles.current}>1</button><button onClick={()=>setPage(2)}>2</button><button onClick={()=>setPage(p=>p+1)}><ChevronRight/></button><button>25 / page<ChevronDown/></button></div></footer></section>
      <section className={styles.dualTables}><ApprovalTable rows={data.approvals} onAction={setModal}/><ConflictTable rows={data.conflicts} onAction={setModal}/></section>
      <section className={styles.analytics}><Trend data={data.trend} period={period} setPeriod={setPeriod}/><Distribution data={data.distribution} active={distribution} setActive={setDistribution}/><Precedence/></section>
      <Scorecard items={data.scorecards}/>
    </div><OperationalRail data={data} onAction={setModal}/></div>
    {modal&&<CommissionModal type={modal} data={data} selected={selected} onClose={()=>setModal(null)} onConfirm={confirm}/>} 
  </main>;
}

function Context({data}){return <section className={styles.context}><div>{Object.entries(data.context).map(([key,value])=><p key={key}><span>{key.replace(/([A-Z])/g," $1")}:</span><b>{value}</b></p>)}</div><aside><LockKeyhole/>Access limited to assigned business context</aside></section>}
function RulesTable({rows,selected,setSelected,toggleAll,menu,setMenu,menuRef,onAction}){if(!rows.length)return <div className={styles.empty}><BadgeDollarSign/><h3>No commission rules match the filters</h3><p>Clear or adjust the current search and status controls.</p></div>;const heads=["Rule Name","Rule ID","Rule Type","Scope","Business Unit","Channel","Seller / Segment","Category / Brand","Commission Rate","Minimum Fee","Maximum Fee","Effective From","Effective To","Revenue Impact","Settlement Impact","Approval Status","Conflict Status","Rule Status","Approved By","Last Updated","Action"];return <div className={styles.tableWrap}><table><thead><tr><th><input aria-label="Select all commission rules" type="checkbox" checked={selected.length===rows.length} onChange={toggleAll}/></th>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><input aria-label={`Select ${row.name}`} type="checkbox" checked={selected.includes(row.id)} onChange={()=>setSelected(items=>items.includes(row.id)?items.filter(id=>id!==row.id):[...items,row.id])}/></td><td><b>{row.name}</b></td><td>{row.id}</td><td>{row.type}</td><td>{row.scope}</td><td>{row.unit}</td><td>{row.channel}</td><td>{row.segment}</td><td>{row.category}</td><td><b>{row.rate}</b></td><td>{row.min}</td><td>{row.max}</td><td>{row.from}</td><td>{row.to}</td><td>{row.revenue}</td><td>{row.settlement}</td><td><Badge value={row.approval}/></td><td><Badge value={row.conflict}/></td><td><Badge value={row.status}/></td><td>{row.approver}</td><td>{row.updated}</td><td className={styles.actionCell}><button aria-label={`Actions for ${row.name}`} onClick={()=>setMenu(menu===row.id?null:row.id)}><MoreVertical/></button>{menu===row.id&&<div ref={menuRef} className={styles.rowMenu}>{["View Rule","Edit Rule","Duplicate Rule","Review Approval","Resolve Conflict","Archive Rule"].map(action=><button key={action} onClick={()=>{setMenu(null);onAction(`${action}: ${row.name}`)}}>{action}</button>)}</div>}</td></tr>)}</tbody></table></div>}
function Badge({value}){const tone=["Approved","Clear","Active","Low"].includes(value)?"success":["Conflict Detected","High","Rejected"].includes(value)?"danger":["Pending Approval","Minor Overlap","Medium"].includes(value)?"warning":"info";return <span className={`${styles.badge} ${styles[tone]}`}>{value}</span>}
function ApprovalTable({rows,onAction}){return <section className={styles.card}><header className={styles.cardHeader}><h2>Pending Commission Approvals</h2><button onClick={()=>onAction("View All Approvals")}>View all (7)</button></header><div className={styles.smallTable}><table><thead><tr>{["Rule","Requested Change","Requested By","Requested Date","Revenue Impact","Settlement Impact","Conflict Status","Approval SLA","Action"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.rule}><td>{row.rule}</td><td>{row.change}</td><td>{row.by}</td><td>{row.date}</td><td className={styles.bad}>{row.revenue}</td><td className={styles.good}>{row.settlement}</td><td>{row.conflict}</td><td>{row.sla}</td><td><button onClick={()=>onAction("Review Approval")}>Review</button></td></tr>)}</tbody></table></div></section>}
function ConflictTable({rows,onAction}){return <section className={styles.card}><header className={styles.cardHeader}><h2>Rule Conflict Summary</h2><button onClick={()=>onAction("View All Conflicts")}>View all conflicts (4)</button></header><div className={styles.smallTable}><table><thead><tr>{["Conflict Type","Affected Rules","Severity","Impact","Action"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.type}><td>{row.type}</td><td>{row.rules}</td><td><Badge value={row.severity}/></td><td>{row.impact}</td><td><button onClick={()=>onAction("Resolve Conflict")}>Resolve Conflict</button></td></tr>)}</tbody></table></div></section>}
function Trend({data,period,setPeriod}){return <section className={styles.card}><header className={styles.cardHeader}><h2>Commission Revenue &amp; Rate Trend</h2><div className={styles.segmented}>{["Daily","Weekly","Monthly","Quarterly","Custom"].map(item=><button aria-pressed={period===item} onClick={()=>setPeriod(item)} key={item}>{item}</button>)}</div></header><div className={styles.chart}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:12,right:12,left:-20,bottom:0}}><CartesianGrid stroke="#eee" vertical={false}/><XAxis dataKey="date" tick={{fontSize:8}}/><YAxis tick={{fontSize:8}}/><Tooltip/><Legend wrapperStyle={{fontSize:8}}/><Bar dataKey="revenue" fill="#7b001a"/><Bar dataKey="gmv" fill="#cbb8b9"/><Line dataKey="avg" stroke="#f39700" strokeWidth={2}/><Line dataKey="exception" stroke="#3d91d1"/></ComposedChart></ResponsiveContainer></div></section>}
function Distribution({data,active,setActive}){return <section className={styles.card}><header className={styles.cardHeader}><h2>Commission Structure Distribution</h2></header><div className={styles.segmented}>{["Rule Type","Business Unit","Channel","Seller Segment","Status"].map(item=><button aria-pressed={active===item} onClick={()=>setActive(item)} key={item}>{item}</button>)}</div><div className={styles.distribution}><div><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius={45} outerRadius={68} stroke="#fff">{data.map(item=><Cell fill={item.color} key={item.label}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><span><b>84</b>Total Rules</span></div><ul>{data.map(item=><li key={item.label}><i style={{background:item.color}}/><span>{item.label}</span><b>{item.value}</b><em>({(item.value/84*100).toFixed(1)}%)</em></li>)}</ul></div></section>}
function Precedence(){return <section className={`${styles.card} ${styles.precedence}`}><header className={styles.cardHeader}><h2>Commission Precedence</h2><HeartPulse/></header><ol>{["Approved seller-specific exception","Approved promotional override","Category-specific rule","Channel-specific rule","Business-unit rule","Standard marketplace rule"].map(item=><li key={item}>{item}</li>)}</ol><p><Info/>Effective rule overrides lower-precedence rules. Lower precedence rates are ignored when a higher rule applies.</p></section>}
function Scorecard({items}){return <section className={`${styles.card} ${styles.scorecard}`}><h2>Commission Health Scorecard</h2><div>{items.map((item,index)=><article key={item.label}><span><CheckCircle2/></span><small>{item.label}</small><strong>{item.value}%</strong><b className={item.status==="Warning"?styles.warning:styles.success}>{item.status}</b></article>)}</div></section>}

function OperationalRail({data,onAction}){return <aside className={styles.rail}><Rail title="Commission Health"><div className={styles.healthScore}><strong>89</strong><span>/100</span><em>Stable</em></div>{data.health.map(item=><Progress key={item.label} label={item.label} value={item.value}/>)}</Rail><Rail title="Priority Commission Alerts"><div className={styles.alerts}>{data.alerts.map(item=><button key={item.title} onClick={()=>onAction(item.action)}><AlertTriangle className={styles[item.tone]}/><span><b>{item.title}</b><small>{item.detail}</small></span><em>{item.action}</em></button>)}</div><button className={styles.railLink} onClick={()=>onAction("View All Alerts")}>View all alerts (12)</button></Rail><Rail title="Commission Status Summary"><div className={styles.statusGrid}>{[["Active",84],["Scheduled",12],["Pending Approval",7],["Draft",9],["Expiring",8],["Expired",14],["Conflicts",4],["Exceptions",11]].map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</div></Rail><Rail title="Approval SLA Summary">{[["Standard Rules",92],["Seller Exceptions",68],["Category Rules",85],["Channel Rules",90],["Promotional Rules",75],["Conflict Resolutions",60]].map(x=><Progress key={x[0]} label={x[0]} value={x[1]}/>)}</Rail><Rail title="Financial Impact">{[["Commission Revenue","LKR 4.18M"],["Estimated Monthly Revenue","LKR 4.46M"],["Pending Settlement Impact","LKR 6.82M"],["Exception Value","LKR 420,000"],["Revenue at Risk","LKR 185,000"],["Reconciliation Rate","98.6%"]].map(([a,b])=><p className={styles.money} key={a}><span>{a}</span><b className={a==="Revenue at Risk"?styles.bad:""}>{b}</b></p>)}</Rail><Rail title="Quick Queues"><div className={styles.queues}>{[["Pending Approvals",7],["Rule Conflicts",4],["Seller Exceptions",5],["Expiring Rules",8],["Missing Approvers",3],["Settlement Variances",6]].map(([a,b])=><button key={a} onClick={()=>onAction(a)}><span>{a}</span><b>{b}</b><ChevronRight/></button>)}</div><button className={styles.railLink}>View all queues</button></Rail></aside>}
function Rail({title,children}){return <section className={styles.railCard}><h2>{title}</h2>{children}</section>}
function Progress({label,value}){return <div className={styles.progress}><p><span>{label}</span><b>{value}%</b></p><i><b style={{width:`${value}%`}}/></i></div>}

function CommissionModal({type,data,selected,onClose,onConfirm}){const [busy,setBusy]=useState(false);const [reason,setReason]=useState("");const [error,setError]=useState("");const isCreate=type==="Create Commission Rule";const isCompare=type==="Compare Rules";const isFilters=type==="More Filters";const isSave=type==="Save View";const sensitive=/Approve|Conflict|Archive|Bulk|Exception|Settlement|Approver/.test(type);const submit=async()=>{if(sensitive&&!reason.trim()){setError("An audit reason is required for this workflow.");return}setBusy(true);try{await onConfirm(type,reason)}finally{setBusy(false)}};return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="commission-modal-title"><header><div><small>Commission Management · Frontend Preview</small><h2 id="commission-modal-title">{type}</h2></div><button aria-label="Close dialog" onClick={onClose}><X/></button></header><div className={styles.modalBody}>{isCreate?<div className={styles.formGrid}>{["Rule name","Rule type","Business unit","Sales channel","Seller / segment","Product category","Commission rate","Minimum fee","Maximum fee","Effective from","Effective to","Approver"].map(label=><label key={label}>{label}<input placeholder={label}/></label>)}</div>:isCompare?<div className={styles.compare}>{data.rules.slice(0,2).map(row=><article key={row.id}><h3>{row.name}</h3><p>Rate <b>{row.rate}</b></p><p>Revenue <b>{row.revenue}</b></p><p>Status <Badge value={row.status}/></p></article>)}</div>:isFilters?<div className={styles.formGrid}>{filters.map(label=><label key={label}>{label}<select><option>All</option><option>Requires attention</option></select></label>)}</div>:isSave?<label className={styles.field}>View name<input placeholder="My commission view"/></label>:<><p>This workflow is a safe frontend preview because the repository has no commission mutation endpoint.</p><label className={styles.field}>Internal note or audit reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Enter decision context"/></label></>}{error&&<p className={styles.formError} role="alert">{error}</p>}</div><footer><button onClick={onClose} disabled={busy}>Cancel</button><button className={styles.primary} onClick={()=>void submit()} disabled={busy}>{busy?"Saving…":"Confirm"}</button></footer></section></div>}
function Loading(){return <div className={styles.loading} role="status" aria-label="Loading marketplace commissions"><div/><section>{Array.from({length:12},(_,i)=><i key={i}/>)}</section><div/><div/></div>}
