"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, Archive, BarChart3, CheckCircle2, ChevronLeft, ChevronRight, Download, MoreHorizontal, Package, RefreshCw, Search, SlidersHorizontal } from "lucide-react";
import toast from "react-hot-toast";
import { useDebounce } from "@/hooks/useDebounce";
import { useMarketplaceListings } from "@/hooks/admin/useMarketplaceListings";
import { exportMarketplaceListings } from "@/services/api/marketplaceListingsService";
import type { MarketplaceListingsFilters } from "@/types/marketplaceListings";
import styles from "./marketplace-listings.module.css";

const display = (value: string | null | undefined) => value ? value.replaceAll("-", " ").replace(/\b\w/g, letter => letter.toUpperCase()) : "â€”";
const tone = (value: string | null) => ["live", "verified", "compliant", "low"].includes(value ?? "") ? styles.success : ["rejected", "violation", "high", "critical"].includes(value ?? "") ? styles.danger : ["pending-review", "medium"].includes(value ?? "") ? styles.warning : styles.neutral;
const money = (amount: number, currency: string | null) => currency ? new Intl.NumberFormat("en-LK", { style: "currency", currency }).format(amount) : amount.toLocaleString("en-LK");

export function MarketplaceListingsView() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  const [search, setSearch] = useState(params?.get("search") ?? ""); const delayedSearch = useDebounce(search, 350); const [selected, setSelected] = useState<string[]>([]); const [exporting, setExporting] = useState(false);
  const filters = useMemo<MarketplaceListingsFilters>(() => ({ search: delayedSearch || undefined, status: params?.get("status") ?? "all", sellerId: params?.get("seller") ?? undefined, categoryId: params?.get("category") ?? undefined, currency: params?.get("currency") ?? undefined, sortBy: params?.get("sortBy") ?? "updatedAt", sortDirection: params?.get("sortDirection") === "asc" ? "asc" : "desc", page: Number(params?.get("page") ?? 1), perPage: Number(params?.get("perPage") ?? 25) }), [delayedSearch, params]);
  const { data, loading, refreshing, error, stale, refresh } = useMarketplaceListings(filters);
  const update = (changes: Record<string, string | number | null>) => { const next = new URLSearchParams(params?.toString() || ""); Object.entries(changes).forEach(([key, value]) => value === null || value === "" || value === "all" ? next.delete(key) : next.set(key, String(value))); router.replace(`${pathname ?? ""}${next.size ? `?${next}` : ""}`, { scroll: false }); };

  useEffect(() => { if (delayedSearch !== (params?.get("search") ?? "")) update({ search: delayedSearch || null, page: null }); }, [delayedSearch]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => setSelected([]), [filters.page, filters.status, filters.search]);

  const sort = (key: string) => update({ sortBy: key, sortDirection: filters.sortBy === key && filters.sortDirection === "asc" ? "desc" : "asc", page: null });
  const runExport = async () => { setExporting(true); try { await exportMarketplaceListings(filters); toast.success("Filtered listings exported"); } catch { toast.error("Listings export failed"); } finally { setExporting(false); } };

  if (loading && !data) return <main className={styles.state} aria-busy="true"><h1>Marketplace Listings Management</h1><p>Loading database listingsâ€¦</p></main>;
  if (error && !data) return <main className={styles.state} role="alert"><h1>Marketplace Listings Management</h1><p>{error}</p><button onClick={() => void refresh()}>Retry</button></main>;
  if (!data) return null;
  const allSelected = data.items.length > 0 && data.items.every(row => selected.includes(row.id));

  return <main className={styles.page}>
    <header className={styles.pageHeader}><div><h1>Marketplace Listings Management</h1><p>Manage, verify, and monitor database-backed product listings across the SL Beauty ecosystem.</p></div><div className={styles.headerActions}><button className={styles.secondary} disabled={!data.permissions.can_export || exporting} onClick={() => void runExport()}><Download size={14}/>{exporting ? "Exportingâ€¦" : "Export Listings"}</button><button className={styles.dark} disabled={!data.permissions.can_bulk_action || !selected.length} title={data.permissions.can_bulk_action ? "Select listings" : "No approved bulk listing workflow exists"}><SlidersHorizontal size={14}/>Bulk Actions</button><button className={styles.primary} disabled={!data.permissions.can_create} title="Use the existing supplier product workflow to create catalogue products">Create Listing</button></div></header>
    {(error || stale) && <div className={styles.inlineError} role="alert">{error ?? "Live refresh is temporarily unavailable. Showing the last successful database response."}</div>}
    <section className={styles.context}><div><span>Tenant: <b>Not modelled</b></span><span>Ecosystem: <b>Beauty Marketplace</b></span><span>Business Unit: <b>Not modelled</b></span><span>Channel: <b>Not modelled</b></span><span>Currency: <b>{data.filters.currency ?? "Mixed"}</b></span></div><aside><i/>{stale ? "Stale data" : "Live API"}<small>Last updated: {new Date(data.meta.generatedAt).toLocaleString("en-LK")}</small><button aria-label="Refresh listings" disabled={refreshing} onClick={() => void refresh(true)}><RefreshCw className={refreshing ? styles.spin : ""} size={14}/></button></aside></section>
    <div className={styles.layout}><div className={styles.workspace}>
      <section className={styles.kpis}>{data.metrics.map((metric, index) => <button key={metric.id} disabled={metric.availability === "unavailable"} title={metric.reason} onClick={() => update({ status: metric.id, page: null })} className={`${styles.kpi} ${filters.status === metric.id ? styles.selectedKpi : ""}`}><span>{metric.label}</span><strong>{metric.availability === "available" ? metric.value?.toLocaleString() : "Not available"}</strong><i className={styles.neutral}>{index % 3 === 0 ? <Package/> : index % 3 === 1 ? <CheckCircle2/> : <Archive/>}</i></button>)}</section>
      <section className={styles.listCard}><div className={styles.tabs} role="tablist">{data.metrics.filter(metric => metric.availability === "available").map(metric => <button role="tab" aria-selected={filters.status === metric.id} className={filters.status === metric.id ? styles.activeTab : ""} key={metric.id} onClick={() => update({ status: metric.id, page: null })}>{metric.label.replace(" Listings", "")} <b>{metric.value?.toLocaleString()}</b></button>)}</div>
        <div className={styles.filterPanel}><div className={styles.filterRow}><label className={styles.search}><Search size={14}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name, SKU or sellerâ€¦"/></label><button onClick={() => sort("name")}>Sort: Name</button><button onClick={() => sort("price")}>Sort: Price</button><button onClick={() => sort("stock")}>Sort: Stock</button></div>{(search || filters.status !== "all") && <div className={styles.chips}><span>Filters:</span>{search && <button onClick={() => setSearch("")}>Search: {search}</button>}{filters.status !== "all" && <button onClick={() => update({ status: null, page: null })}>Status: {display(filters.status)}</button>}<button className={styles.clear} onClick={() => { setSearch(""); router.replace(pathname ?? ""); }}>Clear all</button>
</div>}</div>
        <div className={styles.tableWrap}><table><thead><tr><th><input aria-label="Select current page" type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? [] : data.items.map(row => row.id))}/></th>{[["Listing","name"],["Listing ID","listingCode"],["Seller",null],["Product",null],["Brand",null],["Category",null],["Selling Price","price"],["Stock","stock"],["Sales (30D)",null],["Conversion (30D)",null],["Verification",null],["Policy Status",null],["Risk",null],["Listing Status",null],["Updated","updatedAt"],["Action",null]].map(([label,key]) => <th key={label}>{key ? <button onClick={() => sort(key)}>{label}</button> : label}</th>)}</tr></thead><tbody>{data.items.map(row => <tr key={row.id}><td><input aria-label={`Select ${row.name}`} type="checkbox" checked={selected.includes(row.id)} onChange={() => setSelected(current => current.includes(row.id) ? current.filter(id => id !== row.id) : [...current, row.id])}/></td><td><Link className={styles.detailLink} href={`/admin/marketplace/listings/${row.id}`}>{row.name}</Link><small>{row.descriptor ?? "â€”"}</small></td><td>{row.listingCode}</td><td>{row.seller ? <Link href={`/admin/marketplace/sellers/${row.seller.id}`}>{row.seller.name}</Link> : "â€”"}</td><td>{row.product.name}</td><td>{row.brand?.name ?? "â€”"}</td><td>{row.category?.name ?? "â€”"}</td><td>{money(row.sellingPrice.amount, row.sellingPrice.currency)}</td><td className={row.stock === 0 ? styles.stockWarning : ""}>{row.stock.toLocaleString()}</td><td>{row.sales30Days.toLocaleString()}</td><td>{row.conversionRate30Days === null ? "â€”" : `${row.conversionRate30Days}%`}</td><td><span className={`${styles.badge} ${tone(row.verificationStatus)}`}>{display(row.verificationStatus)}</span></td><td><span className={`${styles.badge} ${tone(row.policyStatus)}`}>{display(row.policyStatus)}</span></td><td><span className={`${styles.badge} ${tone(row.riskLevel)}`}>{display(row.riskLevel)}</span></td><td><span className={`${styles.badge} ${tone(row.listingStatus)}`}>{display(row.listingStatus)}</span></td><td>{new Date(row.updatedAt).toLocaleString("en-LK")}</td><td><Link aria-label={`View ${row.name}`} href={`/admin/marketplace/listings/${row.id}`}><MoreHorizontal size={16}/></Link></td></tr>)}{!data.items.length && <tr><td className={styles.empty} colSpan={17}>No database listings match the active filters.</td></tr>}</tbody></table></div>
        <footer className={styles.pagination}><span>Showing {data.meta.from ?? 0} to {data.meta.to ?? 0} of {data.meta.total.toLocaleString()} listings</span><div><button disabled={data.meta.page <= 1} onClick={() => update({ page: data.meta.page - 1 })}><ChevronLeft size={13}/>Previous</button><button className={styles.current}>{data.meta.page}</button><span>of {data.meta.totalPages}</span><button disabled={data.meta.page >= data.meta.totalPages} onClick={() => update({ page: data.meta.page + 1 })}>Next<ChevronRight size={13}/></button></div></footer>
      </section></div><aside className={styles.rail}><section className={styles.railCard}><h2>Listing Health <BarChart3 size={14}/></h2><div className={styles.empty}>{data.health.availability === "unavailable" ? "Not available: no approved listing-health formula exists." : data.health.score}</div></section><section className={styles.railCard}><h2>Priority Alerts</h2><div className={styles.alerts}>{data.alerts.map(alert => <Link key={alert.id} className={styles[alert.severity]} href={alert.href}><AlertTriangle size={15}/><span><b>{alert.title}</b><small>{alert.detail}</small></span></Link>)}{!data.alerts.length && <div className={styles.empty}>No supported listing alerts.</div>}</div></section><section className={styles.railCard}><h2>Review SLA / Verification SLA</h2><div className={styles.empty}>Not available: listing SLA deadlines and policies are not modelled.</div></section></aside></div>
  </main>;
}
