"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import {AlertTriangle,Check,ChevronRight,ClipboardList,Download,ExternalLink,Info,Mail,RefreshCw,ShieldCheck,Store,UserRound,X,XCircle} from "lucide-react";
import toast from "react-hot-toast";
import {fetchMarketplaceSellerDetail,recordSellerDetailPreviewAction} from "@/services/api/marketplaceSellerDetailService";
import styles from "./seller-performance-detail.module.css";

const tabs=["Overview","Sales & Orders","Fulfilment & SLA","Cancellations & Returns","Customer Experience","Policy & Compliance","Communications","Improvement Plans","Audit History"];
const counts={"Policy & Compliance":2,Communications:4,"Improvement Plans":1,"Audit History":18};
const interventions=["Maintain Active Status","Place Under Review","Create Improvement Plan","Restrict Channel","Suspend Seller","Escalate Review","Reinstate Seller"];

export function SellerPerformanceDetailView({sellerId}){
  const router=useRouter();const searchParams=useSearchParams();const [data,setData]=useState(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [modal,setModal]=useState(null);const [status,setStatus]=useState("Monitoring");const [audit,setAudit]=useState([]);
  const activeTab=useMemo(()=>tabs.find(tab=>tab.toLowerCase().replaceAll(" ","-").replaceAll("&","and")===searchParams.get("tab"))??"Overview",[searchParams]);
  const load=async(refresh=false)=>{try{setError("");refresh?setRefreshing(true):setLoading(true);const result=await fetchMarketplaceSellerDetail(decodeURIComponent(sellerId));setData(result);setStatus(result.ownership["Review Status"]);if(refresh)toast.success("Seller detail refreshed from the frontend fixture");}catch(e){setError(e.message==="SELLER_NOT_FOUND"?"The requested seller could not be found.":"Seller performance details could not be loaded.");}finally{setLoading(false);setRefreshing(false)}};
  useEffect(()=>{const controller=new AbortController();void fetchMarketplaceSellerDetail(decodeURIComponent(sellerId),controller.signal).then(result=>{setData(result);setStatus(result.ownership["Review Status"])}).catch(e=>{if(e.name!=="AbortError")setError(e.message==="SELLER_NOT_FOUND"?"The requested seller could not be found.":"Seller performance details could not be loaded.")}).finally(()=>setLoading(false));return()=>controller.abort()},[sellerId]);
  const changeTab=tab=>{const q=new URLSearchParams(searchParams.toString());tab==="Overview"?q.delete("tab"):q.set("tab",tab.toLowerCase().replaceAll(" ","-").replaceAll("&","and"));router.replace(`/admin/marketplace/sellers/${encodeURIComponent(sellerId)}${q.size?`?${q}`:""}`,{scroll:false})};
  const complete=async(action,note)=>{const event=await recordSellerDetailPreviewAction(data.id,action,note);setAudit(items=>[event,...items]);if(action==="Place Under Review")setStatus("Under Review");if(action==="Maintain Active Status"||action==="Reinstate Seller")setStatus("Monitoring");setModal(null);toast.success(`${action} saved in local preview state (not server-persisted)`) };
  if(loading&&!data)return <div className={styles.loading} role="status" aria-label="Loading seller performance detail"><div/><div/><section><i/><i/><i/></section><div/></div>;
  if(error&&!data)return <section className={styles.state} role="alert"><XCircle/><h1>Seller unavailable</h1><p>{error}</p><div><Link href="/admin/marketplace/sellers">Back to Sellers</Link><button onClick={()=>void load()}>Retry</button></div></section>;
  if(!data)return <section className={styles.state}><Store/><h1>No seller detail available</h1></section>;
  if(data.permissions?.canView===false)return <section className={styles.state}><ShieldCheck/><h1>Permission required</h1><p>Your role cannot access this seller performance record.</p></section>;
  return <main className={styles.page}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><Link href="/admin/marketplace/sellers">Sellers</Link><ChevronRight/><span>{data.id}</span></nav>
    <header className={styles.header}><div><div className={styles.titleRow}><h1>{data.name}</h1>{data.badges.map(badge=><span key={badge}><Check/>{badge}</span>)}</div><p>{data.description}</p></div><div className={styles.headerActions}><button onClick={()=>setModal("Contact Seller")}><Mail/>Contact Seller</button><button onClick={()=>setModal("Export Report")}><Download/>Export Report</button><button className={styles.primary} onClick={()=>setModal("Place Under Review")}>Place Under Review</button></div></header>
    <div className={styles.live}><i/>Live data <small>Last updated: {data.lastUpdated}</small><button aria-label="Refresh seller detail" disabled={refreshing} onClick={()=>void load(true)}><RefreshCw className={refreshing?styles.spin:""}/></button></div>
    <Summary data={data}/><Lifecycle items={data.lifecycle}/>
    <div className={styles.tabs} role="tablist" aria-label="Seller detail sections">{tabs.map((tab,index)=><button role="tab" aria-selected={activeTab===tab} tabIndex={activeTab===tab?0:-1} key={tab} onClick={()=>changeTab(tab)} onKeyDown={e=>{if(e.key==="ArrowRight")changeTab(tabs[(index+1)%tabs.length]);if(e.key==="ArrowLeft")changeTab(tabs[(index-1+tabs.length)%tabs.length])}}>{tab}{counts[tab]&&<b>{counts[tab]}</b>}</button>)}</div>
    <div className={styles.layout}><div className={styles.workspace} role="tabpanel">{activeTab==="Overview"?<Overview data={data}/>:<TabPanel tab={activeTab} data={data} audit={audit}/>}</div><InterventionRail data={data} status={status} onAction={setModal}/></div>
    {modal&&<ActionModal type={modal} data={data} onClose={()=>setModal(null)} onConfirm={complete}/>} 
  </main>;
}

function Summary({data}){const k=data.kpis;const items=[["Active Listings",k.listings],["Total Orders",k.orders],["GMV",k.gmv],["Average Order Value",k.aov],["Fulfilment Rate",k.fulfilment],["Cancellation Rate",k.cancellation],["Return Rate",k.returns],["Customer Rating",`${k.rating} ★`],["SLA Breaches",k.sla],["Policy Findings",k.findings],["Settlement Status",k.settlement],["Assigned Manager",k.manager],["Last Activity",k.activity]];return <section className={styles.summary}>{items.map(([label,value],index)=><div className={index===12?styles.wide:""} key={label}><span>{label}</span><strong className={[4,5,9,10].includes(index)?styles.good:index===6?styles.warn:""}>{value}</strong></div>)}</section>}
function Lifecycle({items}){return <section className={styles.lifecycle} aria-label="Seller lifecycle">{items.map((item,index)=><div className={`${styles.step} ${styles[item.state]}`} key={item.label}><div>{item.state==="complete"?<Check/>:item.state==="active"?<span/>:"•"}</div><b>{item.label}</b><small>{item.date}</small></div>)}</section>}

function Overview({data}){return <div className={styles.overview}><section className={`${styles.card} ${styles.performance}`}><div className={styles.performanceTotal}><h2>Seller Performance Score</h2><p><strong>{data.performanceScore}</strong><span>/100</span><b>Excellent</b></p><em>{data.recommendation}</em><small>Score updated: {data.lastUpdated}</small></div><div className={styles.breakdown}><h2>Score Breakdown (8 Dimensions)</h2><div>{data.dimensions.map(item=><article key={item.label}><div className={item.warning?styles.warningRing:""} style={{"--score":`${item.score}%`}}><span>{item.score}%</span></div><b>{item.label}</b></article>)}</div></div></section><InfoCard title="Marketplace Summary" values={data.marketplaceSummary} action="Full Marketplace Analysis"/><InfoCard title="Operational Health" values={data.operationalHealth} alert="SLA Alert|1 breach detected in last 30 days."/><InfoCard title="Risk & Compliance" values={data.riskCompliance} action="View Policy Findings (2)"/><InfoCard title="Financial Reliability" values={data.financialReliability}/><CustomerCard data={data.customerExperience}/><ActivityCard data={data.activities}/></div>}
function InfoCard({title,values,action,alert}){return <section className={styles.card}><h2>{title}</h2><dl>{Object.entries(values).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{alert&&<div className={styles.alert}><AlertTriangle/><p><b>{alert.split("|")[0]}</b><span>{alert.split("|")[1]}</span></p></div>}{action&&<button className={styles.textAction}>{action}<ChevronRight/></button>}</section>}
function CustomerCard({data}){return <section className={`${styles.card} ${styles.customer}`}><h2>Customer Experience</h2><div className={styles.customerTop}><span><b>{data.rating}</b>★</span><p><strong>{data.sentiment}</strong><em>{data.summary}</em><small>(Last 30 Days)</small></p></div><div className={styles.sentiment}><p>Positive (4–5)<b>{data.positive}%</b></p><p>Neutral (3)<b>{data.neutral}%</b></p><p>Negative (1–2)<b>{data.negative}%</b></p></div><button className={styles.textAction}>View Customer Feedback<ChevronRight/></button></section>}
function ActivityCard({data}){return <section className={`${styles.card} ${styles.activity}`}><h2>Recent Seller Activity</h2>{data.map((item,index)=><div key={item.title}><span className={styles[item.tone]}>{index<2?<ClipboardList/>:index===2?<AlertTriangle/>:<XCircle/>}</span><b>{item.title}</b><time>{item.at}</time></div>)}<button className={styles.textAction}>View All Activity<ChevronRight/></button></section>}

function TabPanel({tab,data,audit}){if(tab==="Audit History")return <section className={`${styles.card} ${styles.tabPanel}`}><h2>Audit History</h2>{audit.length?audit.map(item=><article key={item.id}><b>{item.action}</b><span>{new Date(item.at).toLocaleString()}</span><p>{item.note||"No note provided."}</p></article>):<p>No local audit events in this session. The 18 server audit records are unavailable because no detail API exists.</p>}</section>;const descriptions={"Sales & Orders":`${data.kpis.orders} orders generated ${data.kpis.gmv} GMV during the reporting period.`,"Fulfilment & SLA":`${data.kpis.fulfilment} fulfilment with ${data.kpis.sla} SLA breach.`,"Cancellations & Returns":`${data.kpis.cancellation} cancellation rate and ${data.kpis.returns} return rate.`,"Customer Experience":`Customer rating is ${data.kpis.rating} with highly positive sentiment.`,"Policy & Compliance":`${data.kpis.findings} policy findings and a 96% compliance score.`,Communications:"Four seller communications are associated with this performance review.","Improvement Plans":"One improvement plan is associated with this seller."};return <section className={`${styles.card} ${styles.tabPanel}`}><h2>{tab}</h2><p>{descriptions[tab]}</p><div><span>Seller</span><b>{data.name}</b></div><div><span>Data source</span><b>Frontend fixture</b></div><div><span>Last updated</span><b>{data.lastUpdated}</b></div></section>}

function InterventionRail({data,status,onAction}){return <aside className={styles.rail}><section className={styles.intervention}><header><h2>Intervention Panel</h2><ShieldCheck/><small>Live update: {data.lastUpdated}</small></header><div className={styles.health}><p><span>Health Score</span><b>{data.performanceScore}%</b></p><i><b style={{width:`${data.performanceScore}%`}}/></i></div><h3>Review Ownership</h3>{Object.entries({...data.ownership,"Review Status":status}).map(([label,value])=><p className={styles.ownership} key={label}><span>{label}</span><b className={label==="Review Status"?styles.good:label==="Elapsed Time"?styles.warn:""}>{value}</b></p>)}<h3>Intervention Actions</h3><div className={styles.interventions}>{interventions.map((action,index)=><button className={`${index===0?styles.primary:""} ${action.includes("Restrict")||action.includes("Suspend")?styles.dangerAction:""} ${action.includes("Reinstate")?styles.reinstate:""}`} key={action} onClick={()=>onAction(action)}>{action}</button>)}</div></section><section className={styles.related}><h2>Related Records</h2>{data.related.map(item=><button key={item.label} onClick={()=>onAction(`View ${item.label}`)}><span><ExternalLink/>{item.label}</span>{item.count&&<b>{item.count}</b>}<ChevronRight/></button>)}<button className={styles.viewAll}>View All Records<ChevronRight/></button></section></aside>}

function ActionModal({type,data,onClose,onConfirm}){const [note,setNote]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const isExport=type==="Export Report";const isContact=type==="Contact Seller";const isView=type.startsWith("View ");const sensitive=/Review|Restrict|Suspend|Escalate|Reinstate|Maintain|Improvement/.test(type);const submit=async()=>{if(sensitive&&!note.trim()){setError("An audit note is required for this intervention.");return}setBusy(true);try{if(isExport){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${data.id}-performance.json`;a.click();URL.revokeObjectURL(url);onClose();toast.success("Seller report exported");return}await onConfirm(type,note)}finally{setBusy(false)}};return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="action-title"><header><div><small>Seller Detail · Frontend Preview</small><h2 id="action-title">{type}</h2></div><button aria-label="Close dialog" onClick={onClose}><X/></button></header><div className={styles.modalBody}>{isContact?<><label>Subject<input defaultValue={`Performance review — ${data.id}`}/></label><label>Message<textarea placeholder="Write a message to the seller"/></label></>:isView?<div className={styles.safe}><Info/><p>This related-record destination is not defined in the repository, so it is displayed safely without opening a 404 route.</p></div>:<><p>Apply <b>{type}</b> to <b>{data.name}</b> ({data.id}). No mutation API exists; confirmation updates only this page session.</p>{!isExport&&<label>Internal audit note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Enter decision context"/></label>}</>}{error&&<p className={styles.formError} role="alert">{error}</p>}</div><footer><button onClick={onClose} disabled={busy}>Cancel</button>{!isView&&<button className={styles.primary} onClick={()=>void submit()} disabled={busy}>{busy?"Saving…":isContact?"Send Message":isExport?"Export":"Confirm"}</button>}</footer></section></div>}
