"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {ChevronRight,LockKeyhole,RefreshCw,ShieldCheck,Store,XCircle} from "lucide-react";
import {fetchMarketplaceSellerDetail} from "@/services/api/marketplaceSellerDetailService";
import styles from "./seller-performance-detail.module.css";

const label=value=>value?value.replaceAll("-"," ").replace(/\b\w/g,c=>c.toUpperCase()):"Not available";
const metric=value=>value?.available?value.value:"Not available";
const money=value=>value?.available?new Intl.NumberFormat("en-LK",{style:"currency",currency:value.currency,maximumFractionDigits:0}).format(value.value):"Not available";

export function SellerPerformanceDetailView({sellerId}){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState("");const active=useRef(null);
  const load=useCallback(async(background=false)=>{active.current?.abort();const controller=new AbortController();active.current=controller;background?setRefreshing(true):setLoading(true);setError("");try{setData(await fetchMarketplaceSellerDetail(sellerId,controller.signal))}catch(e){if(e?.name!=="AbortError")setError(e?.status===404?"The requested seller could not be found.":"Seller performance details could not be loaded.")}finally{if(active.current===controller){setLoading(false);setRefreshing(false)}}},[sellerId]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void load(true)},(data?.meta?.refreshIntervalSeconds??30)*1000);return()=>{clearInterval(timer);active.current?.abort()}},[data?.meta?.refreshIntervalSeconds,load]);
  if(loading&&!data)return <div className={styles.loading} role="status" aria-label="Loading seller performance detail"><div/><div/><section><i/><i/><i/></section><div/></div>;
  if(error&&!data)return <section className={styles.state} role="alert"><XCircle/><h1>Seller unavailable</h1><p>{error}</p><div><Link href="/admin/marketplace/sellers">Back to Sellers</Link><button onClick={()=>void load()}>Retry</button></div></section>;
  if(!data)return <section className={styles.state}><Store/><h1>No seller detail available</h1></section>;
  if(data.permissions?.canView===false)return <section className={styles.state}><LockKeyhole/><h1>Permission required</h1></section>;
  const seller=data.seller;
  const items=[["Seller ID",seller.sellerCode],["Type",seller.type||"Not available"],["Country",seller.country||"Not available"],["Status",label(seller.status)],["Verification",label(seller.verificationStatus)],["Risk",label(seller.riskLevel)],["Active Listings",seller.activeListings],["Orders",seller.orders],["GMV",money(seller.gmv)],["Average Order Value",money(seller.aov)],["Fulfilment Rate",seller.fulfilmentRate.available?`${metric(seller.fulfilmentRate)}%`:"Not available"],["Cancellation Rate",seller.cancellationRate.available?`${metric(seller.cancellationRate)}%`:"Not available"],["Return Rate",seller.returnRate.available?`${metric(seller.returnRate)}%`:"Not available"],["Customer Rating",metric(seller.rating)],["SLA Breaches",metric(seller.slaBreaches)],["Policy Findings",metric(seller.policyFindings)],["Last Activity",seller.lastActivityAt?new Date(seller.lastActivityAt).toLocaleString():"Not available"]];
  return <main className={styles.page}><nav className={styles.breadcrumb}><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><Link href="/admin/marketplace/sellers">Sellers</Link><ChevronRight/><span>{seller.sellerCode}</span></nav><header className={styles.header}><div><div className={styles.titleRow}><h1>{seller.name}</h1><span><ShieldCheck/>{label(seller.verificationStatus)}</span></div><p>Database-backed seller record and current-period marketplace metrics.</p></div><div className={styles.headerActions}><button disabled title="No approved seller mutation workflow is defined">Seller Actions</button></div></header><div className={styles.live}><i/>Live polling <small>Last updated: {new Date(data.meta.dataAsOf).toLocaleString()}</small><button aria-label="Refresh seller detail" onClick={()=>void load(true)} disabled={refreshing}><RefreshCw className={refreshing?styles.spin:""}/></button></div><section className={styles.summary}>{items.map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</section><div className={styles.layout}><div className={styles.workspace}><section className={`${styles.card} ${styles.tabPanel}`}><h2>Metric availability</h2>{[["Seller Health",data.health],["Performance Scorecard",data.scorecard],["Seller SLA",data.sla]].map(([name,value])=><div key={name}><span>{name}</span><b>{value.available?value.value:`Not available — ${label(value.reason)}`}</b></div>)}</section></div><aside className={styles.rail}><section className={styles.intervention}><header><h2>Administration</h2><ShieldCheck/></header><p>State-changing controls are disabled because this repository does not define approved seller transitions, reason rules, or seller audit events.</p><div className={styles.interventions}><button disabled>Place Under Review</button><button disabled>Restrict Seller</button><button disabled>Suspend Seller</button><button disabled>Reactivate Seller</button></div></section></aside></div></main>;
}
