"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, CalendarDays, ChevronDown, ChevronRight, CircleDollarSign, Download, Info, RefreshCw, Search, ShieldAlert, Star, UserRound, Users } from "lucide-react";
import { CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import toast from "react-hot-toast";
import { useMarketplaceSellers } from "@/hooks/admin/useMarketplaceSellers";
import { exportMarketplaceSellers } from "@/services/api/marketplaceSellersService";
import styles from "./seller-marketplace-performance.module.css";

const statusTabs = [["all","All Sellers"],["active","Active"],["under-review","Under Review"],["high-risk","High Risk"],["inactive","Inactive"],["suspended","Suspended"],["new","New Sellers"]];
const colors = { low:"#299436", medium:"#f3a000", high:"#eb391c", critical:"#9a001d" };

export function SellerMarketplacePerformanceView() {
  const router = useRouter(); const searchParams = useSearchParams();
  const [draftSearch, setDraftSearch] = useState(searchParams.get("search") || "");
  const filters = useMemo(() => ({ search:searchParams.get("search") || undefined, status:searchParams.get("status") || "all", riskLevel:searchParams.get("riskLevel") || undefined, verificationStatus:searchParams.get("verificationStatus") || undefined, currency:searchParams.get("currency") || undefined, dateFrom:searchParams.get("dateFrom") || undefined, dateTo:searchParams.get("dateTo") || undefined, sortBy:searchParams.get("sortBy") || "updatedAt", sortDirection:searchParams.get("sortDirection") || "desc", page:Number(searchParams.get("page") || 1), perPage:Number(searchParams.get("perPage") || 25) }), [searchParams]);
  const { data, loading, refreshing, error, stale, refresh } = useMarketplaceSellers(filters);
  const update = values => { const next = new URLSearchParams(searchParams.toString()); Object.entries(values).forEach(([key,value]) => value === undefined || value === "" || value === "all" ? next.delete(key) : next.set(key,String(value))); router.replace(`/admin/marketplace/sellers${next.size ? `?${next}` : ""}`, { scroll:false }); };
  useEffect(() => { const timer=setTimeout(() => { if (draftSearch !== (searchParams.get("search") || "")) update({search:draftSearch,page:1}); },350); return()=>clearTimeout(timer); },[draftSearch]); // eslint-disable-line react-hooks/exhaustive-deps
  const exportReport = async () => { try { await exportMarketplaceSellers(filters); toast.success("Seller performance report exported"); } catch { toast.error("The seller report could not be exported."); } };
  if (loading && !data) return <SellerLoading/>;
  if (error && !data) return <section className={styles.state} role="alert"><ShieldAlert/><h1>Seller Marketplace Performance</h1><p>{error}</p><button onClick={()=>void refresh()}>Retry</button></section>;
  if (!data) return null;
  return <main className={styles.page}>
    <nav className={styles.breadcrumb}><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><span>Sellers</span></nav>
    <header className={styles.header}><div><h1>Seller Marketplace Performance</h1><p>Database-backed seller sales, fulfilment, returns, ratings and marketplace risk.</p></div><div className={styles.headerActions}><button disabled={!data.permissions.canExport} onClick={()=>void exportReport()}><Download/>Export Performance Report</button><button disabled title="Comparison workflow is not defined by the current domain model"><Users/>Compare Sellers</button><button disabled title="Seller mutations require a defined audited workflow">Seller Actions<ChevronDown/></button><button className={styles.primary} disabled title="Seller onboarding is not implemented in this admin domain">Add Marketplace Seller</button></div></header>
    <ContextBar data={data} stale={stale} refreshing={refreshing} refresh={refresh} update={update}/>
    <div className={styles.layout}><div className={styles.workspace}>
      <section className={styles.kpis}>{data.metrics.map((metric,index)=><Metric key={metric.id} metric={metric} index={index}/>)}</section>
      <section className={styles.charts}><article className={styles.card}><header className={styles.cardHeader}><h2>Seller Performance Trend</h2><span>{data.context.dateFrom} – {data.context.dateTo}</span></header><Trend data={data.trend} currency={data.context.currency}/></article><article className={styles.card}><header className={styles.cardHeader}><h2>Seller Risk Distribution</h2></header><RiskDistribution data={data.riskDistribution}/></article></section>
      <Unavailable data={data.unavailable}/>
      <section className={`${styles.card} ${styles.sellerCard}`}><div className={styles.tabs}>{statusTabs.map(([id,label])=><button role="tab" aria-selected={filters.status===id} key={id} onClick={()=>update({status:id,page:1})}>{label}</button>)}</div>
        <div className={styles.filters}><div className={styles.filterTop}><label className={styles.search}><Search/><input value={draftSearch} onChange={e=>setDraftSearch(e.target.value)} placeholder="Search seller, email or seller ID…"/></label><select aria-label="Risk level" value={filters.riskLevel || ""} onChange={e=>update({riskLevel:e.target.value,page:1})}><option value="">All risk levels</option>{["low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Verification status" value={filters.verificationStatus || ""} onChange={e=>update({verificationStatus:e.target.value,page:1})}><option value="">All verification states</option>{["pending","verified","rejected"].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Date from" type="date" value={filters.dateFrom||data.context.dateFrom} onChange={e=>update({dateFrom:e.target.value,page:1})}/><input aria-label="Date to" type="date" value={filters.dateTo||data.context.dateTo} onChange={e=>update({dateTo:e.target.value,page:1})}/><select aria-label="Sort sellers" value={filters.sortBy} onChange={e=>update({sortBy:e.target.value,page:1})}><option value="updatedAt">Last updated</option><option value="name">Name</option><option value="orders">Orders</option><option value="gmv">GMV</option><option value="rating">Rating</option><option value="risk">Risk</option></select><button className={styles.clear} onClick={()=>{setDraftSearch("");router.replace("/admin/marketplace/sellers")}}>Clear all</button><button aria-label="Refresh table" onClick={()=>void refresh(true)}><RefreshCw className={refreshing?styles.spin:""}/></button></div></div>
        <div className={styles.tableTitle}><h2>Seller Marketplace Performance</h2><span>{data.meta.total} sellers</span></div><SellerTable rows={data.items} currency={data.context.currency}/>
        <footer className={styles.pagination}><span>Page {data.meta.page} of {Math.max(1,data.meta.lastPage)} · {data.meta.total} sellers</span><div><button disabled={data.meta.page<=1} onClick={()=>update({page:data.meta.page-1})}>Previous</button><button className={styles.current}>{data.meta.page}</button><button disabled={data.meta.page>=data.meta.lastPage} onClick={()=>update({page:data.meta.page+1})}>Next</button></div></footer>
      </section>
    </div><OperationalRail data={data}/></div>
  </main>;
}

function format(value, unit){ if(value===null||value===undefined)return "Unavailable"; if(unit==="%")return `${Number(value).toFixed(1)}%`; if(unit)return `${unit} ${new Intl.NumberFormat("en-LK",{maximumFractionDigits:0}).format(value)}`; return new Intl.NumberFormat("en-LK",{maximumFractionDigits:2}).format(value); }
function Metric({metric,index}){const Icon=[UserRound,Star,ShieldAlert,AlertTriangle,CircleDollarSign,CircleDollarSign,Users,AlertTriangle,RefreshCw,Star,ShieldAlert,AlertTriangle][index]||Info;return <article title={metric.definition||metric.reason}><span className={`${styles.kpiIcon} ${styles[metric.availability==="available"?"green":"orange"]}`}><Icon/></span><div><small>{metric.label}</small><strong>{format(metric.value,metric.unit)}</strong><em>{metric.availability==="available"?"Live database":"Not available"}</em></div></article>}
function ContextBar({data,stale,refreshing,refresh,update}){return <section className={styles.context}><div><div><CircleDollarSign/><span>Currency</span><strong>{data.context.currency||"Selection required"}</strong></div><div><CalendarDays/><span>Date range</span><strong>{data.context.dateFrom} – {data.context.dateTo}</strong></div>{data.context.currencies.length>1&&<div><select aria-label="Currency" value={data.context.currency||""} onChange={e=>update({currency:e.target.value,page:1})}><option value="">Select currency</option>{data.context.currencies.map(x=><option key={x}>{x}</option>)}</select></div>}</div><footer><Info/>Access is permission scoped <aside><i/>{stale?"Stale data":"Live data"}<small>Updated {new Date(data.generatedAt).toLocaleString()}</small><button disabled={refreshing} onClick={()=>void refresh(true)}><RefreshCw className={refreshing?styles.spin:""}/></button></aside></footer></section>}
function Trend({data,currency}){const latest=data.at(-1)||{};return <div className={styles.trendBody}><dl><div><dt>Orders</dt><dd>{latest.orders||0}</dd></div><div><dt>{currency?"GMV":"GMV"}</dt><dd>{currency?format(latest.gmv,currency):"Select currency"}</dd></div><div><dt>Fulfilment</dt><dd>{format(latest.fulfilmentRate||0,"%")}</dd></div><div><dt>Cancellation</dt><dd>{format(latest.cancellationRate||0,"%")}</dd></div></dl><div className={styles.chartCanvas}><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke="#eee" vertical={false}/><XAxis dataKey="date" tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip/><Legend/><Line type="monotone" dataKey={currency?"gmv":"orders"} stroke="#831126" dot={false}/><Line type="monotone" dataKey="fulfilmentRate" stroke="#27933b" dot={false}/><Line type="monotone" dataKey="cancellationRate" stroke="#f39a00" dot={false}/><Line type="monotone" dataKey="returnRate" stroke="#3271c8" dot={false}/></LineChart></ResponsiveContainer></div></div>}
function RiskDistribution({data}){const total=data.reduce((n,x)=>n+x.value,0);return <div className={styles.riskBody}><div className={styles.donut}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="level" innerRadius={55} outerRadius={78}>{data.map(x=><Cell key={x.level} fill={colors[x.level]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><span><b>{total}</b>Assessed</span></div><ul>{data.map(x=><li key={x.level}><i style={{background:colors[x.level]}}/><span>{x.level}</span><b>{x.value}</b><em>{x.percentage}%</em></li>)}</ul></div>}
function Unavailable({data}){return <section className={`${styles.card} ${styles.scorecard}`}><h2>Unavailable metrics</h2><div>{data.map(item=><article key={item.id}><span>{item.label}</span><p><small>{item.reason}</small></p><b className={styles.watch}>Unavailable</b></article>)}</div></section>}
function SellerTable({rows,currency}){if(!rows.length)return <div className={styles.empty}><Users/><h3>No sellers match these filters</h3><p>Clear or adjust the filters.</p></div>;return <div className={styles.tableWrap}><table><thead><tr>{["Seller","Seller ID","Type","Listings","Orders","GMV","Fulfilment","Cancellation","Returns","Rating","Verification","Risk","Status","Last Activity"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><Link className={styles.sellerLink} href={`/admin/marketplace/sellers/${row.id}`}>{row.name}</Link></td><td><Link className={styles.sellerLink} href={`/admin/marketplace/sellers/${row.id}`}>{row.sellerCode}</Link></td><td>{row.businessType||"—"}</td><td>{row.activeListings}</td><td>{row.orders}</td><td><b>{row.gmv?format(row.gmv.amount,row.gmv.currency):currency?"0":"Select currency"}</b></td><td>{format(row.fulfilmentRate,"%")}</td><td>{format(row.cancellationRate,"%")}</td><td>{format(row.returnRate,"%")}</td><td>{row.rating??"—"}</td><td><Badge value={row.verificationStatus}/></td><td><Badge value={row.riskLevel||"unassessed"}/></td><td><Badge value={row.status}/></td><td>{new Date(row.lastActivityAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
function Badge({value}){const tone=["active","verified","low"].includes(value)?"success":["high","critical","suspended","rejected"].includes(value)?"danger":["medium","pending","under-review"].includes(value)?"warning":"neutral";return <span className={`${styles.badge} ${styles[tone]}`}>{String(value).replaceAll("-"," ")}</span>}
function OperationalRail({data}){return <aside className={styles.rail}><section className={styles.railCard}><header><h2><i>A</i>Priority Seller Alerts</h2></header><div className={styles.alerts}>{data.alerts.length?data.alerts.map(item=><Link href={`/admin/marketplace/sellers/${item.sellerId}`} key={item.id}><AlertTriangle/><span><b>{item.title}</b><small>{item.sellerName||`Seller ${item.sellerId}`}</small></span></Link>):<p>No open supplier risk events.</p>}</div></section><section className={styles.railCard}><header><h2><i>B</i>Data integrity</h2></header><p>GMV excludes cancelled orders and never combines currencies.</p><p>Risk uses each supplier’s active risk profile.</p><p>SLA and weighted scores are intentionally not inferred.</p></section></aside>}
function SellerLoading(){return <div className={styles.loading} role="status" aria-label="Loading seller marketplace performance"><div/><section>{Array.from({length:12},(_,i)=><i key={i}/>)}</section><div/><div/></div>}
