"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowUpDown, BadgeDollarSign, BarChart3, Building2, CalendarDays, Check, ChevronDown, ChevronRight, CircleDollarSign, Columns3, Download, Expand, Filter, Globe2, LockKeyhole, MoreHorizontal, PackageCheck, Pause, Plus, RefreshCw, Save, Search, Share2, ShieldAlert, Star, Store, Upload, UserRound, Users, X, XCircle } from "lucide-react";
import { CartesianGrid, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Cell } from "recharts";
import toast from "react-hot-toast";
import { fetchMarketplaceSellers, recordSellerPreviewAction } from "@/services/api/marketplaceSellersService";
import styles from "./seller-marketplace-performance.module.css";

const statusTabs=["All Sellers","Active","Under Review","High Risk","SLA Breach","Restricted","Suspended","New Sellers"];
const filters=["Seller Status","Risk Level","Business Unit","Sales Channel","Marketplace","Customer Rating","SLA Status","Settlement Status","Assigned Manager"];
const kpiIcons=[UserRound,Star,ShieldAlert,Pause,CircleDollarSign,BarChart3,PackageCheck,XCircle,RefreshCw,Star,ShieldAlert,AlertTriangle];

export function SellerMarketplacePerformanceView() {
  const router=useRouter();
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [refreshing,setRefreshing]=useState(false);
  const [activeTab,setActiveTab]=useState("All Sellers"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState([]); const [menu,setMenu]=useState(null); const [modal,setModal]=useState(null); const [period,setPeriod]=useState("Weekly"); const [riskView,setRiskView]=useState("Risk Level");
  const [sort,setSort]=useState("Last Activity"); const [page,setPage]=useState(1); const [columnsOpen,setColumnsOpen]=useState(false); const [advanced,setAdvanced]=useState(false); const menuRef=useRef(null);
  const load=async(refresh=false)=>{try{setError("");if(refresh)setRefreshing(true);else setLoading(true);const result=await fetchMarketplaceSellers();setData(result);if(refresh)toast.success("Seller performance refreshed from the frontend fixture");}catch(e){if(e.name!=="AbortError")setError("Seller marketplace performance could not be loaded.");}finally{setLoading(false);setRefreshing(false)}};
  useEffect(()=>{const controller=new AbortController();void fetchMarketplaceSellers(controller.signal).then(setData).catch(e=>{if(e.name!=="AbortError")setError("Seller marketplace performance could not be loaded.")}).finally(()=>setLoading(false));return()=>controller.abort()},[]);
  useEffect(()=>{const close=e=>{if(menuRef.current&&!menuRef.current.contains(e.target))setMenu(null)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
  const rows=useMemo(()=>data?.sellers.filter(row=>{const matches=Object.values(row).join(" ").toLowerCase().includes(query.toLowerCase());const status=activeTab==="All Sellers"||activeTab===row.status||(activeTab==="High Risk"&&row.risk==="High")||(activeTab==="SLA Breach"&&row.sla>0)||(activeTab==="New Sellers"&&row.id.endsWith("142"));return matches&&status})??[],[data,query,activeTab]);
  const toggleAll=()=>setSelected(selected.length===rows.length?[]:rows.map(row=>row.id));
  const exportReport=()=>{if(!data)return;const lines=[["Seller","Seller ID","GMV","Fulfilment","Risk","Status"],...data.sellers.map(row=>[row.name,row.id,row.gmv,row.fulfilment,row.risk,row.status])];const blob=new Blob([lines.map(line=>line.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="seller-marketplace-performance.csv";anchor.click();URL.revokeObjectURL(url);toast.success("Performance report exported")};
  const previewAction=async(action,ids=selected)=>{await recordSellerPreviewAction(action,ids);setModal(null);toast.success(`${action} saved in local preview state (not server-persisted)`) };
  if(loading&&!data)return <SellerLoading/>;
  if(error&&!data)return <section className={styles.state} role="alert"><ShieldAlert/><h1>Seller Marketplace Performance</h1><p>{error}</p><button onClick={()=>void load()}>Retry</button></section>;
  if(!data)return <section className={styles.state}><Users/><h1>No seller performance data</h1><p>There are no sellers available for the current business context.</p></section>;
  if(data.permissions?.canView===false)return <section className={styles.state}><LockKeyhole/><h1>Permission required</h1><p>Your role cannot access Marketplace seller performance.</p></section>;
  return <main className={styles.page}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><span>Sellers</span></nav>
    <header className={styles.header}><div><h1>Seller Marketplace Performance</h1><p>Monitor seller sales, fulfilment, cancellations, returns, customer experience, SLA compliance and marketplace risk.</p></div><div className={styles.headerActions}><button onClick={exportReport}><Download/>Export Performance Report</button><button onClick={()=>setModal("Compare Sellers")}><Share2/>Compare Sellers</button><button onClick={()=>setModal("Seller Actions")}>Seller Actions<ChevronDown/></button><button className={styles.primary} onClick={()=>setModal("Add Marketplace Seller")}><Plus/>Add Marketplace Seller</button></div></header>
    <ContextBar data={data} refreshing={refreshing} onRefresh={()=>void load(true)}/>
    <div className={styles.layout}><div className={styles.workspace}>
      <section className={styles.kpis} aria-label="Seller performance metrics">{data.kpis.map((kpi,index)=>{const Icon=kpiIcons[index];return <article key={kpi.id}><span className={`${styles.kpiIcon} ${styles[kpi.tone]}`}><Icon/></span><div><small>{kpi.label}</small><strong>{kpi.value}</strong><em className={kpi.direction.includes("Bad")||kpi.direction==="down"?styles.negative:styles.positive}>{kpi.direction.startsWith("down")?"↓":"↑"} {kpi.change}</em></div></article>})}</section>
      <section className={styles.charts}><article className={styles.card}><header className={styles.cardHeader}><h2>Seller Performance Trend</h2><div className={styles.segmented}>{["Daily","Weekly","Monthly","Quarterly","Custom"].map(item=><button key={item} aria-pressed={period===item} onClick={()=>setPeriod(item)}>{item}</button>)}<button aria-label="Choose custom period"><CalendarDays/></button></div></header><PerformanceTrend data={data.trend}/></article><article className={styles.card}><header className={styles.cardHeader}><h2>Seller Risk Distribution</h2></header><div className={styles.segmented}>{["Risk Level","Seller Status","Business Unit","Custom"].map(item=><button key={item} aria-pressed={riskView===item} onClick={()=>setRiskView(item)}>{item}</button>)}</div><RiskDistribution data={data.risks}/></article></section>
      <Scorecard items={data.scorecards}/>
      <section className={`${styles.card} ${styles.sellerCard}`}><div className={styles.tabs} role="tablist" aria-label="Seller status">{statusTabs.map(tab=><button role="tab" aria-selected={activeTab===tab} key={tab} onClick={()=>{setActiveTab(tab);setPage(1)}}>{tab}</button>)}</div>
        <div className={styles.filters}><div className={styles.filterTop}><label className={styles.search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search seller, company, seller ID, brand or marketplace…"/></label>{filters.slice(0,5).map(label=><button key={label}>{label}<ChevronDown/></button>)}<button className={styles.clear} onClick={()=>{setQuery("");setActiveTab("All Sellers")}}>Clear All</button><button onClick={()=>setModal("Save View")}><Save/>Save View</button><span>Sort By</span><button>{sort}<ChevronDown/></button></div><div className={styles.filterBottom}>{filters.slice(5).map(label=><button key={label}>{label}<ChevronDown/></button>)}<button onClick={()=>setAdvanced(true)}><Filter/>More Filters</button><button className={styles.columns} onClick={()=>setColumnsOpen(x=>!x)}><Columns3/>Columns</button><button aria-label="Refresh table" onClick={()=>void load(true)}><RefreshCw/></button></div></div>
        <div className={styles.tableTitle}><h2>Seller Marketplace Performance</h2><div><span>{rows.length} of 142 sellers</span><button disabled={!selected.length} onClick={()=>setModal("Bulk Actions")}>Bulk Actions<ChevronDown/></button><button disabled={selected.length<2} onClick={()=>setModal("Compare Sellers")}><Users/>Compare</button><button aria-label="Change table density"><Columns3/></button><button aria-label="Expand table"><Expand/></button></div></div>
      <SellerTable rows={rows} selected={selected} setSelected={setSelected} toggleAll={toggleAll} menu={menu} setMenu={setMenu} menuRef={menuRef} onAction={setModal} onOpenSeller={id=>router.push(`/admin/marketplace/sellers/${encodeURIComponent(id)}`)}/>
        {rows.length>0&&<footer className={styles.pagination}><span>Showing 1 to {rows.length} of 142 sellers</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button>{[1,2,3].map(n=><button className={page===n?styles.current:""} key={n} onClick={()=>setPage(n)}>{n}</button>)}<span>…</span><button onClick={()=>setPage(36)}>36</button><button onClick={()=>setPage(p=>p+1)}>Next</button></div></footer>}
      </section>
    </div><OperationalRail data={data} onAction={setModal}/></div>
    {(modal||advanced||columnsOpen)&&<SellerModal type={advanced?"More Filters":columnsOpen?"Table Columns":modal} data={data} selected={selected} onClose={()=>{setModal(null);setAdvanced(false);setColumnsOpen(false)}} onConfirm={previewAction}/>} 
  </main>;
}

function ContextBar({data,refreshing,onRefresh}){const icons=[UserRound,Building2,Store,Share2,Globe2,BadgeDollarSign,CalendarDays];return <section className={styles.context}><div>{Object.entries(data.context).map(([key,value],index)=>{const Icon=icons[index];return <div key={key}><Icon/><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{value}</strong></div>})}</div><footer><LockKeyhole/>Access limited to assigned business context <aside><i/>Live data <small>Last updated: {data.lastUpdated}</small><button aria-label="Refresh sellers" disabled={refreshing} onClick={onRefresh}><RefreshCw className={refreshing?styles.spin:""}/></button></aside></footer></section>}

function PerformanceTrend({data}){return <div className={styles.trendBody}><dl><div><dt>GMV</dt><dd>LKR 45.2M</dd><em>↑ 12.4%</em></div><div><dt>Fulfilment</dt><dd>93.4%</dd><em>↑ 2.1 pp</em></div><div><dt>Cancellation</dt><dd>2.8%</dd><em>↓ 0.6 pp</em></div><div><dt>Returns</dt><dd>3.6%</dd><em>↓ 0.4 pp</em></div></dl><div className={styles.chartCanvas} role="img" aria-label="Seller performance trend"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:12,right:12,left:-22,bottom:0}}><CartesianGrid stroke="#eee" vertical={false}/><XAxis dataKey="date" tick={{fontSize:9}}/><YAxis yAxisId="left" tick={{fontSize:9}} domain={[0,10]}/><YAxis yAxisId="right" orientation="right" tick={{fontSize:9}} domain={[0,100]}/><Tooltip/><Legend wrapperStyle={{fontSize:9,top:-5}}/><Line yAxisId="left" type="monotone" dataKey="gmv" stroke="#831126" dot={false} strokeWidth={2}/><Line yAxisId="right" type="monotone" dataKey="fulfilment" stroke="#27933b" dot={false}/><Line yAxisId="left" type="monotone" dataKey="cancellation" stroke="#f39a00" dot={false}/><Line yAxisId="left" type="monotone" dataKey="returns" stroke="#3271c8" dot={false}/></LineChart></ResponsiveContainer></div></div>}

function RiskDistribution({data}){return <div className={styles.riskBody}><div className={styles.donut}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="label" innerRadius={55} outerRadius={78} startAngle={90} endAngle={-270} stroke="#fff"><Cell fill="#299436"/><Cell fill="#f3a000"/><Cell fill="#eb391c"/><Cell fill="#9a001d"/></Pie><Tooltip/></PieChart></ResponsiveContainer><span><b>142</b>Total</span></div><ul>{data.map(item=><li key={item.label}><i style={{background:item.color}}/><span>{item.label}</span><b>{item.value}</b><em>{item.percent}%</em></li>)}</ul></div>}

function Scorecard({items}){return <section className={`${styles.card} ${styles.scorecard}`}><h2>Seller Performance Scorecard <span title="Performance across the last 30 days">ⓘ</span></h2><div>{items.map(item=><article key={item.label}><span>{item.label}</span><p><strong>{item.value}%</strong><em className={item.negative?styles.negative:styles.positive}>{item.negative?"↓":"↑"} {item.change}</em></p><b className={item.status==="Watch"?styles.watch:styles.good}>{item.status}</b></article>)}</div></section>}

function SellerTable({rows,selected,setSelected,toggleAll,menu,setMenu,menuRef,onAction,onOpenSeller}){
  if(!rows.length)return <div className={styles.empty}><Users/><h3>No sellers match these filters</h3><p>Clear or adjust the current search and status filters.</p></div>;
  const heads=["Seller","Seller ID","Seller Type","Business Unit","Channels","Active Listings","Orders","GMV","Avg. Order Value","Fulfilment Rate","Cancellation Rate","Return Rate","Customer Rating","SLA Breaches","Policy Findings","Settlement Status","Risk Level","Seller Status","Assigned Manager","Last Activity","Action"];
  const detailActions=["View Seller","View Performance","Review Seller"];
  return <div className={styles.tableWrap}><table><thead><tr><th><input aria-label="Select all sellers" type="checkbox" checked={selected.length===rows.length} onChange={toggleAll}/></th>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><input aria-label={`Select ${row.name}`} type="checkbox" checked={selected.includes(row.id)} onChange={()=>setSelected(items=>items.includes(row.id)?items.filter(id=>id!==row.id):[...items,row.id])}/></td><td><Link className={styles.sellerLink} href={`/admin/marketplace/sellers/${encodeURIComponent(row.id)}`}>{row.name}</Link></td><td><Link className={styles.sellerLink} href={`/admin/marketplace/sellers/${encodeURIComponent(row.id)}`}>{row.id}</Link></td><td>{row.type}</td><td>{row.unit}</td><td>{row.channels}</td><td>{row.listings}</td><td>{row.orders}</td><td><b>{row.gmv}</b></td><td>{row.aov}</td><td>{row.fulfilment}</td><td>{row.cancellation}</td><td>{row.returns}</td><td>{row.rating}</td><td>{row.sla}</td><td>{row.findings}</td><td><Badge value={row.settlement}/></td><td><Badge value={row.risk}/></td><td><Badge value={row.status}/></td><td>{row.manager}</td><td>{row.activity}</td><td className={styles.actionCell}><button aria-label={`Actions for ${row.name}`} onClick={()=>setMenu(menu===row.id?null:row.id)}><MoreHorizontal/></button>{menu===row.id&&<div ref={menuRef} className={styles.rowMenu}>{[...detailActions,"Compare Seller","View Listings","View Settlements","Suspend Seller"].map(action=><button key={action} onClick={()=>{setMenu(null);detailActions.includes(action)?onOpenSeller(row.id):onAction(`${action}: ${row.name}`)}}>{action}</button>)}</div>}</td></tr>)}</tbody></table></div>
}

function Badge({value}){const tone=["Active","Clear","Low"].includes(value)?"success":["High","Exception","Suspended"].includes(value)?"danger":["Medium","Pending","Under Review"].includes(value)?"warning":"neutral";return <span className={`${styles.badge} ${styles[tone]}`}>{value}</span>}

function OperationalRail({data,onAction}){return <aside className={styles.rail}><RailCard title="Marketplace Seller Health" mark="A"><div className={styles.healthScore}><strong>87</strong><span>/100</span><em>● Stable</em></div>{data.health.map(item=><Progress key={item.label} label={item.label} value={item.value}/>)}</RailCard><RailCard title="Priority Seller Alerts" mark="B" action="View All"><div className={styles.alerts}>{data.alerts.map(item=><button className={styles[item.tone]} key={item.title} onClick={()=>onAction(item.action)}><AlertTriangle/><span><b>{item.title}</b><small>{item.detail}</small></span><em>{item.action}</em></button>)}</div></RailCard><RailCard title="Seller Status Summary" mark="C"><div className={styles.summaryGrid}>{[["Active",126],["Under Review",12],["High Risk",9],["Restricted",5],["Suspended",4],["New This Month",6]].map(([a,b])=><p key={a}><span>● {a}</span><b>{b}</b></p>)}</div></RailCard><RailCard title="Marketplace SLA Summary" mark="D">{[["Order acceptance",96],["Fulfilment confirmation",93],["Dispatch",92],["Customer response",90],["Return response",88],["Dispute response",85]].map(x=><Progress key={x[0]} label={x[0]} value={x[1]}/>)}</RailCard><RailCard title="Financial Reliability" mark="E">{[["Total Settlements","LKR 31.6M"],["Pending Settlements","LKR 6.82M"],["Exceptions","LKR 420,000"],["Refund Liability","LKR 1.24M"],["Chargebacks","LKR 185,000"],["Reconciliation Rate","98.6%"]].map(([a,b])=><p className={styles.money} key={a}><span>{a}</span><b>{b}</b></p>)}</RailCard><RailCard title="Quick Queues" mark="F"><div className={styles.queues}>{[["High-Risk Sellers",9],["SLA Breaches",23],["Settlement Exceptions",7],["Policy Findings",14],["Rating Deteriorations",8],["Verification Expiring",11]].map(([a,b])=><button key={a} onClick={()=>onAction(a)}><span>{a}</span><b>{b}</b><ChevronRight/></button>)}</div></RailCard></aside>}

function RailCard({title,mark,action,children}){return <section className={styles.railCard}><header><h2><i>{mark}</i>{title}</h2>{action&&<button>{action}</button>}</header>{children}</section>}
function Progress({label,value}){return <div className={styles.progress}><p><span>{label}</span><b>{value}%</b></p><i><b style={{width:`${value}%`}}/></i></div>}

function SellerModal({type,data,selected,onClose,onConfirm}){const [busy,setBusy]=useState(false);const [reason,setReason]=useState("");const [error,setError]=useState("");const sensitive=/Suspend|Bulk/.test(type??"");const confirm=async()=>{if(sensitive&&!reason.trim()){setError("An audit reason is required.");return}setBusy(true);try{await onConfirm(type,selected)}finally{setBusy(false)}};return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="seller-modal-title"><header><div><small>Marketplace Sellers · Frontend Preview</small><h2 id="seller-modal-title">{type}</h2></div><button aria-label="Close dialog" onClick={onClose}><X/></button></header><div className={styles.modalBody}>{type==="Compare Sellers"?<><p>Select at least two sellers from the table to compare performance, risk, SLA and financial reliability.</p><div className={styles.compareGrid}>{data.sellers.filter(row=>selected.length?selected.includes(row.id):true).slice(0,2).map(row=><article key={row.id}><h3>{row.name}</h3><p>GMV <b>{row.gmv}</b></p><p>Fulfilment <b>{row.fulfilment}</b></p><p>Risk <Badge value={row.risk}/></p></article>)}</div></>:type==="More Filters"?<div className={styles.formGrid}>{filters.map(label=><label key={label}>{label}<select><option>All</option><option>Requires attention</option></select></label>)}</div>:type==="Table Columns"?<div className={styles.checkGrid}>{["Seller ID","Seller Type","Business Unit","Channels","Orders","GMV","Fulfilment","Risk","Status","Last Activity"].map(label=><label key={label}><input type="checkbox" defaultChecked/>{label}</label>)}</div>:type==="Add Marketplace Seller"?<div className={styles.formGrid}>{["Legal seller name","Business registration","Seller type","Business unit","Sales channel","Assigned manager"].map(label=><label key={label}>{label}<input placeholder={label}/></label>)}</div>:type==="Save View"?<label className={styles.singleField}>View name<input placeholder="My seller view"/></label>:<><p>This action is available as a safe frontend workflow. The repository does not contain a seller mutation endpoint.</p><label className={styles.singleField}>Internal note or audit reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label></>}{error&&<p className={styles.formError} role="alert">{error}</p>}</div><footer><button onClick={onClose} disabled={busy}>Cancel</button><button className={styles.primary} onClick={()=>void confirm()} disabled={busy}>{busy?"Saving…":"Confirm"}</button></footer></section></div>}

function SellerLoading(){return <div className={styles.loading} role="status" aria-label="Loading seller marketplace performance"><div/><section>{Array.from({length:12},(_,i)=><i key={i}/>)}</section><div/><div/></div>}
