"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, CalendarDays, ChevronDown, ChevronRight, CircleDollarSign, Download, LockKeyhole, PackageCheck, RefreshCw, Search, ShieldAlert, Star, UserRound, Users } from "lucide-react";
import { CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import toast from "react-hot-toast";
import { useMarketplaceSellers } from "@/hooks/admin/useMarketplaceSellers";
import { exportMarketplaceSellers } from "@/services/api/marketplaceSellersService";
import styles from "./seller-marketplace-performance.module.css";

const tabs = [["all","All Sellers"],["active","Active"],["under-review","Under Review"],["high-risk","High Risk"],["suspended","Suspended"],["new","New Sellers"]];
const kpiIcons = [UserRound, Star, ShieldAlert, AlertTriangle, CircleDollarSign, CircleDollarSign, PackageCheck, AlertTriangle, RefreshCw, Star, ShieldAlert, AlertTriangle];
const colors = { low:"#299436", medium:"#f3a000", high:"#eb391c", critical:"#9a001d" };

const titleCase = value => value ? value.replaceAll("-"," ").replace(/\b\w/g, c => c.toUpperCase()) : "Not available";
const money = metric => metric?.available ? new Intl.NumberFormat("en-LK", { style:"currency", currency:metric.currency, maximumFractionDigits:0 }).format(metric.value) : "Not available";
const metricValue = metric => {
  if (!metric?.available) return "Not available";
  if (metric.format === "money") return new Intl.NumberFormat("en-LK", { style:"currency", currency:metric.currency, notation:"compact", maximumFractionDigits:1 }).format(metric.value);
  if (metric.format === "percent") return `${metric.value}%`;
  return new Intl.NumberFormat("en-LK", { maximumFractionDigits:2 }).format(metric.value);
};

export function SellerMarketplacePerformanceView() {
  const router=useRouter(), pathname=usePathname(), searchParams=useSearchParams();
  const paramsKey=searchParams.toString();
  const filters=useMemo(()=>({status:searchParams.get("status")||"all",search:searchParams.get("search")||"",riskLevel:searchParams.get("riskLevel")||undefined,currency:searchParams.get("currency")||undefined,dateFrom:searchParams.get("dateFrom")||undefined,dateTo:searchParams.get("dateTo")||undefined,sortBy:searchParams.get("sortBy")||"updatedAt",sortDirection:searchParams.get("sortDirection")||"desc",page:Number(searchParams.get("page")||1),perPage:Number(searchParams.get("perPage")||25)}),[paramsKey]); // eslint-disable-line react-hooks/exhaustive-deps
  const [search,setSearch]=useState(filters.search), [selected,setSelected]=useState([]), [exporting,setExporting]=useState(false), [compareOpen,setCompareOpen]=useState(false);
  const {data,loading,refreshing,error,stale,refresh}=useMarketplaceSellers(filters);
  const setFilter=(name,value,reset=true)=>{const next=new URLSearchParams(searchParams.toString());value&&value!=="all"?next.set(name,String(value)):next.delete(name);if(reset&&name!=="page")next.delete("page");router.replace(`${pathname}${next.size?`?${next}`:""}`,{scroll:false});};
  useEffect(()=>setSearch(filters.search),[filters.search]);
  useEffect(()=>{const timer=window.setTimeout(()=>{if(search!==filters.search)setFilter("search",search)},350);return()=>window.clearTimeout(timer)},[search,filters.search]); // eslint-disable-line react-hooks/exhaustive-deps
  const runExport=async()=>{setExporting(true);try{await exportMarketplaceSellers(filters);toast.success("Seller performance report exported")}catch(e){toast.error(e instanceof Error?e.message:"Export failed")}finally{setExporting(false)}};
  if(loading&&!data)return <SellerLoading/>;
  if(error&&!data)return <State icon={ShieldAlert} title="Seller Marketplace Performance" message={error}><button onClick={()=>void refresh()}>Retry</button></State>;
  if(!data)return <State icon={Users} title="No seller performance data" message="No sellers are available for this business context."/>;
  if(data.permissions?.canView===false)return <State icon={LockKeyhole} title="Permission required" message="Your role cannot access Marketplace seller performance."/>;
  const allSelected=data.items.length>0&&data.items.every(row=>selected.includes(row.id));
  return <main className={styles.page}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><span>Sellers</span></nav>
    <header className={styles.header}><div><h1>Seller Marketplace Performance</h1><p>Live seller, order, listing, risk, rating and settlement data for the selected period.</p></div><div className={styles.headerActions}><button disabled={!data.permissions.canExport||exporting} onClick={()=>void runExport()}><Download/>{exporting?"Exporting…":"Export Performance Report"}</button><button disabled={selected.length<2} onClick={()=>setCompareOpen(true)}><Users/>Compare Sellers</button><button disabled title="No approved seller state-transition workflow is defined">Seller Actions<ChevronDown/></button><button className={styles.primary} disabled title="Seller onboarding is not exposed by the current backend">Add Marketplace Seller</button></div></header>
    <ContextBar data={data} refreshing={refreshing} stale={stale} onRefresh={()=>void refresh(true)}/>
    <div className={styles.layout}><div className={styles.workspace}>
      <section className={styles.kpis} aria-label="Seller performance metrics">{data.kpis.map((kpi,index)=>{const Icon=kpiIcons[index]||UserRound;return <article key={kpi.id} title={kpi.reason||kpi.definition}><span className={`${styles.kpiIcon} ${styles[index%2?"amber":"burgundy"]}`}><Icon/></span><div><small>{kpi.label}</small><strong>{metricValue(kpi)}</strong><em>{kpi.available?"Current period":titleCase(kpi.reason)}</em></div></article>})}</section>
      <section className={styles.charts}><article className={styles.card}><header className={styles.cardHeader}><h2>Seller Performance Trend</h2><div className={styles.segmented}><button aria-pressed="true">Daily</button>{["Weekly","Monthly","Quarterly","Custom"].map(x=><button disabled title="The backend currently exposes daily aggregation only" key={x}>{x}</button>)}<button disabled aria-label="Choose custom period"><CalendarDays/></button></div></header><PerformanceTrend trend={data.trend}/></article><article className={styles.card}><header className={styles.cardHeader}><h2>Seller Risk Distribution</h2></header><RiskDistribution data={data.risks}/></article></section>
      <Scorecard items={data.scorecards}/>
      <section className={`${styles.card} ${styles.sellerCard}`}>
        <div className={styles.tabs} role="tablist" aria-label="Seller status">{tabs.map(([id,label])=><button role="tab" aria-selected={filters.status===id} key={id} onClick={()=>setFilter("status",id)}>{label}</button>)}</div>
        <div className={styles.filters}><div className={styles.filterTop}><label className={styles.search}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search seller name or ID…"/></label><select aria-label="Risk level" value={filters.riskLevel||"all"} onChange={e=>setFilter("riskLevel",e.target.value)}><option value="all">All risk levels</option>{["low","medium","high","critical"].map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select><select aria-label="Currency" value={filters.currency||""} onChange={e=>setFilter("currency",e.target.value)}><option value="">Automatic currency</option>{data.availableCurrencies.map(x=><option key={x}>{x}</option>)}</select><button className={styles.clear} onClick={()=>{setSearch("");router.replace(pathname,{scroll:false})}}>Clear All</button><span>Sort By</span><select value={filters.sortBy} onChange={e=>setFilter("sortBy",e.target.value)}><option value="updatedAt">Last Activity</option><option value="name">Seller Name</option><option value="orders">Orders</option><option value="gmv">GMV</option><option value="rating">Rating</option><option value="risk">Risk</option></select><button aria-label="Refresh table" onClick={()=>void refresh(true)}><RefreshCw className={refreshing?styles.spin:""}/></button></div></div>
        <div className={styles.tableTitle}><h2>Seller Marketplace Performance</h2><div><span>{data.meta.from??0}–{data.meta.to??0} of {data.meta.total} sellers</span><button disabled={selected.length<2} onClick={()=>setCompareOpen(true)}><Users/>Compare</button></div></div>
        <SellerTable rows={data.items} currency={data.context.currency} selected={selected} setSelected={setSelected} allSelected={allSelected}/>
        <Pagination meta={data.meta} onPage={page=>setFilter("page",page,false)}/>
      </section>
    </div><OperationalRail data={data}/></div>
    {compareOpen&&<CompareDialog rows={data.items.filter(row=>selected.includes(row.id))} onClose={()=>setCompareOpen(false)}/>} 
  </main>;
}

function ContextBar({data,refreshing,stale,onRefresh}){const c=data.context;return <section className={styles.context}><div>{[["Tenant",c.tenant],["Ecosystem",c.ecosystem],["Country",c.country||"All countries"],["Currency",c.currency||"Select currency"],["Date range",`${c.dateFrom} – ${c.dateTo}`],["Timezone",c.timezone]].map(([k,v])=><div key={k}><UserRound/><span>{k}</span><strong>{v}</strong></div>)}</div><footer><LockKeyhole/>Access limited to authenticated administrators <aside><i/><b>{stale?"Stale":"Live polling"}</b><small>Last updated: {new Date(data.meta.dataAsOf).toLocaleString()}</small><button aria-label="Refresh sellers" disabled={refreshing} onClick={onRefresh}><RefreshCw className={refreshing?styles.spin:""}/></button></aside></footer></section>}
function PerformanceTrend({trend}){if(!trend.available)return <div className={styles.empty}><p>Not available: {titleCase(trend.reason)}</p></div>;if(!trend.items.length)return <div className={styles.empty}><p>Insufficient data for the selected period.</p></div>;return <div className={styles.trendBody}><div className={styles.chartCanvas} role="img" aria-label={`Daily seller GMV in ${trend.currency} and cancellation rate`}><ResponsiveContainer width="100%" height="100%"><LineChart data={trend.items}><CartesianGrid stroke="#eee" vertical={false}/><XAxis dataKey="period" tick={{fontSize:9}}/><YAxis yAxisId="money" tick={{fontSize:9}}/><YAxis yAxisId="rate" orientation="right" tick={{fontSize:9}}/><Tooltip formatter={(value,name)=>name==="gmv"?new Intl.NumberFormat("en-LK",{style:"currency",currency:trend.currency}).format(value):`${value}%`}/><Legend/><Line yAxisId="money" type="monotone" dataKey="gmv" stroke="#831126" dot={false}/><Line yAxisId="rate" type="monotone" dataKey="cancellationRate" stroke="#f39a00" dot={false}/></LineChart></ResponsiveContainer></div></div>}
function RiskDistribution({data}){const total=data.reduce((n,x)=>n+x.count,0);if(!total)return <div className={styles.empty}><p>No active supplier risk assessments are available.</p></div>;return <div className={styles.riskBody}><div className={styles.donut}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="count" nameKey="level" innerRadius={55} outerRadius={78} startAngle={90} endAngle={-270}>{data.map(x=><Cell key={x.level} fill={colors[x.level]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><span><b>{total}</b>Assessed</span></div><ul>{data.map(x=><li key={x.level}><i style={{background:colors[x.level]}}/><span>{titleCase(x.level)} risk</span><b>{x.count}</b><em>{x.percentage}%</em></li>)}</ul></div>}
function Scorecard({items}){return <section className={`${styles.card} ${styles.scorecard}`}><h2>Seller Performance Scorecard</h2><div>{items.map(item=><article key={item.id} title={item.reason}><span>{item.label}</span><p><strong>{item.available?`${item.value}%`:"Not available"}</strong></p><b className={styles.neutral}>{item.available?titleCase(item.status):"Formula required"}</b></article>)}</div></section>}
function SellerTable({rows,selected,setSelected,allSelected}){if(!rows.length)return <div className={styles.empty}><Users/><h3>No sellers match these filters</h3><p>Clear or adjust the current search and filters.</p></div>;const toggleAll=()=>setSelected(allSelected?selected.filter(id=>!rows.some(r=>r.id===id)):[...new Set([...selected,...rows.map(r=>r.id)])]);return <div className={styles.tableWrap}><table><thead><tr><th><input aria-label="Select all sellers" type="checkbox" checked={allSelected} onChange={toggleAll}/></th>{["Seller","Seller ID","Type","Country","Active Listings","Orders","GMV","Average Order Value","Fulfilment","Cancellation","Returns","Rating","SLA Breaches","Policy Findings","Risk","Status","Verification","Last Activity"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><input aria-label={`Select ${row.name}`} type="checkbox" checked={selected.includes(row.id)} onChange={()=>setSelected(ids=>ids.includes(row.id)?ids.filter(id=>id!==row.id):[...ids,row.id])}/></td><td><Link className={styles.sellerLink} href={`/admin/marketplace/sellers/${row.id}`}>{row.name}</Link></td><td>{row.sellerCode}</td><td>{row.type||"Not available"}</td><td>{row.country||"Not available"}</td><td>{row.activeListings}</td><td>{row.orders}</td><td><b>{money(row.gmv)}</b></td><td>{money(row.aov)}</td><td>{displayRate(row.fulfilmentRate)}</td><td>{displayRate(row.cancellationRate)}</td><td>{displayRate(row.returnRate)}</td><td>{row.rating.available?row.rating.value:"Not available"}</td><td>{row.slaBreaches.available?row.slaBreaches.value:"Not available"}</td><td>{row.policyFindings.available?row.policyFindings.value:"Not available"}</td><td><Badge value={row.riskLevel}/></td><td><Badge value={row.status}/></td><td><Badge value={row.verificationStatus}/></td><td>{row.lastActivityAt?new Date(row.lastActivityAt).toLocaleString():"Not available"}</td></tr>)}</tbody></table></div>}
const displayRate=m=>m?.available?`${m.value}%`:"Not available";
function Badge({value}){if(!value)return <span className={`${styles.badge} ${styles.neutral}`}>Not available</span>;const tone=["active","approved","low"].includes(value)?"success":["high","critical","suspended","rejected"].includes(value)?"danger":["medium","pending"].includes(value)?"warning":"neutral";return <span className={`${styles.badge} ${styles[tone]}`}>{titleCase(value)}</span>}
function Pagination({meta,onPage}){if(meta.totalPages<=1)return null;return <footer className={styles.pagination}><span>Showing {meta.from??0} to {meta.to??0} of {meta.total} sellers</span><div><button disabled={meta.page===1} onClick={()=>onPage(meta.page-1)}>Previous</button><button className={styles.current}>{meta.page}</button><button disabled={meta.page===meta.totalPages} onClick={()=>onPage(meta.page+1)}>Next</button></div></footer>}
function OperationalRail({data}){return <aside className={styles.rail}><RailCard title="Marketplace Seller Health"><Unavailable block={data.health}/></RailCard><RailCard title="Priority Seller Alerts">{data.alerts.length?<div className={styles.alerts}>{data.alerts.map(x=><Link className={styles[x.severity]} key={x.id} href={x.href}><AlertTriangle/><span><b>{x.title}</b><small>{x.detail}</small></span></Link>)}</div>:<p>No active seller alerts.</p>}</RailCard><RailCard title="Seller Status Summary"><div className={styles.summaryGrid}>{Object.entries(data.statusSummary).map(([k,v])=><p key={k}><span>{titleCase(k.replace(/([A-Z])/g,"-$1"))}</span><b>{v}</b></p>)}</div></RailCard><RailCard title="Marketplace SLA Summary"><Unavailable block={data.sla}/></RailCard><RailCard title="Financial Reliability">{data.financial.available?<>{[["Total settlements",data.financial.total],["Pending settlements",data.financial.pending],["Settlement exceptions",data.financial.exceptions],["Refund liability",data.financial.refundLiability]].map(([k,v])=><p className={styles.money} key={k}><span>{k}</span><b>{new Intl.NumberFormat("en-LK",{style:"currency",currency:data.financial.currency,maximumFractionDigits:0}).format(v)}</b></p>)}</>:<Unavailable block={data.financial}/>}</RailCard><RailCard title="Quick Queues"><div className={styles.queues}>{data.quickQueues.map(x=><Link key={x.id} href={x.href}><span>{x.label}</span><b>{x.count}</b><ChevronRight/></Link>)}</div></RailCard></aside>}
function RailCard({title,children}){return <section className={styles.railCard}><header><h2>{title}</h2></header>{children}</section>}
function Unavailable({block}){return <div className={styles.empty}><p>{block.available===false?`Not available: ${titleCase(block.reason)}`:"Insufficient data"}</p></div>}
function CompareDialog({rows,onClose}){return <div className={styles.backdrop} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={styles.modal} role="dialog" aria-modal="true"><header><h2>Compare Sellers</h2><button onClick={onClose}>Close</button></header><div className={styles.compareGrid}>{rows.map(row=><article key={row.id}><h3>{row.name}</h3><p>GMV <b>{money(row.gmv)}</b></p><p>Orders <b>{row.orders}</b></p><p>Cancellation <b>{displayRate(row.cancellationRate)}</b></p><p>Risk <Badge value={row.riskLevel}/></p></article>)}</div></section></div>}
function SellerLoading(){return <main className={`${styles.page} ${styles.loading}`} aria-busy="true"><div/><div/><div/><div/></main>}
function State({icon:Icon,title,message,children}){return <section className={styles.state} role="alert"><Icon/><h1>{title}</h1><p>{message}</p>{children}</section>}
