import { ReturnRefundCase, SelectedReturnRefundCaseDetailsData, ReturnsRefundOperationsRailData } from "./types";

export const MOCK_RETURN_REFUND_CASES: ReturnRefundCase[] = [
  {
    id: "CS-2026-008315",
    reference: "CS-2026-008315",
    customerName: "Anila Perera",
    customerId: "CUS-8315",
    isVip: true,
    priority: "High",
    issueType: "Refund Delay",
    caseStatus: "Refund Pending",
    relatedOrderId: "ORD-1029381",
    returnRef: "RET-2026-7831",
    returnStatus: "Completed",
    pickupStatus: "Collected",
    inspectionStatus: "Inspection Pass",
    refundRef: "RFD-2026-4421",
    refundStatus: "Refund Pending",
    refundAmount: "LKR 12,450.00",
    disputeStatus: "Dispute Open",
    eligibility: "Eligible",
    supplier: "GlowLine",
    dependency: "Waiting Finance",
    sentiment: "Concerned",
    risk: "High",
    slaStatus: "At Risk",
    assignedAgent: "Sarah K.",
    assignedTeam: "Returns Team A",
    lastCustomerUpdate: "May 1, 10:21 AM",
    age: "1d 6h",
  },
  {
    id: "CS-2026-008210",
    reference: "CS-2026-008210",
    customerName: "Dulani Silva",
    customerId: "CUS-8210",
    isVip: false,
    priority: "High",
    issueType: "Return Request",
    caseStatus: "Pickup Open",
    relatedOrderId: "ORD-1029445",
    returnRef: "RET-2026-7108",
    returnStatus: "Requested",
    pickupStatus: "Pending Pickup",
    inspectionStatus: "—",
    refundRef: "—",
    refundStatus: "Pending",
    refundAmount: "—",
    disputeStatus: "No Dispute",
    eligibility: "Eligible",
    supplier: "BeautyHub",
    dependency: "Waiting Logistics",
    sentiment: "Neutral",
    risk: "Medium",
    slaStatus: "On Track",
    assignedAgent: "Nimal R.",
    assignedTeam: "Returns Team B",
    lastCustomerUpdate: "Apr 30, 08:14 PM",
    age: "2d 2h",
  },
  {
    id: "CS-2026-008176",
    reference: "CS-2026-008176",
    customerName: "Ravi Ahmed",
    customerId: "CUS-8176",
    isVip: false,
    priority: "High",
    issueType: "Inspection Issue",
    caseStatus: "Inspection",
    relatedOrderId: "ORD-1029517",
    returnRef: "RET-2026-7111",
    returnStatus: "In Transit",
    pickupStatus: "Collected",
    inspectionStatus: "Inspection Pending",
    refundRef: "—",
    refundStatus: "Pending",
    refundAmount: "—",
    disputeStatus: "No Dispute",
    eligibility: "Under Review",
    supplier: "GlowLine",
    dependency: "Waiting Inspection",
    sentiment: "Concerned",
    risk: "High",
    slaStatus: "At Risk",
    assignedAgent: "Chandana D.",
    assignedTeam: "Returns Team A",
    lastCustomerUpdate: "Apr 29, 05:00 PM",
    age: "3d 7h",
  },
  {
    id: "CS-2026-008051",
    reference: "CS-2026-008051",
    customerName: "Tharushi Bandara",
    customerId: "CUS-8051",
    isVip: false,
    priority: "High",
    issueType: "Refund Failed",
    caseStatus: "Refund Failed",
    relatedOrderId: "ORD-1029192",
    returnRef: "RET-2026-7322",
    returnStatus: "Delivered",
    pickupStatus: "Collected",
    inspectionStatus: "Inspection Pass",
    refundRef: "RFD-2026-4319",
    refundStatus: "Refund Failed",
    refundAmount: "LKR 5,810.00",
    disputeStatus: "No Dispute",
    eligibility: "Eligible",
    supplier: "BeautyHub",
    dependency: "Finance Failed",
    sentiment: "Concerned",
    risk: "High",
    slaStatus: "At Risk",
    assignedAgent: "Sanjeewa M.",
    assignedTeam: "Returns Team B",
    lastCustomerUpdate: "Apr 29, 09:20 PM",
    age: "3d 5h",
  },
  {
    id: "CS-2026-007942",
    reference: "CS-2026-007942",
    customerName: "Nadeesha Wick",
    customerId: "CUS-7942",
    isVip: false,
    priority: "High",
    issueType: "Exchange Request",
    caseStatus: "Refund Approved",
    relatedOrderId: "ORD-1029355",
    returnRef: "RET-2026-7355",
    returnStatus: "Delivered",
    pickupStatus: "Collected",
    inspectionStatus: "Inspection Pass",
    refundRef: "RFD-2026-4195",
    refundStatus: "Refund Approved",
    refundAmount: "LKR 3,680.00",
    disputeStatus: "No Dispute",
    eligibility: "Eligible",
    supplier: "GlowLine",
    dependency: "Waiting Customer",
    sentiment: "Satisfied",
    risk: "Medium",
    slaStatus: "On Track",
    assignedAgent: "Ravishi P.",
    assignedTeam: "Returns Team A",
    lastCustomerUpdate: "Apr 29, 10:15 AM",
    age: "4d 20h",
  },
  {
    id: "CS-2026-007914",
    reference: "CS-2026-007914",
    customerName: "Kavindu Perera",
    customerId: "CUS-7914",
    isVip: false,
    priority: "High",
    issueType: "Customer Dispute",
    caseStatus: "Dispute Review",
    relatedOrderId: "ORD-1029132",
    returnRef: "RET-2026-7444",
    returnStatus: "Delivered",
    pickupStatus: "Collected",
    inspectionStatus: "Inspection Fail",
    refundRef: "—",
    refundStatus: "—",
    refundAmount: "—",
    disputeStatus: "Dispute Open",
    eligibility: "Not Eligible",
    supplier: "BeautyHub",
    dependency: "Waiting Supplier",
    sentiment: "Very Concerned",
    risk: "High",
    slaStatus: "At Risk",
    assignedAgent: "Janith T.",
    assignedTeam: "Returns Team A",
    lastCustomerUpdate: "Apr 28, 09:17 AM",
    age: "4d 1h",
  },
];

export const MOCK_SELECTED_RETURN_CASE_DETAILS: SelectedReturnRefundCaseDetailsData = {
  caseInfo: MOCK_RETURN_REFUND_CASES[0],
  summaryMetrics: {
    caseAge: "1d 6h",
    returnAge: "4d",
    refundValue: "LKR 12,450",
    refundDelay: "26h",
    customerContactsCount: 3,
    currentDependency: "Finance",
    nextCustomerUpdate: "22m",
    caseHealthPercent: 84,
  },
  originalOrder: {
    orderId: "ORD-1029381",
    orderDate: "Apr 22, 2026",
    creditValue: "LKR 12,450.00",
    status: "Delivered",
    customer: "Anila Perera",
    returnableValue: "LKR 12,450.00",
  },
  returnDetails: {
    returnRef: "RET-2026-7831",
    reason: "Refund Delay",
    requestedDate: "Apr 24, 2026",
    returnStatus: "Pickup Open",
    eligibility: "Eligible",
    returnMethod: "Pickup",
    returnValue: "LKR 12,450",
  },
  reverseLogistics: {
    collectionStatus: "Collected",
    pickupDate: "May 1, 2026",
    carrier: "Maple Express",
    waybill: "MPG-487654321",
    warehouseReceipt: "WR-5650-091201",
    returnLogisticsSla: "On Track",
    lastLogisticsUpdate: "May 1, 11:05 AM",
  },
  inspection: {
    status: "Inspection Pass",
    result: "Approved",
    condition: "Good",
    packaging: "Yes",
    date: "May 1, 2026",
    inspector: "Nuwan S.",
    eligibilityResult: "Eligible",
  },
  refundDetails: {
    refundRef: "RFD-2026-4421",
    refundStatus: "Refund Pending",
    requestedAmount: "LKR 12,450.00",
    approvedAmount: "—",
    paymentMethod: "Apple Wallet",
    expectedCompletion: "May 3, 01:00 PM",
  },
  refundTimeline: {
    stages: [
      { label: "Return Received", timestamp: "May 1 07:12 AM", status: "completed" },
      { label: "Pickup", timestamp: "May 1 09:30 AM", status: "completed" },
      { label: "Received", timestamp: "May 1 11:05 AM", status: "completed" },
      { label: "Inspection", timestamp: "May 1 12:00 PM", status: "completed" },
      { label: "Refund Approved", timestamp: "May 1 12:45 PM", status: "completed" },
      { label: "Finance Processing", timestamp: "Waiting", status: "active" },
    ],
  },
  timingAnalysis: {
    expectedReturnCompletion: "May 1, 12:30 PM",
    actualReturnCompletion: "May 1, 11:05 AM",
    expectedRefundApproval: "May 1, 1:00 PM",
    actualRefundApproval: "May 1, 12:45 PM",
    expectedRefundCompletion: "May 3, 1:00 PM",
    currentRefundCommitment: "May 3, 1:00 PM",
    refundVariance: "+4h 00m",
    confidencePercent: 78,
  },
  eligibilityPolicy: {
    returnWindow: "Pass",
    productCondition: "Pass",
    productCategory: "Pass",
    fraudSafeEvaluation: "Pass",
    hygieneRestriction: "Pass",
    promotionalRestriction: "Pass",
    proofOfPurchase: "Pass",
    overallEligible: "Yes",
    policyCode: "RET-POL-v6",
  },
  disputeWorkspace: {
    disputeRef: "DSP-2026-001118",
    reason: "Refund Disputed",
    customerPosition: "Finance not processed",
    evidenceCompleteness: "70%",
    customerClaim: "Dispute Team",
    escalationLevel: "Level 2",
    decisionDue: "May 4, 2026",
  },
  investigationChecklist: [
    { label: "Website return eligibility", isCompleted: true },
    { label: "Verify eligibility documentation", isCompleted: true },
    { label: "Confirm inspection result", isCompleted: true },
    { label: "Confirm refund approval", isCompleted: true },
    { label: "Check finance progress", isCompleted: false },
    { label: "Customer communication", isCompleted: false },
    { label: "Close case & secure notes", isCompleted: false },
    { label: "QA case closure review", isCompleted: false },
  ],
  blockingIssues: {
    financeProcessing: "Pending",
    customerUpdateDue: "Due",
    inspectionPending: "No",
  },
  dependencies: {
    logistics: "Completed",
    warehouseQa: "Completed",
    finance: "Waiting",
    supplier: "Not Required",
    customer: "Awaiting Info",
    compliance: "Not Required",
  },
  financeEscalation: {
    escalationStatus: "Escalated",
    owner: "Finance Ops",
    reason: "Processing Delay > 24h",
    escalatedAt: "May 1, 01:10 PM",
    nextEscalation: "Level 3",
    due: "May 2, 01:10 PM",
  },
  recoveryPlan: {
    progressPercent: 46,
    steps: [
      { stepNumber: 1, label: "Contact Finance", status: "done" },
      { stepNumber: 2, label: "Confirm Payment", status: "in progress" },
      { stepNumber: 3, label: "Customer Notification", status: "in progress" },
      { stepNumber: 4, label: "Follow-up & Confirmation", status: "pending" },
      { stepNumber: 5, label: "Apology & Closure", status: "pending" },
      { stepNumber: 6, label: "Case Closure", status: "pending" },
    ],
  },
  customerCommunication: {
    latestMessage: "Hi, I returned the item but haven't received my refund yet.",
    sentiment: "Concerned",
    botArticleUsed: "Returns & Refund Policy",
    agentNotes: "Customer follow-up scheduled",
    customerFollowUp: "May 1, 09:52 AM",
    lastContact: "May 1, 09:52 AM",
  },
  customerImpact: {
    sentiment: "Concerned",
    repeatContactRisk: "Medium",
    churnRisk: "High",
    financialImpact: "Medium",
    reputationRisk: "Medium",
  },
  returnRefundSla: [
    { metric: "Response SLA", target: "24h", status: "Met" },
    { metric: "Pickup SLA", target: "24h", status: "Met" },
    { metric: "Inspection SLA", target: "24h", status: "Met" },
    { metric: "Refund Approval SLA", target: "24h", status: "Met" },
    { metric: "Finance Processing SLA", target: "24h", status: "At Risk" },
    { metric: "Refund Completion SLA", target: "48h", status: "At Risk" },
  ],
  exceptionHistory: [
    { dateTime: "May 1, 01:05 PM", exception: "Finance Processing Delay", status: "Open" },
    { dateTime: "Apr 30, 11:42 AM", exception: "Payment Gateway Retry", status: "Resolved" },
  ],
  repeatIssueAnalysis: {
    previousReturns90d: 1,
    productReturnRate: "3.2%",
    itemLevelOutcome: "Approved",
    exchangeEligibility: "Yes",
  },
};

export const MOCK_OPERATIONS_RAIL_DATA: ReturnsRefundOperationsRailData = {
  healthScore: 93,
  scoreLegend: [
    { label: "Excellent", range: "81–100", color: "text-emerald-600" },
    { label: "Good", range: "61–80", color: "text-blue-600" },
    { label: "Fair", range: "41–60", color: "text-amber-600" },
    { label: "Poor", range: "21–40", color: "text-orange-600" },
    { label: "Critical", range: "0–20", color: "text-red-600" },
  ],

  caseSummary: {
    open: 264,
    critical: 9,
    atRisk: 24,
    escalated: 13,
    reopened: 16,
  },

  returnSummary: {
    pending: 74,
    pickupDelayed: 28,
    inspectionPending: 36,
    rejected: 31,
  },

  refundSummary: {
    pending: 52,
    approved: 68,
    failed: 8,
    rejected: 10,
    partial: 14,
  },

  disputeSummary: {
    active: 21,
    highSeverity: 8,
    refundAmountCount: 6,
    awaitingDecision: 9,
  },

  dependencySummary: {
    waitingLogistics: 32,
    waitingFinance: 27,
    waitingSupplier: 18,
    waitingCustomer: 11,
  },

  quickQueues: [
    { label: "Critical Return Cases", count: 9, variant: "danger" },
    { label: "Pickup Delays", count: 28, variant: "warning" },
    { label: "Inspection Delays", count: 36, variant: "warning" },
    { label: "Refund Exceptions", count: 18, variant: "info" },
    { label: "Customer Disputes", count: 21, variant: "danger" },
    { label: "SLA At Risk", count: 24, variant: "warning" },
  ],
};
