'use client';
import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState}from'react';
import {fetchFinanceDashboard,fetchFinanceOperation,fetchFinanceOperations}from'@/services/api/financeCommandCenterService';
import type{FinanceDashboard,FinanceFilters,FinanceOperationDetail,FinanceOperationsResponse}from'@/types/financeCommandCenter';

type ContextValue={dashboard:FinanceDashboard|null;operations:FinanceOperationsResponse|null;detail:FinanceOperationDetail|null;filters:FinanceFilters;loading:boolean;refreshing:boolean;operationsLoading:boolean;detailLoading:boolean;error:Error|null;operationsError:Error|null;setFilters:(patch:Partial<FinanceFilters>)=>void;refresh:()=>void;selectRecord:(key:string|null)=>void};
const Context=createContext<ContextValue|null>(null);
const iso=(date:Date)=>date.toISOString().slice(0,10);
function initialFilters():FinanceFilters{const to=new Date(),from=new Date();from.setDate(to.getDate()-29);const query=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(window.location.search);return{dateFrom:query.get('dateFrom')||iso(from),dateTo:query.get('dateTo')||iso(to),currency:query.get('currency')||'LKR',search:query.get('search')||'',domain:query.get('domain')||'',status:query.get('status')||'',sort:query.get('sort')||'transactionDate',direction:query.get('direction')==='asc'?'asc':'desc',page:Number(query.get('page'))||1,perPage:Number(query.get('perPage'))||25};}
export function FinanceCommandCenterProvider({children}:{children:React.ReactNode}){const[filtersState,setFiltersState]=useState(initialFilters);const[dashboard,setDashboard]=useState<FinanceDashboard|null>(null),[operations,setOperations]=useState<FinanceOperationsResponse|null>(null),[detail,setDetail]=useState<FinanceOperationDetail|null>(null);const[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[operationsLoading,setOperationsLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false);const[error,setError]=useState<Error|null>(null),[operationsError,setOperationsError]=useState<Error|null>(null);const dashboardController=useRef<AbortController|null>(null),operationsController=useRef<AbortController|null>(null),detailController=useRef<AbortController|null>(null);const key=JSON.stringify(filtersState);
const load=useCallback(async(background=false)=>{dashboardController.current?.abort();const c=new AbortController();dashboardController.current=c;background?setRefreshing(true):setLoading(true);try{setDashboard(await fetchFinanceDashboard(filtersState,c.signal));setError(null)}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e:new Error('Unable to load finance data.'))}finally{if(!c.signal.aborted){setLoading(false);setRefreshing(false)}}},[key]);
const loadOperations=useCallback(async()=>{operationsController.current?.abort();const c=new AbortController();operationsController.current=c;setOperationsLoading(true);try{setOperations(await fetchFinanceOperations(filtersState,c.signal));setOperationsError(null)}catch(e){if(!c.signal.aborted)setOperationsError(e instanceof Error?e:new Error('Unable to load finance operations.'))}finally{if(!c.signal.aborted)setOperationsLoading(false)}},[key]);
useEffect(()=>{void load();void loadOperations();return()=>{dashboardController.current?.abort();operationsController.current?.abort()}},[load,loadOperations]);useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==='visible'){void load(true);void loadOperations()}},(dashboard?.meta.refreshIntervalSeconds??30)*1000);const visible=()=>{if(document.visibilityState==='visible'){void load(true);void loadOperations()}};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visible)}},[dashboard?.meta.refreshIntervalSeconds,load,loadOperations]);
const setFilters=useCallback((patch:Partial<FinanceFilters>)=>setFiltersState(current=>{const next={...current,...patch,page:patch.page??(Object.keys(patch).some(k=>!['page','sort','direction'].includes(k))?1:current.page)};if(typeof window!=='undefined'){const q=new URLSearchParams();Object.entries(next).forEach(([k,v])=>{if(v!==''&&v!==undefined)q.set(k,String(v))});window.history.replaceState(null,'',`${window.location.pathname}?${q}`)}return next}),[]);
const selectRecord=useCallback((recordKey:string|null)=>{detailController.current?.abort();if(!recordKey){setDetail(null);return}const c=new AbortController();detailController.current=c;setDetailLoading(true);void fetchFinanceOperation(recordKey,c.signal).then(setDetail).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e:new Error('Unable to load record detail.'))}).finally(()=>{if(!c.signal.aborted)setDetailLoading(false)})},[]);
const value=useMemo(()=>({dashboard,operations,detail,filters:filtersState,loading,refreshing,operationsLoading,detailLoading,error,operationsError,setFilters,refresh:()=>{void load(true);void loadOperations()},selectRecord}),[dashboard,operations,detail,filtersState,loading,refreshing,operationsLoading,detailLoading,error,operationsError,setFilters,load,loadOperations,selectRecord]);return<Context.Provider value={value}>{children}</Context.Provider>}
export function useFinanceCommandCenter(){const value=useContext(Context);if(!value)throw new Error('FinanceCommandCenterProvider is required');return value}
export function useOptionalFinanceCommandCenter(){return useContext(Context)}
