'use client';
import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState}from'react';
import type{FinanceAlertItem,FinanceContext,FinanceHealthScore,FinanceKpi,PaymentPortfolioRow,RevenueActivityItem,RevenuePortfolioRow}from'@/types/finance';
import{fetchPaymentsManagement,fetchRevenueReceivables,type FinancePageFilters}from'@/services/api/financeRevenuePaymentsService';
type PageData={context:FinanceContext;totals:Record<string,number>;rows:any[];alerts:FinanceAlertItem[];trend?:any[];statuses?:any[];methods?:any[];aging?:any[];capabilities:Record<string,boolean>;permissions:{canExport:boolean;canMutate:boolean};meta:{page:number;perPage:number;total:number;lastPage:number;generatedAt:string}};
type Value={data:PageData|null;filters:FinancePageFilters;loading:boolean;refreshing:boolean;error:Error|null;setFilters:(p:Partial<FinancePageFilters>)=>void;refresh:()=>void};
const RevenueContext=createContext<Value|null>(null),PaymentsContext=createContext<Value|null>(null);
const iso=(d:Date)=>d.toISOString().slice(0,10);function initial():FinancePageFilters{const to=new Date(),from=new Date();from.setDate(to.getDate()-29);return{dateFrom:iso(from),dateTo:iso(to),currency:'LKR',search:'',status:'',page:1,perPage:25}}
function Provider({children,kind}:{children:React.ReactNode;kind:'revenue'|'payments'}){const[filters,setState]=useState(initial),[data,setData]=useState<PageData|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<Error|null>(null);const ctl=useRef<AbortController|null>(null);const key=JSON.stringify(filters);const load=useCallback(async(bg=false)=>{ctl.current?.abort();const c=new AbortController();ctl.current=c;bg?setRefreshing(true):setLoading(true);try{setData(kind==='revenue'?await fetchRevenueReceivables(filters,c.signal):await fetchPaymentsManagement(filters,c.signal));setError(null)}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e:new Error('Unable to load finance data.'))}finally{if(!c.signal.aborted){setLoading(false);setRefreshing(false)}}},[kind,key]);useEffect(()=>{void load();return()=>ctl.current?.abort()},[load]);useEffect(()=>{const id=window.setInterval(()=>{if(document.visibilityState==='visible')void load(true)},30000);return()=>clearInterval(id)},[load]);const setFilters=useCallback((p:Partial<FinancePageFilters>)=>setState(x=>({...x,...p,page:p.page??1})),[]);const value=useMemo(()=>({data,filters,loading,refreshing,error,setFilters,refresh:()=>void load(true)}),[data,filters,loading,refreshing,error,setFilters,load]);const C=kind==='revenue'?RevenueContext:PaymentsContext;return<C.Provider value={value}>{children}</C.Provider>}
export function RevenueReceivablesProvider({children}:{children:React.ReactNode}){return<Provider kind="revenue">{children}</Provider>}export function PaymentsManagementProvider({children}:{children:React.ReactNode}){return<Provider kind="payments">{children}</Provider>}export function useRevenueReceivables(){const v=useContext(RevenueContext);if(!v)throw new Error('RevenueReceivablesProvider is required');return v}export function usePaymentsManagement(){const v=useContext(PaymentsContext);if(!v)throw new Error('PaymentsManagementProvider is required');return v}
const money=(n:number|undefined,c='LKR')=>n===undefined||n===null?'Not available':`${c} ${Number(n).toLocaleString('en-US',{maximumFractionDigits:2})}`;function kpi(id:string,num:number,iconName:string,title:string,subLabel:string,value:string,available=true):FinanceKpi{return{id,num,iconName,title,subLabel,value,delta:available?'Live':'Unavailable',isPositive:available,status:available?'positive':'neutral',sparkline:[]}}
export function revenueView(data:PageData|null){const t=data?.totals??{},c=data?.context.baseCurrency??'LKR';return{context:data?.context,kpis:[kpi('gmv',1,'ShoppingBag','GMV','Gross Merchandise Value',money(t.gmv,c)),kpi('gross_sales',2,'TrendingUp','Gross Sales','Before Deductions',money(t.grossSales,c)),kpi('net_sales',3,'DollarSign','Net Sales','After Discounts & Refunds',money(t.netSales,c)),kpi('recognized',4,'CheckCircle','Recognized Revenue','Recognition domain not configured','Not available',false),kpi('deferred',5,'Clock','Deferred Revenue','Recognition domain not configured','Not available',false),kpi('receivables',6,'FileText','Total Receivables','Outstanding Invoices',money(t.outstanding,c)),kpi('collections',7,'Wallet','Collections','Invoice Amount Paid',money(t.collections,c)),kpi('outstanding',8,'AlertCircle','Outstanding','Receivables Balance',money(t.outstanding,c)),kpi('discounts',9,'Tag','Discounts','Order Discounts',money(t.discounts,c)),kpi('refunds',10,'RotateCcw','Refunds','Completed Refunds',money(t.refunds,c)),kpi('overdue',11,'AlertTriangle','Overdue','Past Due Balance',money(t.overdue,c)),kpi('disputed',12,'ShieldAlert','Disputed','Open Dispute Balance',money(t.disputed,c))],rows:(data?.rows??[])as RevenuePortfolioRow[],alerts:data?.alerts??[],aging:data?.aging??[],activity:((data?.rows??[]).slice(0,8).map((r:any,i:number)=>({id:r.ref,time:r.dueDate||'',title:`Invoice ${r.invoiceRef} is ${r.receivableStatus}`,ref:r.relatedOrder,amount:money(r.outstandingAmount,r.currency),user:r.operator,type:i%2?'invoice':'payment'})))as RevenueActivityItem[]};}
export function paymentsView(data:PageData|null){const t=data?.totals??{},c=data?.context.baseCurrency??'LKR',attempts=t.attempts??0;return{context:data?.context,kpis:[kpi('attempts',1,'CreditCard','Payment Attempts','Payment Records',String(attempts)),kpi('authorized',2,'CheckCircle','Authorized Payments','Authorized Records',String(t.authorized??0)),kpi('captured',3,'DollarSign','Captured Payments','Captured Value',money(t.captured,c)),kpi('success',4,'Percent','Payment Success Rate','Successful / Attempts',`${attempts?((t.successful/attempts)*100).toFixed(1):'0.0'}%`),kpi('failed',5,'AlertTriangle','Failed Payments','Failed & Declined',String(t.failed??0)),kpi('failed_value',6,'ShieldAlert','Failed Payment Value','Failed Amount',money(t.failedValue,c)),kpi('pending',7,'Clock','Pending Capture','Awaiting Completion',String(t.pending??0)),kpi('reversed',8,'RotateCcw','Reversed Transactions','Reversed & Voided',String(t.reversed??0)),kpi('duplicates',9,'Layers','Duplicate Candidates','Duplicate domain not configured','Not available',false),kpi('holds',10,'Lock','Payment Holds','Hold domain not configured','Not available',false),kpi('refunds',11,'Undo2','Refunded Payments','Completed Refunds',money(t.refundAmount,c)),kpi('fees',12,'Receipt','Processing Fees','Recorded Fees',money(t.fees,c))],rows:(data?.rows??[])as PaymentPortfolioRow[],alerts:data?.alerts??[],trend:data?.trend??[],statuses:data?.statuses??[],methods:data?.methods??[],health:[]as FinanceHealthScore[]};}
