"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { AlertTriangle, Archive, Check, CheckCircle2, ChevronRight, CircleAlert, Clipboard, Copy, Download, ExternalLink, Eye, Info, MoreVertical, Package, Pause, RefreshCw, ShieldCheck, UserRound, X, XCircle } from "lucide-react";
import toast from "react-hot-toast";
import { fetchMarketplaceListingDetail, recordLocalListingAudit } from "@/services/api/marketplaceListingDetailService";
import type { LocalAuditEvent, MarketplaceListingDetail } from "@/types/marketplaceListingDetail";
import styles from "./listing-detail.module.css";

const tabs=["Overview","Listing Content","Product Match","Pricing","Inventory","Seller Eligibility","Media","Claims","Channels","Performance","Communications","Audit"];
const counts:Record<string,number>={Claims:3,Communications:3,Audit:12};
const moreActions=["Edit Listing","View Product Master","View Seller","View Brand Authorization","View Inventory","View Pricing Rule","Add Internal Note","Copy Listing ID","Export Listing Summary","View Audit History","Archive Listing"];
const decisionActions=["Approve and Publish","Approve with Conditions","Request Seller Changes","Suspend Listing","Reject Listing","Escalate Review"];

export function ListingDetailView({listingId}:{listingId:string}) {
  const router=useRouter(); const searchParams=useSearchParams();
  const [data,setData]=useState<MarketplaceListingDetail|null>(null); const [error,setError]=useState(""); const [refreshing,setRefreshing]=useState(false);
  const [modal,setModal]=useState<string|null>(null); const [menuOpen,setMenuOpen]=useState(false); const [status,setStatus]=useState(""); const [audit,setAudit]=useState<LocalAuditEvent[]>([]);
  const menuRef=useRef<HTMLDivElement>(null); const activeTab=tabs.find(tab=>tab.toLowerCase().replaceAll(" ","-")===searchParams.get("tab"))??"Overview";
  const load=async(refresh=false)=>{try{setError("");if(refresh)setRefreshing(true);const result=await fetchMarketplaceListingDetail(decodeURIComponent(listingId));setData(result);setStatus(result.status);if(refresh)toast.success("Listing refreshed from the frontend fixture");}catch(e){setError((e as Error).message==="LISTING_NOT_FOUND"?"This listing could not be found.":"Listing details could not be loaded.");}finally{setRefreshing(false)}};
  useEffect(()=>{const controller=new AbortController();void fetchMarketplaceListingDetail(decodeURIComponent(listingId),controller.signal).then(result=>{setData(result);setStatus(result.status)}).catch(e=>{if(e.name!=="AbortError")setError(e.message==="LISTING_NOT_FOUND"?"This listing could not be found.":"Listing details could not be loaded.")});return()=>controller.abort()},[listingId]);
  useEffect(()=>{const close=(event:MouseEvent)=>{if(menuRef.current&&!menuRef.current.contains(event.target as Node))setMenuOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
  const changeTab=(tab:string)=>{const q=new URLSearchParams(searchParams.toString());tab==="Overview"?q.delete("tab"):q.set("tab",tab.toLowerCase().replaceAll(" ","-"));router.replace(`/admin/marketplace/listings/${encodeURIComponent(listingId)}${q.size?`?${q}`:""}`,{scroll:false})};
  const addAudit=async(action:string,note="")=>{const event=await recordLocalListingAudit(listingId,action,note);setAudit(items=>[event,...items]);return event};
  const handleMore=async(action:string)=>{setMenuOpen(false);if(!data)return;if(action==="Copy Listing ID"){await navigator.clipboard?.writeText(data.id);toast.success("Listing ID copied");return}if(action==="Export Listing Summary"){const blob=new Blob([JSON.stringify({...data,localAudit:audit},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${data.id}-summary.json`;anchor.click();URL.revokeObjectURL(url);toast.success("Listing summary exported");return}setModal(action)};
  if(error)return <div className={styles.state} role="alert"><CircleAlert/><h1>Listing unavailable</h1><p>{error}</p><div><Link href="/admin/marketplace/listings">Back to Listings</Link><button onClick={()=>void load()}>Retry</button></div></div>;
  if(!data)return <div className={styles.loading} role="status" aria-label="Loading listing detail"><div/><div/><div/><div/></div>;
  return <main className={styles.page}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><Link href="/admin/marketplace/listings">Listings</Link><ChevronRight/><span>{data.id}</span></nav>
    <header className={styles.header}><div className={styles.titleBlock}><h1>{data.title}</h1><p><span className={styles.liveDot}/>Live data <i/> Last updated: {data.lastUpdated}<button className={styles.iconPlain} aria-label="Refresh listing" onClick={()=>void load(true)} disabled={refreshing}><RefreshCw className={refreshing?styles.spin:""}/></button></p></div><div className={styles.headerActions}>
      <button className={styles.secondary} onClick={()=>setModal("Preview Marketplace Page")}><Eye/>Preview Marketplace Page</button>
      <button className={styles.secondary} onClick={()=>setModal("Request Seller Update")}>Request Seller Update</button>
      <button className={styles.primary} onClick={()=>setModal("Keep Live")}><Check/>Keep Live</button>
      <div className={styles.more} ref={menuRef}><button className={styles.iconButton} aria-label="More listing actions" aria-expanded={menuOpen} onClick={()=>setMenuOpen(x=>!x)}><MoreVertical/></button>{menuOpen&&<div className={styles.moreMenu}>{moreActions.map(action=><button key={action} className={action==="Archive Listing"?styles.dangerText:""} onClick={()=>void handleMore(action)}>{action}</button>)}</div>}</div>
    </div></header>
    <section className={styles.context} aria-label="Listing context">{[["Seller",data.seller],["Marketplace",data.marketplace],["Brand",data.brand],["Country",data.country],["Region",data.region],["Category",data.category]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <Progress stages={data.stages}/>
    <div className={styles.tabs} role="tablist" aria-label="Listing detail sections">{tabs.map(tab=><button key={tab} role="tab" aria-selected={activeTab===tab} tabIndex={activeTab===tab?0:-1} onKeyDown={e=>{const index=tabs.indexOf(tab);if(e.key==="ArrowRight")changeTab(tabs[(index+1)%tabs.length]);if(e.key==="ArrowLeft")changeTab(tabs[(index-1+tabs.length)%tabs.length])}} onClick={()=>changeTab(tab)}>{tab}{counts[tab]&&<b>{counts[tab]}</b>}</button>)}</div>
    <div className={styles.layout}><div className={styles.main} role="tabpanel">{activeTab==="Overview"?<Overview data={data}/>:<TabPanel tab={activeTab} data={data} audit={audit}/>}</div><ReviewRail data={data} status={status} onAction={setModal}/></div>
    {modal&&<WorkflowModal type={modal} data={data} onClose={()=>setModal(null)} onComplete={async(action,note,nextStatus)=>{await addAudit(action,note);if(nextStatus)setStatus(nextStatus);setModal(null);toast.success(`${action} saved to local preview state (not server-persisted)`)}}/>}
  </main>;
}

function Progress({stages}:{stages:MarketplaceListingDetail["stages"]}){return <section className={styles.progress} aria-label="Moderation progress"><h2>Moderation Progress</h2><div className={styles.progressScroll}>{stages.map((stage,index)=><div className={`${styles.step} ${styles[stage.state]}`} key={stage.label}><div className={styles.marker}>{stage.state==="complete"?<Check/>:index+1}</div><span>{stage.label}</span></div>)}</div></section>}

function Overview({data}:{data:MarketplaceListingDetail}){return <div className={styles.overview}>
  <section className={`${styles.card} ${styles.summary}`}><div className={styles.cardHeader}><h2>Moderation Summary</h2><span className={styles.moderate}>Conflict Risk: Moderate</span></div><div className={styles.score}><div><strong>{data.score}</strong><small>/100</small></div><dl><div><dt>Validations</dt><dd>32</dd></div><div><dt>Minor Exceptions</dt><dd>3</dd></div><div><dt>Policy Findings</dt><dd>2</dd></div></dl></div><p><b>Recommendation: Approve with Conditions.</b> Listing content matches master catalogue with minor deviations in key claims, permission, and compliance notes.</p></section>
  <section className={`${styles.card} ${styles.identity}`}><h2>Identity Map</h2><div className={styles.identityFlow}><div><small>Listing Instance</small><strong>{data.title}</strong><em>ID: {data.id}</em></div><ChevronRight/><div><small>Product Master</small><strong>Radiance Vitamin C Serum</strong><em>Ref: {data.productMaster}</em></div><ChevronRight/><div><small>Seller</small><strong>SKU: {data.sku}</strong><em>EAN: {data.ean}</em></div></div></section>
  <ComparisonTable data={data}/>
  <section className={`${styles.card} ${styles.price}`}><h2>Price &amp; Revenue Control <Info/></h2><div className={styles.priceTop}><div><small>Listing Price</small><strong>{data.price}</strong></div><div><small>MRP / Compare</small><strong>LKR 12,800 – 12,900</strong></div></div><p><span>Catalogue Minimum</span><b>LKR 12,100</b></p><p><span>Max Safe Range (Compliance)</span><b>LKR 13,200</b></p><div className={styles.goodNote}><CheckCircle2/>Listing price is in safe compliance range.</div></section>
  <section className={`${styles.card} ${styles.inventory}`}><h2>Inventory &amp; Logistics <Info/></h2><div className={styles.inventoryGrid}><div><small>Current Available</small><strong>{data.stock.toLocaleString()}</strong><em>units (FIFO 4.2 days)</em></div><div><small>Warehouse Sync</small><b><CheckCircle2/>Active Sync</b><em>Last checked: 6 mins ago</em></div></div><div className={styles.infoNote}><Info/>Allocated for SL Lanka Central Fulfillment. Buffer levels met at 18% (723 units).</div></section>
  <section className={`${styles.card} ${styles.authority}`}><h2>Seller Authority</h2><div className={styles.sellerName}><span>{data.seller.slice(0,2).toUpperCase()}</span><div><strong>{data.seller}</strong><small>Tier 1 Elite Partner</small></div></div><p><span>Brand Auth Status</span><b className={styles.valid}>VALID</b></p><p><span>Auth Certificate</span><b className={styles.certificate}>VIEW CERT</b></p><p><span>Compliance Score</span><b>98.4%</b></p></section>
  <section className={`${styles.card} ${styles.findings}`}><h2>Policy &amp; Risk Findings</h2>{data.findings.map((finding,index)=><div className={styles[`risk${index}`]} key={finding.title}>{index===0?<XCircle/>:index===1?<AlertTriangle/>:<Info/>}<p><b>{finding.title}</b><span>{finding.detail}</span></p><em>{finding.severity}</em></div>)}</section>
  </div>}

function ComparisonTable({data}:{data:MarketplaceListingDetail}){return <section className={`${styles.card} ${styles.comparison}`}><div className={styles.cardHeader}><h2>Catalogue Alignment Comparison</h2><span className={styles.match}>96% Overall Match</span></div><div className={styles.tableWrap}><table><thead><tr><th>Attribute</th><th>Listing Value</th><th>Master Value</th><th>Status</th><th>Details</th></tr></thead><tbody>{data.comparison.map(row=><tr key={row.attribute}><th>{row.attribute}</th><td>{row.listing}</td><td>{row.master}</td><td><span className={styles[row.status.replaceAll(" ","").toLowerCase()]}>{row.status==="Match"?<CheckCircle2/>:row.status==="Missing"?<XCircle/>:<AlertTriangle/>}{row.status}</span></td><td>{row.detail}</td></tr>)}</tbody></table></div></section>}

function TabPanel({tab,data,audit}:{tab:string;data:MarketplaceListingDetail;audit:LocalAuditEvent[]}){if(tab==="Pricing")return <section className={`${styles.card} ${styles.tabCard}`}><h2>Pricing</h2><p>Current listing price <b>{data.price}</b> is within the approved range of LKR 12,100–13,200.</p><ComparisonTable data={{...data,comparison:data.comparison.filter(row=>row.attribute==="Price")}}/></section>;if(tab==="Inventory")return <section className={`${styles.card} ${styles.tabCard}`}><h2>Inventory</h2><h3>{data.stock.toLocaleString()} units available</h3><p>Warehouse sync is active. Central fulfillment allocation and stock buffer are healthy.</p></section>;if(tab==="Audit")return <section className={`${styles.card} ${styles.tabCard}`}><h2>Audit History</h2>{audit.length?audit.map(item=><article key={item.id}><b>{item.action}</b><span>{new Date(item.at).toLocaleString()} · {item.actor}</span><p>{item.note||"No moderation note provided."}</p></article>):<div className={styles.empty}>No local audit events in this session. The 12 server records are unavailable because no detail API exists.</div>}</section>;const descriptions:Record<string,string>={"Listing Content":data.description,"Product Match":"The listing is mapped to product master PM-VITC-30ML with a 96% overall match.","Seller Eligibility":`${data.seller} is an eligible Tier 1 seller with valid brand authorization.`,Media:"Seven listing images are aligned to the product master.",Claims:"Three claims require moderation; one lacks supporting documentation.",Channels:"Web and mobile marketplace publication channels are enabled.",Performance:"30-day sales and conversion metrics are monitored from the listings workspace.",Communications:"Three seller communications are associated with this moderation review."};return <section className={`${styles.card} ${styles.tabCard}`}><h2>{tab}</h2><p>{descriptions[tab]}</p><div className={styles.placeholderRows}>{["Review status","Data source","Last updated"].map((label,index)=><div key={label}><span>{label}</span><b>{index===0?"In Review":index===1?"Frontend fixture":data.lastUpdated}</b></div>)}</div></section>}

function ReviewRail({data,status,onAction}:{data:MarketplaceListingDetail;status:string;onAction:(x:string)=>void}){return <aside className={styles.rail}>
  <section className={styles.railCard}><h2>Review Status</h2><div className={styles.completion}><p><span>Overall Completion</span><b>{data.completion}%</b></p><div><i style={{width:`${data.completion}%`}}/></div></div><div className={styles.currentStatus}><ShieldCheck/><p><b>{status==="Live"?"In Review":status}</b><span>Policy &amp; Risk</span></p><em>Active now</em></div></section>
  <section className={styles.railCard}><h2>Reviewer &amp; SLA Details</h2>{[["Assigned Reviewer",data.reviewer],["Review SLA",data.reviewSla],["Elapsed Time",data.elapsed],["Due Date",data.dueDate],["Last Updated",data.lastUpdated]].map(([label,value],index)=><p className={styles.railRow} key={label}><span>{label}</span><b>{index===0&&<UserRound/>}{value}</b></p>)}</section>
  <section className={styles.railCard}><h2>Decision Actions</h2><div className={styles.decisionButtons}>{decisionActions.map((action,index)=><button key={action} className={`${index===0?styles.publish:""} ${action==="Reject Listing"?styles.reject:""} ${action==="Suspend Listing"?styles.suspend:""}`} onClick={()=>onAction(action)}>{index<2?<Check/>:action.includes("Request")?<Clipboard/>:action.includes("Suspend")?<Pause/>:action.includes("Reject")?<XCircle/>:<ExternalLink/>}{action}</button>)}</div><div className={styles.permission}><ShieldCheck/>Sensitive actions require admin permission and confirmation, and are locally audit-logged.</div></section>
  <section className={styles.railCard}><h2>Related Records</h2>{[["Product Master",data.productMaster],["Seller Profile",data.seller],["Brand Authorization","VALID"],["Inventory Record",`INV-${data.sku}`],["Price Rule","PR-2026-004"],["Policy Case","PC-2026-0192"],["Duplicate Listing","None Found"],["Audit History","12 Records"]].map(([label,value])=><button className={styles.related} key={label} onClick={()=>onAction(`View ${label}`)}><span>{label}</span><b>{value}</b><ChevronRight/></button>)}</section>
  </aside>}

function WorkflowModal({type,data,onClose,onComplete}:{type:string;data:MarketplaceListingDetail;onClose:()=>void;onComplete:(action:string,note:string,status?:string)=>Promise<void>}){const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [note,setNote]=useState("");const [reviewed,setReviewed]=useState(false);const [category,setCategory]=useState("");const [changes,setChanges]=useState("");const [instructions,setInstructions]=useState("");const [due,setDue]=useState("");const [priority,setPriority]=useState("Normal");const [notify,setNotify]=useState(true);const isUpdate=type==="Request Seller Update"||type==="Request Seller Changes";const isPreview=type==="Preview Marketplace Page";const isSimpleView=type.startsWith("View ")&&!type.includes("Audit History");const submit=async()=>{if(isUpdate&&(!category||!changes.trim()||!instructions.trim()||!due)){setError("Complete all required seller update fields.");return}if(type==="Keep Live"&&!reviewed){setError("Confirm that policy and risk findings were reviewed.");return}setBusy(true);try{const next=type.includes("Publish")?"Published":type.includes("Suspend")?"Suspended":type.includes("Reject")?"Rejected":type==="Keep Live"?"Live":undefined;await onComplete(type,note||changes,next)}catch{setError("The action could not be completed.");setBusy(false)}};return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className={`${styles.modal} ${isPreview?styles.previewModal:""}`} role="dialog" aria-modal="true" aria-labelledby="workflow-title"><header><div><small>Listing Moderation · Frontend Preview</small><h2 id="workflow-title">{type}</h2></div><button aria-label="Close dialog" disabled={busy} onClick={onClose}><X/></button></header>
  {isPreview?<div className={styles.preview}><div className={styles.productImage}><Package/></div><div><span className={styles.statusBadge}>{data.status}</span><h3>{data.title}</h3><p>Sold by <b>{data.seller}</b></p><strong>{data.price}</strong><p>{data.stock.toLocaleString()} units in stock</p><p>{data.description}</p></div></div>:isUpdate?<div className={styles.form}><label>Update category *<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Select category</option>{["Product information","Pricing","Images","Compliance documentation","Claims","Inventory","Brand authorization","Certification","Packaging details"].map(x=><option key={x}>{x}</option>)}</select></label><label>Requested changes *<textarea value={changes} onChange={e=>setChanges(e.target.value)} /></label><label>Seller instructions *<textarea value={instructions} onChange={e=>setInstructions(e.target.value)} /></label><div className={styles.formGrid}><label>Due date *<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option>Normal</option><option>High</option><option>Urgent</option></select></label></div><label>Attach supporting note<input type="text" placeholder="Reference or supporting note"/></label><label className={styles.check}><input type="checkbox" checked={notify} onChange={e=>setNotify(e.target.checked)}/>Notify seller</label><label>Internal note<textarea value={note} onChange={e=>setNote(e.target.value)}/></label></div>:isSimpleView?<div className={styles.safeView}><Info/><p><b>{type}</b> is shown in this internal drawer because the repository has no confirmed destination route. No 404 link was opened.</p></div>:<div className={styles.confirm}><p>You are about to apply <b>{type}</b> to <b>{data.title}</b> ({data.id}).</p><label>Moderation note {type==="Keep Live"?"(optional)":"(required for audit)"}<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add decision context"/></label>{type==="Keep Live"&&<label className={styles.check}><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I confirm policy and risk findings were reviewed.</label>}<div className={styles.localNotice}><Info/>No mutation API exists. Confirmation updates only this page session and its local audit trail.</div></div>}
  {error&&<p className={styles.formError} role="alert">{error}</p>}<footer><button className={styles.secondary} disabled={busy} onClick={onClose}>Cancel</button>{!isPreview&&!isSimpleView&&<button className={styles.primary} disabled={busy} onClick={()=>void submit()}>{busy?"Saving…":isUpdate?"Send Request":"Confirm"}</button>}</footer></section></div>}
