"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ChevronRight, RefreshCw } from "lucide-react";
import { fetchMarketplaceListingDetail, type MarketplaceListingDetailResponse } from "@/services/api/marketplaceListingDetailService";
import styles from "./listing-detail.module.css";

export function ListingDetailView({ listingId }: { listingId: string }) {
  const [data, setData] = useState<MarketplaceListingDetailResponse | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(""); try { setData(await fetchMarketplaceListingDetail(listingId)); } catch { setError("This database listing could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { const controller = new AbortController(); void fetchMarketplaceListingDetail(listingId, controller.signal).then(setData).catch(error => { if (error.name !== "AbortError") setError("This database listing could not be loaded."); }).finally(() => setLoading(false)); return () => controller.abort(); }, [listingId]);
  if (loading) return <div className={styles.loading} role="status" aria-label="Loading listing detail"><div/><div/><div/></div>;
  if (error || !data) return <div className={styles.state} role="alert"><AlertTriangle/><h1>Listing unavailable</h1><p>{error}</p><button onClick={() => void load()}>Retry</button></div>;
  const row = data.listing;
  return <main className={styles.page}><nav className={styles.breadcrumb}><Link href="/admin/marketplace">Marketplace</Link><ChevronRight/><Link href="/admin/marketplace/listings">Listings</Link><ChevronRight/><span>{row.listingCode}</span></nav><header className={styles.header}><div className={styles.titleBlock}><h1>{row.name}</h1><p><span className={styles.liveDot}/>Live API <i/> Last updated: {new Date(row.updatedAt).toLocaleString("en-LK")}<button className={styles.iconPlain} onClick={() => void load()}><RefreshCw/></button></p></div></header><section className={styles.context}>{[["Seller",row.seller?.name ?? "â€”"],["Product",row.product.name],["Category",row.category?.name ?? "â€”"],["Status",row.listingStatus],["Stock",row.stock.toLocaleString()],["Risk",row.riskLevel ?? "Not available"]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><div className={styles.layout}><div className={styles.main}><section className={styles.card}><h2>Database Listing</h2><p>{row.descriptor ?? "No listing description is available."}</p><p>Listing ID: <b>{row.listingCode}</b></p><p>30-day sales: <b>{row.sales30Days.toLocaleString()}</b></p><p>Policy status: <b>{row.policyStatus ?? "Not available"}</b></p><p>Verification status: <b>{row.verificationStatus ?? "Not available"}</b></p></section></div><aside className={styles.rail}><section className={styles.railCard}><h2>Listing Health</h2><p>{data.health.availability === "unavailable" ? "Not available: no approved formula exists." : "Available"}</p></section><section className={styles.railCard}><h2>Listing SLA</h2><p>{data.sla.availability === "unavailable" ? "Not available: no listing SLA policy exists." : "Available"}</p></section></aside></div></main>;
}
