'use client';
import { useCallback, useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { AlertTriangle, CheckCircle2, Database, RefreshCw, Search } from 'lucide-react';
import { GovernanceData, GovernanceQuery, GovernanceRecord, getFinanceOperation, getFinanceOperations, getReconciliation } from '@/services/api/financeGovernanceService';

const statusClass=(s:string)=>s==='completed'?'bg-emerald-50 text-emerald-700':s==='failed'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700';
export function FinanceGovernanceWorkspace({mode}:{mode:'reconciliation'|'operations'}){
 const [data,setData]=useState<GovernanceData|null>(null),[selected,setSelected]=useState<GovernanceRecord|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [query,setQuery]=useState<GovernanceQuery>({page:1,per_page:20,sort:'created_at',direction:'desc'});
 const load=useCallback(async(silent=false)=>{const c=new AbortController();if(!silent)setLoading(true);setError('');try{const next=mode==='reconciliation'?await getReconciliation(c.signal):await getFinanceOperations(query,c.signal);setData(next);if(next.records.length)setSelected(current=>current??next.records[0]);}catch(e){setError(e instanceof Error?e.message:'Unable to load finance governance data.');}finally{setLoading(false);}return()=>c.abort();},[mode,query]);
 useEffect(()=>{void load();},[load]); useEffect(()=>{const id=setInterval(()=>void load(true),30000);return()=>clearInterval(id)},[load]);
 const choose=async(r:GovernanceRecord)=>{setSelected(r);if(mode==='operations')try{setSelected(await getFinanceOperation(r.id));}catch{/* table record remains usable */}};
 const title=mode==='reconciliation'?'Reconciliation, Exceptions & Financial Controls':'Finance Reports, Import, Export & Audit';
 return <div className="min-h-screen bg-[#f6f7f9] text-slate-900"><header className="sticky top-0 z-20 border-b bg-white px-5 py-4"><div className="mx-auto flex max-w-[1720px] items-start justify-between gap-4"><div><p className="text-[10px] text-slate-500">Finance / {title}</p><h1 className="text-xl font-bold">{title}</h1><p className="mt-1 text-xs text-slate-500">Authoritative operational records and audit evidence from the SL Beauty database.</p></div><button onClick={()=>void load()} className="flex items-center gap-2 rounded-md bg-[#99002f] px-3 py-2 text-xs font-semibold text-white"><RefreshCw size={14}/>Refresh</button></div></header>
 <main className="mx-auto grid max-w-[1720px] gap-4 p-4 xl:grid-cols-[1fr_280px]"><section className="min-w-0 space-y-4">
  <div className="rounded-lg border bg-white p-3 text-xs"><b>Tenant:</b> {data?.context.tenant??'SL Beauty'} <span className="mx-3 text-slate-300">|</span><b>Source:</b> database <span className="mx-3 text-slate-300">|</span><b>Updated:</b> {data?.meta.updatedAt?new Date(data.meta.updatedAt).toLocaleString():'—'}</div>
  {loading&&!data?<State text="Loading live finance records…"/>:error?<State error text={error}/>:data?.available===false?<div className="rounded-xl border border-amber-300 bg-amber-50 p-8 text-center"><AlertTriangle className="mx-auto mb-3 text-amber-600"/><h2 className="font-bold">Reconciliation data is not available</h2><p className="mt-2 text-sm text-amber-800">The repository has no authoritative reconciliation ledger, match engine, exception workflow, or control-test schema. No financial match results are being inferred or fabricated.</p><code className="mt-3 inline-block text-xs">{data.reason}</code></div>:<>
   <div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6">{data?.kpis.map(k=><div key={k.label} className="rounded-lg border bg-white p-3"><div className="text-[10px] font-semibold uppercase text-slate-500">{k.label}</div><div className="mt-1 text-xl font-bold">{k.value}</div></div>)}</div>
   <div className="rounded-xl border bg-white"><div className="flex flex-wrap gap-2 border-b p-3"><label className="flex min-w-56 flex-1 items-center gap-2 rounded border px-3"><Search size={14}/><input aria-label="Search operations" value={query.search??''} onChange={e=>setQuery(q=>({...q,search:e.target.value,page:1}))} placeholder="Search reference or title" className="w-full py-2 text-xs outline-none"/></label>{['domain','job_type','status'].map(f=><input key={f} aria-label={f} value={String(query[f as keyof GovernanceQuery]??'')} onChange={e=>setQuery(q=>({...q,[f]:e.target.value,page:1}))} placeholder={f.replace('_',' ')} className="rounded border px-3 py-2 text-xs"/>)}</div>
    <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{['Reference','Operation','Domain','Title','Status','Processed','Rejected','Initiated by','Created'].map(h=><th key={h} className="whitespace-nowrap px-3 py-2">{h}</th>)}</tr></thead><tbody>{data?.records.map(r=><tr key={r.id} onClick={()=>void choose(r)} className={`cursor-pointer border-t hover:bg-rose-50 ${selected?.id===r.id?'bg-rose-50':''}`}><td className="px-3 py-2 font-mono font-semibold text-[#99002f]">{r.reference}</td><td className="px-3 py-2">{r.operationType}</td><td className="px-3 py-2">{r.domain}</td><td className="px-3 py-2 font-medium">{r.title}</td><td className="px-3 py-2"><span className={`rounded px-2 py-1 ${statusClass(r.status)}`}>{r.status}</span></td><td className="px-3 py-2 font-mono">{r.processedRecords.toLocaleString()}</td><td className="px-3 py-2 font-mono">{r.rejectedRecords.toLocaleString()}</td><td className="px-3 py-2">{r.initiatedBy}</td><td className="whitespace-nowrap px-3 py-2">{new Date(r.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!data?.records.length&&<div className="p-10 text-center text-sm text-slate-500">No records match the active filters.</div>}</div>
    <div className="flex items-center justify-between border-t p-3 text-xs"><span>{data?.meta.total??0} records</span><div className="flex gap-2"><button disabled={(data?.meta.page??1)<=1} onClick={()=>setQuery(q=>({...q,page:(q.page??1)-1}))} className="rounded border px-3 py-1 disabled:opacity-40">Previous</button><span className="px-2 py-1">Page {data?.meta.page} / {data?.meta.lastPage}</span><button disabled={(data?.meta.page??1)>=(data?.meta.lastPage??1)} onClick={()=>setQuery(q=>({...q,page:(q.page??1)+1}))} className="rounded border px-3 py-1 disabled:opacity-40">Next</button></div></div></div>
   <div className="rounded-xl border bg-white p-4"><h2 className="text-xs font-bold uppercase">Selected operation</h2>{selected?<div className="mt-3 grid gap-3 text-xs md:grid-cols-4"><Field l="Reference" v={selected.reference}/><Field l="Status" v={selected.status}/><Field l="Processed / Total" v={`${selected.processedRecords.toLocaleString()} / ${selected.totalRecords.toLocaleString()}`}/><Field l="Rejected" v={selected.rejectedRecords.toLocaleString()}/><Field l="Domain" v={selected.domain}/><Field l="Initiated by" v={selected.initiatedBy}/><Field l="Updated" v={new Date(selected.updatedAt).toLocaleString()}/><Field l="Error" v={selected.errorSummary??'None recorded'}/></div>:<p className="mt-3 text-xs text-slate-500">Select a row to inspect it.</p>}</div>
  </>}
 </section><aside className="space-y-4"><Rail title="Capabilities">{data&&Object.entries(data.capabilities).map(([k,v])=><div key={k} className="flex justify-between py-1 text-xs"><span>{k}</span><span className={v?'text-emerald-700':'text-slate-500'}>{v?'Available':'Unavailable'}</span></div>)}</Rail><Rail title="Recent audit activity">{data?.audit.length?data.audit.slice(0,10).map(a=><div key={a.id} className="border-b py-2 text-xs"><div className="font-medium">{a.description}</div><div className="mt-1 text-[10px] text-slate-500">{a.actor??'System'} · {new Date(a.created_at).toLocaleString()}</div></div>):<p className="text-xs text-slate-500">No scoped finance report/import/export audit events were recorded.</p>}</Rail><Rail title="Data integrity"><div className="flex items-center gap-2 text-xs text-emerald-700"><CheckCircle2 size={15}/>No synthetic fallback values</div><div className="mt-2 flex items-center gap-2 text-xs text-slate-600"><Database size={15}/>Database-backed response</div></Rail></aside></main></div>;
}
function State({text,error=false}:{text:string;error?:boolean}){return <div className={`rounded-xl border p-10 text-center text-sm ${error?'border-red-200 bg-red-50 text-red-700':'bg-white text-slate-500'}`}>{text}</div>}
function Field({l,v}:{l:string;v:string}){return <div><div className="text-[10px] uppercase text-slate-500">{l}</div><div className="mt-1 break-words font-semibold">{v}</div></div>}
function Rail({title,children}:{title:string;children:ReactNode}){return <div className="rounded-xl border bg-white p-4"><h3 className="mb-2 text-[11px] font-bold uppercase">{title}</h3>{children}</div>}
